Feature/사이드바 제작 #104
KEEPER31337/Homepage-Front-R2 pull request #160
Opened 2023-01-26 14:41 UTC by lcqff

## 분류
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈
#104 
#103 
#102 

## 작업 요약
홈페이지 사이드바,헤더,전체적인 레이아웃을 추가하고 헤더와 사이드바 내부 기능들을 구현하였다. 

## 작업 상세 설명
사이드바
  - 카테고리 클릭시 tint됨
  - 다른 카테고리를 클릭하면 기존 tint 꺼지고 클릭한 카테고리가 tint
  - 서브 카테고리 클릭 시 폰트 파란색으로 바뀜
  - 다른 서브 카테고리 클릭시 폰트 하얀색으로 바뀜, 클릭된 서브카테고리의 폰트가 파란색으로 바뀜

헤더
  - 아이콘 클릭 시 위키, 깃허브 이동
  - 프로필 클릭 시 프로필,프로필 수정, 로그아웃 창 뜸

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분
한...시간? 30분?

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/214864014-6b0834f5-bb88-4b02-a8c6-e8c40591302b.png)

2023-01-27 02:35 UTC, publdaze requested changes
지금 develop 머지된 브랜치 변경사항도 같이 올라와있는 것 같습니다.
develop 한 번 풀 받아서 conflict 해결 후 push 하고 Re-request review 해주세요

2023-01-27 03:25 UTC, publdaze reviewed
사용하지 않는데 들어간 코드들이 꽤나 보이는 것 같습니다. 커밋 올리기 전에 그런 부분 체크해보고 신중히 올려주면 좋을 것 같아요! 😀

2023-01-27 03:25 UTC, publdaze commented on src/component/layout/Sidebar/category.js
> +];
저희 이제 KEEPER라는 카테고리가 따로 없는 걸로 알고 있고, 작성하신 코드 상에도 사용하는 부분이 없는 것 같은데 해당 변수를 따로 만들어둔 이유가 있나요?

2023-01-27 03:25 UTC, publdaze commented on tailwind.config.js
> +        darkPoint: '#111827',
색상이 리뉴얼1때 사용하던 색상 커스텀 그대로 가져오신 것 같은데 저희 색상 디자인 회의때 정해진 색상으로 변경해주세요! 피그마에서 확인하시면 각 색상들 파악하기 쉬울 거에요! 그리고 각 색상들 개별적으로 적용한 부분도 여기서 지정한 custom color로 다 변경 부탁드립니다.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/78250089/215002251-b5cff2a4-b76f-4463-b01a-59782932d4f2.png"> <img width="322" alt="image" src="https://user-images.githubusercontent.com/78250089/215002274-fc1cdc5b-f683-4d00-b11f-00296a5c87d0.png">

2023-01-27 03:29 UTC, publdaze commented on src/component/layout/Sidebar/category.js
> +// 서브 카테고리 목록(회장,부회장,서기): 1000번대
id 선정 임의로 이렇게 선정해주신 건가요? 아니면 id 이렇게 지정한 이유가 있나요?

2023-01-27 06:04 UTC, lcqff commented on src/component/layout/Sidebar/category.js
> +];
저건 이전 카테고리 js에서 긁어왔습니다!! 사용자가 로그인 하기 전에 카테고리를 한정해서 보여주는 기능은 여전히 쓸거같아 남겨놨습니다~~~

2023-01-27 06:06 UTC, lcqff commented on src/component/layout/Sidebar/category.js
> +// 서브 카테고리 목록(회장,부회장,서기): 1000번대
제가 임의로 했습니다~ 혹시 권장되는 방식이 있나요?

2023-01-27 06:06 UTC, lcqff commented on src/component/layout/Header/component/HeaderIcon.tsx
> +};
이것도 이전 코드에서 긁어온 건데 일단 쓰임이 없을 거 같으니 지우겠습니다!

2023-01-27 06:07 UTC, lcqff commented on src/component/layout/Header/Header.tsx
> +import { Popover } from '@headlessui/react';
아~~ 이전코드에서 긁어왔습니다 material걸로 바꾸겠습니다~! ㅠㅠ

2023-01-27 06:07 UTC, lcqff commented on src/component/layout/Header/component/HeaderIcon.tsx
> +import { Disclosure, Menu, Transition } from '@headlessui/react';
이것도 material걸로 바꾸겠습니다,,,

2023-01-27 06:53 UTC, publdaze commented on src/component/layout/Sidebar/category.js
> +];
아하! 그런 의도였군요! 동아리 소개와 메인페이지가 현재 기획 상에서는 합쳐져서 메인 페이지에 동아리 소개도 같이 보여주게 되어있습니다! 그래서 따로 카테고리로 빼두지 않아도 괜찮을 것 같아요!

2023-01-27 07:08 UTC, publdaze commented on src/component/layout/Sidebar/category.js
> +// 서브 카테고리 목록(회장,부회장,서기): 1000번대
음.. 글쎄요! 권장되는 방식이 있는 지는 잘 모르겠습니다!

2023-01-28 02:36 UTC, koty08 requested changes
이번 리뷰 진행하면서 Typescript 추가하면서 정리해야 할 부분들이 생겼다고 느꼈습니다.

interface를 별도로 분리하여 관리하는것이 좋은지라, 해당 파일 네이밍이나 폴더 구조,
interface 자체의 네이밍 컨벤션 등등..

제가 익숙한 컨벤션들이 있긴 하지만, 같이 맞춰가는 것이 좋을 것 같아 추후에 제가 여러가지 알아본 뒤 노션에 정리해보도록 하겠습니다.

2023-01-28 02:36 UTC, koty08 commented on src/component/layout/Sidebar/component/SidebarContents.tsx
> +  category: any;
해당 category type도 `Sidebar.tsx` 에서 사용되는 **thiscategory** interface export 하여 사용하면 될 것 같습니다!

2023-01-28 02:36 UTC, koty08 commented on src/component/layout/Sidebar/component/SidebarContents.tsx
> +        <div>{category?.name}</div>
`?.` Optional 연산자 사용하신 이유가 있을까요? category Props가 null인 상황은 없을 것 같습니다.

2023-01-28 02:36 UTC, koty08 commented on src/component/layout/Sidebar/component/SidebarContents.tsx
> +          {category.subs.map((item: any) => {
이 부분도 Sidebar.tsx 에서 사용되는 **sub** interface export 하여 type 사용하시면 될 것 같습니다!

2023-01-28 02:36 UTC, koty08 commented on src/atoms.tsx
> +export const SidebarCategoryState = atomFamily({
State에 Category의 id값만 담고 있다면 `CategoryIdState` 로 네이밍 변경하는게 좋을 것 같습니다!
(아래의 Subcategory도 동일)

2023-01-28 02:36 UTC, koty08 commented on src/component/layout/Sidebar/Sidebar.tsx
> +          {categories.map((category) =>
jsx에서 map 함수 생성하여 리스트 생성 시에는 자식 Component에 key 값 설정이 필요합니다.

![image](https://user-images.githubusercontent.com/43947871/215237578-6dd316e7-ae58-46f4-acae-8e52547033e9.png)

> React에서는 key prop를 사용하여 컴포넌트와 DOM 요소 간의 관계를 생성합니다. React 라이브러리는 이 관계를 이용하여 컴포넌트 렌더링 여부를 결정하기 때문에 불필요한 렌더링을 방지하기 위하여 각 자식 컴포넌트마다 독립적인 Key 값을 넣어줘야 하는데 Key 값이 없는 경우에 발생하는 오류입니다.
https://redcow77.tistory.com/647

2023-01-28 02:43 UTC, koty08 commented on src/component/layout/Sidebar/component/SidebarContents.tsx
> +const SidebarContents = ({ category, styles }: SidebarContentsProps) => {
props interface로 type 관리 좋습니다! 👍 👍 👍 네이밍도 너무 좋아요!

2023-01-29 04:01 UTC, publdaze commented on src/component/layout/Sidebar/category.js
> +// 카테고리: 0~9
따로 분리하는 거 너무 좋을 것 같아요! 👍
혹시 폴더명 `common`으로 제안하신 이유가 있을까요? `components` 폴더 내에 공통 컴포넌트들을 넣을 예정인데`common`이`공통`이라는 의미를 가지고 있어서 어떤 걸 넣어야할 지 애매할 것 같다는 생각이 들어요!

그래서 다른 방안 한 번 생각해봤는데 `src/data` 내에 위치시키는 건 어떨까요? 해당 폴더 내에 백엔드 API 등을 통해서 가져올 필요가 없는 정적인 데이터들을 모아두면 좋을 것 같아요!

그리고 `components`폴더 하위에 있는 게 좋을지 밖에 있는게 좋을지도 고민되는 부분이긴 한데, `components` 폴더 내에는 react element를 반환하는 것만 두면 어떨까해서 `components` 하위가 아닌 같은 라인으로 `data` 폴더 생성해 사용하는 건 어떨까 해요!

++ 추가로
`component` 폴더명도 `components`로 변경하면 좋을 것 같네요!
중요한 부분은 아닌 것 같긴하지만 제가 작업한 [절대 경로 설정하기 PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/125)에 우선적으로 `components` 사용하고 있기도 하고, 여기저기 둘러보니까 components로 주로 많이 쓰는 것 같더라구요! 그리고 이미 개발 시작한 다른 분들도 `components`로 폴더명 지정해 사용하고 있는 걸로 알고 있어요!

2023-01-29 04:28 UTC, publdaze commented on src/atoms.tsx
> +export const SidebarCategoryState = atomFamily({
태영님 말씀대로 네이밍 변경하면 해당 state가 어떤 걸 의미하는 지 명료하게 전달되는 것 같아 좋은 것 같습니다!

여기에 덧붙여서 컴포넌트가 아닌 변수명은 `camelCase`를 사용하여 첫글자는 소문자로 표기해주면 좋을 것 같습니다! 그리고 [recoil 공식 문서](https://recoiljs.org/ko/docs/api-reference/utils/atomFamily/)에 보니 `atomFamily`함수를 사용한 변수 접미사로 **Family**를 붙이더라구요! 사용하지 않는 사례들도 있는 것 같지만 저희는 `atom`과 구분을 위해 **Family**를 뒤에 붙여주는 건 어떨까요?
그래서 최종적으로 `categoryIdStateFamily`을 변수명으로 하면 어떨까 제안드립니다!

2023-01-29 06:50 UTC, lcqff commented on src/component/layout/Sidebar/category.js
> +];
넵 수정하겠습니다~~

2023-01-29 10:34 UTC, amaran-th approved these changes
다른 분들이 리뷰 너무 잘 달아주셔서 제가 마땅히 덧붙일 게 없네요...!
좀 더 공부해서 다음부턴 리뷰 달 수 있도록 할게요
늦어서 죄송합니다...! 수고하셨습니다!

2023-01-29 12:59 UTC, lcqff commented on package.json
> +    "postcss": "^8.4.21",
왜 생긴 건진 모르겠지만 없어도 작동 잘 되네요....!! 아마도? 이전 코드 옮겨오면서 같이 옮겨져왔는데 해당 부분 사용하는 코드는 제가 지워버린듯..

2023-01-29 13:06 UTC, lcqff commented on src/component/layout/Sidebar/component/SidebarContents.tsx
> +        <div>{category?.name}</div>
테스트하면서 붙인 건데 수정을 안한 모양입니다! 수정완료했습니다!

2023-01-29 14:55 UTC, amaran-th requested changes

2023-01-29 14:55 UTC, amaran-th commented on src/components/layout/Header/Header.tsx
> +import Logo from '../../../assets/keeper_logo.png';
여기 경로는 절대경로로 수정해주시면 더 좋을 것 같아요!

2023-01-29 14:55 UTC, amaran-th commented on src/components/layout/Sidebar/Sidebar.tsx
> +import { categoryIdStateFamily } from '../../../atoms';
여기도 상대경로 말고 절대경로로 수정해주시면 좋을 것 같아요!

2023-01-30 06:54 UTC, amaran-th commented on tailwind.config.js
> -module.exports = withMT({
혹시 별 다른 이유가 없으면 요 withMT 다시 복구해주실 수 있나요...!
이게 없으니까 material tailwind 디자인이 깨집니다!

2023-01-30 06:54 UTC, amaran-th commented on tailwind.config.js
> +    },
찾아보니까 폰트도 색상처럼 config 파일에 지정해줄 수 있더라구요! 저희 디자인에서 결정된 폰트 사이즈도 지정해주시면 좋을 것 같아요!(28, 20, 16, 12pt)

[관련 게시글](https://goddino.tistory.com/281)

2023-01-30 06:54 UTC, amaran-th commented on src/App.tsx
> +    <div className="min-h-full bg-[#26262C]">
여기에 taliwind.config에서 설정해줬던 기본 폰트/기본 폰트 사이즈 설정 넣어주시면 좋을 것 같아요!
font-basic text-base(=16pt)

2023-01-30 06:54 UTC, lcqff commented on tailwind.config.js
> -module.exports = withMT({
수정햇오요

2023-01-30 07:15 UTC, publdaze commented on tailwind.config.js
> -module.exports = withMT({
> 혹시 별 다른 이유가 없으면 요 withMT 다시 복구해주실 수 있나요...! 이게 없으니까 material tailwind 디자인이 깨집니다!

맞아요! material tailwind 사용하려면 필수적으로 들어가야하는 부분이랍니다!

2023-02-01 12:24 UTC, koty08 approved these changes
넵 수정 확인했습니다! 추후 Typescript Convention 생기면서 관련 수정사항 생기면 별도로 PR 파서 진행하면 좋을 것 같습니다! 수고하셨습니다! 👍 👍

2023-02-01 13:49 UTC, publdaze reviewed
제가 이부분 이어받아서
- custom color로 사용되지 않고 직접 색상코드 넣은 부분 수정
- tailwind css 유틸리티 클래스 순서 적용 (추가된 플러그인 사용)
- 사용되지 않는 import문 및 변수 및 타입 제거
- 사이드바 라우터 경로와 연동
- 폴더구조 재정리
- 추가적인 리팩토링 적용

등등 추가 작업이 진행할 것 같은데 해당 PR에 계속 변경사항과 커밋이 쌓이게되면
히스토리 및 변경 내용이 과하게 쌓일 것 같고 PR 단위가 크다보니 다시 리뷰 요청하기 어려울 것 같아서
해당 PR close 하고 조금 더 세분화된 단위로 연후님 코드 정리해서 PR 올려가며 작업해도 괜찮을까요?
리뷰어로 연후님과 지금 리뷰어로 선정되어 있는 분들도 그대로 리뷰어 지정해도 두려고 하는데 그렇게 진행해도 될 지 답변 부탁드립니다!

@lcqff @koty08 @amaran-th

2023-02-02 03:10 UTC, koty08 commented
넵 좋습니다~

2023-02-02 05:22 UTC, lcqff commented
넵~~

2023-02-02 06:48 UTC, amaran-th commented
네!

2023-02-03 10:00 UTC, closed without merging