Feature/공통컴포넌트 모달 제작 #131
KEEPER31337/Homepage-Front-R2 pull request #164
Opened 2023-01-30 01:20 UTC by mia2583

## 연관 이슈
> #131

## 작업 요약
> - 공통 모달 컴포넌트인 ActionModal 제작
> 아직 최종 완성본은 아니고 보완, 수정할 점이 있으나 공통 컴포넌트라 필요한 사람들 미리 사용할 수 있게 개발 완성된 부분까지 올립니다. 더 작업해야하는 부분은 밑에 필요한 추가 작업에 작성

## 작업 상세 설명
> - 모달의 제목, 내용, 추가 실행 코드, 버튼 이름과 버튼 클릭 시 동작을 정의하여 사용 가능
>      1. 사용 방법
>          `<ActionModal title="제목" contents="내용" code="<p>추가코드</p>" buttonName="버튼이름" onClick={동작함수} />`
>      2. 결과 화면
>         ![image](https://user-images.githubusercontent.com/83392142/215368562-bb9c81f6-dc60-4257-9ab1-68398e5a53d4.png)

## 필요한 추가 작업
> [ ] 모달 크기 조절(사용자로부터 입력을 받아서 모달 크기 조절)
> [ ] 창이 일정 이상 작아지면 글자 깨짐/모달 깨짐 수정
> [ ] css 테일윈드 적용 순서 플러그인 설치 후 적용

## 리뷰 요구사항
> 15-20분?

## Preview 이미지
원래 목표했던 이미지는 아래와 같습니다.
![image](https://user-images.githubusercontent.com/83392142/215367937-a95276d8-2791-468b-ba40-c1a718f89599.png)

2023-01-31 00:18 UTC, publdaze commented
저희 커밋 메시지를 `Type : 커밋 제목`
이런 식으로 작성하기로 정해서 다음부터는 맞춰주면 좋을 것 같아요! 😀
그리고 커밋에 이슈 번호를 달아줘야 이슈에 해당 커밋이 반영돼서 이슈 살펴볼 때 어떻게 작업되는 지 확인하기 좋아서
이슈번호도 같이 달아주세요!

ex. 
```
feat : 공통 모달 기본틀 제작하기
- 다른 코드에서 활용할 수 있도록 공통 모달 제작
- 제목, 내용, 버튼 이름 입력 가능

#131
```

2023-01-31 00:33 UTC, publdaze commented on .vscode/settings.json
> +}
prettier defaultFormmater로 지정해서 사용하는 거 user 차원에서 했는데 저희가 모두 공통적으로 사용하는 부분이면 workspace쪽에 따로 설정해둬도 괜찮을 것 같네요!

이 커밋과는 상관 없는 부분이니 따로 커밋 분리해주면 좋을 것 같고 프로젝트 전체에 반영되는 세팅 부분의 경우는 슬랙으로도 한 번 전달해주면 좋을 것 같아요!

2023-01-31 00:43 UTC, publdaze requested changes

2023-01-31 00:43 UTC, publdaze commented on src/App.tsx
> +  );
저희가 router를 사용해서 url을 통해 각 페이지를 접근하도록 하고 있어요!
그래서 `App.tsx` 파일에 직접적으로 컴포넌트를 불러오는 방식이 아닌 `useMainRouter.tsx` 파일에서 router 경로 설정해 사용하면 됩니다!

세미나 관리 페이지의 경우는 제가 이미 아래와 같이 라우터 설정해두었습니다.
```tsx
{
  path: 'admin',
  children: [
    {
      path: 'seminarManage',
      element: <SeminarManage />,
    },
  ],
},
```
그래서 `admin/seminarManage` 이 경로로 들어가면 바로 해당 컴포넌트 작업 사항이 보일거에요!

App.tsx 변경사항은 원래대로 돌려놔주면 될 것 같습니다!

2023-01-31 02:03 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  );
현재 SeminarManage의 경로가 `pages/admin/SeminarManage.tsx` 이런 경로로 되어있는데
제가 라우터 설정할 때 임의로 이렇게 생성하면서 아무 생각 없이 해뒀었네요.. 죄송합니다!
admin 폴더 내에는 관리자 페이지들이 다 들어갈 예정이라 폴더로 묶으면 좋을 것 같아요

그래서 `pages/admin/SeminarManage/SeminarManage.tsx` 이런 경로로 위치시키는 걸로 변경부탁드립니다!.. 인데 해당 PR은 공통컴포넌트 모달 제작 부분이니까 나중에 세미나 관리 페이지 작업하실 때 변경하는 게 좋을 것 같네요!

화면에 제대로 출력되는지 확인하기 위해 작성한 테스트용 코드는 따로 올리지 않고 로컬에 두고 확인해보는 게 좋을 것 같습니다!
해당 라인에 대한 불필요한 변경내용이 쌓이기도 하고, 실제로 해당 부분 코드 작성할 때 또 변경사항으로 잡히다보니
리뷰하는 입장에서나 추후 해당 부분 내역 확인 하게 될 일이 있을 때도 파악하기 어려울 것 같아요!

2023-01-31 02:10 UTC, mia2583 commented on .vscode/settings.json
> +}
아 헉...커밋 메세지 형식을 헷갈려서 잘못 적었네요.. 앞으로는 잘 반영하겠습니다. 이슈 번호도 달아서..
prettier는 부분은 다시 삭제하려고 했는데 놔둬야겠네요. 피드백 감사합니다~!!

2023-01-31 02:17 UTC, publdaze reviewed
Nit:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/78250089/215641513-08685663-3b4e-4278-bc54-a5c76afc0b13.png">

저희가 커밋 타입 지정한 것 중에 `design`이라는 타입이 있습니다!
올려주신 커밋중
- [feat] css 적용
- [chore] 버튼 색 수정

의 경우에는 `design` 타입을 쓰는 게 더 좋을 것 같아요!

2023-01-31 02:33 UTC, mia2583 commented on src/App.tsx
> +  );
오호...라우터를 이렇게 사용하는군요..!다시 원래대로 돌려놨습니다.

2023-01-31 02:42 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  );
넵! 나중에 세미나 관리 페이지 작업할 때 따로 수정하겠습니다. 다음부터는 코드 올릴 때 한번 더 확인해서 필요한 내용만 올리도록 하겠습니다. 
그리고 이번 pr에 올렸던 테스트용 코드 다시 삭제하려고 하는데 혹시 오히려 삭제한 것도 변경사항으로 떠서 내역 확인할 때 더 불편할까요...?

2023-01-31 02:44 UTC, mia2583 commented
아하 design 타입! 참고하겠습니다. 감사합니다~

2023-01-31 11:33 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  );
음... 다른 pr에 뜨는 것 보다는 이 PR에서 처리하는 게 더 나을 것 같아욤!

2023-01-31 13:03 UTC, koty08 approved these changes
ModalProps Interface 좋습니다~ 이대로 진행 후 추가 작업까지 잘 부탁 드리겠습니다! 👍 👍

2023-02-01 00:19 UTC, mia2583 commented on .github/pull_request_template.md
> +
커밋하기 전에 폐기했는데...소스트리가 계속 리로딩 되면서 자동으로 다시 올라갔네요...ㅜㅠ

2023-02-01 14:00 UTC, publdaze requested changes

2023-02-02 06:21 UTC, pipisebastian approved these changes
수고하셨습니다!!

2023-02-03 09:01 UTC, publdaze requested changes

2023-02-03 09:01 UTC, publdaze commented on src/components/modal/ActionModal.tsx
> +          <div dangerouslySetInnerHTML={{ __html: code }} />
[리액트 공식문서](https://ko.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)를 참고해서 말씀드리자면
일반적으로 코드에서 HTML을 설정하는 것은 사이트 간 스크립팅 공격에 쉽게 노출될 수 있기 때문에 위험하다고 합니다!
react에서 사용할 수 있도록 `innerHTML`을 대체한 `dangerouslySetInnerHTML`을 제공하고 있긴 하지만
위험하다는 건 마찬가지라 꼭 필요한 상황이 아니면 사용을 자제하면 좋을 것 같아요!

내용과 코드 부분이 다 내용 부분에 들어가는 것 같은데 두가지 합쳐서 children으로 내용 부분을 컴포넌트나 내용 text나 자유롭게 받아올 수 있도록 처리해주는건 어떨까요?

2023-02-03 09:03 UTC, publdaze commented on src/components/modal/ActionModal.tsx
> +            <span>{buttonName}</span>
앗 한 줄씩 잡고 코멘트 남겼는데 4줄이 잡혔네요..! 마지막 줄에 달아두었다고 봐주시면 감사하겠습니다! 아래 두 코멘트도 마찬가지 입니다!

2023-02-04 14:41 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +interface ModalProps {
오호 좋은 생각입니다. 수정할게요!

2023-02-04 14:49 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +          <div dangerouslySetInnerHTML={{ __html: code }} />
안 그래도 저도 사용을 위해 찾아봤는데 `dangerouslySetInnerHTML`는 보안 위험 때문에 사용을 지양하라고 하더라고요...
근데 모달 내에 다른 사용자가 자유롭게 내용을 넣을 수 있으면 좋겠다고 생각해서 결국 사용하기로 했습니다

제가 작성할 때 내용과 코드 부분을 분리한 이유는 `content`의 경우에는 단순히 글을 입력하는 용도로 사용하고 `code`는 버튼이나 셀럭터와 같이 기능을 추가할 때 사용했으면 하여 용도에 따라 분리했습니다. 
음.. 둘을 하나로 합치는 게 더 나은 것 같나요?

2023-02-05 04:46 UTC, publdaze commented on src/components/modal/ActionModal.tsx
> +          <div dangerouslySetInnerHTML={{ __html: code }} />
children으로 받아오면 내부 내용 자유롭게 받아올 수 있을거에요!

content와 code 분리하지 않고 children 컴포넌트로 받아오는게 좋을 것 같다는 의견인데,
모달 내부에서 text로 contents가 들어가지 않고 바로 버튼과 테이블로만 이루어지는 경우도 있고, 들어올 수 있는 형태가 자유롭다보니 사용하는 부분에서 어떻게 구현이 되는지 바로 확인할 수 있도록 묶어서 처리하면 어떨까 해요!

2023-02-05 09:56 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +            <span>{buttonName}</span>
아...?그러게요..?저번에도 이런 비슷한 실수를 했던 거 같은데 제가 습관 비슷하게 이렇게 태그 하나씩 더 추가하나봐요..고치겠습니다!

2023-02-05 11:08 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +            variant="outlined"
제가 `filled`로 했을 때 아래 그림처럼 해당 버튼에 마우스가 hover되었을 때 밑에 생기는 색번짐?이 싫어서 `outlined`로 했었습니다. 
- hover 하지 않을 때
![image](https://user-images.githubusercontent.com/83392142/216815313-208a3a00-31e8-40ba-a8b0-9d8d858670f4.png)
- `filled`일 때
![image](https://user-images.githubusercontent.com/83392142/216815233-f5e060eb-1466-4fa4-9467-8e978b68e8aa.png)
- `outlined`일 때
![image](https://user-images.githubusercontent.com/83392142/216815306-987576b3-8780-46f0-883c-e31da6fa7a14.png)
그 당시에는 버튼 각 디자인 요소를 custom할 수 있는지 몰라서 일단 제일 맘에 드는 `outlined`로 했는데...한번 `filled`이면서 해당 효과로 바꿀 수 있는지 찾아보겠습니다!

2023-02-05 11:11 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +            variant="outlined"
아 저희 혹시 버튼은 공통 요소로 제작 안하나요?

2023-02-06 00:46 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +          <div dangerouslySetInnerHTML={{ __html: code }} />
제가 children에 대해 몰랐어서 정확하게 이해를 못했었는데 이번에 수정하면서 알아봤더니 이런 좋은 기능이 있었군요!
이걸 쓰면 `dangerouslySetInnerHTML` 사용도 없어지네요!!
덕분에 좋은 기능 알아갑니다~~

2023-02-07 15:30 UTC, publdaze commented on src/components/modal/ActionModal.tsx
> +            variant="outlined"
공통 컴포넌트로 제작하겠습니다!

2023-02-07 15:57 UTC, publdaze approved these changes
수고하셨습니다!

폴더명 `modal` -> `Modal`으로 변경해두었습니다!
로컬에서는 폴더명 변경이 반영되지 않을 수도 있는데 변경되지 않았다면 직접 변경 부탁드립니다!

Nit : 커밋 타입으로 chore을 많이 쓰시는 것 같은데 저희 프로젝트에서는 chore 타입을
- eslint 설정, prettier 설정, 패키지 매니저 수정(ex. .gitignore), .env 파일 변경 등

이러한 경우에 사용하기로 하였습니다! 저희 프로젝트의 규칙에 맞게 타입 사용하면 좋을 것 같아요!
[개발자 가이드](https://www.notion.so/7ff764b527954408922ab7509c7c3dce#fa44bfade77941bd86ee88503e58d3c9)에 타입들 정리해두었으니 한 번 확인 부탁드려요!

2023-02-08 01:26 UTC, publdaze commented
custom 색상 적용 안 된 것 같아서 [이슈](https://github.com/KEEPER31337/Homepage-Front-R2/issues/190) 따로 생성해두었습니다!
이 PR은 공통적으로 사용되는 부분이니 먼저 머지하고 다른 작업에 영향이 안가는 custom 색상으로 변경하는 부분은 별도의 PR으로 올려줘도 될 것 같습니다!

2023-02-12 06:59 UTC, merged