Feature/테이블 공통 컴포넌트 제작 #130
KEEPER31337/Homepage-Front-R2 pull request #165
Opened 2023-01-30 06:34 UTC by publdaze

## 연관 이슈
- #130

## 작업 요약
- 테이블 row와 colomn 배열 넣으면 조회 가능하도록 구현

## 작업 상세 설명
- `column` 속성 중 `key`로 각 `column`에 매칭되는 `row` 값을 구분할 수 있도록 함.
- `column` 속성 중 `headerName`를 통해 table header에 들어가는 각 column명들을 지정할 수 있도록 함.
- `rows`는 column의 key값을 객체 `key`로 가지도록 하며, `value`로 테이블에 들어가 값을 넣도록 함.

## 리뷰 요구사항
> 15분

## Preview 이미지
<img width="728" alt="image" src="https://user-images.githubusercontent.com/78250089/215404474-de644015-fef4-4c7a-b8d3-1c9321ce166b.png">

<details>
<summary>preview 예시코드</summary>
<div markdown="1">

``` tsx
const Example = () => {
  const columns = [
    { key: 'no', headerName: '번호' },
    { key: 'title', headerName: '제목' },
    { key: 'writer', headerName: '작성자' },
    { key: 'createDate', headerName: '작성일' },
    { key: 'watching', headerName: '조회수' },
  ];

  const rows = [
    { id: 1, no: 1, title: 'Rust study 하실 분?', writer: '장서윤', createDate: '2023.01.29', watching: 32 },
    { id: 2, no: 2, title: 'Rust study 하실 분?2', writer: '장서윤2', createDate: '2023.01.30', watching: 33 },
    { id: 3, no: 3, title: 'Rust study 하실 분?3', writer: '장서윤3', createDate: '2023.01.31', watching: 34 },
  ];

  return <StandardTable columns={columns} rows={rows} />;
};
```

</div>
</details>

2023-01-30 06:42 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +  rows: Record<string, any>[];
1. row 객체의 `key`로 column의 `key property의 value`와 `id`만 들어갈 수 있도록 타입 지정하고 싶은데 정해진 값이 아니라 props로 받아오는 거라 타입을 어떻게 지정하면 좋을 지 모르겠네요.. 혹시 좋은 방법있을까요?~?

2. row의 value로는 다양한 타입의 값이 올 수 있어서 any 타입을 사용하였는데 좀 더 자유도가 낮은 `unknown` 타입을 추천하더라구요, 하지만 `unknown` 타입은 아래 24라인의 `row[column.key]` 이 코드에서 ReactNode에  unknown을 할당할 수 없다고 에러가 발생하여 any 타입으로 지정해주었습니다. 혹시 더 좋은 방법이 있다면 추천 부탁드립니다.

2023-01-30 06:52 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +        ))}
이부분 코드 부가설명 드리자면, 각 row 정보를 api에서 받아오거나 저희가 임의의 데이터를 넘겨줄 때
해당하는 column의 위치와 매번 순서를 맞춰주기 어려울 수도 있을 것 같아서
row 정보를 원하는 column에 위치하도록 하기 위해 column의 key를 매칭시켜 값을 얻도록 구현하였습니다.

2023-01-31 11:56 UTC, amaran-th approved these changes

2023-01-31 12:29 UTC, Ji-Hyeon212 approved these changes

2023-01-31 13:43 UTC, koty08 requested changes

2023-01-31 13:43 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +  rows: Record<string, any>[];
두 부분 모두 Typescript의 `Union Type` 으로 해결할 수 있습니다. 코드량이 많아지지만 좀더 Strict 하게 관리할 수 있게 됩니다.

예시로서 아래와 같이 구현이 가능합니다.
![image](https://user-images.githubusercontent.com/43947871/215775161-9e464a5d-efc0-47c8-a1fb-c496eb7a4fdd.png)
![image](https://user-images.githubusercontent.com/43947871/215775271-af6d5f44-7c20-4e4a-ba80-704c25724ab5.png)



> https://typescript-kr.github.io/pages/unions-and-intersections.html
실제로도 여러 라이브러리에서도 const한 string으로 union type을 사용하고 있습니다. ex) **stripe** typescript 코드 중 locale 관련 부분
https://www.npmjs.com/package/@stripe/stripe-js?activeTab=explore
![image](https://user-images.githubusercontent.com/43947871/215776199-23c93361-4c67-4d7b-8ed2-357f822ef660.png)

2023-01-31 13:43 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +        ))}
좋습니다~! 👍 👍

2023-02-01 05:35 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +  rows: Record<string, any>[];
Generic을 사용하면 될 것 같습니다.
> https://velog.io/@ovogmap/React-Typescript-%EC%A0%9C%EB%84%A4%EB%A6%AD-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

![image](https://user-images.githubusercontent.com/43947871/215960048-49d39441-6ba9-43f6-8eb5-a739321f3bf9.png)
![image](https://user-images.githubusercontent.com/43947871/215960090-e442602b-4244-42f4-a40f-0ab31e378e18.png)

2023-02-01 11:29 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +  rows: Record<string, any>[];
우와 Generic을 이렇게 사용하는 거였군요! 존재만 알고 있었는데 실제로 사용해보는 건 처음이네요!! 좋은 정보 감사합니다! Generic 사용해 수정해서 올려 보겠습니다!

2023-02-01 12:59 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +interface StandardTableProps<T extends Record<string, any>> {
태영님이 알려주신 Generic 타입으로 타입을 받아올 수 있도록 해두었고, 해당 타입에서 객체 형식으로만 받아올 수 있도록 한정지어주었습니다.

여기서 any타입으로 value 타입을 지정했는데 union으로 들어올 수 있을 만한 타입을 묶기에는 다양한 값이 들어올 수 있다고 판단 되었고, 다른 table 라이브러리를 참고하니 any 타입으로 row의 value값을 대게 받아오는 것 같아서 여기서는 any 타입 사용해도 괜찮지 않을까 하여 이렇게 처리하였습니다.

2023-02-01 13:02 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +const StandardTable = <T,>({ columns, rows }: StandardTableProps<T extends Record<string, any> ? T : never>) => {
이 라인에서 `extends` 뒤에 삼항 연산자를 사용하였는데 사용하지 않으면 parsing error를 반환하더라구요.
위의 interface 형식과 조금 차이가 나는게 조금 불편하긴 한데 일단 error 발생하지 않도록 반영해주었습니다.
객체형식으로 정상적으로 받아오면 받아온 `T`타입을 반환하도록 하였고 정상적으로 받아오지 않을 경우 `never` 타입을 반환하도록 처리하였습니다.

2023-02-01 13:08 UTC, publdaze commented on src/components/Table/StandardTable.tsx
> +            <TableCell key={column.key as string}>{column.headerName}</TableCell>
17, 25라인에서 이와 같이 `string` 타입이라는 것을 명시해준 이유는
column의 `key`속성 타입이 `keyof T`가 되면서 `string`, `number`, `symbol` 3가지 타입이 들어올 수 있게 되었습니다.
여기서 컴포넌트의 key값으로는 `symbol` 타입을 사용할 수 없기 때문에 column.key로 들어오게 되는 `string` 타입으로 특정지어 주었습니다.

2023-02-01 13:26 UTC, publdaze reviewed
preview 예시 코드 업데이트 해두었는데 이부분도 확인 부탁드립니다!

columns의 key마다 `as keyof IExampleRow`으로 매번 타입 지정 해주는 게 괜찮은 방법일까요?..
안 넣으면 props 전달할 때 타입 식별이 잘 되지 않아 지정해주긴 했는데 더 좋은 방법을 없을까 싶네요..!

2023-02-02 12:09 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +interface StandardTableProps<T extends Record<string, any>> {
넵 `any` 타입 사용 동의합니다!

2023-02-02 12:13 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +const StandardTable = <T,>({ columns, rows }: StandardTableProps<T extends Record<string, any> ? T : never>) => {
실제로 Parameter로 받아오는 generic `T`는 함수 앞에서 받아오기 때문에 앞의 T에 extends를 적용시키면 에러가 나지 않습니다.
![image](https://user-images.githubusercontent.com/43947871/216321329-dba43e99-2ad8-46c0-9d91-4797c4563720.png)

2023-02-02 12:17 UTC, koty08 commented on src/components/Table/StandardTable.tsx
> +            <TableCell key={column.key as string}>{column.headerName}</TableCell>
넵 좋습니다!

2023-02-02 12:48 UTC, koty08 commented
![image](https://user-images.githubusercontent.com/43947871/216329073-d9366ff9-c3c8-428f-be32-b068b6ad3f56.png)
한 줄로 다음과 같이 가능합니다.

현재는 Dummy Data라 각 행마다 `as`로 Type Casting이 필요하지만, 실제 데이터의 경우 변수로서 넘어올 것이기에 한 번만 적어줘도 가능할 것 같습니다.

2023-02-02 13:09 UTC, publdaze commented
오홍! columns 변수에 대한 타입으로 한 번에 지정해주면 되겠군요! 감사합니다!

2023-02-03 09:10 UTC, merged