Feature/메인페이지 메인화면 #116
KEEPER31337/Homepage-Front-R2 pull request #166
Opened 2023-01-30 15:23 UTC by jasper200207

## 연관 이슈
- #116 

## 작업 요약
- 메인화면에 Keeper로고 표시 및 메인 소개글 표시

## 작업 상세 설명
- tailwind.config.js에 backgroundImage를 설정하여 이미지 배경 적용
- 메인화면의 크기는 100vh로 설정하여 한 화면에 들어오도록 설정 (추후에 헤더와 사이드바가 적용될때 수정이 필요해 보임)
- img로 로고를, p로 메인 소개글 삽입 및 m-auto로 가운데 정렬

## 리뷰 요구사항
- 5분
- 너비나 높이가 반응형에 적합할지 확인 부탁드립니다.
- 가능하면 스크롤에 반응하는 에니메이션을 넣어보고 싶은데 잘 아시는 분 있나요....

## Preview 이미지
<img width="1728" alt="스크린샷 2023-01-31 오전 12 20 50" src="https://user-images.githubusercontent.com/51306225/215518234-e6515660-f308-4bf2-a387-5661c8af7918.png">

2023-01-31 14:06 UTC, koty08 requested changes

2023-01-31 14:06 UTC, koty08 commented on src/pages/home/Home.tsx
> +    <div className="flex bg-galaxy bg-contain bg-repeat">
모바일 화면에서 background-repeat시 외관상 잘려보이는 느낌이 있어, 
`<div className="flex bg-galaxy bg-cover lg:bg-contain lg:bg-repeat">` 로 수정하면 좋을 것 같습니다.
## Before
![image](https://user-images.githubusercontent.com/43947871/215782103-5169055c-e4fa-48fb-867d-9f78a2ef2b74.png)
## After
![image](https://user-images.githubusercontent.com/43947871/215782338-ec7e1551-99b4-409a-a8d2-208aa2b84e87.png)

2023-02-01 06:44 UTC, amaran-th approved these changes

2023-02-07 14:02 UTC, publdaze requested changes

2023-02-07 14:02 UTC, publdaze commented on src/pages/home/Home.tsx
> +          </p>
이부분 텍스트를 변수로 따로 빼는 건 어떨까요? 변수로 빼면 나중에 슬로건을 수정할 일이 있을 때 쉽게 변경 가능하고, 코드가 좀 더 readable 해질 것 같아요! 개행도 같은 스타일(css)을 가지는 태그를 반복할 필요 없이 string에 `\n`으로 개행 넣어줄 수 있을 것 같네요!

2023-02-22 09:58 UTC, closed without merging