Feature/스터디 페이지 UI 구성 #153
KEEPER31337/Homepage-Front-R2 pull request #171
Opened 2023-02-01 18:34 UTC by amaran-th

## 연관 이슈
#153

## 작업 요약
스터디 페이지(메인화면, 스터디 생성/수정 모달창) 레이아웃 구성

## 작업 상세 설명
- 스터디 페이지(메인화면, 스터디 생성/수정 모달창)의 전반적인 레이아웃을 구성하고, 스터디 페이지에 사용된 컴포넌트들에 프로젝트에 맞는 스타일을 적용하였습니다.
- 페이지에 사용된 컴포넌트들(button, select, accordion, chip 등)은 추후 컴포넌트들이 사용되는 유형이 확실히 정리가 되면 공통 컴포넌트로 새로 구현해보겠습니다!
- 예전 스터디 목록 페이지와 그 외 자잘한 스타일은 추후 작업할 계획입니다.

## 리뷰 요구사항
10분...? 
select 클릭 시에 border 색상이 blue-500으로 바뀌는데 이걸 변경하는 방법을 모르겠습니다! 혹시 아시는 분은 제보해주세요!
코드를 짜다보니 div와 span을 너무 많이 남발한 것 같아서, 혹시 더 깔끔하게 작성할 수 있는 방법이 있으면 알려주시면 감사하겠습니다!

## Preview 이미지
![image](https://user-images.githubusercontent.com/81465068/216130528-30182f86-e424-4273-b036-07ceef129281.png)
![image](https://user-images.githubusercontent.com/81465068/216130669-e4916cbc-b863-4c61-8dfb-11ba48800ac4.png)

2023-02-02 05:16 UTC, lcqff requested changes

2023-02-02 05:16 UTC, lcqff commented on src/pages/Study/StudyItem.tsx
> +             * */}
주석부분 지워주세요!

2023-02-02 13:21 UTC, koty08 requested changes
전체적으로 Component Props에 Type 정의하신거 ~Props로 네이밍 변경 해주시고,
const theme 으로 ThemeProvider value로 들어가는 값들에 대해서 `satisfies`키워드로 Type 설정해주시면 좋을 것 같습니다!

> Type들이 다 라이브러리에 존재하는 것 같습니다!

![image](https://user-images.githubusercontent.com/43947871/216335583-d06c192c-7611-4c41-8de9-992c27606379.png)

2023-02-02 13:21 UTC, koty08 commented on src/pages/Study/StudyItem.tsx
> +const LinkIcon = (name: string): JSX.Element => {
조건문 여러개 보단 객체로 처리하는 것도 좋을 것 같습니다~
`const LinkIconDatas = {
    github: <VscGithubInverted className="h-[28px] w-[28px]" />,
    notion: <SiNotion className="h-[28px] w-[28px]" />, ...
  }`

2023-02-02 13:21 UTC, koty08 commented on src/pages/Study/StudyModal.tsx
> +  studyId: number | null;
`null` 대신 `undefined`사용 해주세요!

2023-02-02 13:21 UTC, koty08 commented on src/pages/Study/share/StudyAccordion.tsx
> +const StudyAccodion = ({ id, headerContent, bodyContent }: StudyItemType) => {
Accodion 오타 있는것 같습니다!

2023-02-02 13:21 UTC, koty08 commented on src/pages/Study/share/StudyAccordion.tsx
> +  },
ex) satisfies 예시 `satisfies AccordionStylesType,`

2023-02-05 17:40 UTC, amaran-th commented on src/pages/Study/StudyItem.tsx
> +const LinkIcon = (name: string): JSX.Element => {
리뷰 반영하여 인덱스 시그니쳐 방식으로 구현하려고 했으나, 저희가 github과 notion 외 기타 링크가 첨부된 경우 해당 링크의 명칭을 사용자가 임의로 설정할 수 있게 하기로 해서 아래와 같이 코드를 작성해야 원래 방식과 동일하게 동작합니다....! 이런 점까지 고려했을 때 함수 방식과 객체 방식 중 어느 게 더 적절할지 의견 주시면 감사하겠습니다!
```
const LinkIconData: IconType = {
  github: <VscGithubInverted className="h-[28px] w-[28px]" />,
  notion: <SiNotion className="h-[28px] w-[28px]" />,
  etc: <VscLink className="h-[28px] w-[28px]" />,
};
...
<span>{LinkIconData[li.title] ? LinkIconData[li.title] : LinkIconData.etc}</span>
```
*li.title은 plato가 될 수도 있고 blog가 될 수도 있습니다

2023-02-05 17:40 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +  },
혹시 어떻게 사용할 수 있는지 사용 예시 보여주실 수 있나요??
적용해보려고 했는데 방법을 잘 모르겠어서 자꾸 에러가 뜨네요...!
![image](https://user-images.githubusercontent.com/81465068/216835827-ccb5fb30-9a70-4cfc-8e08-e69dd0e77df0.png)

2023-02-06 11:53 UTC, koty08 commented on src/pages/Study/share/StudyAccordion.tsx
> +  },
아 혹시 import 누락되었나요?
![image](https://user-images.githubusercontent.com/43947871/216964797-b5ebf685-4f83-4226-bb47-b6d969936d50.png)

2023-02-06 11:56 UTC, koty08 commented on src/pages/Study/StudyItem.tsx
> +const LinkIcon = (name: string): JSX.Element => {
아아 혹시 그럼 github, notion, 그리고 그 외 이렇게 3개밖에 없는 경우인건가요?

2023-02-06 11:58 UTC, amaran-th commented on src/pages/Study/StudyItem.tsx
> +const LinkIcon = (name: string): JSX.Element => {
네네!

2023-02-06 12:01 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +  },
아뇨...! import문 넣어줬는데도 이러네요...
에러는 아래와 같이 뜹니다!
![image](https://user-images.githubusercontent.com/81465068/216966258-e3dc46b0-5564-471d-857f-dd36ebb2824b.png)

2023-02-06 12:41 UTC, lcqff approved these changes

2023-02-07 15:28 UTC, publdaze requested changes

2023-02-07 15:28 UTC, publdaze commented on src/pages/Study/StudyItem.tsx
> +                <span className="underline">{capitalize(li.title)}</span>
`capitalize` 의도는 좋은 것 같습니다!
기획자 입장에서 말씀드리자면 형태를 강제하지 않고 사용자에게 자유롭게 쓸 수 있도록 하면 좋을 것 같습니다!
예를 들어 `HackCTF`라고 적고 싶은데 `Hackctf`로 자동 변환되어 원하는 형태 나오지 않으면 아쉬운 부분이 생길 것 같아요!
(추신, 이런 부분은 구현하기 전 기획자와도 한 번 얘기 나눠보면 좋을 것 같네요 😄)

2023-02-07 15:28 UTC, publdaze commented on src/pages/Study/StudyModal.tsx
> +                        console.log('xxx');
`console.log`는 제거하고 올려주면 좋을 것 같습니다!

2023-02-07 15:28 UTC, publdaze commented on src/pages/Study/share/StudyAccordion.tsx
> +        <AccordionHeader className="h-[80px]" onClick={() => handleOpen(id)}>
`open`하는 부분에 `id`값으로 따로 비교 후 open 해주는 이유가 있나요?
Accodion이 여러번 호출되어 각 Accodion이 열리는 걸 구분해주기 위해서였다면
이미 key로 구분되고 있어서 별도의 id로 다시 체크해줄 필요 없을 것 같습니다!

2023-02-14 00:49 UTC, amaran-th commented on src/pages/Study/StudyItem.tsx
> +                <span className="underline">{capitalize(li.title)}</span>
넵 알겠습니다!

2023-02-14 00:50 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +const StudyAccodion = ({ id, headerContent, bodyContent }: StudyItemType) => {
넵 수정하겠습니다~!

2023-02-14 00:51 UTC, amaran-th commented on src/pages/Study/Study.tsx
> +    </div>
헉 그런 기능이 있는지 몰랐네요...! 앞으론 그렇게 하겠습니다!

2023-02-14 04:52 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +        <AccordionHeader className="h-[80px]" onClick={() => handleOpen(id)}>
그 혹시 제가 이해가 잘 안된 것 같은데 그럼 open엔 어떤 요소를 넣으면 될까요...?? true/false로 설정해주면 동작을 안 하더라구요..! 안넣으면 에러가 발생하구요

2023-02-14 05:51 UTC, publdaze commented on src/pages/Study/share/StudyAccordion.tsx
> +        <AccordionHeader className="h-[80px]" onClick={() => handleOpen(id)}>
```tsx
const Icon = ({ open }: ArrowIconProps) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={`${open ? 'rotate-180' : ''} h-[20px] w-[20px] transition-transform`}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
    >
      <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
    </svg>
  );
};

const StudyAccordion = ({ headerContent, bodyContent }: AccordionProps) => {
  const [open, setOpen] = useState(false);

  const handleOpen = () => {
    setOpen((prev) => !prev);
  };

  return (
    <ThemeProvider value={theme}>
      <Accordion open={open} icon={<Icon open={open} />}>
        <AccordionHeader className="h-[80px]" onClick={() => handleOpen()}>
          {headerContent}
        </AccordionHeader>
        <AccordionBody className="space-y-[30px] py-[30px] px-[41px]">{bodyContent}</AccordionBody>
      </Accordion>
    </ThemeProvider>
  );
};
```

boolean으로 이렇게 구현하시면 될 것 같아요!

2023-02-14 13:44 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +        <AccordionHeader className="h-[80px]" onClick={() => handleOpen(id)}>
아항...!! 감사합니다! 코드에 반영할게요~~!

2023-02-14 17:20 UTC, amaran-th commented on src/pages/Study/StudyModal.tsx
> +                        console.log('xxx');
아 그거 나중에 현재 선택된 회원들 배열에서 해당 회원을 제거하는??그런 함수 동작 구현하려고 만들어둔건데 일단 틀만 잡아둔거라 아무 동작이나 집어넣은겁니다...! 비워두니까 eslint 오류가 뜨더라구요! 나중에 데이터 하드코딩해서 구현해놓고 다시 푸시할게요!

2023-02-15 00:42 UTC, publdaze commented on src/pages/Study/StudyModal.tsx
> +                        console.log('xxx');
아하 그렇군요!
빈 함수 미리 선언해둘 때 `// TODO`로 해두면 어떨까하는데 슬랙에 한 번 제안해보겠습니다!

2023-02-28 04:42 UTC, amaran-th commented
슬슬 api 관련 코드도 작성해야 하고, 디자인은 계속 변경사항이 있어서 디자인이 최종적으로 완성될때까지 열어두는 것보단 이 풀리퀘는 이쯤에서 머지하고 추후 디자인적인 수정사항은 따로 이슈를 파서 진행하는 게 더 좋을 것 같습니다!

2023-03-01 15:18 UTC, publdaze approved these changes
리팩토링 구조적으로 크게 변할만한 부분은 거의 해둔 것 같아서 이정도만 처리해두고 approve 해두겠습니다. 제가 리팩토링 한 부분 중에 의아한 부분 있으면 얼마든 질문 주세요!

추후 공통 컴포넌트 사용하여 제거될만한 컴포넌트는 그대로 share 폴더 내부에 두었고 추가 작업하면서 또 수정될만한 부분은 리팩토링 하지 않았으니 참고해주세요!

2023-03-01 17:14 UTC, amaran-th commented on src/pages/Study/share/StudyAccordion.tsx
> +  },
해결 되었습니다!

2023-03-02 02:05 UTC, koty08 approved these changes

2023-03-03 09:37 UTC, merged