Feature/세미나관리 페이지 UI
KEEPER31337/Homepage-Front-R2 pull request #173
Opened 2023-02-02 14:28 UTC by mia2583

## 연관 이슈
#120 #135

## 작업 요약
- 세미나 관리 페이지의 전체 UI를 구성
- 추가 버튼 클릭 시 새로운 세미나 추가

## 작업 상세 설명
- 세미나 관리 페이지 UI
- 세미나 버튼 클릭 시 "출석 전"으로 채워진 새로운 세미나(열) 추가

## 리뷰 요구사항
15-20분
- 현재 임시로 데이터 구조를 생성한 후 해당 데이터는 커밋에 포함하지 않았기 때문에 코드 실행하면 에러가 납니다. 
- 임시로 사용한 데이터의 구조와 내용은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/83392142/216351533-1f32ba7f-a4f0-4f04-8716-b1fead641388.png)
![image](https://user-images.githubusercontent.com/83392142/216351195-145e3d08-6e03-4687-a449-29efec35cb50.png)
![image](https://user-images.githubusercontent.com/83392142/216351394-ccaacab8-0ac6-4cca-bb95-be2e74fca985.png)

## Preview 이미지
현재 테이블의 글자색이 어둡고 배경도 어두워서 잘 안보입니다..
![image](https://user-images.githubusercontent.com/83392142/216351786-be0fe71b-e374-438d-80d2-1b701e2c18e7.png)

2023-02-07 11:58 UTC, publdaze requested changes

2023-02-07 11:58 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  ]);
혹시 여기 자동으로 줄바꿈 된건가요? 제 환경에서는 prettier에 이부분 줄바꿈 없도록 처리 하더라구요! 확인 부탁드립니다!

2023-02-07 11:58 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +          <div className="h-full w-full max-w-[1080px] border border-black bg-white">
레이아웃 임시로 작성한 부분인 것 같은데 이런 부분은 커밋할 때 제외하고 올려주면 좋을 것 같네요!
소스트리에서 코드의 일부만 선택하여 스테이지에 올릴 수 있으니 참고해주세요!
<img width="479" alt="image" src="https://user-images.githubusercontent.com/78250089/217233804-b771e236-efde-47fa-9c0f-41c635b6e0c4.png">

2023-02-07 11:58 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +          <div className="h-full w-full max-w-[1080px] border border-black bg-white">
이제 레이아웃도 develop에 올라간 상태라 그것도 pull 받아서 적용해주면 좋을 것 같아요!

2023-02-07 11:58 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +            <SeminarContent />
위의 임시 레이아웃을 빼면 따로 `Seminarcontent` 컴포넌트로 구분하지 않아도 괜찮을 것 같은데 `SeminarContent` 컴포넌트의 내용 `SeminarManage` 컴포넌트 내부로 옮기는 건 어떨까요?

2023-02-07 11:58 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
state와 handler 사이에 개행으로 구분해주면 더 보기 좋을 것 같아요!

2023-02-07 11:59 UTC, publdaze commented
테이블 css 관련해서 아직 처리하지 않았는데 빠른 시일 내에 처리해서 올려두겠습니다!

2023-02-07 12:49 UTC, publdaze commented
임시로 목업 데이터 구조 생성한 건 올려줘도 괜찮을 것 같습니다!
제가 [예전 PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/164#discussion_r1091349616)에 테스트용 코드는 제외하고 올려달라고 해서 이부분도 빼고 올린 건 아닐까 싶긴한데, 그 경우는 해당 코드가 없어도 코드가 실행되기도 하고 작업하는 컴포넌트가 아닌 작업한 부분과 관련이 없는 부분에 작성된 코드여서 제외해달라고 했었습니다!

하지만 이 경우는 해당 데이터가 없으면 에러가 발생하는 상황이라 포함하는게 더 좋을 것 같아요! 작동하지 않는(에러가 발생하는) 코드를 커밋하면 해당 커밋에 접근하여 코드를 실행해볼 경우 코드가 동작하지 않아 해당 커밋 상태를 파악하기 어려울 것 같아요!

목업 데이터가 작업하시는 파일 변경 사항으로 잡히는 부분이 우려되면 별도록 목업 데이터만 모아두는 파일 생성해서 넣어두어도 괜찮을 것 같은데 슬랙에 한 번 얘기해보겠습니다

2023-02-09 03:54 UTC, jasper200207 requested changes

2023-02-09 03:54 UTC, jasper200207 commented on src/components/modal/ActionModal.tsx
> +  const handleOpen = () => setOpen(!open);
useState의 set함수는 비동기 처리로 알고있습니다. 그래서 `setOpen((prev)=>!prev))` 의 형태로 이전상태의 의존하여 바꾸는 것이 좋아보입니다.

2023-02-09 03:54 UTC, jasper200207 commented on src/pages/admin/SeminarManage.tsx
> +    );
위와 같은 이유로 `setListColumns((prev) => [...prev, {}]` 와 `setListRows((prev) => prev.map((row) => {});` 의 형태가 좋아보입니다.

2023-02-12 07:29 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  ]);
아 원래 코드에는 그 사이에 있던 임시 데이터 부분을 빼고 올리다보니 저렇게 따로 줄바꿈 형식으로 올라갔습니다!

2023-02-12 07:35 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +          <div className="h-full w-full max-w-[1080px] border border-black bg-white">
저 부분은 기본적으로 있으면 유용할 거 같아서 일단 올리기는 했는데...이후 코드 수정하면서 계속해서 남아있을지는모르겠네요. 일부 코드 선택, 참고하겠습니다!

2023-02-12 07:40 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +            <SeminarContent />
네넹 임시 레이아웃 때문에 구분한거라 이 부분도 이름이랑 내용 다 수정해서 다시 커밋 올리겠습니다.

2023-02-12 07:53 UTC, mia2583 commented on src/components/modal/ActionModal.tsx
> +  const handleOpen = () => setOpen(!open);
이 부분은 세미나 UI 페이지 부분이 아니라 기존의 ActionModal에서 작성한 코드를 pull로 받아온 거라 해당 부분에서 수정해서 새 PR올리겠습니다.

2023-02-12 08:22 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +    );
넵 수정했습니다~!!
앞으로도 set함수 작성할 때 참고 하겠습니다!

2023-02-12 13:33 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
네엥!이 부분은 따로 커밋을 넣는 것보다는 세미나 추가, 삭제 페이지를 개발하면서 자연스럽게 반영하는 방식으로 진행할게요!

2023-02-12 16:25 UTC, publdaze requested changes
develop 한 번 pull 받아줘야할 것 같습니다!

2023-02-12 16:39 UTC, publdaze requested changes

2023-02-12 16:39 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
저희가 세미나 추가하는 부분 로직은 프론트에서 처리하는 게 아닌 백엔드단에서 처리가 됩니다!
그래서 해당 함수에서 별도의 로직은 넣지 말고 세미나 추가 API 호출하는 것만 처리해주면 될 것 같아요
일단 해당 PR은 UI PR이니 이 PR에서 바로 API 처리하기 보다는 그냥 비워주는 게 좋을 것 같습니다!

빈 함수로 eslint 에러나면 아래 이미지처럼 해두어도 괜찮을 것 같습니다
<img width="255" alt="image" src="https://user-images.githubusercontent.com/78250089/218323594-7325e1d2-3607-4c26-8439-3b59c96bcf59.png">

2023-02-13 12:25 UTC, koty08 approved these changes
좋습니다!

2023-02-15 08:47 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-02-18 05:39 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
임시 데이터들 모두 mocks쪽으로 옮기고 세미나 추가 코드도 삭제했습니다.

2023-02-19 06:07 UTC, publdaze commented
명서님과 얘기 후 일부 리팩토링 제가 진행하였습니다!
대부분 develop에 추가된 컴포넌트 반영 위주로 진행하였습니다!
@mia2583 혹시 해당 커밋들 보고 이상한 부분 있으면 말씀 부탁드립니다!

2023-02-19 06:10 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +      <PageTitle>세미나 관리 {`(${currentTerm.year}년 ${currentTerm.season})`}</PageTitle>
이부분은 변하는 데이터이기 때문에 처음 임시로 하드코딩 해둘 때도 따로 변수로 미리 처리해주면 추후 받아온 데이터 처리하기 더 용이할 것 같아서 이렇게 리팩토링 해두었습니다!

2023-02-19 06:10 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const currentTerm = { year: 2023, season: '1학기' }; // TODO - 임시데이터
일단 임시데이터로 이렇게 해두었는데 학기 정보 받아올 때 어떤 dto로 보내주는 지는 백엔드 쪽과 얘기해보고 그에 맞춰 수정하면 될 것 같습니다!

2023-02-19 06:55 UTC, publdaze requested changes

2023-02-19 06:55 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
이벤트 핸들러 함수의 경우 handle이라는 prefix가 붙으면 좋을 것 같아요! ([참고](https://jaketrent.com/post/naming-event-handlers-react/))
그리고 `addSeminar`라는 함수명은 결과에 중점을 둔 함수명이고 보통 이벤트 핸들러 함수명에 대해 찾아봤을 때 주로 쓰는 것 같아 보이는 `접두사(handle) + 명사(컴포넌트) + 동사(이벤트)` 형태는 원인?에 중점을 둔 함수명인 것 같아서 어떤 식으로 함수명을 작성하면 좋을 지 고민되는 부분인 것 같아요!
후자의 경우 예시로 세미나 추가 버튼 클릭 시 동작이라는 의미로 `handleAddSeminarButtonClick`이런 느낌일 것 같아요! (어순이.. `handleSeminarAddButtonClick` 이게 맞는지 앞에 적은 게 맞는지 잘 모르겠어서 이부분은 감안 부탁드립니다..!)

2023-02-20 13:34 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
혹시 이벤트 핸들러 함수랑 그냥 함수랑은 무슨 차이인가요? 뭔가 의미론적으로는 알겠는데 막상 코드에 적용하려니 명확하게 잘 구분이 안되어서 여쭤봅니다.

이벤트 핸들러 함수명은 handleSeminarAddButtonClick로 좋은 거 같네요! 기능이 이름에서 확실히 명시 되는 거 같아서 좋습니다.

2023-02-20 13:34 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
그리고 추가로 궁금한 점이 있습니다!
사실 가끔 함수나 변수명이 너무 길어질 때 그대로 사용할지 줄일지 고민을 하게 되던데 이름이 긴 것은 아무 문제가 되지 않는 건가요?

2023-02-20 13:39 UTC, mia2583 commented
해당 기능들의 생각나는 부분만 리팩토링하다보니, 앞선 수정으로 쓰이지 않아 불필요하게 남은 코드가 생각보다 많네요.
리팩토링 후에 마지막으로 전체 코드를 보는 습관도 길러야겠습니다..!!

2023-02-21 09:39 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
이벤트 핸들러 함수의 경우 버튼 클릭 같은 이벤트를 다루는 함수라고 보면 될 것 같아요!
사용자의 동작으로 인한 부분을 처리해준다고 볼 수 있겠네요!
저희가 개발 상의 작업을 용이하게 하기 위해서 사용하는 함수가 아닌 사용자와의 상호작용에 관련된 부분은
대부분 이벤트 핸들러라고 보시면 될 것 같아요!

2023-02-21 10:14 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
아무래도 변수명이 짧으면 기억하기 쉽고, 한눈에 들어오니 디버깅하기에도 좋다는 장점이 있는 것 같습니다.
하지만 짧은 이름으로 변수의 의도를 다 표현하지 못해 변수의 역할을 파악하기 어려운 경우는
변수의 의미를 분명히 밝힐 수 있다면 길고 서술적인 이름이 훨씬 낫다고 볼 수 있을 것 같아요.
다만 너무 긴 이름은 입력하기 어렵고 소스코드의 외관 구조를 모호하게 만들 수 있다고 하니 적당히 잘 조율해서 사용하는 게 좋겠죠!

줄일 지 고민은 해보되, 충분한 의미를 전달할 수 있도록은 남겨두자 정도로 정리하고 넘어가겠습니다!

2023-02-22 07:45 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const addSeminar = () => {
넹 알려줘서 감사합니다!
수정했습니닷

2023-02-22 14:40 UTC, publdaze approved these changes
수고 많으셨습니다~!~! 👍👍

2023-02-23 06:04 UTC, merged