Feature/api 받아오는 기본 틀 생성 #177
KEEPER31337/Homepage-Front-R2 pull request #188
Opened 2023-02-06 10:04 UTC by publdaze

## 연관 이슈
- Close #177 

## 작업 요약
- `react query`와 `axios`를 사용하여 API 호출 및 관리가 가능하도록 처리

## 작업 상세 설명
- `react query`와 `axios` 설치 및 사용가능 하도록 세팅
- 구현 방식을 보여주고자 about API 부분 코드 작성

## 리뷰 요구사항
10분, 폴더 구조 및 변수명 타입 처리 방식 부분 중점적으로 봐주시면 좋을 것 같습니다!

2023-02-06 10:06 UTC, publdaze commented on src/api/aboutApi.ts
> +});
커밋 올릴 때 체크 못하고 올려버렸네요...ㅠ
이부분 무시해주시면 됩니다..! (나중에 있는 커밋에서 삭제됩니다!)
다음부터 주의해서 올리겠습니다!

2023-02-06 10:11 UTC, publdaze commented on src/api/aboutApi.ts
> -});
첫번째 커밋에서 잘못들어간 부분 해당 커밋에서 삭제하였습니다!
무시하고 넘어가주시면 됩니다! 다시 한 번 커밋 올릴때 유심히 보지않고 그냥 올린 점 사과드립니다..!

2023-02-06 12:21 UTC, koty08 requested changes

2023-02-06 12:21 UTC, koty08 commented on src/api/aboutApi.ts
> +  return useQuery<string[]>('titleType', fetcher);
react-query에서 queryKey를 객체로 관리하면 유지보수에 용이합니다!
https://www.zigae.com/react-query-key/#%EA%B0%9D%EC%B2%B4%EB%A1%9C-key-%EA%B4%80%EB%A6%AC

2023-02-07 13:32 UTC, publdaze commented on src/api/aboutApi.ts
> +  return useQuery<string[]>('titleType', fetcher);
오호! 확실히 직접 하드코딩 하는 것 보다 유지보수에 용이해보이네요! 👍
객체 key를 어떻게 둬야할 지 감이 잘 안 잡히는데 제 코드에서 적용한다면
그냥 queryKey와 동일하게 객체 key를 둬도 괜찮을까요?

```ts
const aboutKeys = {
  titleType: ['titleType'] as const,
  blockList: ['blockList'] as const
}
```

2023-02-08 12:02 UTC, koty08 commented on src/api/aboutApi.ts
> +  return useQuery<string[]>('titleType', fetcher);
넵 위에 작성하신 예시대로 진행하시면 될 것 같습니다!

2023-02-08 12:17 UTC, publdaze commented on src/api/aboutApi.ts
> +  return useQuery<string[]>('titleType', fetcher);
반영했습니다!

2023-02-09 03:59 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-02-09 12:42 UTC, koty08 approved these changes

2023-02-10 04:45 UTC, mia2583 approved these changes
리뷰 늦어서 죄송합니다...수고하셨습니다!

2023-02-10 04:50 UTC, mia2583 reviewed
오홍..react Query로 이러한 사항들도 설정할 수 있군요.  생각보다 커스텀이 자유롭네요!

2023-02-10 06:21 UTC, merged