Feature/도서관리 페이지 UI #145
KEEPER31337/Homepage-Front-R2 pull request #215
Opened 2023-02-15 05:58 UTC by pipisebastian

## 연관 이슈
Close #145

## 작업 요약
도서관리 페이지(/admin/libraryManage) UI를 구성

## 작업 상세 설명
- develop의 공통컴포넌트(공통 페이지 제목, 버튼, 테이블)등 최신으로 적용했습니다!

## 리뷰 요구사항
1분

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/218944113-b5eb632e-062b-418e-9514-f882f71641c4.png)

## etc
모달창 4개(도서추가, 삭제, 대출관리, 반납관리)는 다른 이슈로 작업하기위해, 먼저 풀리퀘 올립니다!
material tailwind select는 나중에 은지님 공통컴포넌트 만드시면 교체하겠습니다!

2023-02-15 12:36 UTC, koty08 requested changes

2023-02-15 12:36 UTC, koty08 commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +  return enable === true ? (
`boolean`형식이라 `=== true` 는 제외하셔도 될 것 같습니다!

2023-02-15 12:36 UTC, koty08 commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +          <div className="flex w-fit space-x-2">
8px 간격 통일 확인 했습니다!

2023-02-15 14:31 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +  return enable === true ? (
넵 수정했습니다!

2023-02-16 05:14 UTC, mia2583 approved these changes
오옹 수고하셨습니다!!

2023-02-16 09:52 UTC, koty08 approved these changes

2023-02-17 13:47 UTC, publdaze requested changes

2023-02-17 13:47 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +            <OutlinedButton onClick={() => console.log('OutlinedButton')}>반납 관리</OutlinedButton>
특별한 이유가 없는 이상 콘솔 출력한 부분은 제거하고 올려주세요..ㅠㅠㅠ

불필요한 코드이기도 하고 훗날 해당 커밋으로 돌아와 디버깅할 시에 불편을 초래할 수도 있습니다.
해당 부분의 경우에는 동작을 추후 구현할 부분이니까 당연히 나중에 수정되겠지만
미처 발견하지 못하는 부분에 console.log가 남아있으면 보안 이슈가 발생할 수도 있고 사용자 입장에서 
개발자가 신경을 안 썼다는 느낌을 받을 수도 있습니다.
또한 콘솔 출력이 메모리 누수의 원인이 될 수도 있다고 하니 더 조심하는게 좋을 것 같네요! ([참고](https://ui.toast.com/posts/ko_20210611#4-%EC%BD%98%EC%86%94-%EC%B6%9C%EB%A0%A5))

혹시 나중에 구현할 함수 비워두고 싶은데 eslint 에러나는 것 때문에 이렇게 해두신 거면
제가 이전에 슬랙으로 남겨둔 아래 내용처럼 해두면 어떨까합니다!
<img width="631" alt="image" src="https://user-images.githubusercontent.com/78250089/219666727-b72e5341-ebe4-4139-9efb-ce153aa7cc05.png">

2023-02-17 13:47 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +        {/* 테이블 */}
이미 코드로 충분히 테이블이라는 게 설명 되는 것 같아서 이부분은 주석 제거해줘도 될 것 같아요!
[JS 클린코드 주석에 대한 글](https://velog.io/@hojin11choi/JS-Clean-Code-%EC%A3%BC%EC%84%9D)인데 한 번 읽어보면 좋을 것 같아요!

2023-02-17 13:50 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      bookEnable: <BookEnableText enable={false} />,
리뷰 달 때 코드 한 줄만 잡고 달았는데 4줄이 잡히네요...ㅠㅠㅠ
마지막 줄에 해당하는 리뷰입니다..! 아래에도 4줄 잡힌 건 대부분 마지막 줄에 대한 리뷰라고 봐주시면 될 것 같아요..!

2023-02-22 10:57 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      bookEnable: <BookEnableText enable={false} />,
넵! 수정해서 커밋 날렸습니다!

2023-02-22 10:59 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      checkboxEnable: <Checkbox />,
넵! 일단 이번거 머지하고, 다음에 체크박스 은지님이 만드시면 따로 이슈파서 작업하겠습니다!

2023-02-22 11:06 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +}
저게 테이블에 들어가는 row정보이고, api로 받아오는 row랑은 다를것같은데
 
예를들어 api에는 (도서전체개수, 대여된 책의개수) 변수 2개를 가져오는데, 
테이블상에서는 따로 처리를 해줘, (대여된 책의개수/도서전체개수) 변수1개로 만들것같습니다!

이런 경우에는 api row 가 아닌, 테이블 row정보를 dto에 넣어주면 될까요??

2023-02-22 11:50 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +            <OutlinedButton onClick={() => console.log('OutlinedButton')}>반납 관리</OutlinedButton>
아앗 넵넵!!

2023-03-01 16:05 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +}
두 변수가 해당 api를 통해 받아와 개별적으로 사용되는 부분이 없다면 백엔드 쪽에 합쳐서 보내줄 수 있는 지 요구해보거나 
아니면 api 받아오는 부분 작성할 때 then 내부에서 원하는 데이터 형식으로 가공해주면 될 것 같아요!

아래는 메인페이지에 사용하는 api이긴한데 then부분 어느 부분 말하는 건지 예시로 보여주기 위한 이미지입니다.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/78250089/222195192-49df71b1-e55d-45d1-b763-3b00a236e6de.png">

결론적으로는 테이블 row정보를 dto에 넣어주면 되지 않을까 싶습니다!

2023-03-02 06:57 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +              <Option>저자</Option>
혹시 이부분은 selector 공통컴포넌트 머지후에 따로 이슈파서 올려도될까요?

2023-03-02 07:42 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +          </div>
넹! 분리했씁니다!

2023-03-02 07:43 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +        {/* 테이블 */}
넹!! 클린코드.. 어렵습니다,,

2023-03-02 07:43 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +}
감사합니다!! 
임시데이터 mocks에 넣는것도 같이 했는데, 확인부탁드립니다!

2023-03-02 12:43 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +              <Option>저자</Option>
넵! 👍

2023-03-02 13:00 UTC, publdaze requested changes

2023-03-02 13:00 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +  const childComponent = ({ key, value, rowData }: ChildComponent<BookListInfo>) => {
`rowData` 안 쓰이는 것 같은데 제거 부탁드립니다!

2023-03-02 13:47 UTC, publdaze requested changes

2023-03-02 13:47 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +          <SearchBook />
SearchBook 컴포넌트의 경우에는 현재 태영님이 작업중인 공통 컴포넌트 `@component/Section/SearchSection`이 구현되면 해당 컴포넌트 사용하면 좋을 것 같습니다!

2023-03-02 13:47 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +        <div className="flex h-fit w-full justify-between">
여기서 h-fit 클래스를 제거해도 보여지는 UI는 동일한데 `h-fit`을 사용한 이유가 있을까요?

2023-03-02 14:30 UTC, publdaze requested changes

2023-03-02 14:30 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      </div>
여기서 28, 39라인의 div 한 계층 제거하고 29라인에 `mb-5`를 넣어주는 방식으로하면 더 깔끔할 것 같아요!
추가로 29라인에 검색 섹션과 버튼 색션을 중앙 라인에 맞춰주도록 `items-center` 클래스도 추가하면 좋을 것 같네요!

2023-03-02 15:22 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      </div>
오 너무 좋습니다!!

2023-03-02 15:24 UTC, publdaze requested changes

2023-03-02 15:24 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +          <div className="h-fit w-fit text-subGray">대출불가</div>
이 부분에 사용되는 `h-fit` `w-fit`도 필요한 게 아니면 제거해도 괜찮을 것 같아요!

2023-03-02 15:24 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      </div>
왕 깔끔해졌네요!!! 감사합니다!

2023-03-02 15:33 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +          <div className="h-fit w-fit text-subGray">대출불가</div>
쑤정했습니다!!

2023-03-02 15:52 UTC, publdaze approved these changes

2023-03-02 15:52 UTC, publdaze commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      <div className="mb-5 flex w-full items-center justify-between ">
className 끝부분에 공백 하나 들어간 것만 제거해주고 마무리하면 될 것 같아요! 수고하셨습니다~~! 👍

2023-03-02 16:15 UTC, pipisebastian commented on src/pages/admin/LibraryManage/LibraryManage.tsx
> +      <div className="mb-5 flex w-full items-center justify-between ">
왕 꼼꼼하십니다!! 넹!!!

2023-03-02 16:16 UTC, merged