feat : 모달 열림 여부 props로 전달하도록 확장
KEEPER31337/Homepage-Front-R2 pull request #219
Opened 2023-02-15 08:20 UTC by pipisebastian

## 연관 이슈
- #217 #131 

## 예제코드 
모달창 사용하는 컴포넌트에서 추가하면 됩니다.

`const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(!open);
  return (
    <div>
      <FilledButton onClick={() => handleOpen()}>도서 추가</FilledButton>

      <ActionModal
        open={open}
        handleOpen={handleOpen}
        title="도서추가"
        buttonName="추가"
        onClick={() => {
          console.log('1');
        }}
      >
        컨텐츠입니다
      </ActionModal>
    </div>
  );`
  
## 작업 요약
- 기존에는 모달창 컴포넌트안에서 열림여부 state를 관리했는데, 이를 모달창 사용하는 외부에서 관리하도록 수정
- 확인버튼을 누를때 props로 넘겨준 함수(기존) +모달창 닫기함수 추가.

## 작업 상세 설명
- 모달창 컴포넌트 내부
![image](https://user-images.githubusercontent.com/81643702/218971261-ade84647-30c1-4021-8bb0-65696e5d17e5.png)
내부에서 관리하던 state삭제, 외부로 옮김
![image](https://user-images.githubusercontent.com/81643702/218971369-56decf4e-9f96-4693-b9d0-a45608c5facc.png)
모달창 닫기함수 추가

## 리뷰 요구사항
- 3분
- 모달창 쓰고싶습니다! 리뷰 부탁드립니다!

2023-02-15 12:37 UTC, koty08 requested changes

2023-02-15 12:37 UTC, koty08 commented on src/components/Modal/ActionModal.tsx
> +  open: boolean;
open 여부를 나타내는 `boolean` 값이면 변수명을 opened로 하는것이 더 명확할 것 같습니다!

2023-02-15 14:39 UTC, pipisebastian commented on src/components/Modal/ActionModal.tsx
> +  open: boolean;
넵 수정했습니다!! 감사합니다~!

2023-02-16 05:15 UTC, mia2583 approved these changes
좋습니다~~제가 놓쳤던 부분 잘 보완해주셔서 감사합니다!

2023-02-16 09:54 UTC, koty08 approved these changes

2023-02-17 07:11 UTC, publdaze commented
추가적으로 해당 변경 사항에 대한 부분은 아니지만 예제 코드 부분에 대해 한가지 말씀드리고 싶은 부분이 있는데

`setOpen`을 사용하여 충분히 `open` state를 제어할 수 있는데 따로 핸들러를 두는게 과하다는 생각이 조금 들어요. 더 간단하게 구현하는 방법으로 `useReducer`라는 리액트 훅을 사용해보는 거 추천 드립니다! ([참고](https://www.philly.im/blog/things-to-know-about-use-state#%EB%B3%B4%EB%84%88%EC%8A%A4-2-usereducer%EB%A1%9C-state-%ED%86%A0%EA%B8%80-%ED%95%98%EA%B8%B0))

위의 예제 코드를 `useReducer` 훅을 사용하면 이렇게 바꿀 수 있습니다!

``` tsx
const [open, toggleOpen] = useReducer((prev) => !prev, false);

  return (
    <div>
      <FilledButton onClick={toggleOpen}>도서 추가</FilledButton>

      <ActionModal
        opened={open}
        handleOpen={toggleOpen}
        title="도서추가"
        buttonName="추가"
        onClick={toggleOpen}
      >
        컨텐츠입니다
      </ActionModal>
    </div>
  );
```

2023-02-18 07:44 UTC, pipisebastian commented on src/components/Modal/ActionModal.tsx
> +              handleOpen();
아항 너무 조씁니다~!

2023-02-18 08:05 UTC, pipisebastian commented
> 

너무 좋습니당!! 알아갑니다!! 예제코드 수정해놓겠습니다!

2023-02-21 11:14 UTC, publdaze approved these changes
수고 많으셨습니다! 👍👍

2023-02-22 08:24 UTC, merged