Feature/세미나 출석 회원 UI #207
KEEPER31337/Homepage-Front-R2 pull request #224
Opened 2023-02-15 09:59 UTC by lcqff

## 분류
- [ ] 기능 추가

## 연관 이슈
 #207 

## 작업 요약
회원 권한의 출석 페이지 ui 

## 작업 상세 설명
> 

## 리뷰 요구사항
5분
권한 구분하는 api가 없어서 일단 버튼으로 구분 해놨습니다
commit중에 이슈 번호 안 달고 보낸 게 있는데 수정을 못했습니다ㅠㅠ 
input을 meterial tailwind말고 그냥 input 사용했는데 meterial tailwind 사용해서 다음 input으로 자동으로 넘겨주는 기능을 어떻게 넣어야 할지 모르겠어서 일반 input 사용했습니다. 

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/218995065-4e0e83b9-39eb-4e1a-a24a-021abcdf7933.png)

2023-02-16 10:02 UTC, koty08 approved these changes

2023-02-20 07:20 UTC, jasper200207 approved these changes

2023-02-20 16:58 UTC, publdaze requested changes
luxon 쓰는데 @types/luxon 적용 안 되어 있어서 에러 뜨네요! 지금 develop에 해당 라이브러리 설치된 거 머지되어 있으니 풀 받아주세요!

2023-02-21 04:16 UTC, publdaze requested changes

2023-02-21 04:16 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        )}
이부분은 기획에는 없는 버튼인 것 같습니다!

2023-02-21 04:16 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +      <PageTitle>세미나 출석체크</PageTitle>
페이지 제목도 기획 상으로는 `세미나 출석`으로 되어 있는데 확인 부탁드립니다!

2023-02-22 06:48 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        )}
아직 api 적용 전이라 편의를 위해서 나눠놨습니다! 개발 끝난 후에 지우겠습니다!

2023-02-22 14:26 UTC, publdaze requested changes

2023-02-22 14:26 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
`DoAttend`, `SetSeminar` 두가지 컴포넌트를 추가해주셨던데 컴포넌트 이름이 잘 와닿지 않는 것 같아요 🤔
해당 컴포넌트의 동작보다는 해당 컴포넌트가 무엇인지에 중점을 둬서 컴포넌트 이름을 정하면 어떨까하는데
컴포넌트가 카드 형식이니 `SeminarCard` 정도로 네이밍 해주면 어떨까요?

추가적으로 카드 내부에서 공통적인 부분이
- 세미나 명
- 출석 코드 필드
- 출석 지각 text
- 버튼

권한에 따라 다른 부분이
- 출석 필드 disabled 여부
- 출석, 지각 셀렉터 / 카운트 text
- 버튼 text

이정도로 볼 수 있을 것 같은데 같은 부분은 중복적으로 써줄 필요없을 것 같아서
카드 자체는 하나의 카드 컴포넌트를 사용하고 다른 부분만 권한에 따라 처리해보는 건 어떨까요??

2023-02-22 14:26 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +              className="font-small mx-auto mb-[33px] block flex h-[34px] w-[71px] items-center whitespace-nowrap bg-pointBlue text-mainBlack"
`display` css로 block과 flex 두가지가 들어가있네요! 사용하는 클래스만 남겨줘야할 것 같습니다!

2023-02-24 07:40 UTC, lcqff commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
앗~~~ 안 그래도 페이지에서 카드 부분만 빼다가 컴포넌트로 바꿨습니다~~~ 
카드 컴포넌트는 (세미나 생성 후)회원/회장용 카드 두 개 + 세미나 생성 전 카드 하나+세미나 비활성화 상태 카드 하나로 분리할 생각이었는데 은지님 말씀은 이 카드 컴포넌트들을 하나로 합치고 권한에 따라서 삼항연산자 혹은 다른 방식으로 처리하잔 말씀이시죠??
할 수는 있을 거 같은데 조금 염려 되는 게 카드 컴포넌트가 가지는 상태가 이미 많고, 페이지에 재접속 했을시 카운트다운이나 출석상태를 유지하려면 api를 사용해서 카드 컴포넌트의 상태를 또 분리해야하는데 이러면 코드가 너무 복잡해지지 않을까? 염려됩니답,,,

그러니까 카드 컴포넌트를 하나로 합치고 권한에 따라 분리할시
세미나 생성여부, 세미나 활성화 여부, 권한 여부, 세미나 종료 여부, 세미나 출석 여부에 얽히고 설켜서 컴포넌트가 복잡하게 달라질 거 같은데 괜찮을까요?🥺
사실 직접 해본 건 아니라서 어느 정도일진 모르겠지만 최소 삼항 연산자가 중첩되는 부분이 많아질 거 같습니다

2023-03-01 08:34 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
네네 하나로 합치면 어떨까 제안드린 거 맞습니다!
카운트다운이나 출석상태 같은 경우에는 세미나 시작이후에는 권한에 상관없이 동일하게 적용되니 따로 처리해줄 부분은 없을 것 같아요!

세미나 생성 여부의 경우
세미나 시작 버튼이냐 출석 버튼이냐에 따라서 좌우된다고 볼 수 있으니 권한에 따라 버튼만 다르게 보이도록 처리하면 될 것 같고

세미나 활성화 여부의 경우에는
권한과 시작된 상태인지 두가지 상태를 체크해야 하긴 하네욤!

세미나 종료 여부, 세미나 출석 여부는
세미나 시작 이후 사항이니 위에 말씀드린 것 처럼 권한 상관없이 동일하게 처리할 수 있을 것 같아요!

2023-03-01 09:57 UTC, lcqff commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
```
세미나 생성 여부 ? (
	<예정된 세미나가 없습니다>
	) : ( 
    회원권한여부 ? (
        세미나 시작 여부? (
            !세미나 끝남 여부 && (
                <input disable with code>
                <countdown>
            )
        ) : (
            <input창 disable>
            <select>
            <시작 BUTTON></시작>
        )
    ):(
        세미나 시작 여부? (
            !세미나 끝남 여부 && (
                회원 출석 여부 ? (
                    <input disable with code>
                    <countdown>
                    <출석 상태 표시>
                ) : (
                    <input inable>
                    <countdown>
                    <출석 버튼>
                )
            )
        ) : (
            <세미나 비활성화 상태>
        )
    )
)
```

근데 그러면 코드가 위처럼 되지 않을까요? ㅠㅠ
아니면 상태를 처리해줄수 있는 방법이 삼항 연산자 말고 더 있는 건가요? 
아니면 제가 너무 비효율적으로 코드를 생각한 걸지도 모르겠네요,,,,

2023-03-02 02:46 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
앗 제가 세미나 생성 여부를 세미나 시작여부라고 잘못 받아드렸었네요!
흠.. 확실히 처리할 때 좀 복잡해보이긴 하네요!
```
<타이포> {세미나 생성 ? 세미나명 : 예정된 세미나가 없습니다} </타이포>
{세미나 생성 && (
  <출석코드텍스트>
  <input창 value={code} disabled={(회원 && !세미나 시작) || 세미나 출석 || 세미나 끝남}>
  <출석, 지각 텍스트> {(회장 && !세미나 시작) ? <select> : <countdown>}
  )
  {세미나 출석 ? <출석상태 텍스트> : <버튼>{회장 ? 시작 : 출석}</버튼>}
}
```
(권한 있는 경우 임의로 회장이라고 써두었습니다!)

코드를 간략화 해본다면 이정도로 해볼 수 있을 것 같고 이것도 너무 복잡해보인다 싶으면 회원/회장용 컴포넌트 두개로 두되
공통적으로 쓰이는 중복되는 부분에 대하여 컴포넌트로 따로 분리해서 사용하는 것도 방법이 될 수 있을 것 같아요!

2023-03-02 06:07 UTC, lcqff commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
헉~~~ 너무 좋네요@!!
간략화 해주신 코드 좋아보이는데 일단 제가 무서워서(ㅠㅠ) 회장/회원용 두 개로 작업한 다음에 괜찮겠다 싶으면 하나로 합쳐도 괜찮을까요?
어프로브 해주시면 지금 제가 로컬 기능까지 작업을 해둔 상태라 따로 컴포넌트 분리 브랜치 만들어서 컴포넌트 분리 작업한 후 pr 새로 올리겠습니다!

2023-03-03 04:25 UTC, publdaze requested changes

2023-03-03 04:25 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +const DoAttend = ({ seminarDate }: DoAttendProps) => {
일단 다른 부분 Request changes 반영되면 approve 해두겠습니다.
컴포넌트 분리되고 크게 변경될만한 부분의 리뷰는 이 PR에서는 생략하고 진행할게요!

이제 아무래도 뒤로 갈수록 특히 구조적으로 변경되는 부분이 있으면 변경 사항도 크게 잡히게 되고
처음에 딱 잡고 가는 것 보다는 더 변경하기 위해 고려해야할 부분이 늘어나게 될 거라서
해당 PR에서 잡고 갈 수 있는 부분은 잡고 가는게 좋을 것 같긴한데 아무래도 PR 올라온 지 오래되기도 하였고,
계속 잡고 있으면 오히려 늘어질 수도 있을 것 같아서 이부분은 연후님 요량대로 이 PR에서 계속 진행하거나 새로 PR 올려주거나
해주면 될 것 같아요!

새로운 PR로 진행하게 되면 이슈도 새로 파서 여기 코멘트에 이슈 번호 하나 남겨주면 좋을 것 같습니다!

2023-03-03 05:35 UTC, publdaze approved these changes

2023-03-03 05:35 UTC, publdaze commented on src/pages/senimarAttend/DoAttend.tsx
> +import React, { useRef, useState } from 'react';
이부분도 마찬가지로 useRef 제거 해주세요!
일단 approve는 미리 해두겠습니다! 수고하셨어요 👍

2023-03-03 05:39 UTC, merged