Feature/세미나 출석 회장 UI #172
KEEPER31337/Homepage-Front-R2 pull request #226
Opened 2023-02-16 06:38 UTC by lcqff

## 분류
- [ ] 기능 추가

## 연관 이슈
> #172 

## 작업 요약
회장 권한을 가졌을시 보는 세미나 출석 페이지의 세미나 출석 이전 ui

## 작업 상세 설명

## 리뷰 요구사항
5분

이전 pr에서 실수로 이전 브랜치 커밋까지 몽땅 다 가져와버려서 수정하고 새로 pr올렸습니다!! 도균님이 이전 pr에 리뷰 달아주신 사항 확인하고 수정했습니다!

button은 공통컴포넌트로 바꾸려 했으나 추가적으로 필요한 css를 어떻게 추가해야할지 모르겠어서 일단 그대로 뒀습니다

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/219287621-144037af-d9e2-44f3-b855-41d8750d6d0e.png)

2023-02-16 07:05 UTC, publdaze reviewed
세미나 출석 제목과 세미나 관리 버튼은 다른 PR에서 진행하는 건가요?

2023-02-16 07:38 UTC, publdaze requested changes

2023-02-16 07:38 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    console.log(DateTime.now());
커밋 올릴 때 console.log는 제외하고 올려주면 좋을 것 같습니다!

2023-02-16 07:38 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    today = DateTime.now().toFormat('yy.MM.dd');
`today`라는 변수가 해당 스코프 안에서만 사용되는데 더 상위 스코프에서 `let`으로 선언되어 있네요.
`let`을 쓸 경우 재할당이 되어 데이터가 바뀔 수도 있기 때문에 `let`보다는 `const`를 추천드립니다.

[JS 클린코드 사이드 이펙트](https://github.com/qkraudghgh/clean-code-javascript-ko#%EC%82%AC%EC%9D%B4%EB%93%9C-%EC%9D%B4%ED%8E%99%ED%8A%B8%EB%A5%BC-%ED%94%BC%ED%95%98%EC%84%B8%EC%9A%94-part-1) 내용과도 연관된다고 볼수 있을 것 같아서 링크 남깁니다.

2023-02-16 08:18 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    today = DateTime.now().toFormat('yy.MM.dd');
const로 선언하면 useEffect에서 값을 못바꿔서 let으로 설정했는데 그냥 없애고 setSeminarDate로 바로 날짜 넣는 걸로 하겠습니다~!

2023-02-16 08:41 UTC, lcqff commented
> 세미나 출석 제목과 세미나 관리 버튼은 다른 PR에서 진행하는 건가요?

깜빡했네요.. 추가했습니다^-^

2023-02-16 10:03 UTC, koty08 approved these changes

2023-02-16 10:41 UTC, publdaze requested changes

2023-02-16 10:41 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +  useEffect(() => {
<img width="200" alt="image" src="https://user-images.githubusercontent.com/78250089/219304167-e91bba89-8d65-46bc-a1d1-3d2954f636a4.png">

코드 배치가 통용되어 사용되는 건 따로 없고 코드스타일 취향에 따라 갈리는 것 같아요
하지만 저희는 저희 프로젝트 팀 단위에서 서로 코드를 볼 때 알아보기 용이하도록
개발 회의 때 얘기해던 이 순서로 코드 배치해주면 좋을 것 같아요!

2023-02-16 10:41 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    },
Input 스타일의 경우 따로 테마로 넣을 필요없이 아래처럼 간단하게 구현 가능합니다!
```tsx
<Input className="w-10 border-none !bg-white" />
```

disabled 처리됐을 때 배경색 그대로 남기고 싶으면 `disabled:!bg-white` 추가해주고요!
```tsx
<Input className="w-10 border-none !bg-white disabled:!bg-white" />
```

`ThemeProvider` 컴포넌트를 사용할 경우에는 상위에서 제가 커스텀 해두었던 테마가 적용이 풀려서 이 코드처럼
사용하려면 `ThemeProvider` 컴포넌트는 제거 해주셔야 합니다!

2023-02-16 10:48 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    today = DateTime.now().toFormat('yy.MM.dd');
today 변수명 사용해서 해당 코드가 의미하는 바가 더 잘 와닿는 건 좋은 것 같아요!
외부에 선언해두고 값을 바꾸는 방식말고 useEffect 내부에서 const로 선언해 사용하면 될 것 같습니다!

<img width="466" alt="image" src="https://user-images.githubusercontent.com/78250089/219343856-c671da88-0777-476c-be40-f80dfd589eca.png">

2023-02-16 10:53 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +    },
input이 4개 들어가는데 거기에 전부 다 classname 넣기 좀 그래서 따로 만들었는데
    ```
      input: {
            borderRadius: '!rounded-none',
            bgColor: '!bg-white',
            height: 'h-[52px]',
          },
```
필요없는 거 지우고(제가 disable로 만들기 전에 해둔 테마라서 필요 없는게 들어가 있었네요^^;;) 위처럼 바꾸는 것보다 그냥 className으로 하는게 나을까요??

2023-02-16 10:53 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +  useEffect(() => {
아앗~~~~~~ 수정하겠습니다

2023-02-20 07:18 UTC, jasper200207 approved these changes

2023-02-22 14:35 UTC, publdaze requested changes
[세미나 출석 회원 UI PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/224)의 SetSeminar 파일 부분과 동일한 내용이 SenimarAttend 파일에 들어가 위치만 변경된 것 같습니다! 두 PR이 다 머지되면 같은 코드가 서로 다른 파일에 중복적으로 들어가게 될 것 같은데 한 가지만 남겨둬야 할 것 같아요!

2023-02-24 06:25 UTC, lcqff commented
넵! 저도 그게 염려돼서 작업 상세 설명에 적어놨습니다! 회원 브랜치에 회장 브랜치 부분이 포함돼 있어서 회원 브랜치만 머지하면 될거같아요~~

2023-03-03 05:39 UTC, closed without merging