Feature/공통 컨폼 모달 제작 #227
KEEPER31337/Homepage-Front-R2 pull request #237
Opened 2023-02-18 05:59 UTC by mia2583

## 분류
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈
> #227

## 작업 요약
> 확인 버튼이나 X 버튼으로 여닫는 확인용 공통 모달입니다.

## 남은 작업
- [ ] 버튼 색상 커스텀 기능이 추가되면 모달도 색상 커스텀 기능을 추가하고자 합니다.

## 작업 상세 설명
> X버튼만 있는 모달과 확인 버튼이 함께 있는 모달을 합쳐서 구현했습니다.
> showButton에 boolean값에 따라서 버튼이 생성 유무가 적용됩니다.
> 모달 사용 시에는 아래 코드를 참고하시면 됩니다.
> showButton의 boolean에 true 파라미터를 전달할 때에는 특이하게도 `showButton={true}`가 아니라 그냥 `showButton`만 적어주시면 됩니다. 
```
const [open, toggleOpen] = useReducer((pre) => !pre, false);

<FilledButton onClick={toggleOpen}>세미나 추가</FilledButton>
<ConfirmModal opened={open} handleOpen={toggleOpen} title="세미나 추가" showButton={false}>
   컨텐츠입니다
</ConfirmModal>
```

## 리뷰 요구사항
> 2분
> 이전의 공통 액션 모달과 코드가 비슷해서 리뷰하기 편하실 겁니다.

## Preview 이미지

2023-02-19 12:56 UTC, publdaze commented
develop에 있는 사항 변경 사항으로 잡혀있어서 develop 풀 받은 거 올려두었습니다!

2023-02-19 14:23 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        <DialogHeader className="text-left font-bold text-[#4ceef9]">{title}</DialogHeader>
X 아이콘에 의해서 모달 제목 위치가 `ActionModal`과 약간 다른 것 같아요! (`ActionModal`에 비해 더 아래에 제목이 위치) 또한 아이콘 크기에 따라서도 제목의 위치가 변경되니 추후 변경사항이 있을 때 관리하기 어려울 것 같아요!
`ActionModal`을 확인해보니까 18번째 라인의 mt를 다르게 줘서 위치 잡아보려고 하셨던 것 같은데
그렇게 처리하기 보다는 mt는 동일하게 가고 X 아이콘이 다른 요소의 위치에 영향을 주지 않도록 처리해보면 좋을 것 같아요!

2023-02-19 14:27 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        <DialogBody className="mb-6 text-left text-base text-white">{children}</DialogBody>
`text-left`와 `text-base`의 경우에 기본값이라서 따로 적용 안해줘도 될 것 같은데 코드 간단하게 하기 위해서 빼주는 건 어떨까요?
(ActionModal에도 그렇게 되어 있었는데 그때 리뷰할 때는 신경 못썼었네요..! ActionModal 부분은 해당 PR과 별도로 진행해야할 것 같아서 이슈 하나 따로 만들어주면 좋을 것 같습니다!)

2023-02-20 07:26 UTC, jasper200207 approved these changes

2023-02-20 12:18 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        <DialogFooter>{showButton ? <FilledButton onClick={handleOpen}>확인</FilledButton> : null}</DialogFooter>
showButton이 false일 때는 null이라서 확실히 &&연산자가 더 간결할 거 같네요! 수정했습니다~

2023-02-20 12:51 UTC, koty08 approved these changes

2023-02-22 07:25 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        <DialogHeader className="text-left font-bold text-[#4ceef9]">{title}</DialogHeader>
x아이콘을 영향을 안 받게 수정하는 김에 밑에 버튼도 영향 안 받도록 코드 수정했습니다.

2023-02-22 07:26 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        <DialogBody className="mb-6 text-left text-base text-white">{children}</DialogBody>
위의 아이콘 디자인 수정하면서 함께 슬쩍 적용해서 없애 버렸습니다~~
ActionMaodal쪽은 별도로 이슈 파서 수정할게요

2023-02-22 07:38 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +          <VscChromeClose onClick={handleOpen} />
이 부분도 글자 크기 반영했습니다~~감사합니다!

2023-02-25 08:53 UTC, publdaze requested changes

2023-02-25 08:53 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        <div className="absolute right-0 mr-5">
right로 우측에서 어느정도 간격을 띄울 지 설정할 수 있는데 따로 마진으로 띄워준 이유가 있을까요?
별다른 이유가 없으면 `mr-5`을 별도로 넣는 것 보다 `right-5`로 우측 간격을 지정해주는 건 어떤가요?

2023-02-25 09:28 UTC, publdaze requested changes

2023-02-25 09:28 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +    </Dialog>
<img width="319" alt="image" src="https://user-images.githubusercontent.com/78250089/221348435-02ccc8de-f086-4e64-8641-e0bb2ecc1d16.png"> <img width="319" alt="image" src="https://user-images.githubusercontent.com/78250089/221348459-26389484-2684-49c7-ba49-ea9ef989baef.png">
모달과 내부 요소간의 간격을 조절하기 위해서 크게 두가지 box model이 사용되고 있는 것 같아요!

모달의 구조를 잡을 때 구조가 더 잘 파악되도록 css를 적용하려면 아래와 같이 해볼 수 있을 것 같은데
<img width="430" alt="image" src="https://user-images.githubusercontent.com/78250089/221348831-28a7d2c8-94a6-4ffc-8d9a-619d8c6de759.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/78250089/221349368-8a8bf552-13c9-483e-8771-deaed161af38.png"> <img width="295" alt="image" src="https://user-images.githubusercontent.com/78250089/221349395-48f9ef74-c934-45d2-b9c4-11a7d4b65425.png">


18라인에 마진만을 위한 div를 별도로 두지 않고, Dialog 자체에 대하여 17라인에 padding으로 간격을 줄 수 있을 것 같아요!
```tsx
<Dialog open={opened} handler={handleOpen} className="rounded-lg bg-subBlack py-5 pl-10 pr-10">
```

또한 25라인의 DialogBody에 `mb-20`으로 두기 보단 상하 padding을 동일하게 위의 첨부 코드로 모달 자체의 `py-5`로 구성하고
모달의 높이가 children의 구성에 따라 높이가 변할 수 있다는 점을 고려하여 최소 높이를 두고 높이 확장이 가능하도록 `min-h-[80px]`로 css 두면 더 깔끔할 것 같네요!

<img width="856" alt="image" src="https://user-images.githubusercontent.com/78250089/221349566-63b459ed-e428-423e-bb63-b0c3e8767cb8.png">
해당 코멘트에서 추가된 부분으로는 위의 코드 참고하면 될 것 같고, 삭제된 부분은 직접 비교해보면서 살펴봐주세요~!

2023-02-25 11:22 UTC, publdaze requested changes

2023-02-25 11:22 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogFooter>
<img width="519" alt="image" src="https://user-images.githubusercontent.com/78250089/221350745-5cd5c55b-d58d-414a-b31a-e4b24e7ee8ab.png">

`ActionModal`로 구현한 이미지상 2번이 아닌 현재 Pr의 모달의 경우 별도로 모달 자체의 버튼은 없어도 될 것 같습니다!
모달 내부에서 다양한 형태로 구성될 수 있어서 해당 커스텀 모달을 작업하는 사람이 직접 필요한 구성대로
모달 내부에 넣을 수 있도록 이부분은 없애도 괜찮을 것 같아요!

2023-03-02 08:14 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        <div className="absolute right-0 mr-5">
음..분명히 right-5로 했을 때랑 뭔가 차이가 있어서 일부러 저렇게 코드를 작성한 기억이 있는데 지금 다시 해보니까 별 차이가 없네요...
뭐가 문제였을까요...일단 right로 수정했습니다!

2023-03-02 08:15 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +    </Dialog>
오홍 그냥 눈으로 보면서 수정했는데 개발자 도구로 보니까 간격이 찌그러진 모양으로 확실히 보이네요.
두 부분 모두 수정했습니다.

2023-03-02 08:36 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogBody>
![image](https://user-images.githubusercontent.com/83392142/222373886-b26c1fa1-4ceb-41e2-bafc-6b4f4a8637ec.png)
제가 본건 17px이라서 `DialogBody` 에 `pt-0`을 적용했습니다. 그런데 이상하게 `DialogHeader`에는 `pb-5`를 적용해주면 기존의 16px에서 값이 추가가 되어 21px이 되는거 같네요;;
까다롭네요...일단 가능한 body부분으로 수정해놨습니다.

2023-03-02 08:41 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogBody>
아하 `paragraph`가 기본 폰트 사이즈로 지정되어 있군요! 수정했어요~

2023-03-02 08:48 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogFooter>
저번에 이 부분에 대해서 단순 창닫기 용 확인 버튼이 있는 것과 없는 것 둘 다 하기로 했지 않았던가요?
그때 기억이랑 공통 모달 디자인에도 둘 다 있어서 만들었는데 다시 버튼 없는 것만 하기로 했나요?

2023-03-03 04:57 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogFooter>
단순 창닫기 용이라면 X 버튼으로 할 수 있는데 별도록 확인 버튼까지는 필요없을 것 같아서 단순 창닫기 용 확인 버튼은 하지 않기로 한 걸로 기억하고 있어요! 디자인 상에서는 디자이너님이 진행해주셨는데 다양하게 디자인해서 보여준다고 둘 다 만들어 두신 것 같아서 별도로 수정 요청 드리진 않았었습니다!

2023-03-03 06:05 UTC, publdaze requested changes

2023-03-03 06:05 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +  handleOpen: () => void;
이벤트 핸들로 함수로 직접적으로 사용하는 부분이 아니라 prop의 경우에는 앞에 on 접두사로 붙여주면 좋을 것 같아요 ([참고](https://ellie-dev.tistory.com/13))

2023-03-03 06:14 UTC, publdaze requested changes

2023-03-03 06:14 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      </div>
이부분 굳이 div 감싸주지 않고
```tsx
<VscChromeClose className="absolute right-5" size="19" color="#4CEEF9" onClick={handleOpen} />
```
이렇게 바로  아이콘에 css 넣어주면 더 간단하게 표현 가능할 것 같아요!

2023-03-03 07:02 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +    <Dialog open={opened} handler={handleOpen} className="rounded-lg bg-subBlack py-5 pl-10 pr-10">
좌측 우측 같은 padding이 들어가는 거면
`pl-10 pr-10` -> `px-10`
이렇게 변경해주면 더 간단하게 가능해요!

2023-03-03 07:14 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogBody>
<img width="332" alt="image" src="https://user-images.githubusercontent.com/78250089/222654823-9a541ac9-4cef-4f3a-88f2-38eae0289727.png">

저는 위의 이미지 같이 측정을 했어서 20px로 생각했었는데 텍스트 박스 내부에서도 간격이 조금씩 차이가 나서 어떻게 보느냐에 따라 조금씩 차이가 날 것 같아요. 디자이너님께서 보통 4의 배수 단위로 간격을 조정한다고 하셨어서 16px이나 20px 정도로 처리하면 될 것 같은데 정확한 수치는 디자이너님께 한 번 여쭤봐도 좋을 것 같네요!

2023-03-06 12:18 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +      </div>
아하 아이콘에는 따로 className을 넣을 수 있는지 몰랐네요!

2023-03-06 12:28 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogFooter>
아아 넵! 다시 확인 버튼 없는 코드로 수정했습니다

2023-03-06 12:58 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +  handleOpen: () => void;
네에!!수정했습니다!

2023-03-07 08:52 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </DialogBody>
아하 대부분 4의 배수였군요. 그러면 제목이랑 내용 부분의 패딩이 모두 16px이라 같이 맞추고 싶어서 16px로 처리할게요!

2023-03-07 08:54 UTC, mia2583 commented
아...헉...계속 다른 프로젝트랑 헷갈려서 이번에 수정한 커밋 밑에 이슈번호 안 붙였는데...다시 수정못하죠...?ㅜㅠ
다음부터는 진짜 제대로 하겠습니다...

2023-03-07 08:56 UTC, mia2583 commented
이번 pr너무 오래 열려있었던 거 같아서 이만 머지하고 mui로 수정하는 이슈 별도로 pr올리겠습니다!

2023-03-07 12:10 UTC, publdaze requested changes
- #289
- 액션 모달 MUI로 변경한 거 올려놓았는데 이거 먼저 확인 부탁드립니다!
- MUI로 변경되면서 코드 수정하는 것 보다 새로 작성하는 게 더 편할 것 같다 싶으면 이 PR은 close하고 새로 올려주는게 좋을 것 같고, 이 PR에서 짠 코드에 수정만 해서 올리는 게 더 편할 것 같다 싶으면 props라거가 사용하는 부분에서도 차이가 있을 것 같아서 이 PR에서 처리하고 넘어가면 좋을 것 같습니다!
- 개인적으로 이 PR에서 material tailwind 사용한 부분에 대한 커밋은 history에 남기는 게 불필요해보여서 이 PR close하고 새로 하는 걸 더 추천하지만 이부분은 명서님께서 편한대로 진행하면 될 것 같아요!

2023-03-10 04:31 UTC, closed without merging