feat : datapicker 공통컴포넌트 제작
KEEPER31337/Homepage-Front-R2 pull request #239
Opened 2023-02-18 14:53 UTC by pipisebastian

## 연관 이슈
> #213 

## 작업 요약
datepicker 공통컴포넌트 제작,
pread 연산자 해당파일에만 eslint룰 제거
디자인은 추후에 할 예정

## 작업 상세 설명
> props로 label, value, setValue 넘김

## 리뷰 요구사항
> 3분

## 사용 예제
```
import StandardDatePicker from '@components/DatePicker/StandardDatePicker';
import { DateTime } from 'luxon';
```
```
const [value, setValue] = React.useState<DateTime | null>(null);

  return (
    <div>
      <StandardDatePicker date={value} setDate={setValue} label="세미나 출석 날짜" />
    </div>
  );
```

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/219872331-9282d28d-7875-4a3a-b1e2-bc523b0c11cd.png)

2023-02-19 10:50 UTC, publdaze commented
<img width="812" alt="image" src="https://user-images.githubusercontent.com/78250089/219943325-2cc29aaa-05e3-46c3-b543-842e8b1ce6cd.png">
`@types/luxon`이 설치되어 있지 않아 에러 뜨네요!
설치하여 [PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/246) 올려두었으니 해당 PR 머지되면 develop pull 받아서 반영 부탁드립니다!

2023-02-19 11:00 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +/* eslint-disable prettier/prettier */
해당 룰은 왜 무시해둔 건가요?

2023-02-19 11:17 UTC, publdaze requested changes

2023-02-19 11:17 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +import { DatePicker } from '@mui/x-date-pickers/DatePicker';
`TextField`의 경우 보통 MUI 컴포넌트 사용할 때 여러 컴포넌트들을 호출해서 사용하는 경우가 많아서 확장에 용이하도록
```tsx
import { TextField } from '@mui/material';
```
이렇게 변경하면 어떨까요?

그리고 `DatePicker`, `LocalizationProvider`의 경우 한 군데 묶으면 더 깔끔할 것 같습니다! (`AdapterLuxon`도 같이 묶을 수 있을 줄 알았는데 그건 안 되네요..!)
```tsx
import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers';
```

2023-02-19 11:25 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +        renderInput={(params) => <TextField id="standard-basic" label="Standard" variant="standard" {...params} />}
여기 id는 어떤 역할로 사용하신 건가요?
그리고 DatePicker 자체에서 라벨을 지정하는 것 같은데
`TextField`에도 따로 label을 붙인 이유와 Standard라는 텍스트로 label 지정한 이유도 궁금합니다!

2023-02-19 11:30 UTC, publdaze commented
<img width="191" alt="image" src="https://user-images.githubusercontent.com/78250089/219945026-3da77b0d-c6c7-4383-ab63-af358e6f7580.png">

여기 마우스 focus 했을때 라벨 및 bottom 버튼 사라지는 거 제가 selector 컴포넌트 구현하면서 따로 처리해둔게 있는데 해당 PR 올리면 또 말씀드리겠습니다!


<img width="183" alt="image" src="https://user-images.githubusercontent.com/78250089/219945076-9443c4f9-8bcb-47c4-9ed6-caa3ce7d9dab.png">

focus 전 border 색 처리도 포함해서 하고 있어서 이부분 일단은 크게 신경 안 쓰고 있어도 괜찮을 것 같습니다!

2023-02-19 11:43 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +  label: string;
`label`의 경우 사용하지 않는 경우도 있을 것 같아서 optional로 처리하면 어떨까요?

2023-02-19 16:15 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +/* eslint-disable prettier/prettier */
그때 에러떠서 빨리 fix하는걸 썼었는데, 지우니까 제대로 동작하네요...!? 지웠습니다!

2023-02-19 16:15 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +import { DatePicker } from '@mui/x-date-pickers/DatePicker';
좋습니당!

2023-02-19 16:16 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +        renderInput={(params) => <TextField id="standard-basic" label="Standard" variant="standard" {...params} />}
그거슨,, textfiled공식문서 예제코드를 그대로 가져왔기때문입니다!
다시보니 필요가 없네요,, 꼼꼼히 읽겠습니다!!

2023-02-19 16:16 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +  label: string;
좋습니당!!

2023-02-19 16:18 UTC, pipisebastian commented
type/luxon머지된후에 코드리뷰 커밋날리겠습니다!

2023-02-20 13:01 UTC, koty08 approved these changes

2023-02-20 13:10 UTC, mia2583 commented on src/components/DatePicker/StandardDatePicker.tsx
> +        renderInput={(params) => <TextField id="standard-basic" label="Standard" variant="standard" {...params} />}
혹시  `renderInput`은 어떤 역할을 하는 코드인가요?

2023-02-21 05:51 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +        renderInput={(params) => <TextField id="standard-basic" label="Standard" variant="standard" {...params} />}
datepicker에서 무조건 넣으라고하는 props입니당! 자세히는 잘모르지만
datapicker를 담는 인풋창을 커스텀할수있습니다! 지금은 mui의 standard방식의 TextField를 썼습니다!

mui datelicker공식문서
https://mui.com/x/api/date-pickers/date-picker/

2023-02-22 08:47 UTC, pipisebastian commented
> <img alt="image" width="812" src="https://user-images.githubusercontent.com/78250089/219943325-2cc29aaa-05e3-46c3-b543-842e8b1ce6cd.png">
> 
> `@types/luxon`이 설치되어 있지 않아 에러 뜨네요! 설치하여 [PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/246) 올려두었으니 해당 PR 머지되면 develop pull 받아서 반영 부탁드립니다!

풀받아서 잘 작동하는거 확인했습니당!

2023-02-22 11:30 UTC, mia2583 approved these changes

2023-02-24 11:42 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +/* eslint-disable prettier/prettier */
제거된 거 push 안 된 것 같습니다! 확인부탁드려요~!

2023-02-25 07:28 UTC, publdaze requested changes

2023-02-25 07:28 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +/* eslint-disable prettier/prettier */
제거된 거 push 안 된 것 같습니다! 확인부탁드려요~!

2023-02-26 05:52 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +/* eslint-disable prettier/prettier */
헛헛.. 다시 지웠습니다!!

2023-02-26 06:41 UTC, publdaze requested changes

2023-02-26 06:41 UTC, publdaze commented on src/components/DatePicker/StandardDatePicker.tsx
> +import { DatePicker } from '@mui/x-date-pickers/DatePicker';
`TextField` 부분 반영 안 된 것 같아요ㅠㅠ 확인부탁드립니다!

2023-02-26 06:51 UTC, publdaze commented
Nit: 리뷰 반영한 것도 각 커밋을 의도를 파악할 수 있도록 관련성 있는 것이 아니면 따로 커밋 올려주고 커밋에서 왜 변경을 했는 지에 대한 부분도 파악이 되도록 작성하면 좋을 것 같아요!
[좋은 커밋](https://velog.io/@skynet/%EC%A2%8B%EC%9D%80-%EC%BB%A4%EB%B0%8B%EC%9D%84-%EC%9E%91%EC%84%B1%ED%95%98%EB%8A%94-%EB%B2%95)에 대한 글인데 간단하게 보고 넘어가도 좋을 것 같습니다!

2023-02-28 13:27 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +import { DatePicker } from '@mui/x-date-pickers/DatePicker';
아앗.... 넹.....!

2023-02-28 13:33 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +import { DatePicker } from '@mui/x-date-pickers/DatePicker';
수정했습니다! 여러번 번거롭게해서 죄송합니다ㅜㅜ

2023-02-28 13:49 UTC, publdaze requested changes

2023-03-01 02:59 UTC, pipisebastian commented on src/components/DatePicker/StandardDatePicker.tsx
> +interface DatePickerProps {
조씁니다!!!

2023-03-01 03:04 UTC, publdaze approved these changes
수고하셨습니다!! 👍

2023-03-01 12:03 UTC, merged