Feature/검색 인풋 공통컴포넌트 구현 #240
KEEPER31337/Homepage-Front-R2 pull request #249
Opened 2023-02-20 07:33 UTC by pipisebastian

## 연관 이슈
> - close #240

## 작업 요약
- props에 className, label, useRef ,동작할 함수 4개 넣어줘야함
- 검색아이콘 클릭 + 검색창에서 엔터시 함수 동작하도록
- className props로 넣어 tailwind css적용되도록

## 예제 코드
``` tsx
 import SearchInput from '@components/Input/SearchInput';
```
``` tsx
const inputText = useRef<HTMLInputElement>(null);
  const SearchAPI = () => {
    console.log(inputText?.current?.value);
  };

  return (
    <div>
      <SearchInput className="w-full " label="세미나 출석 날짜" inputText={inputText} onActionSearch={SearchAPI} />
    </div>
  );
```

## 리뷰 요구사항
> 3분, tailwind 적용잘되고, value값 가져오는거 확인했습니다!

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/220041343-902c9752-f417-448c-942e-82e8ac7bea93.png)

2023-02-20 12:44 UTC, koty08 approved these changes
좋습니다! 👍

2023-02-20 13:18 UTC, mia2583 commented
preview이미지를 보다가 생각난 건데 세미나 출석 날짜의 경우에는 입력 날짜 형식이 있을 수 있잖아요,
그래서 입력 힌트(placeholder) 문구도 컴포넌트 사용자가 적을 수 있게 하면 어떨까요?

2023-02-22 11:31 UTC, mia2583 approved these changes

2023-02-26 06:21 UTC, publdaze commented
Nit : 세미나 출석 날짜 같이 날짜가 들어가는 경우는 보통 datepicker를 통해 사용될 거라 다른 예시를 들면 더 좋지 않을까 합니다!

2023-02-26 06:21 UTC, publdaze requested changes

2023-02-26 06:21 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +      className={`${className}`}
여기서 className 받아온 거 제외하고 따로 넣어줄 게 없으면
`className={className}` 이렇게 해주면 더 깔끔하고 불필요한 연산을 줄일 수 있을 것 같아요!

2023-02-26 06:34 UTC, publdaze requested changes

2023-02-26 06:34 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +      inputRef={inputText}
`value`로 인풋 값을 충분히 받아올 수 있을 것 같은데 Ref로 사용한 이유가 있을까요?
작성해주신 예시를 보면 value값을 얻기위해서 ref로 dom 요소 자체를 가져오던데
특별한 이유가 없으면 `inputRef`보다는 `value`와 `onChange` property로 값을 제어하는 게 좋을 것 같습니다!

2023-03-01 03:08 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
> +      inputRef={inputText}
검색 input이라, onchange로 바뀔때마다 들어오는게 불필요하다 생각했습니다! 
근데 은지님 말대로 dom요소 다 가져오는것도 낭비같네요,,,

다른분들 input컴포넌트는 어떻게 했는지 알아보고 오겠습니다!

2023-03-01 05:30 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +      inputRef={inputText}
그렇네요! 아무래도 저희 현재 기획상 검색은 실시간으로 반영되는 형태가 아닌 이벤트 발생 시 결과값만 필요하니까 매번 바뀌는 값을 업데이트 하는 것도 불필요해 보이긴 하네요! 저도 어떤 방식이 더 좋을 지 시간 될 때 한 번 조사해보겠습니다!

2023-03-02 11:48 UTC, pipisebastian commented
> preview이미지를 보다가 생각난 건데 세미나 출석 날짜의 경우에는 입력 날짜 형식이 있을 수 있잖아요, 그래서 입력 힌트(placeholder) 문구도 컴포넌트 사용자가 적을 수 있게 하면 어떨까요?

제가 예시를 세미나 출석 날짜로 들었는데, 날짜의경우 datepciker를 쓰면되고
생각해보니 검색창같은 경우, 이미 label로도 알려주고 있어서 placeholder가 필요없을 것 같아서요! , 혹시 placeholder지우는거 괜찮을까요??

2023-03-02 11:53 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
> +      inputRef={inputText}
state로 react가 관리하는게 나을것같습니다! [공식문서](https://ko.reactjs.org/docs/refs-and-the-dom.html)에서도 ref사용은 남용하지 말라고하고,
input쓰는건 더 잘게 컴포넌트를 쪼개서 렌더링최소화하면 좋을것같습니다!

2023-03-02 12:02 UTC, mia2583 commented
> 제가 예시를 세미나 출석 날짜로 들었는데, 날짜의경우 datepciker를 쓰면되고 생각해보니 검색창같은 경우, 이미 label로도 알려주고 있어서 placeholder가 필요없을 것 같아서요! , 혹시 placeholder지우는거 괜찮을까요??

아하 넵넵!! 생각해보니 그렇네요!다시 지웁시닷

2023-03-02 12:32 UTC, pipisebastian commented
기존에 useRef썼는데, state로 바꾸고, placeholder는 없앴습니다! 
다시 코드리뷰 부탁드립니다!

2023-03-03 07:59 UTC, publdaze requested changes

2023-03-03 07:59 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +      variant="standard"
- #282 

282 PR에서 리뷰랑 겹치는 부분이 있는 것 같아서 해당 PR 리뷰부터 우선적으로 처리 후 이 PR에도 처리해줘야 할 것 같은데 이 PR 브랜치를 282 PR에서 pull 받아서 사용하고 있다보니 머지 자체는 이 PR부터 처리하고 develop 올린 후 282 PR에서 develop pull 받아서 적용하고 282 PR 머지 해야할 것 같습니다.

2023-03-03 07:59 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +            <MdOutlineSearch className="h-5 w-5 text-pointBlue hover:cursor-pointer" onClick={onActionSearch} />
아이콘 자체에 onClick을 넣기보다는 `IconButton` 컴포넌트로 한 번 더 감싸서 Button의 역할이라는 게 표현되도록 하고 버튼에 onClick함수를 넣으면 더 좋을 것 같아요!
그리고 onActionSearch이 무슨 이벤트를 처리하는 핸들러인지 잘 와닿지 않을 것 같아서
`onSearchButtonClick`이라거나 클릭 이벤트를 처리한다는 게 명시되면 좋을 것 같아요!

```tsx
<InputAdornment position="end">
  <IconButton onClick={onActionSearch}>
    <MdOutlineSearch size={20} className="fill-pointBlue" />
  </IconButton>
</InputAdornment>
```
추가적으로 선호도 차이이지만 높이와 넓이 각각 지정해주는 것 말고도 사이즈를 px 단위로 한번에 처리하고 싶으면 `size` 속성 사용할 수 있을 것 같고, 아이콘이다보니 text에 색을 먹이는 것보다는 svg 색상 적용하는 것 처럼 fill에 색상 지정하는 게 더 자연스러울 것 같아요!

2023-03-03 14:02 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
> +      variant="standard"
넵넵!

2023-03-03 14:25 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
> +            <MdOutlineSearch className="h-5 w-5 text-pointBlue hover:cursor-pointer" onClick={onActionSearch} />
iconButtom 컴포넌트도 있군요! size속성이랑 새로운거 많이 알아갑니다! 감사합니다! ദ്ദി*ˊᗜˋ*)

2023-03-05 11:01 UTC, lcqff approved these changes

2023-03-05 11:13 UTC, koty08 approved these changes

2023-03-05 11:14 UTC, publdaze requested changes

2023-03-05 11:14 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +const SearchInput = ({ value, onChange, onSearchButtonClick, ...standardTextFieldProps }: SearchInputProps) => {
interface와 컴포넌트 함수 사이 개행으로 한 줄 띄워주면 좋을 것 같아요!

2023-03-05 11:34 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
> +const SearchInput = ({ value, onChange, onSearchButtonClick, ...standardTextFieldProps }: SearchInputProps) => {
왕 꼼꼼하십니다..! 추가했씁니당!

2023-03-05 11:36 UTC, publdaze approved these changes
굿굿 수고하셨습니다~!~!

2023-03-05 11:38 UTC, merged