Feature/메인페이지 메인 #116
KEEPER31337/Homepage-Front-R2 pull request #259
Opened 2023-02-22 09:58 UTC by jasper200207

## 연관 이슈
- #116 

## 작업 요약
- 메인화면에 Keeper로고 표시 및 메인 소개글 표시
- 브렌치를 새로 만들게 되어서 의도치 않게 pr도 다시 올립니다... 리뷰어는 기존과 동일하게 달아두겠습니다.

## 작업 상세 설명
- tailwind.config.js에 backgroundImage를 설정하여 이미지 배경 적용
- 메인화면의 크기는 100vh로 설정하여 한 화면에 들어오도록 설정 (추후에 헤더와 사이드바가 적용될때 수정이 필요해 보임)
- img로 로고를, p로 메인 소개글 삽입 및 m-auto로 가운데 정렬

## 리뷰 요구사항
- 5분
- 너비나 높이가 반응형에 적합할지 확인 부탁드립니다.
- 가능하면 스크롤에 반응하는 에니메이션을 넣어보고 싶은데 잘 아시는 분 있나요....

## Preview 이미지
![스크린샷 2023-02-22 오후 6 55 20](https://user-images.githubusercontent.com/51306225/220585855-c3091abf-94fe-4cb0-9574-7bd7ac3da78f.png)

2023-02-23 12:13 UTC, koty08 requested changes

2023-02-23 12:13 UTC, koty08 commented on src/pages/home/Home.tsx
> +          <p className="mx-auto whitespace-pre-wrap text-center text-white">{introText}</p>
상위에 `m-auto` 있어서 `mx-auto` 빼도 될 것 같습니다! 그리고 #244 에서 text-white도 default 적용이라 빼셔도 됩니다!

2023-02-23 12:18 UTC, jasper200207 commented on src/pages/home/Home.tsx
> +          <p className="mx-auto whitespace-pre-wrap text-center text-white">{introText}</p>
반영후 커밋 했습니다!

2023-02-24 07:49 UTC, koty08 approved these changes

2023-02-26 02:27 UTC, publdaze reviewed
스크롤로 반응하는 애니메이션이
https://shylog.com/react-custom-hooks-scroll-animation-fadein/
요론 느낌일까욤?~?

2023-02-26 06:03 UTC, publdaze requested changes

2023-02-26 06:03 UTC, publdaze commented on src/pages/home/Home.tsx
> +          <p className="whitespace-pre-wrap text-center">{introText}</p>
디자인 상 텍스트 크기가 20px으로 되어 있는데 적용 안 된 것 같아요! 저희가 20px의 경우에는 h3크기로 지정해두었습니다! (figma 상에서도 디자인할 때 h3 이런 식으로 보통 설정해두는데 이부분은 놓쳐서 20px 그대로 적혀있는 것 같네요..!)

그래서 텍스트 사용할 때 `Typography`를 사용하여 크기 지정해주면 더 편할 것 같아요!
```tsx
<Typography variant="h3" className="whitespace-pre-wrap text-center">
  {introText}
</Typography>
```

(`Typography` 아직 mui에는 폰트 사이즈 적용 안된 상태라서 일단 material tailwind의 `Typography` 써주시면 됩니다! 추후 mui로 한 번 싹 바꾸는 과정 거치겠습니다!)

2023-02-26 09:56 UTC, jasper200207 commented
> 스크롤로 반응하는 애니메이션이 https://shylog.com/react-custom-hooks-scroll-animation-fadein/ 요론 느낌일까욤?~?

넵 맞습니다! 메인페이지 완성후에 참고해서 한번 넣어보겠습니다!

2023-02-27 19:00 UTC, jasper200207 commented on src/pages/home/Home.tsx
> +      <div className="flex h-[calc(100vh-theme(space.header))] w-full flex-col">
> 이부분도 컨테이너에서 이미 header 부분은 padding으로 두어 영역을 안 잡히게 처리해놔서 별도로 계산하여 처리할 필요없이 `h-full`로 넣어도 괜찮을 것 같아요! 상위 div에도 full로 잡아줘야 하긴 하지만요!

이부분은 인트로의 경우 항상 스크린높이 만큼 보여야 해서 넣었던 css 였습니다. 그래서 h-full로 넣으면 밑에 다른 컴포넌트가 들어왔을때, 스크린높이 보다 작아져버려서 따로 넣어준거 였는데 혹시 괜찮은 방법이 있을까요....?

2023-03-01 05:44 UTC, publdaze commented on src/pages/home/Home.tsx
> +    <div className="flex w-[calc(100vw-theme(space.sidebar))] bg-galaxy bg-contain bg-repeat">
PR 올려두었습니다!
- #276

2023-03-01 05:57 UTC, publdaze commented on src/pages/home/Home.tsx
> +      <div className="flex h-[calc(100vh-theme(space.header))] w-full flex-col">
아하 다른 컴포넌트가 들어왔을 때 그런 문제가 있군요!
그러면 h-full 말고 `h-screen`으로 인트로 컴포넌트가 한 화면에 들어오도록 처리해주는 건 어떤가요?

2023-03-01 07:54 UTC, publdaze requested changes

2023-03-01 07:54 UTC, publdaze commented on src/pages/home/Intro.tsx
> +  "'지키다'라는 의미를 가진 단어 'keep'에서 착안하여,\n정보보호에 관한 연구를 진행하고 그 성과를 공유하기 위해 만들어진 동아리입니다.";
`introText` 변수를 `Intro` 컴포넌트 함수 안에 선언하는 건 어떤가요?
`Intro` 부분 외에 사용되는 경우가 없을 것 같고, 해당 block scope내에서만 유효하게 하여 외부 요소에 의해 오염될 가능성을 줄여주면 좋을 것 같아서요!

2023-03-02 14:59 UTC, publdaze approved these changes
굿굿 수고하셨습니다!

2023-03-02 16:13 UTC, pipisebastian approved these changes
수고하셨습니다!!

2023-03-03 07:19 UTC, merged