Feature/셀렉터_공통_컴포넌트_#238
KEEPER31337/Homepage-Front-R2 pull request #264
Opened 2023-02-23 08:03 UTC by publdaze

## 연관 이슈
- #238 

## 작업 요약
- 공통적으로 사용할 수 있는 셀렉터 기본 틀 구현

## 리뷰 요구사항
- 10분
- 디자인적 요소는 아직 완전히 다 들어가 있는 상태는 아니라는 점 감안하고 봐주세요!

## Preview 이미지
<img width="420" alt="image" src="https://user-images.githubusercontent.com/78250089/220851318-bc10ea05-2748-4146-9058-b5741d55bf6f.png">

2023-02-23 12:24 UTC, koty08 requested changes

2023-02-23 12:24 UTC, koty08 commented on src/components/Selector/Selector.tsx
> +const Selector = ({ label, value, onChange, options, className, ...selectProps }: SelectorProps & SelectProps) => {
type이 아닌 interface 형식이다 보니까 **&**(Union)사용보다는 extends 사용하는 것이 좋을 것 같습니다!

```
interface SelectorProps extends SelectProps {
...
}
```

2023-02-27 03:48 UTC, publdaze commented on src/components/Selector/Selector.tsx
> +const Selector = ({ label, value, onChange, options, className, ...selectProps }: SelectorProps & SelectProps) => {
오! `extends`로도 할 수 있었네요!! 감사합니다! 반영해두었습니다!

2023-02-28 04:06 UTC, mia2583 commented
커밋에서 타입 확장 방식 변경 부분이 이해 안되어서 그런데 혹시 무슨 여기에서 타입 확장이라는게 무얼 말하는건가요?

2023-02-28 13:47 UTC, publdaze commented
> 커밋에서 타입 확장 방식 변경 부분이 이해 안되어서 그런데 혹시 무슨 여기에서 타입 확장이라는게 무얼 말하는건가요?

@mia2583 
위에 태영님이 달아주신 코멘트 반영한 커밋인데 mui의 `Select` 컴포넌트에서 사용할 수 있는 props들을 다 허용하기 위해 제가 선언한 `SelectorProps`라는 interface에 mui에서 제공하는 `SelectProps` interface를 가져와 확장된 interface로 구성해주었어요!
처음에는 확장하기 위해서 `&`를 사용했었는데 interface 형식에서는 `extends` 사용하는 것이 좋다고하여서 `extends`로 변경해준걸 타입 확장 방식 변경이라고 표현했었습니다!
(타입 확장의 의미만 놓고 본다면 이미 선언되어있는 다른 타입을 지금 선언하는 타입에서도 사용할 수 있도록 덧붙여준다 정도로 생각해주시면 될 것 같아요!)

2023-03-02 05:23 UTC, pipisebastian commented
그리고 NiceMemberSelector 가 아닌 NiceMemberFilter로 지은 이유도 있을까요? selector가 더 직관적으로 보여서요!

2023-03-02 08:58 UTC, mia2583 commented
> 위에 태영님이 달아주신 코멘트 반영한 커밋인데 mui의 `Select` 컴포넌트에서 사용할 수 있는 props들을 다 허용하기 위해 제가 선언한 `SelectorProps`라는 interface에 mui에서 제공하는 `SelectProps` interface를 가져와 확장된 interface로 구성해주었어요! 처음에는 확장하기 위해서 `&`를 사용했었는데 interface 형식에서는 `extends` 사용하는 것이 좋다고하여서 `extends`로 변경해준걸 타입 확장 방식 변경이라고 표현했었습니다! (타입 확장의 의미만 놓고 본다면 이미 선언되어있는 다른 타입을 지금 선언하는 타입에서도 사용할 수 있도록 덧붙여준다 정도로 생각해주시면 될 것 같아요!)

@publdaze 
아하 그런 의미였군요!! 배워갑니다! 그리고 수고하셨습니다~~

2023-03-02 08:59 UTC, mia2583 approved these changes

2023-03-02 16:37 UTC, jasper200207 approved these changes

2023-03-03 04:53 UTC, Ji-Hyeon212 approved these changes
수고하셨습니다!!

2023-03-03 05:30 UTC, publdaze commented
@pipisebastian
> 수고하셨습니다!
예시에서 혹시 label같은경우 최상위가 아닌, NiceMemberFilter여기서 선언해주는 이유가 있을까요?

최상위가 Example 컴포넌트 부분을 말씀하신 걸까요?
일단 1차적으로 컴포넌트를 분리해서 보여드린 이유를 말씀드리자면 예시라서 하나의 컴포넌트에서 표현할 수도 있었지만
셀렉터에서 사용되는 option 리스트와 핸들러등 부가적인 요소들이 저희가 구현하는 페이지 컴포넌트 내부에 자리를 차지하는 것 보다는
페이지에서 또 한 번 해당 페이지에 특화된 컴포넌트로 분리되어 처리하는 게 깔끔하다고 생각하여 예시에서도 별도의 컴포넌트를 두었습니다.
label 같은 경우도 특화된 컴포넌트에서 고정될 수 있는 부분이기 때문에 최상위에서 내려주기 보다는 NiceMemberFilter에서 바로 라벨을 지정해주었습니다.


> 그리고 NiceMemberSelector 가 아닌 NiceMemberFilter로 지은 이유도 있을까요? selector가 더 직관적으로 보여서요!

이부분은 제가 현장실습할 때 Selector 사용하는 컴포넌트의 경우 Filter로 명명해주었어서 습관처럼 Filter를 붙였네요!
selector가 더 이해하기 좋은 것 같으면 selector로 예시 변경해두겠습니다!

2023-03-03 06:36 UTC, pipisebastian commented
> @pipisebastian
> 
> > 수고하셨습니다!
> > 예시에서 혹시 label같은경우 최상위가 아닌, NiceMemberFilter여기서 선언해주는 이유가 있을까요?
> 
> 최상위가 Example 컴포넌트 부분을 말씀하신 걸까요? 일단 1차적으로 컴포넌트를 분리해서 보여드린 이유를 말씀드리자면 예시라서 하나의 컴포넌트에서 표현할 수도 있었지만 셀렉터에서 사용되는 option 리스트와 핸들러등 부가적인 요소들이 저희가 구현하는 페이지 컴포넌트 내부에 자리를 차지하는 것 보다는 페이지에서 또 한 번 해당 페이지에 특화된 컴포넌트로 분리되어 처리하는 게 깔끔하다고 생각하여 예시에서도 별도의 컴포넌트를 두었습니다. label 같은 경우도 특화된 컴포넌트에서 고정될 수 있는 부분이기 때문에 최상위에서 내려주기 보다는 NiceMemberFilter에서 바로 라벨을 지정해주었습니다.
> 
> > 그리고 NiceMemberSelector 가 아닌 NiceMemberFilter로 지은 이유도 있을까요? selector가 더 직관적으로 보여서요!
> 
> 이부분은 제가 현장실습할 때 Selector 사용하는 컴포넌트의 경우 Filter로 명명해주었어서 습관처럼 Filter를 붙였네요! selector가 더 이해하기 좋은 것 같으면 selector로 예시 변경해두겠습니다!

아항! 감사합니다!! (왕따봉이모티콘) 
selector변경 좋씁니다!! 수고하셨습니다!

2023-03-03 06:36 UTC, pipisebastian approved these changes

2023-03-03 08:44 UTC, koty08 approved these changes

2023-03-03 09:04 UTC, merged