Feature/인풋 공통 컴포넌트 #279
KEEPER31337/Homepage-Front-R2 pull request #282
Opened 2023-03-02 16:09 UTC by pipisebastian

## 연관 이슈
> - close #279

## 작업 요약
- 유효성검사 기능 추가
- 옵셔널 props 4개 (className, label, disabled, error, helperText)
- 필요 props 2개 (state, handler함수 )

## 예제 코드
``` tsx
import React from 'react';
import StandardInput from '@components/Input/StandardInput';

const Example= () => {
  const [inputText, setInputText] = React.useState<string>('');

  const handleInputText = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputText(e.target.value);
  };

  const validation = () => {
    const check = /[^ㄱ-ㅎ가-힣a-zA-Z]/g;
    return check.test(inputText);
  };

  return (
    <div>
      <StandardInput
        className="w-full "
        label="아이디"
        disabled={false}
        inputText={inputText}
        handleInputText={handleInputText}
        isVaild={validation()}
        vaildText="아이디는 한글 또는 영문만 가능합니다"
      />
    </div>
  );
};

export default Example;

```

## 리뷰 요구사항
> 3분, tailwind 적용잘되고, value값 가져오는거 확인했습니다!
검색인풋공통컴포넌트 #240 를 풀받아서, 해당 코드도 같이 있습니다!
맨 밑 커밋([feat: 유효성검사 기능있는 인풋 공통 컴포넌트 구현](https://github.com/KEEPER31337/Homepage-Front-R2/commit/bae7a91f3b896278982d6e04978e0dd33d4557f0))만 확인해주세요!

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/222484232-7b31df8c-53f5-4a5f-a3a7-322d6e93f09c.png)
![image](https://user-images.githubusercontent.com/81643702/222484289-96def50c-74bb-45e3-af6a-db941476807a.png)

2023-03-03 02:50 UTC, pipisebastian commented
여러개 input처리할수있도록 기능추가다한뒤에 다시 풀리퀘 올릴게여!

2023-03-03 05:53 UTC, publdaze requested changes

2023-03-03 05:53 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +    />
공통 컴포넌트의 경우에는 저희가 사용중인 mui 공식 문서를 보고도 컴포넌트의 속성을 쉽게 파악할 수 있도록 되도록이면 용어를 기존 속성과 통일해주면 좋을 것 같아요!

2023-03-03 05:56 UTC, publdaze requested changes

2023-03-03 05:56 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +  handleInputText: React.ChangeEventHandler<HTMLInputElement>;
이벤트 핸들로 함수로 직접적으로 사용하는 부분이 아니라 prop의 경우에는 앞에 on 접두사로 붙여주면 좋을 것 같아요 ([참고](https://ellie-dev.tistory.com/13))

2023-03-03 06:04 UTC, publdaze requested changes

2023-03-03 06:04 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +      helperText={isVaild && vaildText}
helperText를 유효성 검사 없이 쓰고 싶을 때도 있을 것 같아서 여기서 강제하기 보다는 컴포넌트 사용하는 쪽에서 처리할 수 있게 하면 좋을 것 같아요!

++ 오타난 것 같아요 😄 isVaild -> isValid

2023-03-03 06:46 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +    />
넵!! 수정했습니다!

2023-03-03 07:09 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +      helperText={isVaild && vaildText}
넵 수정했습니다!

2023-03-03 07:18 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +  handleInputText: React.ChangeEventHandler<HTMLInputElement>;
아항..! 그렇다면 mui props랑 맞춰서 onChange 그대로 가는거 어떻게 생각하시나요??

![image](https://user-images.githubusercontent.com/81643702/222656450-fc4ffe28-1d0d-4da5-adef-9e287302adae.png)

2023-03-03 14:01 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +      helperText={isVaild && vaildText}
넵 수정했씁니다!

2023-03-05 10:39 UTC, lcqff approved these changes
굿잡!

2023-03-05 11:13 UTC, koty08 approved these changes

2023-03-05 11:34 UTC, publdaze requested changes

2023-03-05 11:34 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +  name: string;
name 필수값으로 넣어주셨네요!

여러 개의 인풋을 한 번에 처리하기 위해 하나의 핸들러를 사용할 때
서로 다른 인풋을 구분하기 위한 방법으로 name 사용하는 예제 너무 잘 짜주신 것 같아요! 👍

여러개의 인풋 구분 용도가 아니라 하나의 인풋만 사용하거나 할 경우는 없어도 될 것 같아서
없어도 무방할 경우 코드량을 조금 더 줄여주기 위해서 optional로 처리하는 건 어떤가요?

2023-03-05 11:45 UTC, publdaze approved these changes
아주 좋습니다~! 🎉

2023-03-05 11:47 UTC, merged