Feature/세미나 출석 카드 컴포넌트 분리 #283
KEEPER31337/Homepage-Front-R2 pull request #284
Opened 2023-03-03 10:56 UTC by lcqff

## 분류
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈
#283 
#207 

## 작업 요약
세미나 출석 페이지를 카드,회장 카드 내용물,회원 카드 내용물로 분리했습니다.
추가적으로 selector, button, input를 컴포넌트로 분리하고 Mui 라이브러리로 교체하는 작업을 했습니다.

## 작업 상세 설명
`세미나 생성여부`에 따라 예정된 세미나가 없습니다 문구를 띄우거나 회장/회원 카드를 띄웁니다.
만일 `세미나 생성여부`가 참일 경우 `회장 권한여부`에 따라 회장카드 혹은 회원카드를 띄웁니다.
`회장 권한 여부`가 참일 경우 회장 카드를 띄웁니다. 
회장 카드에서는 `세미나 존재(시작) 여부`에 따라 셀렉트 컴포넌트 혹은 카운트 다운 컴포넌트를 띄웁니다.
`회장 권한 여부`가 거짓일 경우 `세미나 존재(시작) 여부`에 따라 회원 카드를 띄우거나 '예정된 세미나가 없습니다' 문구를 띄웁니다.

은지님이 회장/회원 카드를 하나로 합치는 것에 대해 건의해주셨는데 회장은 `세미나 존재(시작)여부`가 바뀌어도 내부 컴포넌트(input,select,button)가 바뀌기만 할 뿐인데 비해, 회원의 경우 `세미나 존재(시작) 여부`가 거짓이 되면 내부 컴포넌트(input,countdonw,button)가 사라지고 문구로 교체되는 부분에서 회장/회원 카드를 어떻게 하나로 합쳐야 좋을지 고민입니다. 
좋은 아이디어 있을까요?

## 리뷰 요구사항
20분?
UI같은 경우 변경된 내용으로 뜯어고칠 예정이라 손 안댔습니다!

## Preview 이미지

2023-03-03 11:15 UTC, lcqff commented on src/pages/senimarAttend/components/MemberCardComponent.tsx
> +  const [componentIncorrectAlert, setComponentIncorrectAlert] = useState(<p className="mb-[22px]" />);
세미나 코드 틀렸을 경우 틀렸다는 문구 띄울 공간입니다!

2023-03-04 09:35 UTC, publdaze requested changes
<img width="727" alt="image" src="https://user-images.githubusercontent.com/78250089/222891104-293f9bb2-4a18-4a41-9cb7-a98ccbc72e17.png">
저희 페이지 내에서 사용되는 컴포넌트의 경우 이런 식으로 폴더 구성하면 어떨지 의견 나눴었는데
이런 식으로 폴더 구성해주면 어떨까요?

2023-03-07 09:05 UTC, mia2583 commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
우..우와...useState로 이렇게 컴포넌트를 넣을 수 있는지 몰랐습니다...!!!
대박...배워갑니다

2023-03-08 02:14 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +  );
세미나 비활성화 상태 경우는 문구 따로 띄우는 거 아니었나용??? 그런 줄 알고 figma에 그렇게 만들어놨는데 의견 전달이 잘못된 모양...ㅎㅎ...

2023-03-08 02:14 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
> +      <CardContent className="h-[315px]">{children}</CardContent>
이거 height 안넣으면 회장 내용물이랑 회원 내용물이랑 input 위치가 차이나는데 그게 거슬려서 넣어줬던 걸로 기억합니다!

2023-03-08 12:41 UTC, koty08 approved these changes

2023-03-08 12:41 UTC, koty08 commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  const inputListKey = [0, 1, 2, 3]; // key값 어떻게 줘야할지 모르겠어서 이렇게 했습니다 좋은방법좀ㅠㅠ
추가되는 사항 없이 고유한 식별자가 될 수 있으므로 괜찮을 것 같습니다!

2023-03-09 02:00 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
>        </div>
네! figma에 있는 대로 카드 3개 배치돼서 반투명 상태가 되거나 높이에서 차이 나는 스타일 처리는 따로 브랜치 팔 예정입니다!

2023-03-11 06:35 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +  );
반투명 처리 해놨습니다!

2023-03-11 07:50 UTC, publdaze requested changes
useState에서 state 변수 갱신 함수(set~) 사용하지 않는 부분 제거 해두고, 실제로 사용할 때 추가해서 사용하는 걸로 해도 괜찮을까요?
나중에 사용할 거라 그냥 놔둬도 괜찮을 것 같았는데 터미널에 eslint warning으로 사용하지 않는 변수가 계속 잡혀서 디버깅하는데 불편한 부분이 좀 생기네욤..!

2023-03-11 07:50 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +import { Typography } from '@mui/material';
`Typography` 사용되지 않는 것 같아요!
사용 안 되는 부분 지워주면 좋을 것 같습니다!

2023-03-11 07:50 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
`componentIncorrectAlert`를 state로 두었네요!
출석 코드가 맞는 지 틀린 지 여부에 따라 렌더링할 지만 조건부로 처리해주면 될 것 같은데
따로 state로 둔 이유가 있을까요?

2023-03-11 07:50 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +}
`disabled` 속성을 optional로 두는 건 어떨까요?
`MemberCardComponent.tsx` 12번째 라인에서  `disabled={false}`라고 따로 명시해 주었던데
`disabled` 경우는 특수한 경우라 볼 수 있으니 `disabled`가 아닌 경우에는
따로 지정하지 않아도 되도록 처리하면 좋을 것 같아서요!

2023-03-11 11:43 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
> +      <CardContent className="h-[315px]">{children}</CardContent>
넵! ui부분은 나중에 갈아엎으면서 다 수정할 예정이라 그때 그렇게 적용해보는걸로 하겠습니다!!

2023-03-12 06:11 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
```tsx
  const Attendance = (today: Date) => {
    if (today < attendLimit) {
      // 임시: api에서 출석 status 가져올수 있으면 if문 필요없음
      if (inputCode.join('') === validCode) {
        setIsCorrectCode(true);
        setTempComponent(setAlert['출석']); // TODO: 이후 api로 출석 status 들고오기
        setComponentIncorrectAlert(<p />);
      } else {
        setIsCorrectCode(false);
        setComponentIncorrectAlert(incorrectCodeAlert);
        eraseInput();
        // TODO: Input 내용물 전부 지우기
      }
    } else {
      setIsCorrectCode(true);
      setTempComponent(setAlert['결석']); // TODO: 이후 api로 출석 status 들고오기
      setComponentIncorrectAlert(<p />);
    }
  };
```

전체 코드가 이렇게 되는데
제가 출석이 이미 종료됐을 경우에는 출석코드 맞는지 틀린지 여부(IsCorrectCode)와 상관 없이 무조건 결석 문구가 뜨도록 하기 위해 그렇게 했습니다! 
today < attendLimit && !isCorrectCode 로 해서 삼항 연산자로 해도 될 거 같긴 한데 글케할까용???

2023-03-15 03:00 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
네! 삼항 연산자가 좋을 지 && 연산자가 좋을 지는 아직 감이 안 와서 변경된 코드 보고 그부분은 한 번 피드백 해보겠습니다!

2023-03-15 03:06 UTC, publdaze requested changes

2023-03-15 03:06 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
28라인의 부분은 저희가 사용하는 [mui 라이브러리의 TextField](https://mui.com/material-ui/react-text-field/#validation)(현재 Input 공통 컴포넌트에서 사용하는 컴포넌트)의 `helperText` 속성이 하는 역할과 비슷한 것 같아요!
다른 점이라면 여기에서는 4개의 인풋에 대한 부분은 한 번에 처리해줘야 한다는 게 있긴하지만
28라인의 부분이 Input의 한 역할으로 봐도 될 것 같아서 `helperText` 유사하게 `SeminarInput` 안에서 처리해보는 건 어떨까요?

2023-03-15 03:24 UTC, publdaze requested changes
혹시 리뷰 반영하실 때
[refactor: 리뷰반영](https://github.com/KEEPER31337/Homepage-Front-R2/pull/284/commits/399e1d6c0ffe79af3d1344b67f942143b904a178)
이 커밋처럼 한 번에 묶어서 말고, 각 반영한 내용 커밋 분리해서 올려줄 수 있을까요?
한 번에 서로 다른 변경 사항들이 묶여있어서 각각이 어떤 이유로 수정된 건 지 살펴보기 어려운 것 같아요!

2023-03-15 03:24 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +const BossCardComponent = () => {
저희가 `Component`라는 용어를 react에서 한 단위로써 주로 쓰고 있어서
정확한 의미 전달이 어려울 수 있을 것 같기도 해서
`Component` 대신 `Content` 등과 같은 이름으로 변경하는 건 어떤가요?

2023-03-15 03:24 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +const MemberCardComponent = () => {
> 저희가 Component라는 용어를 react에서 한 단위로써 주로 쓰고 있어서
정확한 의미 전달이 어려울 수 있을 것 같기도 해서
Component 대신 Content 등과 같은 이름으로 변경하는 건 어떤가요?

여기도 마찬가지로요!

2023-03-15 03:24 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
`SeminarButton` 컴포넌트를 별도로 제작한 이유가 있을까요? 공통 컴포넌트인 `FilledButton`를 사용해도 될 것 같아서요!

2023-03-15 11:40 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
사실 저도 FilledButton 쓰고 싶긴 했는데용... 
피그마에서 디자인 된 버튼 크기가 FilledButton 크기랑 다른데 공통 버튼 컴포넌트 css를 어케 바꿔야 할지 몰겠어서 그냥 따로 만들었습니다
지금 생각해보니 그냥 따로 css만들어서 적용시키면 될 거 같긴 하네요??? 글케하까요? 아니면 크기 좀 달라져서 filledButton에서 들고올까요?

2023-03-15 11:58 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
혹시 현재 input을 mui 라이브러리의 TextField로 바꾸자는 뜻은 아니죠??😯
일단 helpertext와 유사하게 사용해보자는 뜻으로 이해하고 SeminarInput 컴포넌트와 합쳐두었습니다!

2023-03-18 03:56 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardComponent.tsx
> +      <div className="mx-auto flex items-center justify-center text-small text-red-500">{componentIncorrectAlert}</div>
네네 이부분에서는 helpertext와 유사하게 사용해보자는 뜻으로 말한거 맞습니다!

2023-03-18 04:04 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
피그마 디자인 페이지에 있는 공통 버튼 가져와 사용한거면 따로 css 적용 안 시키고 FilledButton 그대로 사용하셔도 될 것 같아요!

2023-03-18 04:20 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
좋습니당~~~

2023-03-18 04:28 UTC, publdaze requested changes

2023-03-18 04:28 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +        </>
<img width="200" alt="image" src="https://user-images.githubusercontent.com/78250089/226084493-cf24f609-29e2-40c2-bc97-26b432e0dda7.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/78250089/226084537-50414fbb-ca8e-45c9-9c26-591f4ed44e29.png">

`Countdown`과 `SeminarSelector`에서 출석 지각이라는 텍스트가 겹치는 것 같아요! 위에 이미지가 피그마 디자인에 되어있는 배치인데 빨간 네모 쳐둔 것 처럼 출석 지각 텍스트 묶음과 카운터 or 셀렉터 묶음으로 나눈 후 두 묶음이 들어가는 넓이에 `justify-between` 처리해주면 어떨까요?

2023-03-18 04:29 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
저희 출석체크 페이지 카드에 달린 버튼이 공통 컴포넌트 버튼이랑 다르지않나용...?!?

2023-03-18 04:32 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
엇 저는 공통 컴포넌트 버튼 들고와서 사용하긴 했는데! 뭔가 만지다가 틀어졌을 수도..!

2023-03-18 04:38 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardComponent.tsx
> +      <SeminarButton onClick={startSeminar}>시작</SeminarButton>
그렇다면 공통 컴포넌트 버튼으로 바꾸겠습니당~!

2023-03-18 05:26 UTC, publdaze requested changes

2023-03-18 05:26 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const incorrectCodeAlert = <p className="my-[4px] ">출석코드가 맞지 않습니다. 다시 입력해주세요.</p>;
componentIncorrectAlert state에 DOM element 대신 text로 관리하는 건 어떤가요?
성능 문제와 복잡도가 증가할 수 있어서 DOM 요소를 state에 저장하는 것은 권장되지 않는다고 해요!
경고 메시지 text로 state를 두고 SeminarInput의 helperText에 메시지가 비어 있는지 여부에 따라 text를 전달해주는 건 어떤가요?

2023-03-18 05:33 UTC, publdaze requested changes

2023-03-18 05:33 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      if (0) {
여기 임시이긴 한데 왜 0으로 if문 작성하였는 지 알 수 있을까요? 이 경우에는 무조건 false가 나올텐데
eslint도 뜨고 있어서 유의미한 조건문으로 바꿔줘야 할 것 같아요!

2023-03-18 05:33 UTC, publdaze commented on src/pages/senimarAttend/Card/SeminarCard.tsx
> +import React, { ReactNode, useState } from 'react';
`useState` 지금 사용되지 않고 있어서 제거 부탁드립니다!

2023-03-18 05:34 UTC, publdaze commented
아마 위에꺼 반영되는 것까지 하면 리뷰 끝일 것 같아요!! 화이팅화이팅!!

2023-03-18 08:00 UTC, lcqff commented on src/pages/senimarAttend/Selector/SeminarSelector.tsx
> +  ];
저거 공통 컴포넌트 selector인데 공통 컴포넌트 selector가 id값에서 value 들고오지 않나용???

2023-03-18 08:03 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const incorrectCodeAlert = <p className="my-[4px] ">출석코드가 맞지 않습니다. 다시 입력해주세요.</p>;
와 저 state에 컴포넌트 저장하는 부분에 이런식으로 리뷰 달리는 악몽꿨는데 실현됐네요...
좋습니다! 그렇게 한번 해보겠습니다~

2023-03-18 08:18 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      if (0) {
사실 저도 왜 절케 바꿨는지 기억이 안납니다 벅벅,,, 걍 임시로 절케 해둔 거 같애요
원래는 if 안에 `inputCode.join('') === validCode`가 들어가는데 제가 나중에 input기능 추가하려고 아직 안건드려서 이것도 항상 false가 나오긴 하거든요?? 
일단  `inputCode.join('') === validCode` 넣어두긴 했는데 여전히 문제 있다면 제가 이 pr 머지되고 input 만드는 브랜치 새로 파서 하겠습니답

2023-03-18 08:26 UTC, publdaze commented on src/pages/senimarAttend/Selector/SeminarSelector.tsx
> +  ];
맞아요! value 값으로 쓰이기는 한데 값이 유의미한 값은 아니고 각 옵션을 구분하기 위한 용도라 제가 자주 본 형태는 1,2,3 이런 식으로 순서대로 id를 붙이는 거였어서 따로 내용과 맞춰준 의도가 있는 지 단순히 궁금해서 한 번 물어봤습니당!

각 옵션이 id로 구분만 된다면 어떤 식으로 id 붙일지는 취향 차이일 것 같긴해요!
id 붙이는 방식도 통일하면 좋을 지 개인 취향에 따라 자유롭게 쓰는 게 좋을 지는 아직 잘 모르겠네욤! ㅎㅎ

2023-03-18 08:42 UTC, lcqff commented on src/pages/senimarAttend/Selector/SeminarSelector.tsx
> +  ];
저게저게 BossCardContent보면 제가 SeminarSelector로 `SetLimitValue`를 넘겨주는데 Selector에서 option의 value값을 `SetLimitValue`에 넣어주는 걸로BossCardContent의 `SetAttendValue `(SetLateValue)가 결정됩니다!
나중에 출석/지각 시간을 백엔드로 넘겨줄때 버튼이 클릭된 시간+AttendValue의 값으로 넘겨줘야 해서 option이 5분일때는 value가 5.. 이런 식으로 값을 배정해 줬어요
뭔가.. 설명이 잘 됐는지 모르겠네요😅

2023-03-19 14:21 UTC, publdaze commented on src/pages/senimarAttend/Selector/SeminarSelector.tsx
> +  ];
아하!! 네네 이해했습니다! 이럴 경우는 백엔드에서 옵션 목록을 받아와 id로 넘겨주는 방법도 좋을 것 같기도 하네요!
일단 id를 유의미한 실제 값으로 사용해도 될 지 아닌지는 저도 아는 바가 없어서 그냥 그렇구나 하고 넘어가보겠습니당!

2023-03-19 16:02 UTC, publdaze requested changes

2023-03-19 16:02 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      <SeminarInput helperText={componentIncorrectAlert} />
각 조건에 따라 빈 문자열을 넣을 지 오류메시지를 넣을 지를 처리해주기보다
클릭 시 각 유효성을 체크하고 그 유효성에 따라 정해진 메시지를 띄워주는 형식으로 짜면 어떨까하여
아래처럼 리팩토링 해보았습니다!

이후 다른 기능들 작업되는 사항은 고려 안하고 리팩토링 한 거라 바로 반영해도 괜찮다 싶으면 반영해주시고
지금 당장 이렇게 적용하기는 어렵거나 코드 쓰임과 틀어지는 부분이 있다 싶으면
일단 이 피드백 스루하셔도 됩니다! 나중에 기능 구현한 PR 올라오면 그 PR에서 또 피드백 해보겠습니다!

```tsx
const [isAttendEmpire, setIsAttendEmpire] = useState(false);
const [isCorrectCode, setIsCorrectCode] = useState(false);

const isIncorrectCodeInPeriod = !isAttendEmpire && !isCorrectCode;
const incorrectCodeMsg = '출석코드가 맞지 않습니다. 다시 입력해주세요.';
const attendLimit = new Date(); // 임시
attendLimit.setMinutes(attendLimit.getMinutes() + 5); // 임시
const inputCode = [0, 0, 0, 0];
const validCode = '1234'; // 임시

const handleClickAttendButton = (today: Date) => {
  setIsAttendEmpire(today > attendLimit);
  setIsCorrectCode(inputCode.join('') === validCode);
};

return (
  <>
    <SeminarInput helperText={isIncorrectCodeInPeriod && incorrectCodeMsg} />
```

2023-03-20 08:48 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      <SeminarInput helperText={componentIncorrectAlert} />
호오~~~~~~~ 이런식으로 코드를 짜시다니 생각 못해봤네용!! 
이렇게 하면 정말 멋질거같습니다~! 일케할게용!

2023-03-20 09:14 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      <SeminarInput helperText={componentIncorrectAlert} />
저거 `isAttendEmpire`라고 명칭하신데 이유 있을까요?? 일단 isAttendable로 수정해놨습니답

2023-03-20 15:43 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      <SeminarInput helperText={componentIncorrectAlert} />
기간에 초점을 맞춰서 마감 시간 끝나기 전으로 조건을 주려고 `isAttendEmpire`로 네이밍 해주었는데
추석가능여부로 조건 줄 수도 있겠네요! `isAttendable`도 좋은 것 같습니다!

2023-03-20 15:56 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  helperText?: ReactNode;
`helperText` string 타입으로 더 좁혀줘도 될 것 같아요!

2023-03-21 01:47 UTC, publdaze approved these changes
정말 수고 많으셨습니다!! 드디어 approve네요! 다음 작업들도 화이팅입니다~! 🎉

2023-03-21 02:10 UTC, merged