Feature/스터디 정보 조회 기능 #154
KEEPER31337/Homepage-Front-R2 pull request #288
Opened 2023-03-07 00:47 UTC by amaran-th

## 분류
- [x] 기능 추가
- [ ] 버그 수정
- [x] 리팩토링

## 연관 이슈
- close #154

## 작업 요약
> 스터디 메인 페이지의 완성도를 높였습니다.

## 작업 상세 설명
- mock 데이터 생성 및 연동
- 생성/수정 모달 띄우는 동작 구현(수정의 경우 선택한 스터디 정보가 전달되도록)
- 개선된 UI 반영

## 리뷰 요구사항
- 15분정도 예상합니다!
- 기타
    - 현재 구현하기 무리가 있다고 판단한 기능들입니다. 추후 새로 이슈를 파서 해결할 계획입니다.
        - 썸네일 이미지 적용
        - 실제 API를 통해 받아올 연도 리스트->오래된 스터디 목록 처리 로직
        - 오래된 스터디 목록 UI(게시판 완성되면 가져올 예정)
        - Link 대체방안 생각하기(외부 링크에 대해 제대로 리다이렉트되지 않는 문제)
    - 추신
        - 모달 관련 상세 구현은 별도의 이슈로 처리할 계획입니다. 수정 모달을 띄울 때 데이터를 넘겨주는 부분 외에는 세심히 보지 않아주셔도 괜찮습니다.
      
## Preview 이미지
![image](https://user-images.githubusercontent.com/81465068/223289404-d3e0dd21-214c-42f4-a1b4-f07670a02f53.png)

2023-03-17 05:27 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-03-17 05:27 UTC, jasper200207 commented on src/pages/Study/Modal/StudyModal.tsx
> +              aaa{selectedStudy?.title}
더미 코드가 남아있는거 같습니다!

2023-03-17 06:02 UTC, publdaze reviewed
테스트 코드 작성도 해보면 좋을 것 같아요!

2023-03-17 06:53 UTC, publdaze requested changes

2023-03-17 06:53 UTC, publdaze commented on src/mocks/StudyApi.ts
> +}
interface dto 정해진 거라면 `mocks`에 넣어놨다가 나중에 옮길 필요없이
바로 `src/api/dto.ts` 파일에 선언해주면 될 것 같아요!

interface들 사이에 개행 하나씩 넣어주면 좋을 것 같습니다!

2023-03-17 06:53 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
저희 material-tailwind -> MUI 라이브러리 사용하기로 해서 이부분도 나중에 이슈 따로 파고 한 번 MUI로 변경 부탁드립니다!

2023-03-17 06:53 UTC, publdaze commented on src/pages/Study/Study.tsx
> +  };
year과 season이 스터디를 조회하기 위해 필요한 시기 정보니까 객체로 묶어서 처리하면 깔끔할 것 같아요!
핸들러도 같은 동작을 하니 하나의 핸들러로 더 깔끔하게 구현 가능할 것 같습니다!

2023-03-17 06:53 UTC, publdaze commented on src/pages/Study/Study.tsx
> +      <div className="mb-5 flex  items-center justify-between">
여기 불필요한 공백 추가된 것 같은데 확인 부탁드립니다! 😄
이런 부분은 커밋 올리기 전에 변경 사항 쭉 한 번 살펴보면서 체크해보고 제거하고 올려주면 좋을 것 같아요~!

2023-03-17 06:53 UTC, publdaze commented on src/pages/Study/Study.tsx
> +            label=""
`label` 사용되지 않는 경우 빈스트링 넣기 보다는 optional 값이니 따로 laber 속성 안 넣어주면 더 좋을 것 같습니다!

2023-03-17 06:53 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +  };
console은 제거하고 올려주세요!

불필요한 코드이기도 하고 훗날 해당 커밋으로 돌아와 디버깅할 시에 불편을 초래할 수도 있습니다.
해당 부분의 경우에는 동작을 추후 구현할 부분이니까 당연히 나중에 수정되겠지만
미처 발견하지 못하는 부분에 console.log가 남아있으면 보안 이슈가 발생할 수도 있고 사용자 입장에서
개발자가 신경을 안 썼다는 느낌을 받을 수도 있습니다.
또한 콘솔 출력이 메모리 누수의 원인이 될 수도 있다고 하니 더 조심하는게 좋을 것 같네요! ([참고](https://ui.toast.com/posts/ko_20210611#4-%EC%BD%98%EC%86%94-%EC%B6%9C%EB%A0%A5))

2023-03-22 12:26 UTC, publdaze requested changes

2023-03-22 12:26 UTC, publdaze commented on src/pages/Study/OldStudy.tsx
Nit : 여기 나중에 테이블로 가져올거면 아코디언 관련된 변경사항은 안 쌓아둬도 괜찮을 것 같아요!

2023-03-23 03:24 UTC, amaran-th reviewed
리뷰 감사합니다! 프로젝트에 (체감상)오래 손을 놓고 있었더니 공통 컴포넌트 등 수정해야 할 사항이 많이 보이네요. 이 부분은 추후 새로 이슈 생성하고 반영하도록 할게요!

2023-03-23 03:24 UTC, amaran-th commented on src/mocks/StudyApi.ts
> +}
아하 알겠습니다! 반영했습니다~~

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
넵 따로 TODO 주석 추가해두겠습니다!

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +const AccordionHeaderContent = ({ study }: StudyAccordionHeaderProps) => {
수정 완료했습니다~

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/Modal/StudyModal.tsx
> +              aaa{selectedStudy?.title}
헉 알려주셔서 감사합니다! 삭제했습니다~~

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/OldStudy.tsx
반영했습니다~!

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/Study.tsx
> +      <div className="mb-5 flex  items-center justify-between">
넵 알겠습니다! 미처 신경쓰지 못한 부분이었는데 그렇게 확인할 수 있겠네요...! 알려주셔서 감사합니다~

2023-03-23 03:24 UTC, amaran-th commented on src/pages/Study/Study.tsx
> +            label=""
넵 반영했습니다~!

2023-03-23 03:26 UTC, amaran-th commented on src/pages/Study/OldStudy.tsx
> +const OldStudy = ({ list, memberId }: OldStudyProps) => {
반영하였습니다!

2023-03-23 03:31 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +  };
헉 알겠습니다...! 하지만 저 함수는 형식만 짜놓은 코드라 마땅히 채워넣을 코드가 없어서, TODO 주석을 추가하고 일단은 남겨놔도 괜찮을까요??

2023-03-23 04:24 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +        <div className="space-x-3">
일괄적으로 적용해주었습니다~!

2023-03-23 04:28 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
>  }
오오 안그래도 코드 중복때문에 고민이었는데 이런 타입이 있었군요! 배워갑니다~~
코드에도 반영했습니다!

2023-03-23 04:29 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +        )}
좋은 방법인 것 같아요!! 코드에 반영했습니다~~!

2023-03-23 05:01 UTC, amaran-th commented on src/pages/Study/Study.tsx
> +  };
구현 완료했습니다! 혹시 함수 로직에 대해 더 괜찮은 방안이 있으면 편하게 의견 주세요!
감사합니다~!

2023-03-27 05:26 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +  };
TODO 주석 추가하고 콘솔 부분은 일단 제거해주면 좋을 것 같아요! 로컬에는 편한대로 남겨둬도 괜찮지만 원격에 올라오면 eslint에서도 warning으로 잡아버려서 내가 작업하다 발생한 warning인지 다른 부분에서 발생한 warning인 지 매번 확인하기 번거롭더라구요!

2023-03-31 06:42 UTC, publdaze requested changes

2023-03-31 06:42 UTC, publdaze commented on src/pages/Study/Modal/StudyModal.tsx
> +  selectedStudy?: Partial<StudyListInfo>;
`selectedStudy`는 `StudyListInfo` 타입 중 일부 타입만 가지나요? 왜 `Partial`을 사용하였는 지 궁금합니다!

2023-03-31 06:42 UTC, publdaze commented on src/pages/Study/Modal/StudyModal.tsx
> +const StudyModal = ({ open, handleOpen, selectedStudy }: StudyModalProps): JSX.Element => {
여기서 해당 컴포넌트 함수 타입을 `JSX.Element`로 지정해주었는데
보다 엄격하게 타입 지정해주려면 `JSX.Element` 사용해도 좋아보이지만
TypeScript 컴파일러에서 타입 추론이 충분히 되는 걸로 보이고, 저희가 이제까지 짜온 코드에서 컴포넌트 함수에 대한 타입을 `JSX.Element`로 지정해준 바가 없어서 통일성을 위해 해당 타입 지정은 빼주는 건 어떨까요?

2023-03-31 06:42 UTC, publdaze commented on src/pages/Study/Study.tsx
> +      setCurrentPeriod({ ...currentPeriod, season: Number(event.target.value as string) });
이부분 각각 조건을 두고 반복할 필요 없이 변경하는 대상 key를 `event.target.name`으로 두는 방식으로 하면 더 간단하게 구현 가능할 것 같아요!

2023-03-31 06:45 UTC, publdaze commented
Nit)
저희가 커밋을 확인할 때 리뷰를 반영했다는 사항이 중요하기 보다는 해당 커밋이 어떤 이유로 어떻게 변경된 지가 중요할 것 같아서
코드리뷰 반영한 거에 대한 커밋을 `refactor : 코드 리뷰 반영` 이렇게 커밋 제목을 두기 보다는 변경한 각각에 대한 게 표현되도록 커밋 작성해주면 좋을 것 같아요! 😄

2023-04-02 06:52 UTC, pipisebastian approved these changes
&&연산자 잘 활용하십니당! 수고하셨습니다~

2023-04-02 06:52 UTC, pipisebastian commented on src/pages/Study/Modal/StudyModal.tsx
> +const StudyModal = ({ open, handleOpen, selectedStudy }: StudyModalProps): JSX.Element => {
우왕 JSX.Element type도 있었군요!! 전 몰라서 못썼는데,, ㅎㅁㅎ 알아가욤~

2023-04-04 00:57 UTC, amaran-th commented on src/pages/Study/Modal/StudyModal.tsx
> +  selectedStudy?: Partial<StudyListInfo>;
잘 모르고 vscode에서 권장하는 대로 수정해서 그랬습니다....!
mode 속성까지 추가해서 수정했습니다~~

2023-04-04 00:59 UTC, amaran-th commented on src/pages/Study/Modal/StudyModal.tsx
> +const StudyModal = ({ open, handleOpen, selectedStudy }: StudyModalProps): JSX.Element => {
아 이것도 이전에 어느 컴포넌트에 대해 vscode ide가 권장해준대로 수정해서 그 뒤로 계속 쓰게 됐던 것 같은데, 은지님 말씀대로 통일성 면에선 없애는 편이 나아보이네요!
반영하겠습니당~~

2023-04-04 16:45 UTC, publdaze commented on src/pages/Study/Study.tsx
> +      setCurrentPeriod({ ...currentPeriod, season: Number(event.target.value as string) });
key값으로 name을 넣어주면 됩니다!

```tsx
  const handlePeriodChange = (event: SelectChangeEvent<unknown>) => {
    const { name, value } = event.target;
    setCurrentPeriod({ ...currentPeriod, [name]: value });
  };
```

2023-04-04 16:58 UTC, publdaze requested changes

2023-04-06 11:15 UTC, amaran-th commented on src/pages/Study/Study.interface.ts
> +  mode: 'add' | 'modify';
반영하겠습니다~~!

2023-04-12 14:28 UTC, publdaze requested changes

2023-04-12 14:28 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +import Typography from '@mui/material/Typography';
```tsx
import { Accordion, AccordionSumary, ... } from '@mui/material';
```

이런 식으로 import 해주면 mui 라이브러리에서 들고온 컴포넌트 한 번에 볼 수 있고 코드량도 작아져서 좋을 것 같습니다!

2023-04-12 14:36 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +      <span className="!max-w-16 !min-w-16 !h-16 !max-h-16 !w-16 bg-gray-300">이미지</span>
여기서 important 처리 안 해주면 스타일 적용 안되나요? 단순 span 태그에도 기본적으로 강제되는 스타일이 있어서 important 처리해준건 지 궁금합니다!

2023-04-19 07:00 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +import Typography from '@mui/material/Typography';
반영 했습니다!

2023-04-22 06:07 UTC, publdaze requested changes

2023-04-22 06:07 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
>  import { Divider } from '@mui/material';
<img width="552" alt="image" src="https://user-images.githubusercontent.com/78250089/233765751-1898f879-57f0-4d37-ac2a-19ea2eaf1975.png">

이런 식으로 밑줄 안 뜨는 지도 한 번 확인 부탁드립니다! 안 뜨면 VSCode eslint 확장프로그램 설치되었는 지 확인해보셔야 할 것 같아요!

2023-04-22 06:07 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +import React, { Dispatch, DispatchWithoutAction, SetStateAction, useReducer } from 'react';
`useReducer` 사용 안 되고 있어서 제거 부탁드립니다!

2023-04-22 06:07 UTC, publdaze commented on src/pages/Study/share/StudyChip.tsx
>  import React, { useState } from 'react';
`useState` 사용되고 있지 않는데 제거 부탁드립니다!

2023-04-22 06:07 UTC, publdaze commented on src/pages/Study/share/StudyChip.tsx
> +  font?: 'Normal' | 'Semibold';
chip이 두가지 크기의 폰트로 구분돼서 사용되는 건가요?~?

2023-04-24 02:08 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +  };
아 주석이 있으면 다른 코드가 없어도 오류가 안생기는군요...! console코드 제거했습니다😀

2023-04-24 02:12 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +  };
StudyModal.tsx에도 콘솔 코드가 하나 남아있긴 한데 이 파일은 나중에 모달 구현 이슈 새로 파서 한번에 진행할거라 지금은 패스할게요!

2023-04-24 02:18 UTC, amaran-th commented on src/pages/Study/share/StudyChip.tsx
> +  font?: 'Normal' | 'Semibold';
지금 보니 font보단 fontWeight가 더 정확할 것 같네요!
오해할 수 있을 것 같아서 수정했습니다

2023-04-24 02:23 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
>  import { Divider } from '@mui/material';
밑줄 뜨는데 미처 확인 못하고 지나친 것 같습니다!!
반영했습니다 감사합니다~~

2023-04-24 02:24 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +import React, { Dispatch, DispatchWithoutAction, SetStateAction, useReducer } from 'react';
제거했습니다!

2023-04-24 02:24 UTC, amaran-th commented on src/pages/Study/share/StudyChip.tsx
>  import React, { useState } from 'react';
제거했습니다!

2023-04-24 04:20 UTC, publdaze commented on src/pages/Study/share/StudyChip.tsx
> +  font?: 'Normal' | 'Semibold';
아하 font weight 에 대한 prop! 확실히 헷갈릴 수 있겠네욤! 변경 굿굿 입니다! font weight 의 경우는 굵기 차이가 나는 경우가 2가지 있는 건가요??

2023-04-24 23:46 UTC, publdaze requested changes

2023-04-25 12:56 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
> +import Typography from '@mui/material/Typography';
반영했습니다!

2023-04-28 06:29 UTC, publdaze requested changes
아마 이거 고치는 거랑 slack 투표에 올린 Modify와 Edit중 어떤 용어 쓸 지 결정되면 반영하는 것까지 하고 일단 approve 할 듯 합니다!

2023-04-28 06:29 UTC, publdaze commented on src/pages/Study/Accordion/StudyAccordion.tsx
>        </div>
여기 div가 2번 감싸져 있는데 하나만 사용 가능할 것 같습니다!

2023-04-30 13:56 UTC, amaran-th commented on src/pages/Study/Accordion/StudyAccordion.tsx
>        </div>
반영했습니다!

2023-05-04 00:47 UTC, publdaze approved these changes
너무너무 고생 많으셨습니다!!

2023-05-04 01:46 UTC, merged