Feature/리스트 그리드뷰 전환 기능#134
KEEPER31337/Homepage-Front-R2 pull request #291
Opened 2023-03-09 14:18 UTC by koty08

## 연관 이슈
> #130 #134 
close: #134 

## 작업 요약
> 게시판 내 리스트/그리드 뷰 전환이 가능하게 한다.

## 작업 상세 설명
> Recoil로 테이블 Type을 전역 상태로 관리하였습니다.
Type은 `Grid` `List` 이며, Type State에 따라 보여지는 테이블 컴포넌트를 다르게 처리하였습니다.
> + 추가적으로 기존 더미데이터를 mocks 폴더 내 파일로 리팩토링 진행하였습니다.

## 리뷰 요구사항
> 10분
> Recoil 사용 부분 중점적으로 확인 부탁 드리겠습니다. 🙏 

## Preview 이미지
![image](https://user-images.githubusercontent.com/43947871/224052121-0e926347-4314-465b-9920-d94aec54a79d.png)
![image](https://user-images.githubusercontent.com/43947871/224052136-6cddb049-9555-4498-af9d-dd0ef3d5a479.png)

2023-03-17 05:10 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-03-25 16:19 UTC, publdaze requested changes

2023-03-25 16:19 UTC, publdaze commented on src/pages/board/BoardList.tsx
> +  const [tableType] = useRecoilState<TableType>(tableTypeState);
값 변경없이 읽기만 하는 경우 `useRecoilState` 대신 `useRecoilValue`로도 사용 가능할 것 같아요!

2023-04-02 07:33 UTC, pipisebastian approved these changes
수고하셨습니다~

2023-08-16 05:10 UTC, publdaze commented
프로젝트 상태 지금과 다른 부분이 많은 것 같아서 이 PR은 Close하고 새로 작업하여 PR 올리겠습니다!

2023-08-16 05:10 UTC, closed without merging