style : 인풋공통컴포넌트 border색 포인트컬러로 변경
KEEPER31337/Homepage-Front-R2 pull request #301
Opened 2023-03-16 11:19 UTC by pipisebastian

## 분류
- [ ] 리팩토링

## 연관 이슈
> #282 

## 작업 요약
> 
- 기존 textfield를 그대로 쓰는게 아닌, input, inputLabel, helperText를 각각 나눠서 구현해줌

## 예제 코드
``` tsx
import React from 'react';
import StandardInput from '@components/Input/StandardInput';

const Home = () => {
  const [form, setForm] = React.useState({
    id: '',
    password: '',
    nickname: '',
  });
  const { id, password, nickname } = form;

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setForm({
      ...form,
      [name]: value,
    });
  };

  const [validId, setValidId] = React.useState<boolean>(false);
  const validateId = () => {
    setValidId(/[^ㄱ-ㅎ가-힣a-zA-Z]/g.test(id));
  };

  return (
    <div className="flex w-1/2 flex-col">
      <StandardInput
        label="아이디"
        error={validId}
        helperText={validId ? '아이디는 한글 또는 영문만 가능합니다' : ''}
        name="id"
        value={id}
        onChange={onChange}
        onBlur={validateId}
      />
      <StandardInput
        label="비밀번호"
        placeholder="placeholder입니다!"
        name="password"
        value={password}
        onChange={onChange}
      />

      <StandardInput name="nickname" value={nickname} onChange={onChange} multiline />
    </div>
  );
};

export default Home;

```

## 리뷰 요구사항
> 5분

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/225600253-0c821d00-0015-4c35-8bba-e458368712cb.png)

2023-03-16 11:25 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +      <FormHelperText error={error}>{helperText}</FormHelperText>
해당부분에 error를 안넣어주면, helperText가 유효성검사에 실패하더라도 글자색을 안바꿔줍니다!
원래는 textfield 컴포넌트에서 다 알아서 해줬는데, 분리하니까 다 일일이 넣어줘야하더라구요!

2023-03-16 11:26 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +        className={error ? '' : 'before:!border-b-pointBlue'}
border색깔 포인트컬러로 지정해주는 부분인데, 3항 연산자를 안넣어주면, 
error가 뜨더라도 border색이 자동으로 빨간색으로 바뀌는게 아니라 계속 포인트컬러여서 넣어줬씁니다!

2023-03-17 03:11 UTC, pipisebastian commented
중간에 더 좋은 방법 찾아서 커밋이 많은데, 마지막 커밋만 봐주세요!

2023-03-17 04:06 UTC, Ji-Hyeon212 approved these changes

2023-03-17 05:32 UTC, publdaze requested changes

2023-03-17 05:32 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +      }}
<img width="593" alt="image" src="https://user-images.githubusercontent.com/78250089/225820610-99bdf998-fe1d-4eee-882e-8f03c8f8cd8c.png">

`InputProps={{ className: 'before:!border-pointBlue' }}`
이런 식으로 색 반영하면 더 간단하게 tailwind css 스타일로 적용할 수 있을 것 같은데 이렇게는 어떤가요?

2023-03-17 05:34 UTC, publdaze commented
Nit : 이전에 사용한 방식을 아에 다른 방식으로 바꿔서 필요가 없어진 커밋이 되어버렸다면 reset으로 커밋 되돌아가서 진행하는 걸 추천드려요!

2023-03-17 05:47 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +      }}
허어어억 mui props중에 저런게 있었군요......!!! 알아갑니다ㅜㅜㅜ

2023-03-17 06:03 UTC, publdaze approved these changes
굿굿!!

2023-03-17 06:06 UTC, publdaze reviewed
Nit : 
PR 내용에
> 인용 부분 잘 안 보여서 빼고 쓰기로 했어요!

이슈 번호 앞에 `-` 붙여서 이슈 제목까지 같이 보이게 하도록 정했었답니다!

2023-03-17 06:38 UTC, pipisebastian commented
**추가**
유효성검사를 생각못해, 1번째 사진처럼 border만 포인트컬러가 되서
![image](https://user-images.githubusercontent.com/81643702/225830335-bbf465ae-077f-4959-a74d-b74bb4b32b39.png)
2번째사진처럼 바꿨습니다!
![image](https://user-images.githubusercontent.com/81643702/225830932-1afc3891-b13c-4716-990a-7bbdad642517.png)

2023-03-22 11:10 UTC, publdaze requested changes

2023-03-22 11:10 UTC, publdaze commented on src/components/Input/StandardInput.tsx
> +      InputProps={error ? {} : { className: 'before:!border-pointBlue' }}
`InputProps`가 전달되지 않을 때 기본값이 `undefined`이라서 error 일때는 별도의 스타일을 추가해주지 않는다는 의미이니 `{}`라는 값을 넣어주기 보다는 기본값인 `undefined`로 넣어주면 어떨까요?

2023-03-22 11:10 UTC, publdaze commented
`SearchInput` 컴포넌트는 별도 PR에서 border 색 처리하나요?

2023-03-23 14:18 UTC, pipisebastian commented on src/components/Input/StandardInput.tsx
> +      InputProps={error ? {} : { className: 'before:!border-pointBlue' }}
좋습니다!!!

2023-03-23 14:18 UTC, pipisebastian commented
> `SearchInput` 컴포넌트는 별도 PR에서 border 색 처리하나요?

넵!!

2023-03-24 05:17 UTC, publdaze approved these changes
굿~!

2023-03-25 14:15 UTC, lcqff approved these changes
멋집니당~~~!

2023-03-25 14:16 UTC, merged

2023-03-25 14:16 UTC, mia2583 approved these changes