Feature/confirm modal 제작 #290
KEEPER31337/Homepage-Front-R2 pull request #311
Opened 2023-03-21 08:40 UTC by mia2583

## 분류
- [ v] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈
> #290 

## 작업 요약
> Confirm 모달을 mui 컴포넌트를 이용해 제작했습니다.

## 작업 상세 설명
> 은지님의 ActionModal 코드 참고했어요!
> 단순 내용 확인용 모달이기에 별 다른 동작 없이 x버튼 누르면 닫을 수 있습니다.

## 리뷰 요구사항
> 1분? ActionModal에서 크게 수정사항이 없어서 오래 걸리진 않을 거 같아요.

## Preview 이미지
![image](https://user-images.githubusercontent.com/83392142/226554980-6025fe78-2c5e-410d-88ad-39e634bae591.png)

2023-03-24 05:32 UTC, publdaze commented
Nit: 예제 코드에 `title`에 `"` 끝에 안 달려있어서 예제 테스트 해볼 때 코드 에러 발생하네욤! `"` 추가해주면 좋을 것 같아요!
`date`와 `setDate`도 선언된 코드가 포함 안되어 있는데 예제코드에 포함해주거나 해당 부분을 제외해주거나 하면 좋을 것 같습니다!

2023-03-24 05:52 UTC, publdaze requested changes

2023-03-24 05:52 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +import { Dialog, DialogActions, DialogContent, DialogTitle } from '@mui/material';
`DialogActions` 사용하지 않는 컴포넌트 같아요! 제거해주면 좋을 것 같습니다!

2023-03-24 05:52 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      <VscChromeClose className="absolute right-0 m-5 cursor-pointer" size="19" color="#4CEEF9" onClick={onClose} />
바로 아이콘으로 클릭 이벤트 처리하는 방식 말고 MUI의 `IconButton` 컴포넌트를 사용해보는 건 어떨까요?
해당 부분이 버튼이라는 것도 명확하게 포함되고, hover됐을 때 클릭됐을 때 스타일이 표현돼서 좋을 것 같더라구요!

2023-03-24 05:52 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      <VscChromeClose className="absolute right-0 m-5 cursor-pointer" size="19" color="#4CEEF9" onClick={onClose} />
<img width="680" alt="image" src="https://user-images.githubusercontent.com/78250089/227435015-c8a19d6d-8ab3-4a40-bea4-db63a085f747.png">

저희 아이콘 색 표현할 때 `color`에 넣는 방식 말고 `className`에 넣는 방식으로 결정되어서 이 방식으로 변경 부탁드립니다!

2023-03-27 14:57 UTC, Ji-Hyeon212 approved these changes
오옹 수고하셨습니다👍

2023-03-30 08:19 UTC, koty08 approved these changes

2023-04-01 04:53 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +      <VscChromeClose className="absolute right-0 m-5 cursor-pointer" size="19" color="#4CEEF9" onClick={onClose} />
안그래도 저도 hover할 때 마우스 모양이 바뀌었으면 해서  `className`에 `cursor-pointer` 넣는 방식으로 해결했습니다. 그런데 `IconButton` 컴포넌트가 있군요! 수정했습니다~
아래 아이콘 색상 표현 방식도 바꿨어요.

2023-04-02 08:02 UTC, publdaze requested changes

2023-04-02 08:02 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +import { IconButton } from '@mui/material';
`@mui/material`에서 import 해줄 때 2,4라인 두 군데로 분리되어서 import 하고 있는데 한 번에 import 가능할 것 같아요!

2023-04-02 08:16 UTC, publdaze requested changes

2023-04-02 08:16 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      <div className="absolute right-0 m-3">
`right`, `top`으로 위치 지정하지 않고 마진으로 위치 적용해준 이유가 있을까요?

<img width="446" alt="image" src="https://user-images.githubusercontent.com/78250089/229340448-85599fa5-8cdf-458e-8f40-3d31831412cc.png">
위치 조정을 위해서 마진을 넣은 것 같은데 마진만큼의 공간을 가지고 있는 게 조금 어색한 것 같기도 해서요!

2023-04-02 08:16 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +        </IconButton>
`IconButton`에 width 별로도 지정해준 이유가 있나요? 적용전과 후가 큰 차이 없어보여서 필요성을 잘 모르겠습니다!

2023-04-02 08:16 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +          <VscChromeClose className="fill-pointBlue" size={19} />
<img width="392" alt="image" src="https://user-images.githubusercontent.com/78250089/229340783-0f0766e2-5a2d-4101-babe-684fa75bf867.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/78250089/229340821-0787e201-f534-4a82-b9d3-34b0c915c235.png">
size를 28로 지정해야 디자인 상의 크기와 유사해질 것 같아요! (밑에 이미지의 피그마 사진에서 X규격에 대한 크기가 19정도 사이즈 입니다!)

2023-04-27 00:36 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +      <div className="absolute right-0 m-3">
위치 조정할 때 습관적으로 마진이 제일 먼저 떠오르네요...top, right 머리속에 넣어두겠습니다

2023-04-27 00:43 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +        </IconButton>
아이콘을 div로 감싸주기 전에 x위치를 조정하려고 썼던 코드인데 미처 삭제 못했네요. 수정했습니다!

2023-05-07 15:22 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +          <VscChromeClose className="fill-pointBlue" size={19} />
늦어서 죄송합니다!수정했습니다!!

2023-05-07 15:55 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +    <Dialog open={open} PaperProps={{ className: 'px-2 py-1' }} fullWidth={Boolean(modalWidth)} maxWidth={modalWidth}>
MUI에서 제공하는 배경색이랑 디자인쪽에서 요구하는 배경색이 달라서 `PaperProps`의 `className`으로
`!bg-subBlack brightness-125 !bg-none`
이 코드 추가해줘야할 것 같아요! (액션 모달 참고해주세요!)

이 PR에서 진행해도 되고 아니면 따로 이슈 생성해서 다음 작업으로 PR 올려주셔도 될 것 같습니다!

2023-05-07 15:55 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      </div>
여기서 `div` 태그 감싸지 않고 `IconButton` 컴포넌트에 `div`에 적용한 `className` 넣어주면 `IconButton`의 위치를 바로 지정해줄 수 있을 것 같은데 그렇게 해보면 어떨까요?

(테스트 해본 건 아니라서 동일하게 적용되는 지 확실하지 않습니다. 나중에 한 번 해보고 추가 코멘트 남길게요! 명서님이 먼저 하게 되면 제대로 되는 지 코멘트 부탁드립니다!)

2023-05-08 00:03 UTC, publdaze commented on src/components/Modal/ConfirmModal.tsx
> +      </div>
`absolute`에 important 넣어주면 동일하게 표현되는 것 같습니다!

+ `ml-3` 여백 필요한게 아니면 지워줘도 될 것 같아요!

2023-05-11 10:30 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +    <Dialog open={open} PaperProps={{ className: 'px-2 py-1' }} fullWidth={Boolean(modalWidth)} maxWidth={modalWidth}>
오...색상 차이가 있을 줄은 생각 못했네요 수정했습니다.

2023-05-11 10:42 UTC, mia2583 commented on src/components/Modal/ConfirmModal.tsx
> +      </div>
헐헐헐...제가 정말 헤매다가 div 추가 방식으로 구현했는데...! 한 개만 붙이면 되었다니...흑흑 충격입니당

2023-05-14 12:31 UTC, publdaze approved these changes
굿굿굿 수고하셨습니다~!

2023-05-14 13:23 UTC, merged