Feature/세미나 추가 UI #139
KEEPER31337/Homepage-Front-R2 pull request #313
Opened 2023-03-21 09:26 UTC by mia2583

## 분류
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈
> #139 

## 작업 요약
> 세미나 추가 ui부분 제작했습니다.

## 작업 상세 설명
> 세미나 관리 페이지에서 추가 버튼을 누르면 세미나 추가 관련 모달이 짜잔~하고 나옵니다.
> 
## 리뷰 요구사항
> 5분
> 예전에 ActionModal 변경 전에 미리 코드 작성/커밋해놓고 미뤄놨던 거라 코드 수정하게 된 부분이 좀 있어서 헷갈릴 듯 하네요. 커밋 내역 제목들은 참고만 하고 file changed로 한번에 전체 코드 보는 거 추천드립니다..

## Preview 이미지
![image](https://user-images.githubusercontent.com/83392142/226564758-b83efe51-b68e-43c8-9898-3da3535847d1.png)
![image](https://user-images.githubusercontent.com/83392142/226564804-249d76fe-df0e-4804-9cf7-839c0eff2844.png)

2023-03-26 07:08 UTC, publdaze requested changes

2023-03-26 07:08 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +  const [openSeminarAddModal, setOpenSeminarAddModal] = useState(false);
`useState` 사용할 때 위에서는 `React.useState`로 가져와 사용하고 있고 아래에서는 `useState`로 사용하고 있네요!
둘 중 하나로 통일해서 사용하면 좋을 것 같아요!

`useState` 훅 같은 경우는 자주 사용하는 훅이니 매번 `React.`을 앞에 붙이기 번거로울 수 있을 것 같아서 저는 주로 미리 불러와두고  `useState`로만 사용하는 편입니다!

2023-03-27 06:51 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +  const [openSeminarAddModal, setOpenSeminarAddModal] = useState(false);
오...그냥 냅다 예시 복붙 사용한거라 몰랐는데 그렇네요...같은 useState이네요!수정했습니다.

2023-03-27 06:57 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
> +          }}
오옹 확실히 이렇게 하는 편이 클릭 동작이 하나로 정의되어서 훨씬 코드가 깔끔해보이네요!피드백 감사합니다

2023-04-02 11:07 UTC, publdaze requested changes

2023-04-02 11:07 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
> +          }}
이부분 따로 화살표 함수 내부에서 함수 호출하는 방식 말고
`onActionButonClick={handleSeminarAddButtonClick}`
이런 식으로 바로 핸들러 함수 호출하는 방식 사용하면 더 깔끔할 것 같아요!

2023-04-02 12:22 UTC, publdaze requested changes

2023-04-02 12:22 UTC, publdaze commented on src/pages/admin/SeminarManage.tsx
>        </div>
이부분에서 UI상에서 추가 삭제가 나란히 배치되어 있고, 상위 div(27번 라인)에서 적용하는 하위 요소들의 css가 modal에는 적용 안 되는 부분이라서 저 같은 경우에는 UI상 렌더링되어 보이는 부분이 코드에서도 직관적으로 보이도록 버튼들만 하위 요소로 넣고 modal은 해당 div 바깥쪽으로 빼는 걸 선호하는 편이에요!

하지만 명서님의 의도가 추가 버튼과 직결되는 모달이라서 추가 버튼 아래에 해당 컴포넌트를 위치해주었다면 그것도 나름대로 코드 흐름에서 이해하기 좋은 방식일 것 같아요!

어느 방식으로 처리해줄 지는 취향 차이지 않을까 싶어서 변경 요구하는 코멘트는 아니고, 이렇게도 짜볼 수 있구나하는 거 한 번 생각해보면 좋을 것 같아서 코멘트 적어봤습니다!

2023-05-11 11:17 UTC, mia2583 commented on src/pages/admin/SeminarManage.tsx
>        </div>
서윤님 코드 참고해서 랜더링 UI랑 동작으로 수행되는 modal부분 따로 분리했습니다.
다만 modal 분리를 위해 폴더, 파일 구조를 변경했더니 아예 새로운 파일에 모든 코드가,,,다 들어가버리네요.

"refactor : modal과 UI 랜더링 코드 분리하기" 와 "refactor : 세미나 추가 모달 구현 파일 분리" 이 두 커밋이 해당 내용들을 반영한 커밋들 입니다.

2023-05-19 15:26 UTC, publdaze requested changes

2023-05-19 15:26 UTC, publdaze commented on src/pages/admin/SeminarManage/SeminarManage.tsx
> +  const [openSeminarAddModal, toggleSeminarAddModal] = useReducer((prev) => !prev, false);
이전에 사용하던 `material tailwind` 라이브러리의 `Dialog` 컴포넌트에서는 토글식 핸들러를 필수로 전달해주어야 했어서 리뷰할 때 `useReducer`를 사용하여 상태를 토글하는 방식을 제안했었습니다. 그런데 지금은 `MUI` 라이브러리를 사용하게 되면서, 각각의 사용 부분에서 상태가 항상 `true` 나 `false`로 일관된 값만 사용됩니다. 따라서 토글 형식을 자유롭게 사용하는 방식이 아닌, 사용되는 부분에서 상태가 `true`인지 `false`인지 명확히 구분되면 좋을 것 같아서 `useState`를 사용하여 각각의 상태를 명확하게 설정하는 방식으로 변경하면 어떨까 합니다!

2023-05-22 14:03 UTC, mia2583 commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +        }}
오잉..?!다시 반영했습니다!

2023-05-22 23:50 UTC, mia2583 commented on src/pages/admin/SeminarManage/SeminarManage.tsx
> +  const [openSeminarAddModal, toggleSeminarAddModal] = useReducer((prev) => !prev, false);
넵 수정했습니다!!

2023-05-27 00:20 UTC, Ji-Hyeon212 approved these changes

2023-06-08 01:36 UTC, publdaze requested changes

2023-06-08 01:36 UTC, publdaze commented on src/pages/admin/SeminarManage/SeminarManage.tsx
> +  const [openSeminarAddModal, toggleSeminarAddModal] = useState(false); // useReducer((prev) => !prev, false);
`useState`로 변경되었으니 상태변경함수 네이밍도 toggle -> setOpen으로 prefix 변경하면 어떨까합니다!

2023-06-08 01:36 UTC, publdaze commented on src/pages/admin/SeminarManage/SeminarManage.tsx
> +      <AddSeminarModal open={openSeminarAddModal} toggleOpen={toggleSeminarAddModal} />
여기 props도 toggle -> set 어떨까합니다!

2023-06-08 01:37 UTC, publdaze commented on src/pages/admin/SeminarManage/SeminarManage.tsx
> +  const [openSeminarAddModal, toggleSeminarAddModal] = useState(false); // useReducer((prev) => !prev, false);
혹시 뒤에 `useReducer` 주석 남겨둔 이유가 있나욤?~?

2023-06-08 01:40 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +  };
여기서 `toggleOpen`에 제어하는 부분이 `AddSeminarModal`이 열리고 닫히는 부분 제어하는 것 같은데, `AddSeminarModal`의 내부 버튼인 액션 버튼에 `AddSeminarModal`이 열리는 기능 추가 한게 맞을까요?

2023-06-08 01:41 UTC, publdaze requested changes

2023-08-16 04:17 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +  };
AddSeminarModal의 내부 버튼인 액션 버튼이 보이는 상태는 이미 모달이 열려있는 상태이기 때문에 의미가 없을 것 같아서 제거하겠습니다.

2023-08-16 04:20 UTC, publdaze approved these changes

2023-08-16 04:20 UTC, merged