Feature/도서추가삭제 모달창 UI 구성 #220
KEEPER31337/Homepage-Front-R2 pull request #315
Opened 2023-03-24 12:42 UTC by pipisebastian

## 연관 이슈
- Close #220 

## 작업 요약
- 도서추가, 삭제 모달창 UI 구성

## 작업 상세 설명
- 도서추가 -> 유효성 검사 추가했습니다. 도서명, 저자 둘중 하나라도 입력안하면 모달창 안닫힙니

## 리뷰 요구사항
- 3분
- #303 PR이 선행 PR 이라 먼저 리뷰 후 이 PR 리뷰 부탁드립니다.
- [Feature/인풋공통컴포넌트 border색 포인트컬러로 변경 #301 ](https://github.com/KEEPER31337/Homepage-Front-R2/pull/301) 이 커밋부터 봐주시면 됩니다.

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/227523618-a57a2ff1-e6d7-41ee-87ad-f5679fbb0e9a.png)
![image](https://user-images.githubusercontent.com/81643702/227524077-da1b85fe-35b3-4b90-b22a-47929d436037.png)

2023-03-27 08:06 UTC, mia2583 reviewed
그그 도서 추가에서 도서명, 저자 입력한 후에 추가 버튼 누르면 잘 닫히는데, 이후에 "도서추가" 버튼을 한번 더 누르게 되면 이전에 추가했던 내용들이 그대로 저장되어 나와요!
창이 닫히면 입력된 내용들을 초기화할 필요가 있을 거 같습니다

2023-03-27 15:42 UTC, publdaze requested changes
UI 구성한 부분 말고 기능 관련된 부분도 조금 있는 것 같은데 어느 정도의 기능이 포함되어 있는 지 모르겠어서
유효성 검사 부분, 입력 받는 부분에 대한 기능에 대해 이 PR에서 리뷰 진행하면 되는 걸까요?

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [validAuthor, setValidAuthor] = useState<boolean>(false);
이 두 state가 boolean 값을 나타내니 앞에 `is` prefix를 추가해주면 어떨까요?

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  });
form이라는 변수명으로는 어떤 데이터에 관련된 건지 명확하게 와닿지 않는 것 같아요!
도서정보입력 관련된 변수라는 걸 조금 더 와닿게 네이밍 해보면 어떨까요?

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
여기서도 핸들러 이름이 더 명확히 와닿도록 도서정보입력변경 정도의 의미를 담은 네이밍으로 바꿔보면 어떨까요?

하나의 핸들러로 여러 인풋을 관리 하는 방법은 너무 잘 사용하신 것 같아요! 👍👍

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
여기서 `validate` 단어를 검색해보니 `유효하게 하다`라는 의미를 갖고 있는 것 같더라구요!
이 부분의 함수는 유효성을 체크하는 부분 같아서 `checkValidation`, 여기서 더 나아가 도서 추가에 대한 검증이라는 의미도 내포해주면 좋을 것 같아요!

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [validAuthor, setValidAuthor] = useState<boolean>(false);
```tsx
 const validate = () => {
    setValidTitle(title === '');
    setValidAuthor(author === '');
  };
```
state set 해주는 부분을 보니 빈스트링 일 때(필수값 충족 못했을 때) `true`가 되는 것 같아요!
state가 유효하다는 의미를 가지게 하려면 초기값을 true로 해주고 set 해주는 부분에서 충족 못할 시 `false`를 반환하도록 해야할 것 같아요!

2023-03-27 15:42 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        onClose={toggleOpen}
모달 컴포넌트 라이브러리가 변경되면서 모달을 닫는 핸들러만 사용해도 되는 형태여서
toggle 형태로 핸들러 넘겨주기 보다는 `setOpen(false)` 로 확실히 닫는 동작을 내포한 핸들러를 넘겨주는게 더 좋을 것 같아요!

[해당 PR](https://github.com/KEEPER31337/Homepage-Front-R2/pull/289) 예제 코드 하단에 관련해서 언급해놨는데 확인해봐주세요!

2023-03-29 11:59 UTC, pipisebastian commented
> 해당 PR 머지되면 도서 추가/삭제 모두 이슈가 닫히던데 삭제 모달 UI에서 책 구분 없이 그냥 전체 책 목록이 다 삭제되는 건가요..?

아앗! 도서삭제 UI 이슈 close되는건 빼겠습니다!! 감사합니다!

2023-03-29 12:11 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  });
type을 AddBookInfo로 두고있어서 ` const [bookInfo, setBookInfo]` 로 변경했습니다! 감사합니다!

2023-03-29 12:41 UTC, pipisebastian commented
> UI 구성한 부분 말고 기능 관련된 부분도 조금 있는 것 같은데 어느 정도의 기능이 포함되어 있는 지 모르겠어서 유효성 검사 부분, 입력 받는 부분에 대한 기능에 대해 이 PR에서 리뷰 진행하면 되는 걸까요?

앗 넵..! 다음부턴 이슈따로 파서 작업하겠습니다!!

2023-03-29 13:23 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        onClose={toggleOpen}
넵! 적용했습니다! 감사합니다!!

2023-04-01 04:46 UTC, mia2583 approved these changes
수고하셨습니다~

2023-04-02 10:35 UTC, publdaze requested changes

2023-04-02 10:35 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
<img width="428" alt="image" src="https://user-images.githubusercontent.com/78250089/229347636-67344691-f4f8-4d43-92b4-ce683e49a3c7.png">
저희 슬랙에서 이전에 얘기한 것 처럼 저희 프로젝트에서는 이벤트 핸들러의 실제 구현부 함수 네이밍할 때 prefix로 handle 사용해주면 좋을 것 같아요!

2023-04-02 10:58 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
이부분에서 왜 별도의 handler 함수를 사용하지 않고 화살표 함수 내에서 함수 호출했는 지와
함수명을 PascalCase로 둔 이유도 궁금합니다!

2023-04-02 10:58 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [validAuthor, setValidAuthor] = useState<boolean>(false);
이부분 각각 state로 두는 방식 말고 trigger를 사용하여 수정 시에만 error 문구 처리해주는 방식이 좋을 지 지금 구현된 방식이 좋을지와 둘 다 빈스트링인 지 체크하는 부분이라 공통적인 유효성 검사를 util함수로 따로 빼주는 게 좋을 지 생각해보는 중이라 조금 더 생각해보고 추가 코멘트 달아보겠습니다!

2023-04-02 11:01 UTC, publdaze requested changes

2023-04-02 11:01 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/DeleteBookModal.tsx
> +    </div>
여기서 div로 모달 컴포넌트 상위에 한 뎁스 더 감싸준 이유가 있을까요? (추가 모달도 마찬가지로 한 뎁스 더 감싸져있던데 그렇게 감싸준 이유가 궁금합니다!)

2023-04-02 11:01 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        <div className="flex h-full w-full flex-col space-y-5">
여기 `h-full w-full` 따로 추가해주지 않아도 modal 크기로 기본적으로 잡혀서 동일하게 적용되는 것 같아요!

2023-04-24 08:28 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
그...그러게요..! 수정하겠습니다!!(삐질 이모티콘)

2023-04-24 08:50 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
`handleBookAddButtonClick`은 어떤가요?~?

2023-04-24 08:52 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
넵넵! handleAddBookInfoChange로 변경했습니다!

2023-04-24 08:59 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/DeleteBookModal.tsx
> +    </div>
헤헿 그거슨.. div로 무조건 감싸줘야한다 생각했기때문입니다!! 수정했씁니다~

2023-04-24 09:00 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        <div className="flex h-full w-full flex-col space-y-5">
아항 감사합니다! 수정했습니다!

2023-04-24 12:06 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
오홍!혹시 book add 이 순서로 하는 이유가 있을까욤??
생각해보니 저렇게 한 이유가 파일이름이 `AddBookModal.tsx`라서 통일하려고 add book 이 순서로 했었습니다!
바꾼다면 통일성있게 book add 이순서로 다 바꾸는게 좋을 것 같아서욤! 

그렇게 되면 위에 `handleAddBookInfoChange`  ->  `handleBookAddInfoChange` 로 바꿔야할 것 같은데,, 뭔가 어색해보입니당..!

2023-04-24 12:11 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
저는 add book 순서로 한 이유가, **추가되는 도서** 라는걸 나타내고 싶어서였씁니다!
근데 다시 생각해보니 book add button이 더 자연스러워보이고 이거 참 어렵군요...

아니면 은지님 제안해주신 것 처럼 함수명은 `handleBookAddButtonClick`, 파일명도` BookAddModal.tsx` 로 변경하고
`handleAddBookInfoChange `같은 경우는 Add를 안붙히고 `handleBookInfoChange `로 바꾸는거 어떨까욤??

2023-05-07 15:28 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +        }}
아 저는 추가 버튼으로 add를 동사로 보지 않고 "추가 버튼"으로 생각하고 그렇게 리뷰했었습니다!
서윤님 얘기 들어보니 그렇게도 괜찮아보이네요...!

추가 기능을 사용하는 다양한 페이지들이 있으니 순서 통일해서 사용하면 좋을 것 같은데 슬랙에 투표 올려보는 건 어떨까요?

2023-05-07 16:15 UTC, publdaze requested changes

2023-05-07 16:15 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [totalBookNumber, setTotalBookNumber] = useState<number | undefined>(1);
`totalBookNumber`의 경우 초기값으로 `1`을 넣어준 걸로 봐서 default 값으로 `1`이 무조건 지정되는 것 같네요!
그렇다면 `undefined`라는 타입이 사용될 일은 없는 것 같은데 제거해도 괜찮지 않을까요?~?

2023-05-07 16:15 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
여기서 함수명을 `onReset`으로 해주셨는데 `on`이라는 prefix가 붙으니 이벤트 핸들러 prop명으로 쓰이는 네이밍과 겹쳐서 헷갈릴 수도 있지 않을까 조금 우려가 됩니다! (`on`이라는 prefix를 사용한 별다른 이유가 있다면 그대로 사용하셔도 됩니다!)

그리고 무엇을 리셋하는 지에 대한 내용이 함수명에도 포함되면 좋을 것 같아요!

2023-05-14 10:55 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [totalBookNumber, setTotalBookNumber] = useState<number | undefined>(1);
넵 수정했습니당!

2023-05-14 10:56 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
resetAddBookInfo로 변경해줬습니다!

2023-05-19 15:58 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  const [validAuthor, setValidAuthor] = useState<boolean>(false);
유효성 검사 부분 커스텀 훅으로 뺄까합니다! 이번주 회고 전까지 작업해보고 회고 때 안건으로 얘기해보겠습니다!

2023-05-19 15:58 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +  };
유효성 검사 부분 커스텀 훅으로 뺄까합니다! 이번주 회고 전까지 작업해보고 회고 때 안건으로 얘기해보겠습니다! 22

2023-05-19 16:23 UTC, publdaze requested changes

2023-05-19 16:23 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +      </div>
여기 대부분의 div에 `flex flex-col` 클래스를 사용해주었네요! `StandardInput` block 요소로 추정되는데 block 요소가 맞다면 기본적으로 위에서 아래로 수직으로 쌓이기 때문에  `flex flex-col`를 별도로 추가해주지 않아도 동일하게 수직으로 쌓일 것 같은데 따로 명시해준 이유가 있을까요?

2023-05-19 16:23 UTC, publdaze commented on src/pages/admin/LibraryManage/components/TotalBookNumberSelector.tsx
> +  value?: number;
`value`값으로 넘어오는 `totalBookNumber`가 기본값 `1`이 지정되어 있어서 무조건적으로 값이 전달되는 것 같은데 optional말고 필수값으로 처리해주는 건 어떤가요?

2023-05-19 16:23 UTC, publdaze commented on src/pages/admin/LibraryManage/components/TotalBookNumberSelector.tsx
> +}
`className`을 받아오도록 처리해주었는데 `TotalBookNumberSelector`가 사용되는 곳들에서 스타일이 다르게 적용되는 부분이 있어서 prop으로 받아오는 건가요?

2023-05-20 06:16 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +      </div>
실행 시켜 보니 수평으로 쌓이네요 😮
좀 더 분석해보고 추가 코멘트 달겠습니다! 🧐

2023-05-20 06:57 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +      </div>
<img width="1364" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/ae40d78b-9607-4ee1-923a-8c7edea315d0">

MUI TextField가 input태그가 최상위 태그라고 생각했는데 `inline-flex` display 속성을 가지고 있는 div 태그가 최상위 태그였네요..!!

2023-05-20 07:33 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +      </div>
```tsx
<div className="flex flex-col">
  도서명
  <StandardInput
    error={validTitle}
    helperText={validTitle && '도서명을 입력해주세요'}
    name="title"
    value={title}
    onChange={handleAddBookInfoChange}
  />
</div>
```

```tsx
<div>
  <Typography>도서명</Typography>
  <StandardInput
    error={validTitle}
    helperText={validTitle && '도서명을 입력해주세요'}
    name="title"
    value={title}
    onChange={handleAddBookInfoChange}
  />
</div>
```

서윤님 원래 코드 작성한 대로 `flex flex-col`을 사용하거나 아니면 도서명을 block 태그(`Typography` 컴포넌트는 `p`태그로 이루어져 있습니다)로 감싸주거나 하는 방식이 있을 것 같네요!
요소가 추가될 수 있다는 확장성을 고려하여 수직 정렬에 초첨을 둔다면 `flex flex-col`이 좋을 것 같고,
시맨틱하게 태그로 표현하는 것에 초점을 둔다면 `Typography` 컴포넌트 사용하면 좋을 것 같은데,
어떤 방식을 쓸지는 서윤님 판단에 맡기겠습니다!

+) 66번라인의 `flex flex-col`은 내부 요소가 다 block 요소라서 제거해줘도 될 것 같습니다!

2023-05-20 07:36 UTC, pipisebastian commented on src/pages/admin/LibraryManage/components/TotalBookNumberSelector.tsx
> +  value?: number;
좋습니다!! 수정하겟숩니다!

2023-05-20 07:40 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +      </div>
허어어억 죄송합니다! ui모달창에 썸네일도 들어가면서, 
이거 머지되면 한번 더 ui수정 풀리퀘 올리는데, 거기서 은지님이 추천하신 방법대로 코드 짰었습니다!

해당 풀리퀘에서 바꾸는건 생각 못 했었네욤..! 얼른 수정하겠습니당!

2023-05-20 07:44 UTC, pipisebastian commented on src/pages/admin/LibraryManage/components/TotalBookNumberSelector.tsx
> +}
이부분은..! 예시코드 그대로 가져왔기때문입니당! 생각해보니 도서관리에서 책 권수 정하는 selector는 통일하는게 좋을 것 같습니다! className props빼겠씁니다!

2023-06-03 11:42 UTC, publdaze commented
nit)
[feat : selector props - value optional에서 필수로 변경](https://github.com/KEEPER31337/Homepage-Front-R2/pull/315/commits/956a2ad170998392eb64d21e3a4973e5ee1a268f)
[feat : selector props - className 제거](https://github.com/KEEPER31337/Homepage-Front-R2/pull/315/commits/e6800480f29d93359981095f46af1e2807610ef4)

이 2개의 커밋 같은 경우는 기능 추가한 커밋이라기 보다는 개선한 느낌이라 `refactor` 커밋 타입이 더 어울릴 것 같네요! 😆

2023-06-03 13:27 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +    if (title !== '' && author !== '') {
여기서 if 조건에 들어가는 것도 유효성에 관련된 부분인데, `validate` 함수와 별개로 또 유효성을 체크하는 느낌으로 다가와서,
이렇게 처리하는 게 좋은 방식인지는 모르겠으나 의견을 내보자면
`validate` 함수에서 `title !== '' && author !== ''` 결과 값을 `return`해주어 `isValid` 변수에 담은 후
`if(isValid) ~~` 이런 식으로 진행하면 조금 더 깔끔하지 않을까 합니다!

2023-06-03 13:27 UTC, publdaze commented on src/mocks/LibraryManageApi.ts
> +  { key: 'borrowState', headerName: '대출현황' },
저는 주로 `state` 보다 `status`라는 변수를 더 많이 써서 차이를 찾아봤는데 미묘한 차이가 느껴지긴 한데 확실히 와닿지 않을 수 있을 것 같아서 한 번 차이 찾아보고 [이 블로그](https://remocon33.tistory.com/701)에서 예시가 그나마 더 와닿을 수 있을 것 같아서 이것도 참고해보면 좋을 것 같습니다!

저는 status가 더 어울리는 게 아닐까 추측하는데 서윤님의 의견도 궁금합니다!

2023-06-05 14:14 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +    if (title !== '' && author !== '') {
오홍 그렇게 느낄 수도 있겠군욤,,! 수정했는데 이거 맞을까요??

2023-06-05 14:18 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
> +    if (title !== '' && author !== '') {
네 맞습니다! 👍👍

2023-06-06 05:09 UTC, publdaze requested changes
아앗

<img width="555" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/e84773f8-6acd-481f-897f-cb78117b31fe">  

그 폴더명 저희 `components` 폴더 대신 컴포넌트 내부에서도 분류해서 폴더 생성하기로 정했어서
이 컴포넌트 같은 경우는 selector니까 `Selector` 폴더 만들어서 내부에 위치해주면 좋을 것 같습니다!

2023-06-21 07:19 UTC, publdaze approved these changes
수고하셨습니다!

2023-06-21 07:20 UTC, merged