Feature/세미나 출석 카운트다운 구현 #308
KEEPER31337/Homepage-Front-R2 pull request #316
Opened 2023-03-26 12:23 UTC by lcqff

## 분류
- [x] 기능 추가

## 연관 이슈
#284 #308 #207 #172 

## 작업 요약
회장과 회원 페이지의 카운트다운 기능을 구현했습니다.

## 작업 상세 설명
prop로 카운트다운이 시작하는 시간, 끝나는 시간 두 가지를 받습니다.
props로 시작하는 시간을 받아오는 이유는 카운트다운이 출석 시간을 카운트 다운하는 것과 지각 시간 카운트 다운 하는 것 두 가지가 있는데  지각 시간 카운트는 출석 시간 카운트가 끝나기 전까지 (지각 시간 카운트 시작 시간이 되기 전까지) 카운트다운 되지 않고 그대로 있어야 하기 때문입니다.

leftTime과 diff가 따로 존재하는 이유는 카운트다운이 00:00이 되면 '마감'으로 글씨가 바뀌어야 하는데, diff의 타입이 Duration이라 string값을 대입할 수 없고, Duration | string 으로 타입을 바꾸더라도 toFormat을 적용할 수 없어서 그냥 따로 주었습니다.

참고로 아직 api로 적용한 것이 아니라 새로고침을 해도 카운트 다운이 유지되지 않고, 회원 페이지와 회장 페이지의 카운트 다운이 따로놉니다. 이건 api 적용하면 해결될겁니당

## 리뷰 요구사항
> 10분?

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/227775325-71039c88-0dab-417c-85da-1ae1c453e473.png)

2023-03-27 05:29 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +  const lateLimit = attendLimit.plus({ days: 0, hours: 0, minutes: 0, seconds: 5 }); // 임시: 이후 api에서 가져옴
테스트 용도로 일부러 5분 아니라 5초로 맞춰놨습니다~! 페이지 개발 완료되면 수정할게요!

2023-03-29 04:24 UTC, publdaze requested changes

2023-03-29 04:24 UTC, publdaze commented on src/pages/senimarAttend/Countdown/Countdown.tsx
> +  const [diff, setDiff] = useState<Duration>(endTime.diff(startTime));
`diff`가 어떤 대상들에 대한 차이인지 `diff`라는 변수명으로 파악이 어려울 것 같아요! 변수명이 의미하는 바가 조금 더 명확하게 네이밍 해보면 좋을 것 같아요!

2023-03-31 06:08 UTC, pipisebastian commented
![image](https://user-images.githubusercontent.com/81643702/229036764-3e3fb2f4-6191-4bb3-8c7d-1ce09e5d939d.png)
혹시 이런식으로 뜨는 이유 알 수 있을까요?? 궁금합니당!

2023-03-31 06:16 UTC, pipisebastian commented on src/pages/senimarAttend/Countdown/Countdown.tsx
> +  const id: { current: NodeJS.Timeout | undefined } = useRef();
우왕  리뷰달려고했는데 이미 달아놓으셨군요! 짱입니댜~

2023-03-31 06:30 UTC, pipisebastian commented on src/pages/senimarAttend/Countdown/Countdown.tsx
> +    return () => clearInterval(id.current);
useEffect안에서 return 실제로 사용되는 예제는 첨봐요! 알아갑니당! (따봉~)

2023-03-31 06:39 UTC, pipisebastian commented
다른 부분인데, SeminarSelector 컴포넌트에 27 line  `label=""` 부분은 필요없을 것 같아욤! 나중에 시간되실때 봐주세요~!

2023-03-31 06:39 UTC, pipisebastian approved these changes

2023-04-01 07:13 UTC, lcqff commented
> ![image](https://user-images.githubusercontent.com/81643702/229036764-3e3fb2f4-6191-4bb3-8c7d-1ce09e5d939d.png) 혹시 이런식으로 뜨는 이유 알 수 있을까요?? 궁금합니당!

옆에 사이드바 말씀하시는 건가요 아님 버튼 말씀하시는 건가용???
사이드바는 제가 작업한게 아니라 몰겠구 (카드를 위쪽으로 옮겨야 하긴 하는데 그건 UI 건드는 브랜치에서...) 버튼은 임시로 만들어놔서 개발 완료되면 삭제하겠습니다!

2023-04-02 06:54 UTC, pipisebastian commented
> > ![image](https://user-images.githubusercontent.com/81643702/229036764-3e3fb2f4-6191-4bb3-8c7d-1ce09e5d939d.png) 혹시 이런식으로 뜨는 이유 알 수 있을까요?? 궁금합니당!
> 
> 옆에 사이드바 말씀하시는 건가요 아님 버튼 말씀하시는 건가용??? 사이드바는 제가 작업한게 아니라 몰겠구 (카드를 위쪽으로 옮겨야 하긴 하는데 그건 UI 건드는 브랜치에서...) 버튼은 임시로 만들어놔서 개발 완료되면 삭제하겠습니다!

아항! 넵넵! 수고하셨습니당~

2023-04-02 06:55 UTC, pipisebastian approved these changes

2023-05-02 09:16 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +  const lateLimit = attendLimit.plus({ days: 0, hours: 0, minutes: 0, seconds: 5 }); // 임시: 이후 api에서 가져옴
이거 필요없는 days,hours 인자 지워도 작동되는거 확인했습니다!
근데 어차피 이후에 api 가져오면 아예 안쓸 코드라 수정하진 않겠습니다~

2023-05-04 05:12 UTC, publdaze commented on src/pages/senimarAttend/Countdown/Countdown.tsx
> +  }, [nowTime]);
20번 라인 useEffect와 29번 라인 useEffect의 의존성 배열이 똑같은데 분리해서 사용한 이유가 있을까요??

2023-05-04 05:12 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            handleAttendButtonClick(DateTime.now());
여기서 핸들러 안에서 `DateTime.now()` 변수로 두고 사용한 방식이 아닌 파라미터로 받아서 한 경우 어떤 차이가 있는 지 궁금합니다!

2023-05-04 09:43 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            handleAttendButtonClick(DateTime.now());
이거 그때 설명했던 거 같은데 변수로 고치기로 했던가요?? 
크게 이유가 있다기 보단 제가 카운트다운 기능 작업하면서 사용자가 버튼을 누른 그때의 시간을 전달하지 않으니 오차가 생기는 경우가 있었어서 버릇처럼 해당 부분에도 인자로 버튼을 누른 그 시각을 전달하는 방식으로 작업했습니다 
여기는 딜레이는 크게 없어서 변수로 하나 인자로 넘기나 똑같은 거 같은데 변수로 하는 방식이 더 좋나요?

2023-05-05 06:52 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            handleAttendButtonClick(DateTime.now());
chatgpt 한테 물어봤는데 얼만큼 확실한 정보인지는 모르겠지만 아래 이미지와 같은 답변을 받았습니다!

저기서 첫번째 코드는 연후님이 작성한 코드, 두번째 코드는 파라미터로 넘겨주는 방식이 아닌 아래 코드 같이 핸들러 안에서 호출하는 방식입니다!

```tsx
const handleAttendButtonClick = () => {
  const nowTime = DateTime.now();

  setIsAttendable(nowTime < attendLimit);
  setIsCorrectCode(inputCode.join("") === validCode);
};
```

제가 이해한 만큼 요약해보자면 아래와 같습니다!


> **첫 번째 코드**는 함수의 의존성을 명시적으로 전달하며, 특정 시간값을 갖는 `DateTime` 객체를 인자로 전달할 수 있어 함수의 동작을 테스트하기 용이하다. 또한 함수 호출 시점에서의 시간을 정확하게 측정할 수 있다. 하지만 메모리 사용량 측면에서는 함수 호출 시마다 새로운 객체를 생성하여 인자로 전달하므로 약간의 추가 메모리 사용이 있을 수 있다.
> 
> **두 번째 코드**는 함수 내부에서 시간 값을 가져와 호출 시 인자를 전달해줄 필요가 없으므로 코드가 더 간결해지고 가독성이 좋아진다. 테스트 코드에서 시간 값을 계산하는 부분이 별도의 함수로 분리되기 때문에, 해당 함수를 모듈화하여 재사용성이 높아지며, 유지보수성이 높아진다.

두 번째 코드 방식을 더 추천하고 있는 것 같기는 한데 큰 차이가 없는 것 같아서 이부분은 연후님이 선호하는 방식으로 하면 될 것 같습니다!

아래 답변 캡쳐 이미지 첨부합니다.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/78250089/236386551-6526b990-f2d6-4d6e-906e-8857b421351e.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/78250089/236386566-e97aac09-4cb2-41bf-a09d-47ec2d053fde.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/78250089/236393681-f09c509a-34ac-477a-b1b5-f04b8fc835ff.png">

2023-05-05 06:54 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            handleAttendButtonClick(DateTime.now());
확인 후 re-request review 부탁드립니당! approve 해드릴게욤!

2023-05-07 16:17 UTC, publdaze reviewed
위에 [코멘트 답글](https://github.com/KEEPER31337/Homepage-Front-R2/pull/316#discussion_r1185752751) 남겨두었는데
답글로 달린 거라 알림 안 갔을 것 같아서 추가로 코멘트 남깁니다!

2023-05-08 04:19 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            handleAttendButtonClick(DateTime.now());
앗 확인해놓고 답글다는걸 까먹어버렸어요! 
은지님이 열심히 찾아와주시기도 했고 해당 함수를 분리해 사용할 일도 없을 거 같으니 그냥 함수 내 변수로 수정하겠습니다~ 수정한 후에 DM드릴게요!

2023-05-18 14:02 UTC, publdaze approved these changes
수고하셨습니다!!

2023-05-21 11:25 UTC, merged