Feature/세미나 출석 세미나 input 기능 구현 #309
KEEPER31337/Homepage-Front-R2 pull request #317
Opened 2023-03-26 14:12 UTC by lcqff

## 분류
- [x] 기능 추가

## 연관 이슈
#207 #172 #283 

## 작업 요약
회원들이 코드 입력하는 input 기능을 구현했습니다.

## 작업 상세 설명
회원이 하나의 input창에 하나의 코드를 입력하면 자동으로 다음 input으로 넘어가도록 했습니다. 
혹시 코드를 잘못 적어 한 군데의 코드만 수정할 일이 있을 때를 생각해서 각 input에 값이 적힐 때마다 code값에 저장되도록 했습니다.
회원은 출석 버튼을 누르면 자신의 code가 실제로 옳은지 확인할 수 있습니다. 

## 리뷰 요구사항
10분?

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/227781575-f075e0dd-1851-4b5e-9b2c-1aa74bcefb84.png)

2023-03-30 00:50 UTC, publdaze requested changes

2023-03-30 00:50 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
input 사용한 부분 각각에 대한 ref를 별도로 두고 개별적으로 focus를 주는 방법보다 이벤트로 받아온 `nextElementSibling`를 사용하면 더 간단하게 코드 작성할 수 있을 것 같아요! (한 20줄 정도는 줄일 수 있을지도..?)

추가된 기획에서 입력시 말고 지울 시에도 필드 이동하는 것도 추가돼서 해당 기능 추가까지 들어가면 `nextElementSibling`, `previousElementSibling`을 사용하는 게 코드도 많이 단축되고 복잡도도 훨씬 줄어들 것 같아요!

어떻게 사용되는 지 감이 안 잡히면 [이 블로그 글](https://soft91.tistory.com/100) 참고해봐주면 될 것 같아요!

2023-04-02 06:18 UTC, pipisebastian commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    if (event.keyCode === 8) {
코드 완전 신기방기합니다!!(따따봉~)
`event.keyCode === 8` 이부분에 'keyCode' is deprecated.ts(6385) 해당 문구가 떠서 알아봤는데,
해당 코드를 권장하지 않는다고 하더라구요! 여기 [블로그 ](https://way-be-developer.tistory.com/244)글 참고하면 좋을 것 같아욤!

2023-04-02 07:27 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    if (event.keyCode === 8) {
으악!

2023-04-04 15:51 UTC, publdaze requested changes

2023-04-04 15:51 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  };
이벤트 제어 `onKeyUp` 대신 `onChange`를 사용해보면 어떨까요?
onKeyUp의 경우는 키를 눌렀다가 땠을 때 발생하는 이벤트라서 입력 시 바로바로 반영되지 않고 조금씩 지체되는 느낌이 있더라구요!
또한 빠르게 입력할 때나 한 번에 지우기 위해 backspace를 계속 누르고 있을 때 원하는 대로 동작하지 않는 아쉬움이 있을 것 같아요!

`onChange`로 바꿔줄 경우
23번 라인에서 별도로 타입 명시해주는 부분 없어도 타입 인식 잘되고,
이벤트에서 key 값을 제공해주지 않아서 28라인을 수정해야 하긴하지만 큰 차이 없이 사용 가능할 것 같습니다!

2023-04-04 15:56 UTC, publdaze requested changes

2023-04-04 15:56 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +import React, { useRef, useState } from 'react';
`useRef` 사용되지 않는 것 같은데 확인 부탁드립니다!

그리고 혹시 연후님 vscode 상에서 아래 이미지 같이 밑줄로 warning 표시 안 뜨나요?
<img width="516" alt="image" src="https://user-images.githubusercontent.com/78250089/229848426-3990b826-0f9b-4fe9-8f43-3988008b99d8.png">
만약 안 뜬다면 vscode extension에 Eslint 설치 안 되어 있는 건 아닌지 확인 부탁드립니다!

2023-05-02 09:20 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  };
넹~

2023-05-23 08:17 UTC, publdaze requested changes

2023-05-23 08:17 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setInputCode?.(inputCode.join(''));
`MemberCardContent`파일의 14번째 라인와
```tsx
const [inputCode, setInputCode] = useState('');
```
`SeminarInput`파일의 20번째 라인 코드가
```tsx
const [inputCode, setSeminarInput] = useState([0, 0, 0, 0]);
```
데이터 타입은 다르지만 같은 값을 처리하는 것 같아요!

그리고 `MemberCardContent`파일의 `inputCode`는 버튼 클릭시에만 사용되는 값인 것 같네요!

여기서 드는 의문이 2가지 정도 있었습니다.
1. 같은 값에 데이터 타입만 다른 변수를 따로 지정해서 사용할 필요가 있는가?
2. 버튼 클릭시에만 사용되는 `inputCode` 값을 키입력 KeyUp이벤트 마다 데이터 타입을 맞춰주기 위해 `join()` 해줄 필요가 있을까?

이를 더 최적화할 수 있는 방법을 생각해봤는데
- `MemberCardContent`파일에 숫자 배열 형태의 `inputCode` state를 두고 `inputCode`와 `setInputCode`를 둘 다 props로 받아와 사용한다. 그리고 버튼 클릭 시에만 `inputCode`값을 `join`해 `validCode`와 비교해준다.

이런 방식 또는

- 인풋 관련 컴포넌트니까 보통의 인풋 props 처럼 이밴트 핸들러를 prop으로 받아오는 방식을 사용하여 `inputCode` 관련된 처리를 `SeminarInput`에서는 제외하고 `MemberCardContent`파일에서 해준다. 마찬가지로 버튼 클릭 시에만 `inputCode`값을 `join`해 `validCode`와 비교해준다.

이런 방식으로 처리해줄 수 있을 것 같아요! (이해되게 설명한 지 모르겠네요..ㅎㅎ 제 설명이 부족했다면 질문 주세욤!)
혹시 더 좋은 방식이 있다면 의견 부탁드립니다!!

2023-05-23 08:19 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  };
이부분은 추가 기획할 때 포함해서 기획 후 전달드리겠습니다! 이 PR에서는 일단 넘어갑시당!

2023-06-04 08:31 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setSeminarInput([...inputCode]);
혹시 `inputCode를 복사한 배열`의 선언을 어떻게 하면 좋을지 알려주실 수 있나요?🥺 공식문서에 써있는 대로 함수의 순수성을 보장해주기 위해선 moveNextInput 내부에 선언해줘야 한다 생각해, 처음에는 `const [inputCode, setSeminarInput] = useState([0, 0, 0, 0]);` 자체를 moveNextInput 안으로 옮기려 했으나 Hooks can only be called inside of the body of a function component 라는 워닝이 뜨네요ㅠ
그렇다고 let으로 선언하는 건 불가능하고, 저는 `inputCode를 복사한 배열`을 저장할 변수를 선언해줘야 한다고 생각했는데 혹시 은지님 말 뜻이 이게 아니었을까요?

2023-06-04 09:22 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setInputCode?.(inputCode.join(''));
그러게요???🤔 뭔가 이유가 있어서 저렇게 했던걸로 기억이 나는데 너무 오래돼서 왜 그랬는지 이유가 기억이 안나네요..... 둘 다 배열로 통일시켜줬습니다~

2023-06-07 06:01 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setSeminarInput([...inputCode]);
워닝 발생하는 건 Hook 규칙이 위반되어 발생한 워닝 같은데 궁금하면 [여기](https://ko.legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) 참고해보시면 될 것 같아요!

제가 의도했던 방법은 아래와 같은 방법인데,
```tsx
const copyInputCode = [...inputCode];
copyInputCode[key] = Number(target.value);
setInputCode(copyInputCode);
```
설명을 덧붙이자면 아래와 같습니다!
```tsx
// 기존 `inputCode`를 직접적으로 변경하지 않기 위한 `inputCode`를 복사한 배열 생성
const copyInputCode = [...inputCode];
// 복사한 배열의 원소 변경
copyInputCode[key] = Number(target.value);
// 기존 inputCode 변경을 위해 `setInputCode`에 복사+변경한 배열 넣어주기
setInputCode(copyInputCode);
```

+) 찾아보던 중 흥미로운 걸 발견했는데 공유드립니다!
https://ko.react.dev/learn/updating-arrays-in-state#making-other-changes-to-an-array
 복사한 객체더라도 `copyInputCode[key] = 값` 이런 식으로는 변경이 괜찮아도 예를 들어 `inputCode` 배열의 원소가 `seen`이라는 속성을 갖는 객체일 경우, `copyInputCode[key].seen = 값`이런 식으로 변경하는 건 얕은 복사라서 원본 배열을 직접적으로 바꾸는 것이므로 이렇게 변경하면 안 된다고 해요!

2023-06-07 06:09 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  const [inputCode, setSeminarInput] = useState([0, 0, 0, 0]);
여기 state하나 더 만들 필요 없이 `MemberCardContent.tsx`의 `inputCode` prop으로 들고와 사용하는 건 어떤가요?~?

2023-06-10 05:35 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setSeminarInput([...inputCode]);
그러면 코드가 
```typescript
 const copyInputCode = [...inputCode];
 copyInputCode[key] = Number(target.value);
 setSeminarInput(copyInputCode);
 setInputCode?.(copyInputCode);
``` 
이렇게 되는데 setSeminarInput를 사용할 경우에도 순수성이 보장되지 않는거 아닌가요? 함수 외부에 있는 inputCode를 변경하니까....😯

그러면 아예 SeminarInput의 파라미터로 inputCode를 넘기고 seminarInput 내부의 inputCode는 없애는게 나을까요?

2023-06-10 05:37 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +  const [inputCode, setSeminarInput] = useState([0, 0, 0, 0]);
앗 위에 댓글 달아둔게 여기에 있네요~~ 그럼 고렇게 하겠습니다~

2023-06-11 00:14 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +    setSeminarInput([...inputCode]);
> 그러면 코드가 
> ```typescript
>  const copyInputCode = [...inputCode];
>  copyInputCode[key] = Number(target.value);
>  setSeminarInput(copyInputCode);
>  setInputCode?.(copyInputCode);
> ``` 
> 이렇게 되는데 setSeminarInput를 사용할 경우에도 순수성이 보장되지 않는거 아닌가요? 함수 외부에 있는 inputCode를 변경하니까....😯
> 
> 그러면 아예 SeminarInput의 파라미터로 inputCode를 넘기고 seminarInput 내부의 inputCode는 없애는게 나을까요? 

제가 연후님 질문을 정확히 이해했는지는 모르겠지만...! `setSeminarInput`이라는 함수를 사용해서 변경하는 것도 결국에 `inputCode`를 변경하는 것이니 순수성이 보장 안 되는 거 아닌가? 라는 질문이 맞다면

set함수의 경우는 현재 렌더링이 돌아가는 동안은 값이 바뀌지 않고 끝난 후 다음 렌더링에서 `새로운 값`으로 리렌더링하므로 순수성을 보장할 수 있는 걸로 알고 있습니다! 그래서 `inputCode`가 `SeminarInput` 안에 있거나 밖에 있거나 상관없이 이부분에 대해서는 순수성을 보장할 수 있다고 볼 수 있을 것 같습니다!

2023-06-11 00:21 UTC, publdaze approved these changes
수고 많으셨습니다! 👍 PR머지되면 나머지 세미나 PR들에 충돌 나는 곳은 없는 지 한 번 풀받아서 확인해보면 좋을 것 같아요!

2023-06-11 00:21 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +    console.log(inputCode);
콘솔 테스트 용으로 찍어본 것 같은데 지워도 될 것 같습니다!

2023-06-11 13:44 UTC, pipisebastian commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
>      setIsCorrectCode(inputCode.join('') === validCode);
옹 깔끔합니다!! 굿이에욤!!

2023-06-11 13:45 UTC, pipisebastian commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const [inputCode, setInputCode] = useState([0, 0, 0, 0]);
그냥 궁금한건데 이런거는 type따로 안넣어줘도 되는건가욤?? 궁금해요!

2023-06-11 13:57 UTC, pipisebastian approved these changes

2023-06-24 07:59 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const [inputCode, setInputCode] = useState([0, 0, 0, 0]);
typescript가 보통 파라미터의 타입 오류를 잡아내는데 주로 사용되고 단순 변수 선언에서는 타입 지정을 필수로 보지 않는거 같더라고요! inputCode 외에도 다른 변수들도 다 타입 지정 안돼있습니다... 👉👈
근데 지정해주면 좋기야 할 거 같습니다! 
아님 혹쉬 질문 의도가 이것이 아니었는지,,,,,,, 👉👈

2023-06-24 09:39 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const [inputCode, setInputCode] = useState([0, 0, 0, 0]);
typescript에서 타입 추론도 해주기 때문에 타입 추론되는 부분은 따로 명시적으로 표현해주고 싶다하는 게 아니면 따로 타입 지정 안 해주는 게 좋다..?까지는 모르겠고 안 해줘도 괜찮은 걸로 알고 있습니다!

(연후님꺼 슬쩍 가져다 쓰겠습니당! ㅎㅎ) 질문 의도가 이것이 아니었는지,,,,,,, 👉👈 2222 😆

2023-06-25 11:27 UTC, merged