design : label없을시 margin 제거
KEEPER31337/Homepage-Front-R2 pull request #326
Opened 2023-03-29 05:56 UTC by pipisebastian

## 연관 이슈
- #325 

## 작업 요약
- selector가 label때문에 margin 16px이 존재하는데, label이 없더라도 margin이 유지되어, 이를 제거
- 
## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/228439531-a1347bad-8f45-41d3-8a36-1690cefd39c5.png)

2023-03-30 04:35 UTC, mia2583 approved these changes
수고하셨습니다~~

2023-03-31 05:20 UTC, jasper200207 approved these changes

2023-04-01 07:18 UTC, publdaze requested changes
<img width="483" alt="image" src="https://user-images.githubusercontent.com/78250089/229271646-76a3f8e7-d44c-4c09-abb6-6b084b8fdf1e.png">

혹시 예제 코드를 확인해볼 수 있을까요?
제 확인한 바로는 라벨 마진이 라벨이 없을 경우 잡히지 않아서 별도로 제거하지 않아도 될 것 같아서요!

위의 이미지에서 차례로
라벨 없는 Input, 라벨 없는 Selector, 라벨 있는 Input, 라벨 있는 Selector 입니다!

2023-04-24 09:42 UTC, pipisebastian commented
> css 적용된 부분을 확인해보니 `Select` 자체에 마진이 들어가있다기 보다는 `InputLabel` 컴포넌트가 들어가는데 label이 없을 경우 `InputLabel`의 공간 자체는 남아서 마진으로 잡히는 것 같아요!
> 
> 그래서 `InputLabel`이 없을 경우에 해당 공간이 안 잡히기 때문에 `Select`에 마진을 처리해주는 것보다는 `InputLabel`를 label 여부에 따라서 렌더링 해주도록 처리해주는 게 라벨 공간에 대한 처리라는게 더 직관적으로 받아들일 수 있을 것 같습니다!

헐루 그생각은 왜 못했을까!! 짱이에욤!!!!!!

2023-04-24 23:42 UTC, publdaze approved these changes
굿굿! 수고하셨습니다! 👍

2023-04-25 04:40 UTC, merged