Feature/세미나 출석 회원 출석상태 표시 #310
KEEPER31337/Homepage-Front-R2 pull request #330
Opened 2023-04-01 10:40 UTC by lcqff

## 분류
- [x] 기능 추가

## 연관 이슈
#283 #207 #172 

## 작업 요약
회원이 출석하면 회원의 출석 상태를 나타냅니다.

## 작업 상세 설명
원래는 코드가 옳으면 상태를 보여줘야 하는데 아직 input 컴포넌트 기능 브런치가 머지가 안된터라 input 값을 가져올수 없습니다~~~ 그래서 일단 코드가 틀려도 출석상태 뜨도록 했습니다. #309 머지되면 이부분 수정하겠습니다.

출석상태는 총 3개로 출석, 지각, 결석으로 나뉘고 상태에 따라 텍스트 앞에 뜨는 기호와 텍스트 색깔이 바뀝니다. 
편의상 회원출석 페이지 지나가서 2초가 지나면 지각, 거기서 또 10초가 지나면 결석으로 해놨습니다. (시간은 api 적용되면 자동으로 계산되니 이부분은 신경 안쓰셔도 될 거 같습니다.)

또 UI는 나중에 다 뜯어 고쳐야 하니까 SeminarAttendStatus ui관련된 부분 빼고는 기능측면만 봐주셔도 될 거 같습니다! (출석 버튼이랑 너무 붙어있다 이런거...)

## 리뷰 요구사항
5분?

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/229282035-e3f5f41b-45f7-47be-be1e-96650d830877.png)

2023-04-01 10:44 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
텍스트 색 바뀌는 것도 출석상태마다 다르고, 앞에 붙는 아이콘도 (출석,지각)/결석 별로 달라서 이런식으로 만들었는데 더 좋은 방법 있으면 알려주세요~!

2023-04-01 10:44 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    출석전: <div>ㅤ</div>,
여기 안에 공백 문자를 주었는데 마진 계산해서 css로 넣는 것보다 이게 편리하고 정확할 거 같아서 이렇게 했습니다
혹시 이러면 안된다 거나.. 이것보다 그냥 마진 계산해서 넣자 하시는 분 계시면 의견주세요!

2023-04-06 18:56 UTC, jasper200207 approved these changes

2023-05-07 12:18 UTC, publdaze requested changes
두둥 옛날에 리뷰 달아놓고 pending 상태였었네요...! 카운트다운 PR에 달아둔 리뷰와 중복되는 부분이 대부분이어서 다 지우고 하나 먼저 comment 남깁니당!

2023-05-08 04:16 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +const SeminarAttendStatus = ({ status, className }: AttendStatuesProps) => {
앗~ 저게 이름이 다른줄 몰랐네요😯😯😯 변경하겠습니다!

2023-05-25 09:35 UTC, publdaze requested changes

2023-05-25 09:35 UTC, publdaze commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
```tsx
import React from 'react';
import { VscCheck, VscChromeClose } from 'react-icons/vsc';

export type Status = '출석전' | '출석' | '지각' | '결석';
type ActiveStatus = Exclude<Status, '출석전'>;

interface SeminarAttendStatusProps {
  status: ActiveStatus;
}

const SeminarAttendStatus = ({ status }: SeminarAttendStatusProps) => {
  const statusInfo: {
    [K in ActiveStatus]: { color: string; icon: JSX.Element };
  } = {
    출석: {
      color: 'pointBlue',
      icon: <VscCheck />,
    },
    지각: {
      color: '[#FFA500]',
      icon: <VscCheck />,
    },
    결석: {
      color: 'subRed',
      icon: <VscChromeClose />,
    },
  };

  const { color, icon } = statusInfo[status];

  return (
    <div className={`flex items-center justify-center text-${color}`}>
      {icon}
      <p className="ml-1">{status}</p>
    </div>
  );
};

export default SeminarAttendStatus;
```

말로 설명할 자신이 없어서 제 나름대로 리팩토링 해본 코드 바로 첨부합니다!

- JSX 구조가 동일 -> 각 상태별로 달라지는 color, icon 정보만 분리하여 가져오고 JSX는 고정
- 하나의 `div`에 적용하면 되는 `className`을 별도로 `prop`으로 가져올 필요없이 바로 지정
- 전체 `Status` 타입중 `SeminarAttendStatus`에서 사용되는 `ActiveStatus` 타입 지정

이런 느낌으로 리팩토링 해주었고 이 리팩토링 수용하신다면 추가로
- `Status`는 `SeminarAttendStatus`외에도 seminarAttend 관련 파일에서 사용 가능하니 `seminarAttend` 타입 관리하는 파일에서 가져와 사용하면 좋을 것 같습니다!
- 지각 color의 경우는 warning 컬러로도 활용할 수 있을 것 같고, 해당 색만 색 고정해서 사용하기 보다는 테마가 변경될 수 있다는 확장성도 생각하여 이 색도 커스텀 컬러로 사용하면 좋을 것 같아서 `tailwind.config.js` 파일에 `subOrange`? 정도로 커스텀 컬러 추가해서 사용하면 어떨까합니다!

2023-05-28 13:55 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
오우~~~~ 끝내줍니다~~~~~~~~

2023-05-28 13:57 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    출석전: <div>ㅤ</div>,
아뇨 아마 그렇진 않았던 걸로 기억합니다~~~ 그냥 다른 출석 상태들이랑 똑같이 html 값으로 리턴해주려고 그랬던거 같아요!

2023-05-28 13:59 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +}
오우 텍스트로 union type을 설정할수가 있군요? 배워갑니다~

2023-05-28 14:05 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    <div className={`${className} text-red-500`}>
오우~~

2023-06-04 10:20 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
반영했습니다! 근데 Status가 SeminarAttendStatus외에도 seminarAttend 관련 파일에서 사용 가능하다는게 무슨 소리인지 모르겠습니다🤔 지금은 아니더라도 차후에 사용할수 있다는 뜻인가요? 
seminarAttend 타입 관리하는 파일도 무슨 소린지 잘 모르겠습니다 죄송합니다ㅠㅠ

2023-06-04 10:21 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
tailwind 색상추가는 따로 pr 파겠습니다!

2023-06-07 06:49 UTC, publdaze requested changes

2023-06-07 06:49 UTC, publdaze commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
> 반영했습니다! 근데 Status가 SeminarAttendStatus외에도 seminarAttend 관련 파일에서 사용 가능하다는게 무슨 소리인지 모르겠습니다🤔 지금은 아니더라도 차후에 사용할수 있다는 뜻인가요? seminarAttend 타입 관리하는 파일도 무슨 소린지 잘 모르겠습니다 죄송합니다ㅠㅠ

변경된 코드에서 보면 `SeminarAttendStatus.tsx` 파일의 4번째 라인의 타입 `'지각' | '출석' | '결석'` 과`MemberCardContent.tsx`파일의 18번째 라인에서 사용한 useState의 타입 `undefined | '지각' | '출석' | '결석'`에서 `'지각' | '출석' | '결석'`부분이 출석 상태를 나타내는 타입으로 겹칩니다! 이처럼 세미나출석 페이지에 출석 상태에 대한 타입이 여러군데이서 사용될 수 있다는 의미였고, 이렇게 세미나 출석 페이지 관련 여러 파일에서 공통적으로 사용되는 타입의 경우 `SeminarAttend.interface.ts` 파일을 따로 만들어 타입 관리할 수 있도록 파일안에 타입을 넣어두고 각 사용되는 파일에 불러쓰면 어떤가하는 얘기였습니다!

2023-06-10 06:35 UTC, lcqff commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
혹시 파일 이름을 SeminarAttend.interface.ts로 하신 이유가 있나요??

```
type ActivityStatus = '지각' | '출석' | '결석';

export default ActivityStatus;
```

export할 type 파일을 위와 같이 만들어서 파일 이름을 **ActivityStatus.type.ts**로 했는데

```
type ActivityStatus = '지각' | '출석' | '결석';

interface SeminarAttendStatusProps {
  status: ActivityStatus;
}

export default SeminarAttendStatusProps;

```
처럼 파일을 만들 걸 염두하신건가요??😯

2023-06-10 06:37 UTC, lcqff commented
https://github.com/KEEPER31337/Homepage-Front-R2/pull/330#discussion_r1225151361

2023-06-18 03:15 UTC, publdaze requested changes

2023-06-18 03:15 UTC, publdaze commented on src/pages/senimarAttend/Status/ActivityStatus.type.ts
저희 개발회의 때 한 page를 기준으로, 여러 개의 컴포넌트에서 사용되는 경우 `pages/{페이지이름}/{페이지이름}.interface.ts`로 파일 이름 네이밍하기로 정했어서 경로랑 파일명 맞춰주면 좋을 것 같습니다!

2023-06-18 03:15 UTC, publdaze commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +      color: '[#FFA500]',
- #384 이 PR 머지 가능 상태네요! 머지하고 pull 받아서 바로 적용해버립시다!

2023-06-18 03:15 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const handleAttendButtonClick = (nowTime: DateTime) => {
이부분
- #316 

PR에서 `nowTime` 함수 내 변수로 사용하는 걸로 변경했던 것 같은데 충돌 안 나고 변경사항으로 잡힌 것 같네요!
충돌 안 났을 때 따로 원래 형태로 처리할 수 있는 방법이 있는 지 모르겠는데 안 되면 다시 처리해줘야할 것 같네욤.. 😓

2023-06-24 07:38 UTC, lcqff commented on src/pages/senimarAttend/Status/ActivityStatus.type.ts
아하 그래서였군요~ 확인했습니다!

2023-06-24 07:39 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const handleAttendButtonClick = (nowTime: DateTime) => {
앗 이런~

2023-06-24 08:01 UTC, publdaze commented on src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
> +    </div>
앗 이 코멘트는 확인 못했었네요 ㅎㅎ
https://github.com/KEEPER31337/Homepage-Front-R2/pull/330#discussion_r1240627464
굿굿~!

2023-06-24 09:34 UTC, publdaze requested changes
앗앗 변경해주신 타입 파일
`pages/seminarAttend/SeminarAttend.interface.ts`
으로 경로랑 파일명 추가 변경 제안해도 될까요?

Status 폴더 내부의 여러 컴포넌트 파일에 쓰이는 거면 지금 경로에 위치하는 것도 괜찮을 것 같은데
`MemberCardContent` 컴포넌트에도 사용되니 페이지 하위에 사용되는 타입으로 `{페이지이름}.interface.ts`으로 하면 좋을 것 같아서요!

2023-06-24 09:48 UTC, lcqff commented
아익쿠... 제가 리뷰 확인을 제대로 못했었네욥.... 반영해뒀습니다!

2023-06-24 10:06 UTC, publdaze approved these changes
👍👍👍👍👍

2023-06-25 12:08 UTC, merged