#146 Feature/로그인페이지UI
KEEPER31337/Homepage-Front-R2 pull request #333
Opened 2023-04-02 10:40 UTC by Ji-Hyeon212

## 분류
- [x ] 기능 추가
- [ ] 버그 수정
- [ ] 리팩토링

## 연관 이슈

## 작업 요약
로그인 페이지 UI제작

## 작업 상세 설명
> 디자인 구성한거라 별다른 기능은 없습니다! 유효성 검사 등의 다른 기능은 추가할 예정이니 UI만 확인해주세요

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분
0.1분
## Preview 이미지

2023-04-04 16:29 UTC, publdaze requested changes

2023-04-04 16:29 UTC, publdaze commented on src/pages/login/Login.tsx
> +import { Button, TextField } from '@mui/material';
`@mui/material`에서 import되는 컴포넌트들이 많은 것 같은데 2,3,4,6,8,9,10 라인 한 라인에 정리할 수 있을 것 같아요!

2023-04-04 16:29 UTC, publdaze commented on src/pages/login/Login.tsx
> +    });
콘솔 찍어본 건 원격에는 올리지 않는게 좋을 것 같아요!

해당 커밋으로 돌아와 디버깅할 때 불편을 초래할 수도 있고,
클라이언트에 전달되어야 하는 정보가 아니라 불필요할 것 같아요!

특히 이부분에서는 계정정보가 그대로 콘솔에 노출될 수 있다는 점에서 보안상으로도 위험 할 수 있을 것 같아서
더욱 원격에서는 제거해줘야 할 것 같습니다!

2023-04-04 16:29 UTC, publdaze commented on src/pages/login/Login.tsx
> +  };
여러 입력 필드 하나의 핸들러로 처리하는 방식 굿굿입니다! 👍

2023-04-04 16:29 UTC, publdaze commented on src/pages/login/Login.tsx
> +  };
이 함수는 `onBlur`의 이벤트 핸들러 함수로 사용되는 것 같은데 핸들러 네이밍 방식으로 해주면 어떨까합니다!

2023-04-04 16:29 UTC, publdaze commented on src/pages/login/Login.tsx
> +  const [validId, setValidId] = useState<boolean>(false);
<img width="200" alt="image" src="https://user-images.githubusercontent.com/78250089/229856361-5826da2a-6990-40cb-9aac-944ec232b00b.png">
저희 이전 개발회의 때 코드 작성 순서 관련해서 정해봤었는데 이부분에서는 state가 핸들러들 중간에 위치하고 있는 것 같아요!
이렇게 위치되어 있으면 코드 위치 한눈에 파악하기 어려울 것 같아서 핸들러 상단으로 올려주면 좋을 것 같습니다!

2023-04-28 06:54 UTC, pipisebastian commented
풀리퀘 이름 `#146 Feature/로그인페이지UI`  ->  `Feature/로그인페이지UI #146` 으로 바꿔야할 것 같아욤!

2023-05-07 09:52 UTC, publdaze requested changes

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +            />
`TextField` 대신 저희 공통 컴포넌트로 제작된 Input중 디자인된 거 확인해보니 `BackgroundInput` 컴포넌트 사용하면 될 것 같습니다!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +    <ThemeProvider>
`ThemeProvider`를 통해 적용되고 있는 스타일도 없고, 저희 프로젝트에서 이제 material-tailwind는 사용하지 않기 때문에 해당 태그는 빼줘도 될 것 같습니다!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +      <CssBaseline />
`CssBaseline`은 어떤 의도로 사용한 건지 설명해줄 수 있나요?

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +      <Container component="main" maxWidth="xs">
콘텐츠를 가로로 중앙에 배치하기 위해서 `Container` 컴포넌트를 사용할 수 있군요! 배워갑니다! 👍
Sign Up 페이지에도 적용해봐야겠네요! 굿굿~

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +      <Container component="main" maxWidth="xs">
여기서 `component="main"`으로 지정해준 이유는 뭔지 궁금합니다!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +          <Stack component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }} width="100%">
[Stack 컴포넌트 API](https://mui.com/material-ui/api/stack/)에 `noValidate`라는 prop는 없던데 `noValidate`가 어떻게 쓰이고 있는 건지 궁금합니다!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +          <Stack component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }} width="100%">
`Logo`에 magin bottom을 16px(`mb-4`) 넣어주고
`Stack`에 magin top을 8px(`mt: 1`)넣어주었는데
둘 다 같은 여백 부분인 것 같은데 예를 들어 Logo에만 24px(`mb-6`)을 넣어준 게 아니라 따로 마진을 분리해둔 이유가 있을까요?

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +              helperText={isValidId ? '아이디를 입력해주세요' : ''}
`isValidId`일때만 '아이디를 입력해주세요'라고 띄워주기 위해
`&&` 사용하여 빈스트링을 따로 넣어줄 필요없이 간략하게 표현하는 것도 가능해보이네요!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
이부분도 이벤트 핸들러 함수이니 네이밍할 때 prefix로 `handle` 사용해주도록 변경 부탁드립니다!

2023-05-07 09:52 UTC, publdaze commented on src/pages/login/Login.tsx
> +            <FormControlLabel control={<Checkbox value="remember" color="primary" />} label="로그인 상태 유지" />
`Checkbox` 컴포넌트에 `value`속성을 따로 지정해준 이유가 궁금합니다!

2023-05-08 15:10 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +      <CssBaseline />
MUI에서 제공하는 건데 브라우저마다 똑같은 UI를 적용시키려면 CSSBaseline를 써야 한다고 하길래 넣었었습니다! 그런데 보니까 앱의 최상위 컴포넌트에 추가해줘야 하네요...! 지우는 게 좋을 것 같습니다.

2023-05-08 15:15 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +      <Container component="main" maxWidth="xs">
component 속성을 사용하면 실제 렌더링되는 HTML 요소의 이름을 지정해줄 수가 있다고 알고있는데 기본값인 div보다 main으로 해두는 게 시맨틱 한 것 같아 넣었습니다. 굳이 필요한 부분은 아닙니다!

2023-05-08 15:16 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +          <Stack component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }} width="100%">
제가 착각한 것 같아요..! 지우겠습니다.

2023-05-08 15:17 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +              helperText={isValidId ? '아이디를 입력해주세요' : ''}
오옹 그렇네요 의견 감사합니다!

2023-05-08 15:20 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +            <FormControlLabel control={<Checkbox value="remember" color="primary" />} label="로그인 상태 유지" />
나중에 state 추가해서 체크 유무 관리하려고 넣었습니다!

2023-05-10 00:40 UTC, publdaze commented on src/pages/login/Login.tsx
> +      <Container component="main" maxWidth="xs">
오홍! `main` 태그 찾아보니까 `body`의 주요 구성 요소로 문서에는 **1개**의 `main` 태그만 사용한다고 되어 있어라구요! ([참고](https://developer.mozilla.org/ko/docs/Web/HTML/Element/main))
그래서 로그인 페이지의 주요 요소로 표현하고 싶었던 거면 main의 용도와는 맞지 않는 것 같습니다!

2023-05-10 04:59 UTC, publdaze commented on src/pages/login/Login.tsx
> +            <FormControlLabel control={<Checkbox value="remember" color="primary" />} label="로그인 상태 유지" />
음 `Checkbox`에 `checked`라는 체크 유무를 관리하는 prop이 있더라구요! value와 어떤 차이점이 있는 지는 잘 모르겠지만 `checked`라는 명확한 속성을 제공해주니 이걸 사용하면 어떨까합니다!

2023-05-10 05:03 UTC, publdaze commented
nit :
피드백 변경한 커밋을 서로 연관있는 작업이 아니라면 커밋 분리해주면 좋을 것 같습니다!
나중에 커밋 이력을 볼 일이 있을 때 피드백을 반영했다는 게 중요하기 보다는 해당 커밋이 왜 무엇을 변경하였는 지가 구분이 되어 있어야 각각의 커밋에 대해 파악하기 쉬울 것 같아요!

2023-05-10 05:03 UTC, publdaze reviewed
nit :
피드백 변경한 커밋을 서로 연관있는 작업이 아니라면 커밋 분리해주면 좋을 것 같습니다!
나중에 커밋 이력을 볼 일이 있을 때 피드백을 반영했다는 게 중요하기 보다는 해당 커밋이 왜 무엇을 변경하였는 지가 구분이 되어 있어야 각각의 커밋에 대해 파악하기 쉬울 것 같아요!

2023-05-26 05:43 UTC, publdaze requested changes

2023-05-26 05:43 UTC, publdaze commented on src/pages/login/Login.tsx
> +              sx={{ mb: 2 }}
여기 마진이 적용 안 되고 있는 것 같아서
아이디 인풋은 `className="!mb-4"`
비밀번호 인풋은 `className="!mb-8"`
변경해주면 될 것 같아요!
(디자인 더 정확하게 반영하는 건 기능 개발 후에 해봅시다!)

`BackgroundInput` sx는 받아와도 적용이 안 되도록 처리되어 있고, 이미 mui에 적용된 스타일이 있어서 tailwindcss 사용하려면 important 사용해줘야 하더라구요! 이 방식이 좋은 방식은 아니라고 생각되긴 한데 일단 저희가 `tailwindcss`랑 `mui`를 같이 가져가기로 결정해서 더 좋은 방안을 찾기 전까지 이렇게 해줘야할 것 같아요!

2023-05-26 05:43 UTC, publdaze commented on src/pages/login/Login.tsx
> +  };
핸들러 네미밍에 어떤 이벤트에 대한 핸들러인지 추가해주면 좋을 것 같습니다! 이 경우는 `Blur`인 것 같네요!

2023-05-26 17:42 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +              sx={{ mb: 2 }}
마진이 안 들어간 걸 확인을 못했네요! 로그인 버튼 상단에 마진 주는 걸로 변경했습니다!

2023-05-26 17:42 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +  };
로그인 시에는 유효성 검사가 따로 필요 없는 것 같아 해당 이벤트 핸들러 함수는 제거했습니다!

2023-05-27 02:11 UTC, publdaze approved these changes
수고하셨습니다!

2023-05-27 02:34 UTC, merged