Feature/공통 tab 구현 #341
KEEPER31337/Homepage-Front-R2 pull request #342
Opened 2023-04-25 10:25 UTC by pipisebastian

## 연관 이슈
- close #342

## 작업 요약
- 공통 탭 구현

## 리뷰 요구사항
- 5분
- 페이지 이동부분은 추에 구현할 계획입니다!

## Preview 이미지
![image](https://user-images.githubusercontent.com/81643702/234248997-b88869b3-73b7-41ac-8107-541eaf8fda9d.png)

### Preview 예제코드
```tsx
import React from 'react';
import StandardTab from '@components/tab/StandardTab';

const Example= () => {
  const tabList = [
    { id: 0, label: '도서 관리' },
    { id: 1, label: '반납 관리' },
    { id: 2, label: '흠냐 관리' },
    { id: 3, label: '헤헿 관리' },
  ];
  return (
    <div>
      <StandardTab options={tabList} />
    </div>
  );
};

export default Example;
```

2023-04-28 05:16 UTC, publdaze requested changes
컴포넌트 폴더명 첫글자 대문자로 변경 부탁드립니다!
(폴더 하위에 직접적인 컴포넌트 파일이 들어갈 경우에는 폴더 첫글자도 대문자로 사용하기로 정했었어요~!)

2023-04-28 05:19 UTC, publdaze commented on src/components/tab/StandardTab.tsx
> +  };
여기서 newTab이 인자로 받아와지고 있는데 `Tabs` 컴포넌트에서 제공해주는 건가요?
17번 라인의 호출부에서는 인자를 넘겨주고 있기 않은데 핸들러 함수 안에서 사용되고 있어서 어떤 원리인지 궁금합니다!

2023-05-07 05:06 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +    <Box className="w-fit">
mui 예제코드에서 그렇게 쓰더라구욤! 없어도 될 것 같네욤!! 굿입니다용!

2023-05-07 05:31 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +  };
이것도 mui예제 그대로 가져와서 잘 모르겠네요! 궁금해서 해봤는데, 보통 쓰는 event.target.value로 하면 못 읽더라구요!
[공식문서](https://mui.com/material-ui/api/tabs/)에서도 onChange함수안에 event랑 value 둘다 인자로 있는게 기본인 것 같습니다!
![image](https://user-images.githubusercontent.com/81643702/236659543-54dac15b-e582-4760-a526-537159b762d9.png)

2023-05-07 05:36 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +      <Tabs value={tab} onChange={handleChange}>
은지님 말대로 Tabs의 value 속성은 몇 번째 Tab이 선택되었는지를 나타내는데, **value 값이 0**이면 **1번째 tab**이 선택되었다고 본다고 합니당!

2023-05-07 16:23 UTC, publdaze commented on src/components/tab/StandardTab.tsx
> +      <Tabs value={tab} onChange={handleChange}>
**1번째 tab**(**value 값 0**)이라고 인식하는 기준이 `Tabs` 컴포넌트의 자식 요소 중 첫번째 위치하는 요소로 판단하는 걸까요?

2023-05-07 16:27 UTC, publdaze reviewed
예제 코드에
`{tab === 0 && <div>도서</div>}`
이렇게 `tab`에 조건을 줘서 각 컴포넌트를 표현하도록 작성해주셨는데
MUI에 `Tab`과 같이쓰는 `TabPanel`이라는 컴포넌트가 있는데 각 탭에 해당하는 패널들을 나타내는 거라 별도의 조건문을 쓰지 않고 사용할 수 있더라구요! 이걸로 한 번 예제 작성해보면 어떨까요?

2023-05-08 02:47 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +      <Tabs value={tab} onChange={handleChange}>
넹!

2023-05-09 11:18 UTC, pipisebastian commented
> 예제 코드에 `{tab === 0 && <div>도서</div>}` 이렇게 `tab`에 조건을 줘서 각 컴포넌트를 표현하도록 작성해주셨는데 MUI에 `Tab`과 같이쓰는 `TabPanel`이라는 컴포넌트가 있는데 각 탭에 해당하는 패널들을 나타내는 거라 별도의 조건문을 쓰지 않고 사용할 수 있더라구요! 이걸로 한 번 예제 작성해보면 어떨까요?

`
import React, { useState } from 'react';
import StandardTab from '@components/Tab/StandardTab';
import SignUp from '@pages/SignUp/SignUp';
import LibraryManage from '@pages/admin/LibraryManage/LibraryManage';
import Study from '@pages/Study/Study';

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

const TabPanel = (props: TabPanelProps) => {
  const { children, value, index } = props;

  return <div>{value === index && <div>{children}</div>}</div>;
};

const Example = () => {
  const tabList = [
    { id: 0, label: '도서 관리' },
    { id: 1, label: '반납 관리' },
    { id: 2, label: '흠냐 관리' },
  ];
  const [tab, setTab] = useState(0);

  return (
    <div>
      <StandardTab options={tabList} tab={tab} setTab={setTab} />

      <TabPanel value={tab} index={0}>
        <SignUp />
      </TabPanel>
      <TabPanel value={tab} index={1}>
        <LibraryManage />
      </TabPanel>
      <TabPanel value={tab} index={2}>
        <Study />
      </TabPanel>
    </div>
  );
};

export default Example;

`

2023-05-09 11:26 UTC, pipisebastian commented
> 
다음과 같이 객체안에 ReactNode를 넣어주고, map문으로 돌려줬는데, 
이거는 각 tab마다 어떤 컴포넌트인지 파악하기가 어렵더라구요,, 혹시 더 좋은 방법 있을까요? 조언 부탁드립니당!!

```tsx
import React, { useState } from 'react';
import StandardTab from '@components/Tab/StandardTab';
import SignUp from '@pages/SignUp/SignUp';
import LibraryManage from '@pages/admin/LibraryManage/LibraryManage';
import Study from '@pages/Study/Study';

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

const TabPanel = (props: TabPanelProps) => {
  const { children, value, index } = props;

  return <div>{value === index && <div>{children}</div>}</div>;
};

const Example = () => {
  const tabList = [
    { id: 0, label: '도서 관리', content: <SignUp /> },
    { id: 1, label: '반납 관리', content: <LibraryManage /> },
    { id: 2, label: '흠냐 관리', content: <Study /> },
  ];
  const [tab, setTab] = useState(0);

  return (
    <div>
      <StandardTab options={tabList} tab={tab} setTab={setTab} />
      {tabList.map((option) => (
        <TabPanel value={tab} index={option.id}>
          {option.content}
        </TabPanel>
      ))}
    </div>
  );
};

export default Example;

```

2023-05-20 08:49 UTC, publdaze commented
예제 코드에도 경로 Tab 앞글자 대문자로 바꿔줘야할 것 같습니다!

`import StandardTab from '@components/tab/StandardTab';`
->
`import StandardTab from '@components/Tab/StandardTab';`

2023-05-28 06:06 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +  options: { id: number; label: string }[];
움움 저도 다른분들 코드참고한거라, 확신은 못하는데 options이  { id: number; label: string } type의 객체를 배열[]로 저장하는 type이다! 입니당!!

2023-05-28 06:07 UTC, pipisebastian commented on src/components/tab/StandardTab.tsx
> +  options: { id: number; label: string }[];
그래서 예제코드 보면 option에 다음과같이 들어가요!
```js
const tabList = [
    { id: 0, label: '도서 관리' },
    { id: 1, label: '반납 관리' },
    { id: 2, label: '흠냐 관리' },
  ];
````

2023-05-28 07:45 UTC, publdaze commented
>> 예제 코드에
>> `{tab === 0 && <div>도서</div>}`
>> 이렇게 `tab`에 조건을 줘서 각 컴포넌트를 표현하도록 작성해주셨는데
MUI에 `Tab`과 같이쓰는 `TabPanel`이라는 컴포넌트가 있는데 각 탭에 해당하는 패널들을 나타내는 거라 별도의 조건문을 쓰지 않고 사용할 수 있더라구요! 이걸로 한 번 예제 작성해보면 어떨까요?

> 그 tabpanel을 직접 만드는 것 같더라구요! 그래서 만들어봤는데 어떨까요?? tabPanel컴포넌트로 감싸줘서 깔끔해보이긴 한데, 필요없는 div가 2개 있고, `<TabPanel value={tab} index={0}>` 이 부분이 반복되는게 거슬리더라구요 그래서
>  ...
> 다음과 같이 객체안에 ReactNode를 넣어주고, map문으로 돌려줬는데,
이거는 각 tab마다 어떤 컴포넌트인지 파악하기가 어렵더라구요,, 혹시 더 좋은 방법 있을까요? 조언 부탁드립니당!!

`TabPanel` 직접 구현해주는 방법 말고 컴포넌트 있는걸 들고 오는 걸 생각했는데 이건 저희가 설치한 `@mui/material`가 아닌 `@mui/lab` 버전으로 따로 설치해야 사용할 수 있었네요!
원래 의도는 `TabPanel` 컴포넌트가 Tab 컴포넌트와 유기적인 사용이 가능하도록 하고, 탭 내부의 내용이라는게 코드에 가시적으로 보이도록 하고,`TabPanel` 자체에서 제공하는 부가기능을 편리하게 사용할 수 있을 것 같아서 제안을 했었는데
사실 lab버전 라이브러리를 설치하거나 따로 컴포넌트를 구현해서 사용할 정도의 필요성은 못느껴서 일단 조건부로 사용하는 방식대로 가도 괜찮을 것 같습니다!

> 필요없는 div가 2개 있고
> ```tsx
> interface TabPanelProps {
>  children?: React.ReactNode;
>  index: number;
>  value: number;
>}
>
>const TabPanel = (props: TabPanelProps) => {
>  const { children, value, index } = props;
>
>  return <div>{value === index && <div>{children}</div>}</div>;
>};
>```

에 대한 부분 살푼 코멘트 남기자면 div태그가 불필요하다고 느껴지면 아래와 같이 코드 짜는 것도 가능할 것 같습니다!
```tsx
interface TabPanelProps {
  children: JSX.Element;
  index: number;
  value: number;
}

const TabPanel = (props: TabPanelProps) => {
  const { children, value, index } = props;

  return value === index ? children : null;
};
```
-  일단 [불필요한 구성요소 렌더링 방지](https://legacy.reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering)를 위해 조건에 맞지 않는 경우 null을 반환하도록 하면 상위 태그를 하나 더 묶을 필요가 없이 처리가 가능합니다.
- 그리고 해당 컴포넌트를 반환할 때 JSX엘리먼트를 반환하도록 강제되어 타입에 `ReactNode`나 `undefined`가 반환되면 에러를 띄우더라구요! 여기서 `TabPanel`에서는 어차피 내용이 필수적으로 구성될테니 옵셔널을 제거해주고, JSX엘리먼트라는 것도 타입에 명시적으로 선언해주면 하위 태그도 없이 사용하는 것도 가능합니다!

2023-06-01 00:23 UTC, mia2583 commented on src/components/tab/StandardTab.tsx
> +  options: { id: number; label: string }[];
아하아하 감사합니다!

2023-06-01 00:24 UTC, mia2583 approved these changes

2023-06-02 14:48 UTC, pipisebastian commented
> 

오홋!! 친절한 답변 감사합니다!! 또 배워갑니다.. 껄껄..
그러면 따로 컴포넌트 안만들고,  지금 예시 코드대로 가겠씁니다!! 
```
      {tab === 0 && <div>도서</div>}
      {tab === 1 && <div>반납</div>}
      {tab === 2 && <div>흠냐</div>}
``` 원래대로 이걸로 갈게욤!?

2023-06-03 11:20 UTC, publdaze approved these changes
수고하셨습니다! 👍

2023-06-03 11:20 UTC, publdaze approved these changes
수고하셨습니다! 👍

2023-06-03 15:18 UTC, merged