Feature/세미나 출석 카드 3개 UI #331
KEEPER31337/Homepage-Front-R2 pull request #348
Opened 2023-05-05 08:56 UTC by lcqff

## 연관 이슈
#172

## 작업 요약
세미나 출석 페이지에 카드가 (지난 세미나, 최근 세미나, 이후 세미나)3개 뜨도록 바꿨습니다

## 작업 상세 설명
카드 3개를 justify-between을 사용해 정렬했는데 아직 카드 크기에 대한 수정이 이루어지지 않아(추후 디자인 갈아엎을때 바꿀 예정) 카드가 붙어있습니다. 이건 카드 크기 수정이 끝나면 자연스럽게 카드 사이에 20px 여백이 생길 거라 생각합니다

하는 김에 카드 너무 화면 아래에 붙어있는 거 같아 위로 좀 올렸습니다

## 리뷰 요구사항
작업 상세 설명 참고
5분

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/236416252-57372eb0-ac62-4f03-93cb-6f84ebc3004b.png)

2023-05-05 09:04 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
>      </Card>
1. 무슨소린지 잘 모르겠음
2. 이후 api로 교체 예정
3. GTP가 제시해준대로 수정하면 안됨 (뜬금없는 bg-none class는 뭐?)

2023-05-05 09:05 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
>  };
fillbutton 이후 제거 예정

2023-05-05 09:19 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
>      </Card>
아하~~~~~ 있는줄도 몰랐던 bg-none 이 적용돼있었네요??? 디자인 수정 브랜치에서 해당부분 수정함

2023-05-07 16:38 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +  const [futureSeminarDate, setFutureSeminarDate] = useState('towmorrow');
`towmorrow` -> `tomorrow`
오타 난 것 같네요! 😄

그런데 여기서  `tomorrow`라는 string이 사용되는 경우가 있나요?
변수가 사용되는 58번라인을 보면 **_towmorrow 세미나_** 이렇게 표시되는 것 같은데 의도한 동작이 맞을까요??

아 API 추후 적용할 거라서 임시로 아무 string 넣어주신 걸까요?

2023-05-08 04:15 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +  const [futureSeminarDate, setFutureSeminarDate] = useState('towmorrow');
오타ㅋㅋㅋㅠㅠㅠㅠㅠㅠ
네네 나중에 API 적용할거라 임시로 해둔건데 제가 카드 순서를 자꾸 헷갈려해서(오른쪽이 오래된건지... 왼쪽이 오래된건지..)😅😅😅 안헷갈리려고 저렇게 넣어둔것두 있습니다!

2023-05-28 13:43 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
>      </Card>
> 이거 1번에서 github-action이 요구한 수정 저도 헷갈려서!!괜찮으면 수정하는 거 약간 추천! 그 interface 보면 className이라는 이름으로 변수명?으로 작성했는데 이게 뒤에 14번째 코드에서 사용하는 css적용 className이랑 명칭이 동일합니다. 그래서 저도 처음엔 오해하고 16번 코드에서 className을 출력하면 뭐가 나오는지 잠깐 생각했네요😂

근데 저희가 만들어둔 컴포넌트 중에 className을 수정할 때 className이라는 인수명으로 넘겨서 사용하더라구요😯 (selector 참고,,,) 그래서 할 거면 아예 통일 시키는 게 맞는 거 같은데 한번 투표 올려볼까요??

2023-05-30 06:53 UTC, publdaze requested changes

2023-05-30 06:53 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        <SeminarCard className="mt-[-50px]">
2번째 카드 위로 올리기 위해서 별도의 className 추가해주었는데, 이렇게도 해볼 수 있을 것 같아요!

31번째 라인의 상위 태그에 자식 요소중 가운데 요소에 스타일을 적용시켜 준다는 의미로
`[&>*:nth-child(${Math.round(카드수 / 2)})]:mt-[-50px]` 이렇게 tailwind로 스타일 넣을 수 있더라구요!

지금은 카드수가 3개이지만 카드수가 늘어나게 됐을 때도 확장성 있게 스타일 적용이 가능하지 않을까 싶어요!

(Request changes 아니고 그냥 코멘트 입니다! 연후님 판단하기에 더 괜찮다 싶은대로 적용해주세욤~!)

2023-05-30 06:53 UTC, publdaze commented on src/pages/senimarAttend/Card/SeminarCard.tsx
>      </Card>
흠흠! 저도 `className`을 받아와서 `className` props에 그 자체로 넣는 방식(ex. Selector)이 아닌 지금 구현된 방식은 개선되면 좋을 것 같다는 생각입니다!

별도 컴포넌트에 스타일을 적용한 건 해당 스타일을 가진 컴포넌트로써 사용하기 위해서 일텐데 `className`을 prop으로 받도록 하면 사용하는 입장에서는 스타일을 얼마든 지 변경할 수 있다고 기대하게 될 것 같습니다.
하지만 이 코드에서는 `className`으로 받아온 내용이 Card 컴포넌트 `className`중 가장 뒷단에 위치하여 이미 앞부분에 적용된 클래스 유틸리티 같은 경우 적용이 안될 것이라 생각됩니다. (위치를 앞으로 변경한다고 하면 유지하고 싶은 스타일도 얼마든 지 수정할 수 있는 여지를 줄테구요!)

그래서 특정 스타일에 대한 부분만 커스텀 하고 싶은 경우라면 해당 스타일에 대한 부분만 prop으로 받아오게 하거나 커스텀 하고 싶은 상태 조건이 따로 있는 경우라면 상태조건을 받아오고 그에 따른 스타일을 적용하도록 처리하면 어떨까합니다!

2023-06-04 11:20 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        <SeminarCard className="mt-[-50px]">
```tsx
<>
      <div className="flex justify-between">
        <PageTitle>세미나 출석</PageTitle>
        <OutlinedButton>세미나 관리</OutlinedButton>
      </div>
      <div
        className={`mt-[180px] flex justify-between [&>*:nth-child(${Math.round(
          cardDateOrder.length / 2,
        )})]:mt-[-50px] `}
      >
        {cardDateOrder.map((date) => {
          return (
            <SeminarCard>
              {seminarActivated ? (
                <>
                  <Typography className="text-center text-paragraph text-white">{date} 세미나</Typography>
                  {isBoss ? <BossCardContent /> : <MemberCardContent />}
                </>
              ) : (
                <Typography className="text-center text-h3 font-bold">예정된 세미나가 없습니다.</Typography>
              )}
            </SeminarCard>
          );
        })}
      </div>
      {isBoss ? (
        <FilledButton onClick={() => setIsBoss(false)}>회원권한페이지로</FilledButton>
      ) : (
        <FilledButton onClick={() => setIsBoss(true)}>회장권한페이지로</FilledButton>
      )}
    </>
```


넘 좋아보여서 위와 같이 적용시켜봤는데 적용이 안됩니다🥺 nth-child니까 div의 자식 요소인 seminarCard에 적용되는게 맞는 거 같은데 모르겠네요ㅠㅠ

2023-06-04 11:23 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
>      </Card>
위 내용은 은지님이 제시해주신 nth-child 적용하면 아예 className 빼버려도 될것 같습니다! 
근데 nth-child가 적용이안됨...🥺

2023-06-07 09:23 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        <SeminarCard className="mt-[-50px]">
허걱!! `map` 돌린 걸로는 테스트 안 해봤었는데 `map` 함수 사용하면서 뭔가 연산 순서 때문인지 적용이 안되는 것 같네요..! 정확한 이유가 궁금해서 찾아보고 싶은데 제 서치능력으로는 아직 찾지 못했습니당...ㅠ
```tsx
nth-child(${Math.round(
  cardDateOrder.length / 2,
))
```
이부분 그냥
```tsx
nth-child(2)
```
별도의 연산없이 `2`로 지정하니 되긴 하는 것 같아요...!

2023-06-07 09:27 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        <SeminarCard className="mt-[-50px]">
허걱!! `map` 돌린 걸로는 테스트 안 해봤었는데 `map` 함수 사용하면서 뭔가 연산 순서 때문인지 적용이 안되는 것 같네요..! 정확한 이유가 궁금해서 찾아보고 싶은데 제 서치능력으로는 아직 찾지 못했습니당...ㅠ
```tsx
nth-child(${Math.round(
  cardDateOrder.length / 2,
))
```
이부분 그냥
```tsx
nth-child(2)
```
별도의 연산없이 `2`로 지정하니 되긴 하는 것 같아요...!

2023-06-10 07:31 UTC, lcqff commented on src/pages/senimarAttend/SenimarAttend.tsx
> +        <SeminarCard className="mt-[-50px]">
아예 `Math.round(cardDateOrder.length / 2)` 부분만 빼서 변수로 저장해서 넣으려 해봤는데도 안되더라고요...ㅠㅠ map의 문제가 아니라 정규식으로 표현하는 부분에 변수를 삽입하는게 문제인가 싶어요.... 일단은 2로 고정해두었습니다

2023-06-18 03:23 UTC, publdaze requested changes

2023-06-18 03:23 UTC, publdaze commented on src/pages/senimarAttend/Card/SeminarCard.tsx
> +      } `}
className 제거하면서 뒤에 공백 하나 남은 것 같네요 😄 제거 부탁드립니다!

2023-06-24 08:01 UTC, lcqff commented on src/pages/senimarAttend/Card/SeminarCard.tsx
> +      } `}
이런~~~~~

2023-06-24 09:40 UTC, publdaze approved these changes
굿굿 수고많으십니다~!~! 👍👍

2023-06-27 05:32 UTC, pipisebastian approved these changes

2023-06-27 06:07 UTC, merged