Feature/세미나 출석 카드 디자인 수정 #349
KEEPER31337/Homepage-Front-R2 pull request #350
Opened 2023-05-06 14:42 UTC by lcqff

## 연관 이슈
#349 

## 작업 요약
디자인을 바꿨습니다.

## 작업 상세 설명
카드 크기, 폰트 사이즈, 카드 내 요소 배치 순서, 요소들 사이 간격 수정

## 리뷰 요구사항
다른 거 먼저 머지되고 나서 머지해야 할듯 합니다.
5분?

## Preview 이미지
![image](https://user-images.githubusercontent.com/71930280/236630880-ccd265de-46e6-40aa-8717-187dfd5df6df.png)

2023-05-08 00:55 UTC, publdaze requested changes

2023-05-08 00:55 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
>            )}
26번 라인에서 `text-center`로 이미 중앙 정렬 적용해두어서 35번 라인에는 `text-center` 제거해도 중앙 정렬 될 것 같습니다!

2023-05-08 00:55 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +              <p className="mt-[26px] mb-[14px] text-paragraph">출석 코드</p>
저희 기본 font size가 `text-paragraph` 사이즈와 동일해서 따로 스타일 적용하기 않아도 같은 사이즈의 폰트로 적용됩니다! 명시적으로 적어두고 싶으면 그대로 둬도 좋고, 아니면 빼도 괜찮을 것 같습니다!

2023-05-22 00:44 UTC, mia2583 approved these changes
수고하셨습니다!!

2023-05-30 07:03 UTC, publdaze approved these changes
이전 PR 들에서 리뷰한 부분도 몇 군데 보여서 해당 부분 머지되면 pull 받아서 검토하고 머지하면 좋을 것 같습니다! 수고하셨습니다!

2023-06-25 14:08 UTC, pipisebastian approved these changes

2023-07-01 07:00 UTC, merged