Feature/버튼 material tailwind 모듈 mui로 변경 #358
KEEPER31337/Homepage-Front-R2 pull request #360
Opened 2023-05-14 14:58 UTC by pipisebastian

## 연관 이슈
- close #358

## 작업 요약
- material tailwind -> mui로 변경해줬습니다
- css) font-base뺀거는, 어차피 mui에서 폰트 설정 알아서 해주기 때문에, tailwind에서 따로 넣어줄 필요x
- css) 원래보다 살짝 작아질텐데, 그게 글자 크기를 10.5px -> 10px로 바꿨기 때문입니다! 일단은 !text-small로, tailwind상에서 10px로 박아놨습니다! (**font-[10.5px]적용하면 원래랑 똑같이 나옵니다!**)
- 추후에 버튼 font 크기 10px / 14px 선택 가능하도록 기능 추가해야 합니다!

## 리뷰 요구사항
- 1분

2023-05-20 08:30 UTC, publdaze commented
PR 내용 작업요약 3번째 항목에 `font-[10.5px]` -> `text-[10.5px]`인 것 같습니다! 😄

2023-05-20 08:44 UTC, publdaze requested changes

2023-05-20 08:44 UTC, publdaze commented on src/components/Button/OutlinedButton.tsx
> +      className="!focus:ring-0 !h-fit !rounded-sm !border-pointBlue !py-2 !px-6 !text-small !font-semibold !leading-4 !text-pointBlue"
##### 1.
`!focus:ring-0` material tailwind에서는 `focus`했을 시 외곽에 테두리가 적용돼서 ring 두께를 0으로 지정해줬었는데 MUI에서는 기본적으로 `focus`해도 ring 테두리가 생기지 않아서 해당 코드를 적용하기 전과 후과 동일한 것 같아요! 이전에 있던 코드 보존을 위해 놔둔 코드라면 지워줘도 될 것 같습니다!

##### 2.
`h-fit`에 important 안 붙여도 잘 적용되는 것 같아서 `!`빼주면 어떨까합니다!
저희가 MUI에 억지로(?) tailwindcss를 가져다 쓰면서 스타일 충돌이 일어나는 부분은 어쩔 수 없이 important를 사용하고 있긴 하나, important는 CSS 선택자 중 우선순위가 가장 높기 때문에 나중에 더 높은 우선순위를 가져야 하는 요소에 스타일을 적용할 일이 있거나 유지보수 할 때 어려움을 초래할 수도 있으니 남용하는 건 주의할 필요가 있을 것 같아요! 😀

##### 3.
MUI primary 컬러로 `pointBlue` 설정해두어서 `!border-pointBlue`, `!text-pointBlue`를 추가하지 않아도 `pointBlue`색이 적용됩니다. 하지만 border 색의 경우 살짝 연하게 나오는 스타일이 적용되어 있는데 디자인 측면으로 괜찮은지 확인 부탁드립니다! 괜찮다면 두가지 클래스는 빼주면 좋을 것 같습니다! 이유는 색이 변경될 수 있다는 확장성을 고려하여 MUI의 primary 색만 변경하면 전체적인 primary 사용되는 색이 자연스럽게 적용될 수 있기 때문입니다!

2023-05-21 12:10 UTC, jasper200207 approved these changes
수고하셨습니다

2023-05-29 13:49 UTC, amaran-th approved these changes
전체적으로 깔끔하니 제 식견으로는 리뷰할 게 안 보이네요...!
수고하셨습니다ㅎㅎ

2023-05-30 11:37 UTC, lcqff approved these changes
수고하셨습니다~!

2023-06-04 13:27 UTC, pipisebastian commented on src/components/Button/OutlinedButton.tsx
> +      className="!focus:ring-0 !h-fit !rounded-sm !border-pointBlue !py-2 !px-6 !text-small !font-semibold !leading-4 !text-pointBlue"
수정했습니다! 
근데 개인적으로 outlinedButton에 border-pointBlue같은 경우는 원래 색이랑 차이가 많이 보이는 것 같습니닷,,! 
이거는 그대로 유지하는거 어떨까욥..! 뭔가 또랑또랑했던 버튼이 또,,랑,,,,해졌습니다,,

2023-06-05 13:55 UTC, publdaze commented on src/components/Button/OutlinedButton.tsx
> +      className="!focus:ring-0 !h-fit !rounded-sm !border-pointBlue !py-2 !px-6 !text-small !font-semibold !leading-4 !text-pointBlue"
넵넵 그럼 그 부분은 그대로 갑시다!

2023-06-05 14:08 UTC, publdaze requested changes

2023-06-05 14:08 UTC, publdaze commented on src/components/Button/FilledButton.tsx
> +      className="!rounded-sm !py-2 !px-6 !text-small !font-semibold !leading-4 !text-subBlack hover:!opacity-80 hover:!shadow-none"
`h-fit`은 important만 제외하고 스타일은 유지하면 어떨까합니다!

아래 PR에서 처리한 이슈인데
- #242 

예를 들어 아래와 같이 코드를 작성하면
```tsx
        <div className="flex h-32">
          <OutlinedButton>아아</OutlinedButton>
          <FilledButton>아아</FilledButton>
        </div>
        <TextButton>아아</TextButton>
      </div>
```
높이가 상위 div의 높이를 따라가게 되어 기존에 의도했던 높이가 나오지 않는 이슈가 있어서 `h-fit` 넣어줬었습니다!
<img width="203" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/3bd4cb4a-2cd1-4808-9d67-95bcf317959c">

2023-06-18 06:55 UTC, publdaze approved these changes
수고하셨습니다!

2023-06-18 08:33 UTC, merged