Feature/메인페이지 정기활동 #121
KEEPER31337/Homepage-Front-R2 pull request #367
Opened 2023-05-21 10:00 UTC by jasper200207

## 연관 이슈

- #115 
- #122 
- #123 
동시에 하면 깃에서 충돌할거 같아서, 순차적으로 PR날리겠습니다.

## 작업 요약
메인페이지 중 정기활동 부분입니다.

## 작업 상세 설명
홀수 짝수로 나누어서 각각 왼쪽 오른쪽에 이미지가 배치되도록 하였고, 각각 40%, 60% 넓이를 차지합니다.
지금은 벡엔드에서 이미지가 넘어오지 않아서 임의로 이미지를 넣었습니다. 이부분은 추후에 수정하겠습니다.

## 리뷰 요구사항
디자인적인 요소에 틀린부분이 없는지 확인 부탁드립니다.
api 사용법이 맞는지 확인 부탁드립니다.

## Preview 이미지

![sample](https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/8571a5d9-59a4-4184-acc9-5c53d77b7e2b)

2023-05-31 11:44 UTC, lcqff commented
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/71930280/dbff87bd-82d8-4f40-b355-7ae73f695cb5)
figma와 디자인이 다른 부분들이 보이는데 figma와 개발서버 중 어느쪽 디자인이 맞는 건가요?😯

2023-05-31 13:28 UTC, lcqff commented on src/pages/home/Activity.tsx
> +          </div>
삼항 연산자에서 사용하는 두 코드가 많이 겹치는 거 같은데 코드 가독성과 유지보수성 측면에서 이미지 요소와 글상자 요소를 따로 컴포넌트로 분리해보는 거 어떨까요?

2023-05-31 15:29 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +            <div className="flex w-[40%] flex-col whitespace-pre-line px-10 text-left leading-10">
grid를 생각못했네요... grid 좋은거 같습니다!

2023-05-31 15:38 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +          </div>
컴포넌트 분리했습니다! 이미지의 경우는 grid를 적용하면서 필요한 classname이 없을 듯 하여 따로 분리하진 않았습니다.

2023-06-21 04:42 UTC, publdaze requested changes
리뷰 시간이 많이 걸려서 남은 리뷰 나중에 추가로 달아보겠습니다!

2023-06-21 04:42 UTC, publdaze commented on src/pages/home/Activity.tsx
> +    </div>
제 나름대로 한 번 리팩토링 해본 건데 한 번 제안드려봅니다!
```tsx
    <div className="bg-mainBlack">
      {data?.subtitleImages?.map((subtitleImage) => (
        <div key={subtitleImage.id} className="group grid grid-cols-[45%_55%] place-items-center even:text-right">
          <img
            className={`h-[450px] group-even:order-last ${
              subtitleImage.thumbnailPath ? 'w-full object-cover' : 'w-96 object-contain'
            }`}
            src={subtitleImage.thumbnailPath || LogoNeon}
            alt=""
          />
          <SubTitleImageCard subtitleImage={subtitleImage} />
        </div>
      ))}
    </div>
```

아래 주석으로 리팩토링 이유 달아두겠습니다!

```tsx
    <div className="bg-mainBlack">
      {/* 1. key를 index 대신 subtitleImage의 id 값으로 주기
          - reponse로 받아온 subtitleImage에는 고유한 id 값이 존재하기 때문에
          index보다는 id값으로 key를 지정해주면 좋을 것 같습니다! */}
      {data?.subtitleImages?.map((subtitleImage) => (
        /* 2. index % 2 === 0 대신 group even:text-right 사용하기
            - 교차로 바뀌는 게 컴포넌트 자체가 바뀌는 게 아닌 스타일이 변경되는 것이기 때문에
            조건을 주어 서로 다른 스타일을 가진 element를 따로 작성해주기보다
            nth-child(even)을 사용해보면 어떨까 제안드립니다! 
            - group의 경우 아래 자식 요소에서 추가 설명 드리겠습니다
          3. grid-cols-[50%_60%] 보다 grid-cols-[45%_55%]가 더 자연스러운 것 같아서
            디자인 담당자님께 문의 드려봤더니 후자로 하자고 하셔서 grid-cols-[45%_55%]로 가면 될 것 같습니다!
            혹시 다른 의견있으면 디자인 담당자(서윤님)에게 문의하면 될 것 같습니다! */
        <div key={subtitleImage.id} className="group grid grid-cols-[45%_55%] place-items-center even:text-right">
          {/* 4. 높이 고정해주기
                - 이미지마다 크기가 상이할 수 있기 때문에 각 줄마다 높이가 들쑥날쑥 하지 않도록 높이를 고정해줘야 할 것 같습니다!
              5. 교차로 순서 바꿔주기 (위의 group 추가설명입니다.)
                - 상위요소 기준 교차되는 것이므로 상위 요소가 even일 때 img의 순서를 끝으로 가게 하여 SubTitleImageCard와 순서를 변경해주면 어떨까 합니다!
                (grid의 경우 상위요소에서 reverse 해주는 방법이 없는 것 같아서 하위요소의 순서를 지정해주었는데 더 좋은 방법이 있다면 공유 부탁드립니다!)
              6. 이미지 유무에 따른 처리
                - 지금 벡엔드에서 넘어오는 이미지가 없어서 임시로 public에 이미지를 넣어주셨는데,
                  이미지 데이터 받아오지 못할 경우 따로 기본 이미지로 처리해줘야 해서
                  로고로 기본 이미지 넣어주면 될 것 같습니다!
                - 이미지 있을 경우는 영역에 전체적으로 채워지도록 w-full object-cover로 처리하면 될 것 같고,
                  로고의 경우 w가 로고의 크기로 사용되기 때문에 w-96 object-contain로 별도 스타일 지정해줘야 할 것 같습니다!
                */}
          <img
            className={`h-[450px] group-even:order-last ${
              subtitleImage.thumbnailPath ? 'w-full object-cover' : 'w-96 object-contain'
            }`}
            src={subtitleImage.thumbnailPath || LogoNeon}
            alt=""
          />
          <SubTitleImageCard subtitleImage={subtitleImage} />
        </div>
      ))}
    </div>
```

2023-06-21 04:44 UTC, publdaze commented on src/pages/home/Activity.tsx
> +            <img src={subtitleImage.thumbnailPath || '/img/image3.png'} alt="" />
[아래 코멘트](https://github.com/KEEPER31337/Homepage-Front-R2/pull/367#discussion_r1236271946) `6. 이미지 유무에 따른 처리` 확인 부탁드립니다!

2023-06-22 05:33 UTC, lcqff commented on src/pages/home/Activity.tsx
> +    </div>
혹쉬 group even에 대해 정리된 자료가 있을까요??? 저도 이런식으로 리팩토링하고싶었는데 짱구 굴려봐도 어려워서 못하겠더라고요😢 넘 좋아보이는데 검색해봐도 group even에 대해 설명된 자료를 못찾겠습니다ㅠㅠ!

2023-06-22 05:35 UTC, lcqff commented on src/pages/home/Activity.tsx
> +    </div>
아 nth-child(2n)을 tailwind에서 even으로 사용하는거군요~~~~~~~ 짱입니다

2023-06-24 07:08 UTC, lcqff commented on src/pages/home/Activity.tsx
> +      <p className="bg-gradient-to-b from-gray-500 to-white bg-clip-text text-xl text-transparent">
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/71930280/700250fb-a0da-4f11-b7bc-e8debb170027)
또 제 노트북화면에서는 텍스트 우측 정렬돼있는 인포에서 인포내용이 길 경우에 이런 식으로 줄바꿈이 되는데
가독성이 좋지 않은 거 같아 인포 내용에서 좌측 정렬을 추가해도 좋을 거 같습니다
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/71930280/88b2a7c7-3bfe-4dab-bec4-261199959062)
이런식으로...

2023-06-30 13:52 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +    </div>
even은 몰랐는데 감사합니다!

2023-06-30 17:20 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +      <p className="bg-gradient-to-b from-gray-500 to-white bg-clip-text text-xl text-transparent">
이 부분이 디자인 상으로는 우측 정렬이 되어있는데 줄 넘어가면 보기가 힘드네요.....
근데 막상 좌측 정렬을 하면 위의 제목이랑 끝부분 맞추는 기준이 사라져서.....
디자인 담당자의 의견이 필요할거 같습니다.
개인적으로는 피그마 기준으로 기획 이미지 처럼 제목, 인포 모두 좌측부분으로 바꾸는 것도 괜찮을거 같습니다!

2023-07-01 05:15 UTC, publdaze commented on src/pages/home/Activity.tsx
> +      <p className="bg-gradient-to-b from-gray-500 to-white bg-clip-text text-xl text-transparent">
디자인 관련해서는 디자인 담당자 분이 서윤님으로 바뀌어서 서윤님께 문의드리면 될 것 같아요! 슬랙 front-home 채널에도 초대해두었습니다!

2023-07-01 05:15 UTC, publdaze commented on src/pages/home/Activity.tsx
> +      <p className="bg-gradient-to-b from-gray-500 to-white bg-clip-text text-xl text-transparent">
저도 개인적으로는 다 좌측도 좋은 것 같습니다!

2023-07-01 06:57 UTC, publdaze requested changes

2023-07-01 06:57 UTC, publdaze commented on src/pages/home/Activity.tsx
> +  const { data } = useGetBlockListQuery({ type: 'activity' });
`data`로 받아오는 변수명이 좀 더 명확하면 좋을 것 같아요!
여기서는 data로 받아오는 게 정기활동 리스트니까 `activityList`라거나 하는 식으로 바꾸면 어떨까요?
아마 `data`가 기본적인 속성으로 지정되어 있을 거라서 다른 변수명으로 사용할 때는 아마 `{ data:  activityList }` 이런 식으로 하면 될 것 같아요!

2023-07-01 09:28 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +  const { data } = useGetBlockListQuery({ type: 'activity' });
다른 이름으로도 꺼낼수 있었군요.... 참고하겠습니다!

2023-07-01 15:37 UTC, jasper200207 commented on src/pages/home/Activity.tsx
> +      <p className="bg-gradient-to-b from-gray-500 to-white bg-clip-text text-xl text-transparent">
서윤님께 좌측정렬로 통일하는거 확인받았습니다!

2023-07-01 16:09 UTC, publdaze reviewed
<img width="1728" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/3dac0ba9-f76e-4591-a721-28bb9aa84058">

제 화면에서는 소제목?별로 높이 꽉 차게 보이는데 의도된 걸까욤? 🤔
+) `public/img/`에 넣어둔 이미지는 머지하기 전에 지우고 머지하면 좋을 것 같아욤!

2023-07-01 16:16 UTC, jasper200207 commented
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/78250089/250291265-3dac0ba9-f76e-4591-a721-28bb9aa84058.png">
> 제 화면에서는 소제목?별로 높이 꽉 차게 보이는데 의도된 걸까욤? 🤔 +) `public/img/`에 넣어둔 이미지는 머지하기 전에 지우고 머지하면 좋을 것 같아욤!

SubTitleImageCard하나의 높이가 960px인게 맞는거 같아서 의도한 내용입니다. 이미지 지운거 커밋했습니다!

2023-07-01 16:28 UTC, publdaze approved these changes
👍

2023-07-05 10:55 UTC, lcqff approved these changes
굿입니다~

2023-07-05 17:12 UTC, merged