Feature/image 첨부 공통 컴포넌트 구현 #356
KEEPER31337/Homepage-Front-R2 pull request #370
Opened 2023-05-21 17:55 UTC by amaran-th

## 연관 이슈
#356

## 작업 요약
이미지를 첨부할 수 있는 공통 컴포넌트 구현

## 작업 상세 설명
컴포넌트의 프로퍼티와 그 타입은 다음과 같습니다.
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/46ef830a-3efe-4a24-9ffe-ee84bcd4b3e3)

- Title
title 프로퍼티를 설정해 원하는 문구를 입력해줄 수 있습니다.
title 값을 설정하지 않을 시 빈 문자열이 기본으로 설정됩니다.

- isEdit과 thumbnailPath
섬네일이 설정되어 있지 않는 초기 상태와 섬네일을 수정하는 상황을 분리하기 위해 필요합니다.
isEdit이 true이고 thumbnailPath가 존재하면 수정하는 경우이기 때문에 기존에 설정되어 있던 이미지를 불러올 수 있습니다.

- setThumbnail
상위 컴포넌트로 이미지 파일을 전달해줍니다.

- 크기
가로 길이는 100%로 설정하여 해당 컴포넌트를 사용하는 상위 컴포넌트에서 가로 길이를 조절할 수 있습니다. height의 경우 128px로 고정입니다.

- 사용법
드래그 or 클릭으로 이미지를 첨부할 수 있으며, 이미지 첨부 후에는 미리보기로 첨부한 이미지를 확인할 수 있습니다.
이미지가 셋팅된 상태에서 `기본 이미지로`를 클릭하면 설정된 이미지가 제거됩니다.

*섬네일 api가 만들어지면 state 관련 코드에 수정이 필요해질 수 있습니다. 

## 리뷰 요구사항
15분
라이브러리 특성 상 div 태그에 넣어줘야 할 프로퍼티가 많습니다. 그래서 아래와 같이 전개 연산자를 사용해서 속성을 넣어주는 것이 일반적인데, esLint의 규칙 상 태그 내에서 전개 연산자의 사용을 금지하고 있어서, 이에 대해 리뷰어분들의 의견을 여쭙고 싶습니다.
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/18964760-73f7-43dc-8bfe-1d10847cb792)

esLint에서 해당 규칙이 존재하는 이유도 인지하고 있으나, 다음 이미지를 보면 아시다싶이 필요한 속성이 많은 터라 여기에서 꼭 필요한 속성을 찾아내 추출하는 것도 조금 어려울 것 같다고 생각됩니다.(전개 연산자를 사용하지 않은 예시를 찾기 어렵기도 하구요.)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/8321add8-2932-4f54-b416-6c5ed8e3f0c8)
해당 esLint 설정을 끄거나, 이 컴포넌트에 대해서만 지금처럼 주석 처리 해주는 것이 좋을 것 같다는 것이 제 의견입니다.
리뷰 남겨주시면 결정되는 대로 반영해서 푸시하겠습니다!

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/b508e56f-a2a6-452a-b17b-b83a1d992c27)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/f577813c-33c1-414d-ac52-3cc0bc363b34)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/07fc5a92-29f0-42a7-91c4-df1d06d543a0)
*리뉴얼 1때는 이미지 비율을 무조건 정사각형으로 고정시켜놔서 이미지 비율에 따라서 조금 찌그러졌었는데, 이번엔 비율을 유지하게 해보았습니다!
- 상위 컴포넌트에서의 사용 예시
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/e0dc73ce-b3ef-4fa0-8cef-0456d879795a)

2023-05-22 13:32 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-05-22 13:32 UTC, jasper200207 commented on src/components/File/Image/ImageUploader.tsx
> +        {...rootProps}
공통컴포넌트로 사용할 jsx이기도 하니 스프레드 연산자를 사용하는 것이 좋아보입니다!

2023-05-28 14:23 UTC, lcqff approved these changes
수고하셨습니다~

2023-05-28 17:57 UTC, publdaze requested changes

2023-05-28 17:57 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +      <div className="flex w-full items-center justify-between ">
className 끝에 공백 제거 부탁드려요~!

2023-05-28 17:57 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +  };
저희 이벤트 핸들러 함수의 경우 `접두사(handle) + (동사) + 명사(컴포넌트) + 동사(이벤트)`으로 사용중이라 컨벤션 맞춰주면 좋을 것 같아요!

2023-05-28 20:29 UTC, publdaze requested changes

2023-05-28 20:29 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +      >
1. 여기서 `rootProps` 따로 객체로 생성해준 후 넣어준 이유가 있나요?
`rootProps`라는 네이밍으로 해준 이유와 어떤 기준으로 묶은 건 지 궁금합니다!

2. 투명도 표현할 때 `bg-pointBlue/[30%]`으로 대괄호를 사용한 임의 값도 가능하지만 `bg-pointBlue/30` 이런 식으로 [tailwind에서 제공해주는 투명도 처리 방식](https://tailwindcss.com/docs/background-color#changing-the-opacity) 중 30퍼센트가 존재하기 때문에 이렇게 사용하면 어떨까합니다! border의 경우에도 임의 값 대신 border-2로 동일하게 처리 가능할 것 같습니다!
    + bg-opacity-50도 투명도 처리하는 옵션인데 왜 추가적으로 스타일 적용해주신 건지 궁금합니다! (아마 앞에서 이미 투명도 적용하고 있어서 해당 스타일은 적용 안 되는 것 같다 생각되네욤..🤔)

4. 조건부 처리해준 게 두 개나 들어나는데 가독성이 조금 떨어지는 느낌이 들어서 3항 연산자를 사용하여 조건에 따라 빈스트링을 넣는 방식 말고 `&&`을 조금 더 깔끔하게 작성할 수 있지 않을까 생각됩니다. 아래와 같은  느낌으로요!
    ```tsx
    ${isDragActive && 'bg-pointBlue/30 bg-opacity-50'} ${!thumbnailBase64 && 'border-2'}
    ```
    하지만 이 방식이 약간 걸리는 부분은 가독성 측면에서는 조금 깔끔해 질 수 있지만 아무래도 조건이 `false`의 경우 `false`값의 반환하다보니 `className`에 `false`라는 텍스트(?)가 그대로 들어간다는 점입니다. tailwind의 class 유틸리티에는 `false`라는 값이 없고 따로 class로 `false`라고 지정해 사용할 일이 없으니 문제될 부분은 없어보여서 저는 보통 가독성을 더 중요하게 보고 그냥 사용하긴 하지만 그런 부분이 아무래도 어색하게 느껴질 수 있는 부분이라 한 번 생각해보시고 세연님이 더 좋은 처리 방식이라고 생각되는 대로 처리해주면 좋을 것 같습니다!

2023-05-28 21:22 UTC, publdaze requested changes

2023-05-28 21:22 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +            className={`${isDragActive ? 'opacity-50' : ''} h-full w-full object-cover shadow-lg`}
`shadow-lg`가 화면 상으로 별로 눈에 띄지 않던데 넣어준 의도가 궁금합니다!

2023-05-28 21:22 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +              </p>
여기서 p 태그 안에 div를 사용으로 인해 워닝 발생합니다!
<img width="350" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/f19d2319-8e75-4204-9bcc-3d43996891b1">

2023-05-28 21:22 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +                <div className="mx-2 inline-block text-center">
여기서 어차피 중앙 정렬이라 마진 처리해줄 필요성이 잘 느껴지지 않는데 왜 마진 넣어줬는 지 궁금합니다! 그리고 `inline-block` 요소로 지정해준 이유도 궁금합니다!

2023-05-29 13:53 UTC, pipisebastian commented
예시코드도 넣어주면 좋을 것 같습니당~

2023-05-29 14:27 UTC, pipisebastian commented
움냐링 은지님 엄청 자세하게 리뷰해주셔서 남길 말이 없네요! 
Blob객체 신기해요! 수고하셨습니다!!

2023-05-29 14:27 UTC, pipisebastian approved these changes

2023-06-01 00:19 UTC, mia2583 approved these changes
멋집니다~~굿굿

2023-06-16 14:58 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +  };
혹시 어디에 문서화 되어있는지 알려주실 수 있나요?? 확인하고 위키에도 업데이트해두겠습니다!
handleToDefaultImageClick로 변경했습니다~

2023-06-16 15:11 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +      <div className="flex w-full items-center justify-between ">
오 그건 몰랐던 사실이네요...!
말씀해주신 라인에서 w-full 삭제했습니다ㅎㅎ
감사합니다~

2023-06-16 15:15 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +            className={`${isDragActive ? 'opacity-50' : ''} h-full w-full object-cover shadow-lg`}
리뉴얼 1때 코드를 가져오면서 깜빡하고 수정하지 못한 부분인 것 같습니다!
현재 다크모드에서는 필요없는 효과인 것 같아서 제거했습니다~!

2023-06-16 15:16 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +              </p>
수정했습니다!

2023-06-16 15:18 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +                <div className="mx-2 inline-block text-center">
문장 길이를 조절하는 과정에서 잠깐 넣어줬던 속성인 것 같은데 지금은 필요없는 설정이라 삭제했습니다!
`inline-block`도 원래 `div`가 아니라 다른 태그를 사용했어서 넣어준 것 같습니다! 이것도 삭제하겠습니다~!

2023-06-16 17:15 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +  };
오....다시 알아봤는데 설정이 적용되고 있는 게 아니었습니다,,,!!
useDropzone()을 호출할 때  OnDrop과 함께 지정해줘야 하는 거였네요.
제가 별도로 구현했던 검증 로직은 다 걷어내고 라이브러리에서 지원해주는 기능 그대로 사용할 수 있게 했습니다! 여기도 다시 확인 부탁드려요!

2023-06-16 17:18 UTC, amaran-th commented
정성스런 리뷰 감사합니다! 스케줄때문에 너무 오래 방치해버렸네요ㅜㅠ
말씀해주신 부분 대부분 반영했고, 그 과정에서 달라진 코드도 몇 있어서 그 부분만 다시 확인해주시면 좋을 것 같아요!

2023-06-27 00:47 UTC, publdaze commented
혹시 상위 컴포넌트에서의 사용 예시에서 `thumbnail`은 사용되고 있지 않는 것 같은데 `thumbnail` state는 어떻게 사용되는 지 알 수 있을까요?

2023-06-27 00:53 UTC, publdaze requested changes
스프레드 연산자 워닝 떠서 develop 한 번 풀받아주면 좋을 것 같아요!

2023-06-27 00:53 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +        }
array 변수가 여기만 있어서 따로 사용되는 곳이 없는 것 같은데 어떤 용도 인가요?~?

2023-06-27 00:53 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +      reader.readAsDataURL(file);
찾아보니까 `readAsDataURL` 함수가 base64로 인코딩 된 스트링 데이터가 result 속성에 담겨지도록 처리하는 함수인 것 같더라구요!
그래서 base64가 윗부분에서 사용되니 좀 더 흐름적으로 이해하기 쉽도록

`const reader = new FileReader();`
바로 아래에
`reader.readAsDataURL(file);`
위치시키고
그 뒤에 base64 인코딩된 스트링이 사용되는 `reader.onloadend`를 배치하면 어떨까요?

2023-06-27 00:53 UTC, publdaze commented on src/components/Uploader/ImageUploader.tsx
> +  }, []);
너무 길어질 것 같아서 useEffect 부분만 리뷰 라인 잡겠습니다!
https://www.notion.so/6-eeb89a95eda64b88b06c883d1851fdd9?pvs=4#1c7a6652493d44bea721e0585e964d41
저희 개발회의할 때 코드 작성 순서 정했어서

useState
→
hook
→
eventhandler
→
useEffect
→
return

이 순으로 되도록 맞춰주면 좋을 것 같습니다!

2023-06-27 23:09 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +        }
지금 보니 리뉴얼 1에서 사용한 걸 그대로 가져온 것 같은데 이전 코드도 이 코드도 딱히 사용되는 곳이 없는 것 같네요...!
지웠습니당

2023-06-27 23:12 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +      reader.readAsDataURL(file);
좋은 것 같습니다!! 반영했어요~!

2023-06-27 23:16 UTC, amaran-th commented on src/components/Uploader/ImageUploader.tsx
> +  }, []);
반영했습니다!

2023-06-27 23:33 UTC, amaran-th commented
thumbnail state는 추후 API를 호출할 때 요청 데이터로 넣어줄 데이터입니다!
아래 코드는 리뉴얼 1때의 사용 예시에용
```javascript
const createHandler = () => {
    print();
    setClickable(false);
    ipAPI.getIp().then((ipAddress) => {
      console.log([headMember.id, ...memberIdList]);
      studyAPI
        .create({
          year: year,
          season: season,
          title: title,
          information: information,
          memberIdList: [headMember.id, ...memberIdList],
          gitLink: gitLink,
          noteLink: noteLink,
          etcLink: etcLink,
          thumbnailFile: thumbnail,
          token: token,
          ipAddress: ipAddress,
        })
        .then((res) => {
          setClickable(true);
          if (res.success) {
            setOpen(false);
            setChangeFlag(!changeFlag);
          } else {
            alert('스터디 생성 실패! 전산관리자에게 문의하세요~');
          }
        });
    });
  };
```

2023-06-28 02:11 UTC, publdaze approved these changes
굿굿! 수고하셨습니다!

2023-06-28 02:13 UTC, merged