Feature/버튼 disable시 border색 변경 #397
KEEPER31337/Homepage-Front-R2 pull request #399
Opened 2023-06-21 09:11 UTC by pipisebastian

## 연관 이슈
- close #397
- 선행 풀리퀘 #398입니당

## 작업 요약
- outlineButton disable시 border색 pointColor 적용되는거 제거했씁니다

## Preview 이미지
- 일단 outlineButton에 border색만 바꿨는데, 다른 버튼의 disable은 mui 기본 디자인거 그대로 입니다! 
이대로 나쁘지 않을 것 같아서 다 냅뒀습니다!
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/70d06efd-e3ae-4c73-8b06-739a675aee94)

2023-06-22 05:09 UTC, lcqff approved these changes
굿입니다~

2023-06-25 12:15 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-06-25 13:34 UTC, publdaze reviewed
mui 컴포넌트에도 적용이 되는 지는 모르겠는데
https://tailwindcss.com/docs/hover-focus-and-other-states#disabled
tailwind에서 제공해주는 disabled시 스타일 적용하는 게 있더라구요! 한 번 이걸로 처리해보면 어떨까욤?~?

2023-06-30 07:51 UTC, pipisebastian commented
> mui 컴포넌트에도 적용이 되는 지는 모르겠는데 https://tailwindcss.com/docs/hover-focus-and-other-states#disabled tailwind에서 제공해주는 disabled시 스타일 적용하는 게 있더라구요! 한 번 이걸로 처리해보면 어떨까욤?~?

우옹,, 생각도 못했었는데,,! 훨씬 깔끔해졌네요! 감사합니다!

2023-06-30 13:51 UTC, jasper200207 approved these changes

2023-07-01 04:33 UTC, publdaze requested changes

2023-07-01 04:33 UTC, publdaze commented on src/components/Button/FilledButton.tsx
> +      } " h-fit !rounded-sm !py-2 !px-6 !font-semibold !text-subBlack hover:!opacity-80 hover:!shadow-none disabled:!bg-subGray`}
여기 `h-fit` 앞에 큰땨옴표 붙으면 안 될 것 같은데 이전 PR에서 놓쳤었나보네요! 한 번 확인 부탁드리고 제거 부탁드립니다!

2023-07-01 15:41 UTC, pipisebastian commented on src/components/Button/FilledButton.tsx
> +      } " h-fit !rounded-sm !py-2 !px-6 !font-semibold !text-subBlack hover:!opacity-80 hover:!shadow-none disabled:!bg-subGray`}
"도 필요없는거라 같이 제거했숩니다~

2023-07-01 16:13 UTC, publdaze approved these changes
굿~

2023-07-02 14:05 UTC, merged