Feat/ eslint import 순서 정렬 적용
KEEPER31337/Homepage-Front-R2 pull request #423
Opened 2023-07-01 15:25 UTC by lcqff

## 연관 이슈

## 작업 요약
eslint [ import문 순서 정렬](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)하는거 적용했습니다

## 작업 상세 설명
일단 `외부 라이브러리, 내부 라이브러리(@component 같은), 상대 경로, 기타...`
순으로 정렬하게 해두었습니다
react를 제일 위로 올리고 싶어서 pathGroups 설정을 했는데 왜 안먹히는지는 모르겠습니다ㅠㅠ 

## 리뷰 요구사항
정렬 순서나 기타 옵션 추천 받습니다~ 

아래 문서 참고하시면 좋습니다
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
https://tesseractjh.tistory.com/305

## Preview 이미지

2023-07-01 15:27 UTC, pipisebastian commented
오 이거 너무 좋습니다~!

2023-07-01 15:32 UTC, publdaze commented on package.json
> +    "npm": "^9.7.2",
위에 eslint 플러그인 추가되고 업데이트 된 건
`eslint-plugin-import`을 통해 순서 정렬해주기 위해 설치되고
나머지도 그 과정에 업데이트 된 것 같은데

`npm`과 `i` 같은 경우에는 필요한 모듈인가 싶어서요!
혹시 실수로 `npm i npm i` 이렇게 잘못 쳐서 들어가게 된 걸까요?? 아니면 따로 용도가 있는지...! 🤔

2023-07-01 15:35 UTC, jasper200207 approved these changes
순서 다른거 불편했는데 좋습니다!

2023-07-01 15:36 UTC, lcqff commented on package.json
> +    "npm": "^9.7.2",
이런미친~~~ 필요해서 다운받아진건줄 알았는데 진짜로 그렇게 실수를 했습니다!!!!!!!!!!

2023-07-01 15:38 UTC, lcqff commented on package.json
> +    "npm": "^9.7.2",
수정완료..

2023-07-01 15:47 UTC, publdaze commented on .eslintrc.js
> +        },
오오 알파벳순 정렬도 되는 군요!

2023-07-01 15:47 UTC, publdaze commented on .eslintrc.js
> +            pattern: 'react',
혹시 react 뒤에 * 안붙여도 되나요? PR에 참고 링크로 걸리 블로그 내용 보니 react로 시작하는 경로 명에 적용하기 위해서 * 붙여준 것 같네요?~?

2023-07-01 15:47 UTC, publdaze commented on .eslintrc.js
> +            pattern: 'react',
<img width="909" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/248f2f59-5d27-4e8b-8208-700f5c1ace66">

index.tsx에서 테스트 해보았습니다!

이부분이 작성되면 react 모듈이 최상단으로 갈 거라 기대했는데 (*유무와 상관없이) 중간에 위치하네욤..
이부분이 상단에 올라가도록 처리 가능할까욤?~?

2023-07-01 15:48 UTC, publdaze commented on .eslintrc.js
> +            pattern: 'react',
앗 PR 내용에도 있네요

2023-07-01 15:49 UTC, publdaze commented on .eslintrc.js
> +            pattern: 'react',
저도 한 번 찾아보겠습니다!

2023-07-01 15:54 UTC, publdaze commented
정렬 순서
@pages > @components
요정도만 더 추가해줘도 될듯하네용!

2023-07-01 15:55 UTC, publdaze commented
이거 중간에 개행도 넣어주는 군요! 짱입니다!

2023-07-01 16:10 UTC, lcqff commented on .eslintrc.js
> +            pattern: 'react',
깃헙문서에는 *를 안붙이고 사용해서 일단 *을 뺐습니다!!
저도 그렇게 하고싶었는데 안돼서 찾아봤는데 `pathGroupsExcludedImportTypes`를 사용하니까 되네요! 적용했습니다!

2023-07-01 16:25 UTC, publdaze requested changes
`react-dom`
`react-router-dom`

요 두 친구도 상단으로 가도록 요청드려도 될까욤?~? 😆

2023-07-01 16:25 UTC, lcqff commented
@pages > @components 정렬순서 적용해주었습니다~
다만 pathGroups으로 적용하면서 사이에 개행이 추가되네요.🥲 개행이 너무 많은거 같으면 아예 개행 안넣게 설정하겠습니다! (pathGroups 사이에만 안넣는 건 안되는거 같음ㅠㅠ)

2023-07-01 16:29 UTC, publdaze commented
> @pages > @components 정렬순서 적용해주었습니다~ 다만 pathGroups으로 적용하면서 사이에 개행이 추가되네요.🥲 개행이 너무 많은거 같으면 아예 개행 안넣게 설정하겠습니다! (pathGroups 사이에만 안넣는 건 안되는거 같음ㅠㅠ)

🥲 네네 그럼 개행은 뺍시당..!

2023-07-01 16:43 UTC, lcqff commented
> `react-dom` `react-router-dom`
> 
> 요 두 친구도 상단으로 가도록 요청드려도 될까욤?~? 😆

했습니당!

2023-07-01 16:44 UTC, lcqff commented
자동 개행은 제거했습니다1!! 그냥 본인이 원하시는 곳에 개행 넣어서 쓰시면 될거 같습니다🥲

2023-09-01 05:43 UTC, lcqff commented
허걱 근데 머징 블락 뭐지

2023-09-01 05:44 UTC, lcqff commented
아 헐 이거 저희 페이지에 import 순서 적용하는건 따로 pr파서 하기로 했는데 같이 안하니까 오류생기네요!! ;;;

2023-09-01 05:46 UTC, publdaze commented
> 아 헐 이거 저희 페이지에 import 순서 적용하는건 따로 pr파서 하기로 했는데 같이 안하니까 오류생기네요!! ;;;

허걱! 그러면 이 PR에서 같이..! 해주실 수 있나용??

2023-09-01 05:47 UTC, publdaze approved these changes
👍

2023-09-01 06:12 UTC, merged