Feature/로그인기능_#147
KEEPER31337/Homepage-Front-R2 pull request #440
Opened 2023-07-09 06:53 UTC by Ji-Hyeon212

## 연관 이슈
> 연관된 이슈를 모두 기재 → #[Issue번호] 형식
#147
## 작업 요약
> 1~2줄 사이의 요약 설명
사용자 로그인 시 set-cookie의 쿠키 값을 담고 로그인이 됩니다. 이후 api 호출 시 request header에 쿠키가 담겨 보내집니다.

## 작업 상세 설명
> 주요 기능 및 로직에 대한 설명을 작성
- 로그인 완료 시 메인페이지로 이동합니다.
- 리액트 쿼리로 api 호출하는 부분 구현했습니다.

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분
- 0.5분? 리액트 쿼리 사용이 익숙치 않아 간단하게만 구현했습니다.
- 아이디, 비밀번호 null 체크나 로그인 상태 유지 기능 추가로 필요하지만 다른 분들 api 호출 할때 쿠키값 사용하셔야 해서 나머지 사항은 세부 기능 구현으로 다시 올리겠습니다.

## Preview 이미지

2023-07-09 10:30 UTC, publdaze requested changes
쿠키 우여곡절이 많았을텐데 수고 많으셨습니다!
먼저 1차 피드백 남기고 나머지 리뷰 추가로 진행하겠습니다!

2023-07-09 10:30 UTC, publdaze commented on package.json
`package.json`파일과 `package-lock.json` 파일 변경사항이 전체적으로 잡힌 것 같은데 관련해서 변경사항 생길 부분이 있나요? 한 번 확인 부탁드립니다!

2023-07-09 10:30 UTC, publdaze commented on src/api/logInApi.ts
> +// eslint-disable-next-line import/prefer-default-export, func-names, consistent-return
혹시 이 eslint 뭐 관련해서 처리한 건지 알 수 있을까요?

2023-07-09 10:30 UTC, publdaze commented on src/api/logInApi.ts
> +  return axios.post(`${process.env.REACT_APP_API_URL}/sign-in`, { loginId, password }, { withCredentials: true });
아마 index.tsx 파일에 axios 기본 경로로 baseurl `process.env.REACT_APP_API_URL` 지정해줘서 앞에 `${process.env.REACT_APP_API_URL}` 이부분 제거해도 될 것 같습니다!

2023-07-09 10:40 UTC, publdaze requested changes
<img width="436" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/09e5060a-b456-4f5e-9022-a783d9b4334f">

실행시켜보니 loginAPI 파일에서 위와 같은 에러가 뜨면서 화면이 안 뜨던데 혹시 정상적으로 동작 되던가요?

2023-07-09 11:00 UTC, publdaze requested changes

2023-07-09 11:05 UTC, publdaze reviewed
로그인 페이지 렌더링 되는 컴포넌트 부분(return 괄호 안 부분)도 변경사항있나요?

변경사항이 전체적으로 잡혀서 이부분도 리뷰 진행해야 하는 건지 질문 드립니다!

2023-07-09 11:17 UTC, publdaze requested changes

2023-07-09 11:17 UTC, publdaze commented on src/pages/login/Login.tsx
> +  };
핸들러 컨벤션! 이벤트 나타내는 동사(`Click`)는 subfix로 붙여주세요~! 😄

2023-07-09 11:19 UTC, publdaze commented
로그인 페이지 렌더링 되는 컴포넌트 부분(return 괄호 안 부분)도 변경사항있나요?

변경사항이 전체적으로 잡혀서 이부분도 리뷰 진행해야 하는 건지 질문 드립니다!

2023-07-11 15:23 UTC, Ji-Hyeon212 commented on src/api/logInApi.ts
> +  return axios.post(`${process.env.REACT_APP_API_URL}/sign-in`, { loginId, password }, { withCredentials: true });
오옹 그렇네요! 제거 했습니다

2023-07-11 15:24 UTC, Ji-Hyeon212 commented on src/api/logInApi.ts
> +// eslint-disable-next-line import/prefer-default-export, func-names, consistent-return
빨간 밑줄 떠서 설정 했었는데 해당 함수 리뷰 들어온 거 수정하고 손봤더니 없어도 괜찮네요 지웠습니다!

2023-07-11 15:25 UTC, Ji-Hyeon212 commented on src/api/logInApi.ts
> +});
그럼 일단 형식 정해지면 해당 방향으로 수정하고 지금은 넘어가겠습니다.

2023-07-11 15:27 UTC, Ji-Hyeon212 commented
로그인 페이지 렌더링 되는 부분은 onSubmit부분에 핸들러명 바꿔준 거 말고는 없습니다 확인 안하셔도 돼요!!

2023-07-12 07:11 UTC, publdaze commented
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/78250089/252140192-09e5060a-b456-4f5e-9022-a783d9b4334f.png">
> 실행시켜보니 loginAPI 파일에서 위와 같은 에러가 뜨면서 화면이 안 뜨던데 혹시 정상적으로 동작 되던가요?

이 에러 원인 파악해서 아래 발생한 이유 코멘트 쫙 달아두겠습니다.

2023-07-12 09:08 UTC, publdaze commented on src/api/logInApi.ts
> +});
일단 여기서 `useMutation`와 `useNavigation`의 경우 React hook이기 때문에 중첩해서 사용할 수 없습니다. ([참고](https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level))

그렇기에 `useNavigation` 밖으로 빼준 후 사용하여야 하고, hook의 경우 또 React 컴포넌트 함수내에 위치하여야 하므로 ([참고](https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions)) 해당 함수를 한 번 더 감싸는 형태로 만들어 주고 그 내부 함수 최상위에 따로 변수로 빼줘야 할 것 같습니다.

또한 이 함수의 경우는 두가지 커스텀 훅에 대해 관리하는 커스텀 훅으로 볼 수 있으므로 함수 prefix로 `use`를 붙여줘야 할 것 같습니다. ([참고](https://ko.legacy.reactjs.org/docs/hooks-custom.html#using-a-custom-hook))

2023-07-12 09:08 UTC, publdaze commented on src/pages/login/Login.tsx
> +  };
여기도 마찬가지로 커스텀 훅으로 최상단에 훅이 위치해야 하기 때문에 이렇게 바로 함수 내부에서 호출하게 되면 에러가 발생하게 됩니다.

2023-07-12 10:24 UTC, publdaze commented on src/api/logInApi.ts
> +});
에러 원인 파악하면서 기존에 사용해오던 방식으로 해보면서 왜 안되는 지 파악해봤는데 그렇게 적용한 거 그대로 올렸습니다! 일단 별다른 의견 없으면 기존 사용해오던 방식으로 통일하는 걸로 할게요!

2023-07-12 10:27 UTC, publdaze commented on src/api/logInApi.ts
> +      alert('아이디 또는 비밀번호를 확인해주세요.');
저희가 alert로 알려주는 방식은 안 쓰고 있는데 일단 이 pr에서는 상태 파악을 위해 그냥 두는 걸로 하고 나중에 다른 방식(아마 기획된 방식?)으로 알려주도록 처리해봅시다!

2023-07-12 10:41 UTC, pipisebastian commented on src/api/logInApi.ts
> +      navigate('/');
혹시 api불러오는 login.tsx에서  isError, isSuccess 등을 받아서 
login.tsx에서 로그인 에러처리나, 네비게이션 처리 안해주는 이유가 있을까요??
개인적으로 api 호출파일은 딱 호출만 한다고 생각해서,, 의견 궁금합니댱!!

2023-07-12 10:44 UTC, publdaze reviewed
<img width="775" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/99c012c5-734d-42a1-b9d0-04da89ea2698">

develop에서 최신 package.json 상태로 npm 모듈 설치해주고
이 브랜치에서 다시 npm i 하면 뭔가 한 패키지가 지워지네요...!

어떤 패키지인지 파악하기는 어려운데 이 변경사항 유지한 채로 머지하기에는 조금 찝찝해서, package.json 파일은 왜 변경사항 잡히는 지는 모르겠지만 package-lock.json은 변경된 부분이 그래도 꽤나 있는 것 같아서 이전 상태로 롤백 해주는 건 어떤가요?
(develop 브랜치에서 파일 ctrl+c 하고 이 브랜치 돌아와서 ctrl+v 하면 되지 않을까 싶습니다..?!)

2023-07-12 10:44 UTC, publdaze commented on src/index.tsx
> +axios.defaults.withCredentials = true;
혹시 withCredentials 없어도 되긴하던데...!! 필요한 부분일까요? 쿠키 사용시에 뭐가 안 되면 넣어주라는 걸 저도 어디서 보긴했는데 없애도 정상 동작하네요?~? 🧐

2023-07-12 10:54 UTC, publdaze commented on src/api/logInApi.ts
> +      navigate('/');
제가 카테캠 강의 들으면서 강사님도 이런 식으로 api 쪽에서 에러처리를 해주더라구요!
api와 직결된 에러 캐칭이어서 그런 거 아닐까 싶기도하고, 강사님이 설명 들어본 바로는 컴포넌트 함수에 이런 세세한 처리가 들어가게 되면 한 곳에 여러 처리에 대한 코드가 몰리게 되어 코드가 지저분해지고, 컴포넌트 함수 내에서는 대부분 렌더링과 관련된 부분만 처리해주는 것 선호하는 것 같더라구요!
에러 캐칭 말고도 성공했을 때 이후 동작이라거나 이런 부분은 어느 부분에서 관리하는 게 더 좋을 지에 대한 부분은 많이 고민되는 사항인 것 같아요 ㅎㅎ
그래서 코드 짤 때마다 매번 고민해보면서 경험을 쌓아 더 좋은 방향을 찾아갈 수 있도록 노력해야할 것 같다고 생각되네요!! 😆

2023-07-12 13:51 UTC, publdaze approved these changes
일단 답변 못받은 질문사항 중 당장 변경이 필요한 부분은 없는 것 같아서 미리 approve 해두겠습니다! 혹시 추가 변경사항 생기면 re-request review 부탁드려요~! 수고하셨습니다!

2023-07-12 14:03 UTC, Ji-Hyeon212 commented on src/index.tsx
> +axios.defaults.withCredentials = true;
axio에서 요청 파라미터 옵션인 withCredentials은 기본값이 false로 설정되어 있습니다. 이는 cors 요청을 허용하지 않습니다.  저희가 이전에 서버 origin이랑 클라이언트 origin이랑 달라서 쿠키 값이 담는데 문제가 있었는데 그 때 cross-origin끼리도 가능하게 하려고 해당 axios.defaults.withCredentials = true; 구문을 넣었던 것 같습니다. 
지금은 해당 이슈와 관련하여 처리가 되었으니 없어도 될 것 같다는 생각...! 입니다.

2023-07-12 14:04 UTC, Ji-Hyeon212 commented on src/index.tsx
> +axios.defaults.withCredentials = true;
해당 부분은 제거하도록 하겠습니다!!

2023-07-12 14:06 UTC, Ji-Hyeon212 commented on src/api/logInApi.ts
> +      alert('아이디 또는 비밀번호를 확인해주세요.');
넵! 알겠슴다

2023-07-12 14:08 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
> +  };
오오오,,,, 그런 문제가 있는 줄 몰랐네요... 한번씩 흰화면이 나올 때가 있었는 데 잘 뜨는 경우도 있어서 무시하고 넘어갔는데 안일한 생각이었던 것 같습니다🥲 수정해주셔서 감사하고 많이 알아갑니다!!!

2023-07-12 14:22 UTC, Ji-Hyeon212 commented on src/api/logInApi.ts
> +      navigate('/');
컴포넌트에서 로직을 빼려고 한 이유가 큽니다! 저도 로직을 어떻게, 얼마나 분리할 지는 잘 모르겠긴 하네요...ㅠㅎㅎ 하면서 판단 기준을 세워나가야 할 것 같습니당!!

2023-07-12 16:25 UTC, publdaze approved these changes
👍👍👍

2023-07-12 18:08 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-07-13 00:26 UTC, merged