Feature/직책관리 페이지 UI 구성 #447
KEEPER31337/Homepage-Front-R2 pull request #456
Opened 2023-07-15 23:10 UTC by llddang

## 연관 이슈
* #447

## 작업 요약
* 직책관리 페이지의 전체적인 UI 제작했습니다.

## 작업 상세 설명
* Button 와 Tooltip은 MUI 의 컴포넌트를 가져와서 사용했습니다.
* Selector은 공통 컴포넌트로 제작되어 있는 것을 사용했습니다.
* UI만 구성하였고, API 연결은 이후에 할 예정입니다.

## 리뷰 요구사항
* 예상 소요 시간 `5분`

## Preview 이미지
* 전체적인 모습
<img width="1552" alt="스크린샷 2023-07-15 오후 7 03 09" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/c97e010c-fe8c-49bb-9f18-db57660a7497">
* tooltip
<img width="1552" alt="스크린샷 2023-07-15 오후 7 03 12" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/9e209959-e06c-41cd-aff1-b16a731935dd">
* modal
<img width="1552" alt="스크린샷 2023-07-15 오후 7 03 17" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/19d06290-9f94-42df-9161-3778365f034d">

2023-07-16 07:35 UTC, jasper200207 approved these changes
수고하셨습니다

2023-07-16 07:35 UTC, jasper200207 commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +  const [modalOpen, toggleModalOpen] = useReducer((prev) => !prev, false);
useReducer로 상태관리가 가능한건 처음알았습니다!

2023-07-17 12:08 UTC, pipisebastian commented on src/mocks/DutyManageApi.ts
> +      '굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히
조금 무서워요

2023-07-17 20:36 UTC, llddang commented on src/mocks/DutyManageApi.ts
> +      '굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히 굉장히
우잉.. 무섭지 않은 긴 문자열 알려주세요!

2023-07-19 02:56 UTC, publdaze requested changes
디자인이 코드로 구현할 때 어렵지 않을까 걱정했는데 너무 잘해주셨네요! 👍
콘솔에 에러 많이 뜨는 것 같은데 한 번 확인 부탁드려요~! 😄

2023-07-19 03:07 UTC, publdaze requested changes

2023-07-19 03:07 UTC, publdaze commented on src/constants/category.ts
>        },
아 path의 경우는 소문자로 통일해주세요!

2023-07-19 18:09 UTC, llddang commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      <div>
toolTip 안에 한개의 컴포넌트만 들어갈 수 있다는 에러 문구를 봐서 div로 modal과 button 감싸주었습니다.
다시 확인해보겠습니다!

2023-07-19 18:38 UTC, llddang commented on src/pages/admin/DutyManage/DutyManage.tsx
> +              {' '}
넵 저기가 원을 만드는 부분인데요 그냥 `<div></div>`로 하니 에러가 떠서 안에 내용이 있어야 될 듯 하여 넣어줬습니다.
혹시 안에 내용이 없어도 되는 건가요?

2023-07-19 18:38 UTC, llddang commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      <div>
아하 `<></>`으로도 감싸줄 수 있네요!

2023-07-19 19:35 UTC, llddang commented on src/pages/admin/DutyManage/DutyManage.tsx
> +              {' '}
`<div />` 으로 처리하여 공백 없앴습니다!

2023-07-19 19:39 UTC, llddang commented on src/pages/admin/DutyManage/DutyManage.tsx
> +      </div>
아 저 `CreateViceChairman`이 부회장의 `DutyProfileButton`뿐만 아니라 회장과 부회장 사이에 있는 연결 bar까지 생성해주어서 이름을 `CreateViceChairman`이렇게 지었습니다.
혹시 지금도 문제가 있을까요?

2023-07-20 09:54 UTC, publdaze commented on src/pages/admin/DutyManage/DutyManage.tsx
> +              {' '}
굿굿굿 👍

2023-07-22 10:46 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      <div>
오호 MUI 툴팁 컴포넌트는 하나의 태그로 감싸져야 하는 그런게 있나보군요!

> 아 <></> 으로 감싸니까 tooltip이 안 뜹니다.
이유를 알게되면 적겠습니다!

오잉? 넹넹!

2023-07-25 02:53 UTC, publdaze commented on src/pages/admin/DutyManage/DutyManage.tsx
> +      </div>
음..! 네이밍 관련해서는 사실 뭐가 정답이라고 하기 애매해서 이렇게 리뷰드리는 게 맞는 지 잘 모르겠지만 😅
제가 컴포넌트 이름을 봤을 때 `CreateViceChairman`, `CreateMiddleBar` 먼저  Create라는 동사를 봤을 때 내부 동작으로 생성이라는 API 호출해서 생성이 이루어진다거나 하는 기능적인 부분을 가진 컴포넌트구나~! 하고 느껴지더라구요! 그리고 해당 컴포넌트 내부를 살펴보기 전에는 `MiddleBar`바는 별도의 컴포넌트로 만들어져 있는데 UI에 보이는 회장과 부회장 사이에 있는 연결 bar는 `CreateViceChairman`에 들어가 있다는 게 직관적이지 않은 것 같아요!
그래서 개인적인 바람으로는 회장-부회장 사이 연결바 등은 따로 `ConnectBar` 별도의 컴포넌트로 분리해주고, `CreateMiddleBar`등의 경우 그냥 '중앙에 있는 바'라고만 지칭해도 괜찮을 것 같아서 `MiddleBar` 정도로 네이밍 하면 어떨까합니다!
일단 제 개인적인 생각이다보니 다은님이 생각하시기에 반영할 필요성을 못느끼거나 다음 작업이 급하다면 그대로 진행해주시면 됩니다!!

2023-07-25 03:05 UTC, publdaze requested changes
develop 풀 한 번 받아주세요~!
material-tailwind 라이브러리 삭제 및 리액트 버전 다운그레이드 한 것등 반영이 안 되어 있네요!

2023-07-25 03:11 UTC, publdaze reviewed
<img width="1099" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/5b65e964-95c0-4379-bb36-9edbc518658b">

`DutyProfileButton` content에 따라 너비가 변하는 것 같은데 위의 이미지 보시면 전산 관리자와 다른 관리자들 width가 다르게 잡혀서 어색해보이는 것 같아요! width 아에 고정해두는 방향으로 처리하는 건 어떤가요?

2023-07-25 03:44 UTC, publdaze commented
인프라 담당자 추가되고, 전산 관리자도 각각의 버튼으로 구성 되게 되어 구조가 변경될 부분이 좀 보여서 일단 close하고 전산 관리자 부분까지 작업 후 다시 PR 올려주는 걸로 얘기되었습니다!

2023-07-25 03:44 UTC, closed without merging