Feature/게시글 설정 및 업로드 모달 기능 #469
KEEPER31337/Homepage-Front-R2 pull request #470
Opened 2023-07-22 09:49 UTC by publdaze

## 연관 이슈
- Close #469

## 작업 요약
- 게시글 작성 페이지 설정 및 업로드 모달 체크 박스 이벤트 핸들러로 처리해주었습니다.

## 작업 상세 설명
- 게시글 생성 api 호출은 상위 컴포넌트에서 처리할 거라 props로 `postSettingInfo`, `setPostSettingInfo` 받아와서 처리해주었습니다.
- `postSettingInfo` 타입 `null`도 가능하도록 해주었는데 api에서 null로 보내주면 default 값으로 설정해줘서 따로 체크박스 건드리지 않으면 `null` 상태로 보내도 괜찮을 테니 이렇게 처리해주었습니다.
- 각 체크박스는 하나의 핸들러로 다룰 수 있도록 해주었습니다.

## 리뷰 요구사항
- 예상 소요 시간 `3분`

2023-07-22 10:29 UTC, jasper200207 requested changes

2023-07-22 10:29 UTC, jasper200207 commented on src/pages/BoardWrite/Modal/SettingUploadModal.tsx
> +    });
체크박스가 2개 이상이라 확실하게 값을 불러오기 위해서
`setPostSettingInfo((prev) => ({...prev, [name]: checked});`
로 사용하면 좋을 듯 합니다!

2023-07-22 10:29 UTC, jasper200207 commented on src/pages/BoardWrite/Modal/SettingUploadModal.tsx
> +  setPostSettingInfo: React.Dispatch<React.SetStateAction<UploadPostSettings | null>>;
useState를 분리할때는 저런 타입을 사용하는 군요

2023-07-22 12:17 UTC, publdaze commented on src/pages/BoardWrite/Modal/SettingUploadModal.tsx
> +    });
허걱 그부분을 놓쳤네요! 감사합니다! 👍👍

2023-07-22 12:48 UTC, publdaze commented on src/pages/BoardWrite/Modal/SettingUploadModal.tsx
> +    });
반영했습니다!

2023-07-22 15:36 UTC, publdaze commented on src/api/dto.ts
> +  categoryId: string;
엇 이 타입 `number`여야 하는데 `string`으로 지정했었네요! 지금 API 연결 작업 진행 중이라 이 PR에서는 일단 이대로 올리고 🥲 API 연결한 PR에 수정해서 올리도록 하겠습니닷!!

2023-07-22 17:00 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-07-24 05:10 UTC, pipisebastian approved these changes

2023-07-24 12:03 UTC, merged