Feature/직책관리 페이지 UI 구성 #447
KEEPER31337/Homepage-Front-R2 pull request #480
Opened 2023-07-25 05:07 UTC by llddang

## 연관 이슈
* #447 

## 작업 요약
* 직책관리 페이지의 UI 제작했습니다.

## 작업 상세 설명
* Button 와 Tooltip은 MUI 의 컴포넌트를 가져와서 사용했습니다.
* Selector은 공통 컴포넌트로 제작되어 있는 것을 사용했습니다.
* UI만 구성하였고, API 연결은 이후에 할 예정입니다.

## 리뷰 요구사항
* 예상 소요 시간 `10분`

## Preview 이미지
* 기본 화면일때 UI가 화면 안에 다 담기지 않아 화면 크기 80%로 스크린 찍었습니다.
<img width="1552" alt="스크린샷 2023-07-25 오전 12 57 32" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/fd9ce741-2d97-4613-8d19-66785bbda0ca">
<img width="1552" alt="스크린샷 2023-07-25 오전 12 57 49" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/045073f7-a60d-447b-a4ce-efe1a758650e">
<img width="501" alt="스크린샷 2023-07-25 오전 12 57 53" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/77055208/b92df24a-0577-4b36-b147-d0ee59448096">

2023-08-03 15:16 UTC, publdaze requested changes

2023-08-04 06:31 UTC, llddang commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      disabled={roleName === '전산관리자'}
전산관리자는 UI를 봤을 때, 직책이름만 나타나있고 다른 역할이 없어서입니다.
또한 전산관리자 직책을 변경할 때에도 하위 직책인 FRONT, BACK, INFRA의 버튼을 눌러서 변경하기 때문에 'disable' 로 처리했습니나.

2023-08-04 06:32 UTC, llddang commented on src/pages/admin/DutyManage/DutyManage.tsx
> +      <div className="absolute bottom-[14.5px] right-[8.8%] h-0 w-[83%] border-2 border-pointBlue"> </div>
앗 다 변경했다고 생각했는데 아직 남아있네요! 고치겠습니다!

2023-08-04 06:37 UTC, llddang commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +  setTooltipOpen: (arg0: boolean) => void;
아하 변수명을 변경할 수 있었군요! 첫번째 인수이면 arg0로 나타내야하는 줄 알았습니다!

2023-08-04 06:40 UTC, llddang commented on src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
> +  };
아앗 Selector 사용 예시 알기 위해서 다른 사람 코드를 봤더니.. 이런 일이 ㄷㄷ 좀더 신경쓰겠습니다!

2023-08-04 06:44 UTC, llddang commented on src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
> +      </div>
삭제되어야 하는 부분이 남아있어서 혼란을 드린 것 같습니다.
저 부분은 UI 변경되지 전에, 전산관리자 직책을 바꿀때에는 전산관리자 버튼을 눌렀을때 FRONT, BACK 둘다 변경할 수 있었지만 이제는 FRONT, BACK, INFRA들이 하위 컴포넌트로 생성되면서 필요없는 부분이 되었습니다.
삭제하겠습니다!

2023-08-05 07:12 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      disabled={roleName === '전산관리자'}
음..! 아직 이해가 잘 안 돼서...! 😅 추가 질문드립니다! 전산 관리자의 경우 직책 이름만 나타나있고 다른 역할이 없다고 하셨는데, 혹시 다른 직책들은 어떤 역할을 가지고 있는 건가요? 🧐

2023-08-05 07:26 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      disabled={roleName === '전산관리자'}
아 UI에서 아래 이미지 빨간 박스 부분에 대한 처리인가요?

<img width="387" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/92906140-c10f-46ea-9360-6fda6a1348ab">

다른 직책들은 바로 클릭 이벤트로 모달을 띄워주는데, 각 직책관리자의 모달 띄워주는 부분은 해당 라인이 아닌 한단계 아래에서 처리가 되니, 같은 계층에서 전산관리자 텍스트를 가진 UI가 보이도록 동일한 버튼으로 구성하되, 클릭은 처리 안 되도록 해주려고 했던 의도가 맞을까요? 🤔

2023-08-05 08:23 UTC, publdaze requested changes
develop에 라우터, 사이드바 관련해서 변경 사항이 있어 충돌 나는 것 같은데 한 번 pull 받아주세요~!

2023-08-05 21:34 UTC, llddang commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      disabled={roleName === '전산관리자'}
넵 맞습니다!

2023-08-05 21:58 UTC, llddang commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  }
질문이 잘 이해가 안 되어서 그런데요.
질문 내용이 0번 인덱스인 것을 어떻게 알았냐 일까요? 아니면 다른게 가져올 수 있는 방식이 있을 텐데 왜 저렇게 가져왔냐 일까요?
전자 의도의 질문이라면, 그것은 roles가 배열이고, filter을 거쳤을 때 name과 동일한 객체 한개만 남아서 0번 인덱스를 가져왔습니다.
후자라면 코드를 저렇게 쓰는 방법 외에 아직 다르게 가져오는 방법을 몰라서 저렇게 썼습니다!
혹시 예쁜 코드아시면 알려주십쇼!

2023-08-05 23:12 UTC, llddang commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +            </ListItem>
넵!
`LisItemIcon` 대신 `Typography`의 `sx`에 속성 추가해주는 방식으로 바꾸었습니다.
`ListItem`의 속성에 넣었더니 `marker`와 글의 수평선이 맞지 않아서 `Typography`의 속성으로 넣었습니다.

2023-08-06 14:10 UTC, pipisebastian approved these changes
수고하셧씁니다!

2023-08-06 14:10 UTC, pipisebastian commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  }
혹시 find로 뽑아오는건 어떨까요??
`roles.find(role => role.name === '전산관리자').img`

몰랐는데 filter랑 find차이가
find() 는 조건에 부합하는 배열의 첫번째 값만을 리턴하고, filter() 함수는 조건에 부합하는 배열의 모든 값을 **배열 형태**로 리턴한다고 합니다! 

깊게 생각해보지 못했었는데 알아갑니다!

2023-08-08 00:39 UTC, publdaze requested changes

2023-08-08 00:51 UTC, publdaze requested changes

2023-08-08 00:51 UTC, publdaze commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  );
이 부분이 DutyProfileToolTip 컴포넌트 내부에 존재하고 있는데 이렇게 되면 렌더링 될때마다 메모리에 재선언이 발생하기 때문에 바깥으로 빼주고 변수를 받아오거나 별도의 컴포넌트로 만들어 호출하는 방식이 좋다고 해요! 그래서 `DutyProfileToolTip` 컴포넌트 내부가 아닌 분리해주면 어떨까 제안드립니다!

2023-08-08 00:57 UTC, publdaze commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  }
`filter`를 사용하였을 때 배열에 여러 값들이 들어갈 수 있는데 그중 0번째 값을 선택한 이유가 무엇인지 궁금했습니다!
`name`과 동일한 객체 한개인 경우에 대한 처리라면 저도 서윤님이 제안해주신 것처럼 `find` 사용하는 거 좋아보입니다!

2023-08-08 01:21 UTC, publdaze requested changes

2023-08-08 01:21 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +};
```suggestion
return (
    <div>
      {roleName === '전산관리자' ? (
        <>
          <Typography variant="h3" sx={{ fontWeight: 600, color: 'white' }}>
            {roleName}
          </Typography>
          <div className="mx-auto mt-2 h-[160px] w-[5px] bg-gradient-to-b from-pointBlue from-50% to-subBlack to-0% bg-[length:5px_20px] bg-repeat-space" />
        </>
      ) : (
        <Button
          onClick={handleRoleProfileCreateButtonClick}
          sx={{
            width: '120px',
            display: 'flex',
            flexFlow: 'column',
            gap: '4px',
            padding: '12px 0px 4px 0px',
            '&:hover': {
              backgroundColor: muiTheme.palette.secondary.main,
            },
          }}
        >
          <Typography variant="h3" sx={{ fontWeight: 600, color: 'white' }}>
            {roleName}
          </Typography>
          <img className="h-[100px] w-[100px]" alt={roleName} src={badgeImage} />
          <div className="flex h-12 flex-col justify-center">
            <ProfileName roleName={roleName} />
          </div>
        </Button>
      )}
    </div>
  );
```

전산관리자는 버튼 대신 텍스트를 보여줘야 하기 위한 처리였으면 조건부를 좀 더 상위로 올리면 어떨까요? 이부분이 버튼으로써의 역할을 가진다고 보기는 어려울 것 같아서 버튼이지만 disabled된 버튼이라고 처리하는 게 어색해보여서요! 위에 제안드린 방식으로 전산관리자에 대한 처리와 다른 직책에 대한 버튼 처리로 조건부를 나누면 어떨까 제안드립니다!

2023-08-08 01:22 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      disabled={roleName === '전산관리자'}
[추가 코멘트](https://github.com/KEEPER31337/Homepage-Front-R2/pull/480#discussion_r1286506250)로 새로 코드 잡아서 리뷰 남겨두었습니다!

2023-08-08 01:45 UTC, llddang commented on src/pages/admin/DutyManage/DutyManage.tsx
> +        <CreateMiddleBar />
아하 알겠습니다!
오호 맞네요 API 호출한다고 생각할 수도 있겠군요!

2023-08-08 01:58 UTC, llddang commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  );
오호 이런 이슈도 있군요. 처음 생각하게 되었습니다!

2023-08-08 02:51 UTC, llddang commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  );
이 코멘트 보고 react는 언제 re-render되는 건지 궁금해서 찾아봤는데요.
[react-renders-your-components](https://react.dev/learn/render-and-commit#step-2-react-renders-your-components)
위의 문서를 읽어보면 부모 컴포넌트가 re-render 되면 자식 컴포넌트도 re-render 된다고 나와있습니다.
그래서 더 찾아보니 [필요 없는 렌더링 줄이기](https://pks2974.medium.com/react-%EC%9D%98-%EC%84%B1%EB%8A%A5%EC%9D%84-%EC%A1%B0%EA%B8%88-%EC%9D%B4%EB%9D%BC%EB%8F%84-%EC%98%AC%EB%A0%A4%EB%B3%B4%EC%9E%90-performance-optimize-f1a51b8c406c)의 블로그에 나와있는 것 처럼 shouldComponentUpdate를 사용하면 부모 컴포넌트가 렌더링 되어도 자식 컴포넌트의 props가 동일하다면 렌더링 되지 않는다는 것을 알게되었습니다.
하지만 저희 코드를 살펴보니 shouldComponentUpdate를 사용하는 컴포넌트는 없었습니다.
이 경우 위의 내용을 별도의 컴포넌트로 만들어도 부모 컴포넌트가 렌더링 되면 그 아래있는 자식 컴포넌트도 렌더링 될 것이라 생각되어 별도로 분리하는 것에 의미가 있는지 모르겠습니다.
혹시 제가 잘못알고 있는 부분이 있다면 고쳐주세요.

2023-08-08 12:45 UTC, lcqff approved these changes
파란 선 만드는데 고생하셨을거같읍니다,,, 코드 넘 잘쓰셨어요 짱!

2023-08-08 14:38 UTC, publdaze commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  );
`roleName !== '전산관리자'`라는 조건문이 없었다면 다은님 말씀하신 대로 부모 컴포넌트가 리렌더링 될 시에 자식 컴포넌트도 리렌더링 되니 동일한 구성이라면 분리하거나 하지 않거나 렌더링 관점에서 차이는 미미할 것 같아요!

하지만 지금 짜여진 코드에서는 `roleName !== '전산관리자'`로 조건에 따라 호출하고 있기 때문에 차이가 발생할 수 있다고 볼 수 있습니다.

`DutyProfileTooltip` 컴포넌트 내부에 `tooltipContent`가 선언되어 있을 경우,
`roleName !== '전산관리자'`의 조건과 상관없이 `DutyProfileTooltip`이 리렌더링될 때마다 `tooltipContent` 전체 콘텐츠가 새롭게 생성됩니다.

하지만 `DutyProfileTooltip` 컴포넌트 외부로 분리할 경우, 
`DutyProfileTooltip` 컴포넌트의 모든 렌더링에 실행되는 게 아닌 툴팁을 표시해야 할 때만 `tooltipContent`가 호출되니 불필요한 렌더링을 줄일 수 있을 것 같아요

여기서 더 나아가 `useMemo`를 사용한다면 좀 더 최적화할 수 있을 것 같습니다.  `roleName`에 대한 `tooltipContent`가 여러 번 렌더링될 때 이전 결과를 재사용할 수 있기 때문에 메모이제이션을 통해 렌더링 성능을 최적화하는 데 도움이 되지 않을까 싶네요 😆

저도 어떻게 차이가 있을 지 궁금해서 코드로 console에 찍어가며 비교해봤는데 글로 읽는 것 보다 한 번 실행시켜보면 차이를 비교하기 더 좋을 것 같아서 코드 공유드립니다!

`tooltipContent` 호출하던 부분에 `tooltipContent1`(= `tooltipContent`), `tooltipContent2`(외부로 분리), `tooltipContent3`(useMemo 사용) 넣어보며 비교해보시면 될 것 같아요! `tooltipContent1`과 `tooltipContent2` 간의 차이는 아래 이미지 전산관리자 텍스트에 마우스 hover 해보면 차이 확실히 확인하실 수 있을 거에요!

<img width="191" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/0d01e5f7-f3f7-405a-bd6f-4ab327d15f64">


```tsx
import React, { useState, useReducer, useMemo } from 'react';
import { Typography } from '@mui/material';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import { roleDutyListInfo, roles } from '@mocks/DutyManageApi';
import muiTheme from '@constants/muiTheme';

import DescriptionRoleDutyTooltip from './DescriptionRoleDutyTooltip';
import DutyProfileButton from '../Button/DutyProfileButton';
import ChangeRolePersonModal from '../Modal/ChangeRolePersonModal';

interface DutyProfileTooltipProps {
  roleName: string;
}

const tooltipContent2 = (roleName: any) => {
  return (
    <List sx={{ pl: '20px', pr: '8px', py: '2px' }}>
      {console.log('tooltipContent2')}
      {roleDutyListInfo
        .filter((duty) => duty.roleName === roleName)
        .map((data) =>
          data.roleDuty.map((duty) => (
            <ListItem key={duty.key} sx={{ px: '0px', py: '0px' }}>
              {/* fontWeight: 600 = semi-bold */}
              <Typography
                sx={{
                  fontWeight: 600,
                  color: 'white',
                  alignItems: 'start',
                  listStyleType: 'circle',
                  display: 'list-item',
                  '&::marker': {
                    color: muiTheme.palette.primary.main,
                    fontSize: '20px',
                  },
                }}
              >
                {duty.content}
              </Typography>
            </ListItem>
          )),
        )}
    </List>
  );
};

const tooltipContent3 = (roleName: any) =>
  useMemo(
    () => (
      <List sx={{ pl: '20px', pr: '8px', py: '2px' }}>
        {console.log('tooltipContent3')}
        {roleDutyListInfo
          .filter((duty) => duty.roleName === roleName)
          .map((data) =>
            data.roleDuty.map((duty) => (
              <ListItem key={duty.key} sx={{ px: '0px', py: '0px' }}>
                {/* fontWeight: 600 = semi-bold */}
                <Typography
                  sx={{
                    fontWeight: 600,
                    color: 'white',
                    alignItems: 'start',
                    listStyleType: 'circle',
                    display: 'list-item',
                    '&::marker': {
                      color: muiTheme.palette.primary.main,
                      fontSize: '20px',
                    },
                  }}
                >
                  {duty.content}
                </Typography>
              </ListItem>
            )),
          )}
      </List>
    ),
    [roleName],
  );

const DutyProfileTooltip = ({ roleName }: DutyProfileTooltipProps) => {
  const [tooltipOpen, setTooltipOpen] = useState(false);
  const [modalOpen, toggleModalOpen] = useReducer((prev) => !prev, false);

  let badgeImage;
  if (roleName === 'FRONT' || roleName === 'BACK' || roleName === 'INFRA') {
    badgeImage = roles.filter((role) => role.name === '전산관리자')[0].img;
  } else {
    badgeImage = roles.filter((role) => role.name === roleName)[0].img;
  }
  const modalInfo = { name: roleName, badge: badgeImage };

  /* button hover 했을 시 나오는 문장 */
  const tooltipContent1 = (
    <List sx={{ pl: '20px', pr: '8px', py: '2px' }}>
      {console.log('tooltipContent1')}
      {roleDutyListInfo
        .filter((duty) => duty.roleName === roleName)
        .map((data) =>
          data.roleDuty.map((duty) => (
            <ListItem key={duty.key} sx={{ px: '0px', py: '0px' }}>
              {/* fontWeight: 600 = semi-bold */}
              <Typography
                sx={{
                  fontWeight: 600,
                  color: 'white',
                  alignItems: 'start',
                  listStyleType: 'circle',
                  display: 'list-item',
                  '&::marker': {
                    color: muiTheme.palette.primary.main,
                    fontSize: '20px',
                  },
                }}
              >
                {duty.content}
              </Typography>
            </ListItem>
          )),
        )}
    </List>
  );

  return (
    <DescriptionRoleDutyTooltip
      title={roleName !== '전산관리자' ? tooltipContent3(roleName) : null}
      open={tooltipOpen}
      onMouseEnter={() => setTooltipOpen(true)}
      onMouseLeave={() => setTooltipOpen(false)}
      arrow
    >
      <div>
        <DutyProfileButton
          roleName={roleName}
          badgeImage={badgeImage}
          setTooltipOpen={setTooltipOpen}
          toggleModalOpen={toggleModalOpen}
        />
        <ChangeRolePersonModal open={modalOpen} toggleOpen={toggleModalOpen} modalInfo={modalInfo} />
      </div>
    </DescriptionRoleDutyTooltip>
  );
};

export default DutyProfileTooltip;

```

2023-08-08 14:46 UTC, publdaze requested changes

2023-08-08 14:46 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +
오호! 제가 3항연산자 사용하는 식으로 코멘트 남겼던 것 같은데 이렇게 if문으로 걸러주는 방식이 더 깔끔해보이고 좋은 것 같네요! 👍👍

2023-08-08 14:46 UTC, publdaze commented on src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
> +      onClick={handleRoleProfileCreateButtonClick}
`ItBar` 부분도 네이밍 변경 잘 해주셨네요! 👍
`handleRoleProfileCreateButtonClick` 핸들러 부분에도 `직책 프로필을 생성 버튼`으로 생성의 의미가 들어가 모호하지 않을까 하여 한 번 변경 요청 드려봅니다 ㅎㅎ

2023-08-08 15:50 UTC, llddang commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +  );
우왕 섬세한 답변 감사합니다!
비교 가능한 예시군까지 너무 감동입니다!!
바로 실행시켜보겠습니다!

2023-08-09 01:24 UTC, publdaze approved these changes
👍👍 수고하셨어요~!

2023-08-09 02:32 UTC, merged