Feature/아이디,비밀번호 찾기 페이지_#351
KEEPER31337/Homepage-Front-R2 pull request #488
Opened 2023-07-31 13:25 UTC by Ji-Hyeon212

## 연관 이슈
#351, #420, #421

## 작업 요약
>아이디, 비밀번호 찾기 페이지 ui 완료 및 기능 일부 구현 상태 입니다.

## 작업 상세 설명
> 탭 내에서 아이디, 비밀번호 찾기 선택 가능하고 각 탭 마다 여러 단계로 이어지도록 구현되었습니다.
아이디 찾기는 완료되었고 비밀번호 찾기는 2단계 새 비밀번호 설정하는 부분 전까지 구현되었습니다.

## 리뷰 요구사항
> 10분?

## Preview 이미지

2023-07-31 15:49 UTC, pipisebastian approved these changes
수고하셧습니댜~~

2023-07-31 15:49 UTC, pipisebastian commented on src/pages/login/Search/SearchID.tsx
> +  const [isValidEmail, setIsValidEmail] = useState<boolean>(false);
이 부분 `<boolean>`으로 type지정해준거 밑에는 안해줬던데 통일하는거 어떨까욤??

2023-08-03 15:50 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchID.tsx
> +  const [isValidEmail, setIsValidEmail] = useState<boolean>(false);
오 좋습니다! 초기값이 설정되어있으니까 타입 명시는 따로 안하는 걸로 수정했습니다

2023-08-05 07:03 UTC, publdaze requested changes
eslint 워닝 뜨는 거 Files Changed 보고 한 번 체크 부탁드려요!

2023-08-05 07:03 UTC, publdaze commented on src/pages/login/Search/SearchID.tsx
비밀번호 페이지를 보면 각 단계별로 컴포넌트 나눠두신 것 같은데 아이디도 컴포넌트 분리해주면 깔끔할 것 같네요 😄
급한 건 아니니 다른 급한 것 부터 처리하고 이후 작업으로 한 번 고려해보면 어떨까합니다!

2023-08-06 23:47 UTC, Ji-Hyeon212 commented on src/pages/login/Login.tsx
>                <p className="hover:underline hover:duration-300">아이디·비밀번호 찾기</p>
hover시 밑줄을 남길 때 애니메이션 동작이 부드럽게 이어지도록 하고자 넣었습니다.

2023-08-06 23:54 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchPW.tsx
> +    2: <SearchPWSecondStep setCurrentStep={setCurrentStep} firstForm={form} />,
두번째 단계에서 api 호출할 때 첫번째 단계에서 썼던 id랑 email이 필요해서 props로 넘겨주는 데, 아직 관련 부분 작업을 안해서 그렇습니다. 나중에 작업할 때 반영할게요!

2023-08-12 07:46 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchID.tsx
> +  };
id찾기 UI 상에서 다른 단계로 이동하기 위한 플래그라고 보시면 됩니다! 말씀하신대로 isSuccess인 경우 true로 변경하도록 수정했습니다~

2023-08-19 13:19 UTC, publdaze requested changes
eslint 워닝 발생하는 곳 많은 것 같아요! 확인 부탁드립니다!

2023-08-19 13:19 UTC, publdaze commented on src/pages/login/Search/SearchPWFirstStep.tsx
> +  };
여기서 try catch 문 사용한 게 `requestAuthcode`를 통해 api 호출 시 에러가 발생하면 catch 문으로 들어가 잡으려 했던 의도가 맞을까요? 지금 인증 요청 했을 때 API 호출 시 에러가 발생함에도 catch 문으로 안 넘어가는데 왜 그런 지 한 번 찾아보면 좋을 것 같아요!

그리고 reactQuery에서 `onSuccess`, `onError`를 사용해 callBack으로 처리도 가능하니 이것들 활용해보는 걸 추천드려요!

2023-08-19 13:19 UTC, publdaze commented on src/pages/login/Search/SearchPWFirstStep.tsx
> +  };
여기도 마찬가지로 error 안 잡힙니다!

2023-08-20 16:55 UTC, pipisebastian commented on src/api/SearchAccountApi.ts
> +    password: string;
얘네는 따로 dto에 타입정의해놓은게 없을까용?? 있으면 좀 더 깔끔해질 것 같은데, 만드는게 더 코드복잡해지면 넘어가구요!

2023-08-20 16:58 UTC, pipisebastian commented on src/pages/login/Search/SearchID.tsx
> +    if (isError) {
이 부분 isSuccess돌면 isError조건문은 안들어가도 되지 않을까요?? if if보다는 if else if로 하는거 어떤가용?? 왕 사소하긴 하지만..

2023-08-20 17:03 UTC, pipisebastian approved these changes
수고하셨씁니당@! 코멘트들이 너무 사소해서 어프로브합니당~

2023-08-27 10:19 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchID.tsx
> +    if (isError) {
try catch로 변경하였습니다!

2023-08-27 10:24 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchID.tsx
> +              <p className="text-20 font-bold text-pointBlue">{email}</p>
오~ 그렇네요 마진이나 패딩처럼 단순 숫자 표현이 표현이 안되는 군요... 수정했습니다!

2023-08-27 10:26 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchPWFirstStep.tsx
> +              </FilledButton>
그죠...? 인풋이랑 겹쳐서 이상하긴 했는데 일단 small로 해두겠습니다!!

2023-08-27 12:05 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchPWFirstStep.tsx
> +  };
서버에서 에러 처리를 해서 message를 보내주기 때문에 프론트 쪽에서는 에러로 안잡히고 있었네요! 말씀해주신대로 callBack으로 처리해주었습니다.

2023-08-27 12:25 UTC, publdaze requested changes

2023-08-27 12:25 UTC, publdaze commented on src/pages/login/Search/SearchID.tsx
>    };
여기 callback 사용하면 async, await 없어도 되지 않나요?~? 필요성을 잘 모르겠어서 어떤 의도인지 궁금합니다! 👀

2023-08-27 12:25 UTC, publdaze commented on src/pages/login/Search/SearchPWFirstStep.tsx
> +              </FilledButton>
`small` 넣어주셨다가 마지막 커밋에서 다시 사라진 것 같은데 한 번 확인 부탁드려요!

2023-08-27 12:25 UTC, publdaze commented on src/pages/login/Search/SearchPWSecondStep.tsx
> +            )}{' '}
`{' '}` 이부분 잘못 prettier 적용되면서 잘못들어간 것 같습니다! 제거해주세요~!

2023-08-27 13:08 UTC, Ji-Hyeon212 commented on src/pages/login/Search/SearchID.tsx
>    };
맞습니다...! 제거했습니다.

2023-08-27 13:34 UTC, Ji-Hyeon212 commented on src/api/SearchAccountApi.ts
> +};
없습니다...! useQuery로 변경했습니다!

2023-08-27 14:03 UTC, publdaze requested changes

2023-08-27 14:03 UTC, publdaze commented on src/api/SearchAccountApi.ts
> +  return useQuery('checkAuthCode', fetcher);
querykey 관련해서 슬랙 보내놨는데 한 번 확인 부탁드려용~!

2023-08-27 14:03 UTC, publdaze commented on src/pages/login/Search/SearchID.tsx
> +  };
여기도 async, await 없어도 될 것 같습니다!

2023-08-28 14:34 UTC, publdaze approved these changes
굿굿 수고 많으셨습니다!

2023-08-30 00:20 UTC, merged