Feature/세미나 출석 세미나 시작, 출석 api 연동 #416
KEEPER31337/Homepage-Front-R2 pull request #489
Opened 2023-07-31 13:42 UTC by lcqff

## 연관 이슈

## 작업 요약
세미나 출석 페이지의 세미나 시작과 세미나 출석 api를 연동했습니다. 

## 작업 상세 설명
현재 이전,최신,이후 세미나를 가져오는 api를 적용하지 않은 상태로 임시로 7월 2일자의 세미나를 들고옵니다.
세미나 시작했을때 회장 페이지에서 바로 세미나 시작 UI로 넘어가지 않는 버그를 아직 못고쳤습니다ㅠㅠ(새로고침하면 보임)

## 리뷰 요구사항

## Preview 이미지

2023-08-09 12:12 UTC, publdaze commented
위에 테이블 공통 컴포넌트 제작에 멘션 달린 거 무시해주셔도 됩니다! 498 PR 멘션 달아야하는데 489 PR(이 PR) 멘션 실수로 달아버렸어용 ㅎㅎ

2023-08-14 01:37 UTC, publdaze commented
회장 시작 눌렀을 때 바로 카운트다운 보이지 않고 마감으로 뜨더라구요! 새로 고침해야 카운트다운 보이네욤!
<img width="100" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/95fafeec-a960-4947-a778-faa8891a29c7">

중간 세미나 날짜도 처음 뜰 때 바로 안 보이네요. API 호출하고 받아오는데 딜레이가 걸리는 건지 잘모르겠지만 개선이 필요할지도...?! 🤔

2023-08-14 04:20 UTC, publdaze requested changes

2023-08-14 04:20 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const isValidActivityStatus = (value: string): value is ActivityStatus => {
오호 typeScript에 `is` 라는 키워드가 있는 건 처음 알았네요! 👍👍
여기서 `(value: ActivityStatus)` 이렇게도 가능할 것 같은데 `(value: string): value is ActivityStatus` 요렇게 처리해준 이유가 궁금합니다!

2023-08-14 04:20 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +import React, { useEffect } from 'react';
`useEffect` 사용 안 되고 있는 것 같아요!

2023-08-14 04:20 UTC, publdaze commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +      }),
```suggestion
      copyInputCode.map(Number)
```

이렇게 간단하게 작성도 가능할 것 같아요!

2023-08-19 08:12 UTC, pipisebastian approved these changes
헉 3주나 지났었군요... 수고하셨습니다...!

2023-08-20 02:37 UTC, lcqff commented
> 

이거는 아마 이미 마감이 끝난 세미나를 계속 다시 재사용해서?? 그런거라고 예상하고 있습니다! 한 번 새 새 세미나 하나 만들어달라고 요청해보고 처음 출석 시작한 세미나도 그런지 확인해볼게요!

2023-08-20 02:38 UTC, lcqff commented
> 회장 시작 눌렀을 때 바로 카운트다운 보이지 않고 마감으로 뜨더라구요! 새로 고침해야 카운트다운 보이네욤! <img alt="image" width="100" src="https://user-images.githubusercontent.com/78250089/260338041-95fafeec-a960-4947-a778-faa8891a29c7.png">
> 
> 중간 세미나 날짜도 처음 뜰 때 바로 안 보이네요. API 호출하고 받아오는데 딜레이가 걸리는 건지 잘모르겠지만 개선이 필요할지도...?! 🤔

이거는 아마 이미 마감이 끝난 세미나를 계속 다시 재사용해서?? 그런거라고 예상하고 있습니다! 한 번 새 새 세미나 하나 만들어달라고 요청해보고 처음 출석 시작한 세미나도 그런지 확인해볼게요!

2023-08-20 02:45 UTC, lcqff commented on src/api/seminarApi.ts
아놔ㅠ api명 원래 이렇게 돼있었는데 까먹고 이거 뭐지? 하면서 수정해버렸습니다ㅎㅎ... ; 고쳐놓을게욥~

2023-08-20 03:21 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +                endTime={DateTime.fromISO(seminarData.attendanceCloseTime)}
Countdown에서 받는 인자 타입이 DateTime이라 바꿔주었습니다~! string으로는 시간차를 구하기가 어려워서욥

2023-08-20 03:26 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const { mutate: attend, isSuccess, error, data: attendancyData } = attendSeminar(5);
헤헤 진짜 없는단어네용;;ㅎㅎ^//^

2023-08-20 03:57 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const isValidActivityStatus = (value: string): value is ActivityStatus => {
이것저것 하다가 꼬여버린거 같네요😵‍💫 처음에는 ActivityStatus이 아닌 문자열도 매개변수로 사용될 수 있다고 생각한모양입니답,,, 수정해두겠습니다!

2023-08-20 03:59 UTC, lcqff commented on src/pages/senimarAttend/Input/SeminarInput.tsx
> +      }),
우왕 넘신기하네요~~~

2023-08-21 04:56 UTC, publdaze requested changes

2023-08-21 04:56 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +  }, [isSuccess]);
요거 코멘트 한 번 봐주세용~! (사실 react query라는 라이브러리 채택한 이유에 `invalidateQueries`를 사용할 수 있다는 장점을 크게 보고 선정한 거라 개인적으로 `invalidateQueries` 적극 추천 드립니당!)

2023-08-21 04:56 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +                endTime={DateTime.fromISO(seminarData.attendanceCloseTime)}
아하 ~Time으로 끝나는 API 응답으로 오는 시간들 다 변환 과정이 필요한 것 같은데 api 호출하는 부분에서 응답을 처음부터 변형하여 내려주는 건 어떤까요? 응답 변형해서 내리면 컴포넌트 내에서 사용하는 부분은 깔끔하게 처리 가능할 것 같아서요!

예를 들어 feacher 부분을 아래와 같이 작성할 수 있을 것 같아요!
```tsx
  const fetcher = () =>
    axios.get(`/seminars/${id}`).then(({ data }) => {
      const transformedData = {
        ...data,
        openTime: DateTime.fromISO(data.openTime),
        attendanceCloseTime: DateTime.fromISO(data.attendanceCloseTime),
        latenessCloseTime: DateTime.fromISO(data.latenessCloseTime),
      };
      return transformedData;
    });
```

2023-08-23 01:06 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +  }, [isSuccess]);
핫 이거 빠뜨리고 반영을 안했네요ㅋㅋㅋㅋㅋ api 업데이트 때문에 골머리였는데 이런 방법이 있었다니 넘 조습니다~~~!!!!

2023-08-23 02:50 UTC, lcqff commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +                endTime={DateTime.fromISO(seminarData.attendanceCloseTime)}
헉~~~ 너무 좋습니다~~~~

2023-08-23 03:01 UTC, lcqff commented
> > 회장 시작 눌렀을 때 바로 카운트다운 보이지 않고 마감으로 뜨더라구요! 새로 고침해야 카운트다운 보이네욤! <img alt="image" width="100" src="https://user-images.githubusercontent.com/78250089/260338041-95fafeec-a960-4947-a778-faa8891a29c7.png">
> > 중간 세미나 날짜도 처음 뜰 때 바로 안 보이네요. API 호출하고 받아오는데 딜레이가 걸리는 건지 잘모르겠지만 개선이 필요할지도...?! 🤔
> 
> 이거는 아마 이미 마감이 끝난 세미나를 계속 다시 재사용해서?? 그런거라고 예상하고 있습니다! 한 번 새 새 세미나 하나 만들어달라고 요청해보고 처음 출석 시작한 세미나도 그런지 확인해볼게요!

요거 세미나 6,7 새로 만들어주셔서 확인하려 했는데 사용 가능한 세미나 조회 api에서 서버문제라는 response가 와서,, 문의 넣어둔 상태입니답 해결되면 다시 확인해볼게욥

2023-08-23 03:02 UTC, lcqff commented
실수로 서윤님한테 리퀘스트 넣어버렷는데 신경쓰지마세용...!!!!!

2023-08-23 10:48 UTC, publdaze requested changes

2023-08-23 10:48 UTC, publdaze commented on src/pages/senimarAttend/Card/BossCardContent.tsx
> +  }, [isSuccess]);
요거 `invalidateQueries` 반영해주시면서 이부분 코드는 제거해도 잘 동작할 것 같아요!

2023-08-23 10:48 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
>  import { DateTime } from 'luxon';
`DateTime` 이제 사용 안 되는 것 같은데 제거 부탁해요~!

2023-08-23 10:50 UTC, publdaze commented
위에 코멘트 해결된 것 같은 건 `Resolve conversation` 해두었습니다!

2023-08-24 14:34 UTC, pipisebastian approved these changes

2023-08-26 09:44 UTC, publdaze approved these changes
구웃~! 수고하셨습니다!!

2023-08-27 10:31 UTC, merged