Feature/랭킹페이지 UI 구성 #329
KEEPER31337/Homepage-Front-R2 pull request #490
Opened 2023-07-31 15:28 UTC by jasper200207

## 연관 이슈
#329 

## 작업 요약
랭킹페이지 UI입니다

## 작업 상세 설명
API 연결없는 UI입니다

## 리뷰 요구사항
- 10분
- 실수로 History.jsx, Home.jsx 내용이 포함되어 있는데 무시해주시면 됩니다

## Preview 이미지
![sdfg](https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/2ff00f61-d19b-4a01-ac70-06a9e15c4742)
![sdfgff](https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/feb5fbb7-5287-42d8-8dee-e9740ec0548e)

2023-08-08 14:53 UTC, publdaze requested changes

2023-08-11 14:47 UTC, Ji-Hyeon212 approved these changes
굿! 수고하셨습니다~

2023-08-16 01:37 UTC, publdaze requested changes
디자인 반영 쪽으로도 살짝 피드백 남겨 보았습니다!

2023-08-16 01:37 UTC, publdaze commented on src/pages/rank/Rank.tsx
> +          <Avatar alt="profile" className="mr-2 !h-8 !w-8 object-contain" />
`h-6`, `w-6` 으로 24px 맞춰주세용!

여기 `object-contain` 들어간 이유가 궁금합니다!

2023-08-16 01:37 UTC, publdaze commented on src/pages/rank/TopCard.tsx
> +    </div>
```suggestion
    <div className="relative h-full">
      <div className="absolute z-10 h-28 w-80">
        <div className="flex h-full justify-between bg-mainBlack p-4">
          <div className="flex h-full flex-col justify-between">
            <div className="flex">
              <Typography className="border-[1px] border-pointBlue px-3 py-1 text-pointBlue">{index + 1}</Typography>
              <Typography variant="h3" fontWeight="semibold" marginY="auto" marginLeft={1}>
                {item.name}
              </Typography>
              <Typography variant="small" marginY="auto" marginLeft={1}>
                {item.no}기
              </Typography>
            </div>
            <Typography color="primary" fontWeight="semibold">
              {message}
            </Typography>
          </div>
          <Avatar alt="profile" className="my-auto !h-16 !w-16" />
        </div>
      </div>
      <div className="absolute left-2 top-2 h-28 w-80 border-2 border-pointBlue" />
    </div>
```

이거 제가 그냥 디자인 맞춰본다고 해본 건데 해본 김에 공유드립니다! 아바타 크기와 위에 코멘트 남겼던 폰트 적용한 것과 카드 크기 정도 디자인 맞춰본 것 같아요! (이거 그냥 가져다 사용하셔도 되고 도균님 스타일에 맞게 변형해서 사용해도 됩니당!)

2023-08-16 01:37 UTC, publdaze commented on src/pages/rank/Rank.tsx
`tab` 관련 처리하는 부분에서 실제 화면상으로는 탭별로 보일텐데 코드 상으로는 각 구성요소 따라 삼항 연산자로 구분되어서 각 탭에 어떤 요소가 배치되는 건지 한 눈에 파악하기 어려운 것 같아요! 그래서 조금 중복되는 부분이 있더라도 탭별로 구분하면 각 탭에 따라 어떻게 구성되는 지 파악하기 쉽지 않을까해요! 이렇게 처리한다면 아래 코드처럼 각 탭에 대해 별도의 컴포넌트로 빼주고 호출해 사용하면 더 깔끔하게 표현 가능하지 않을까 싶네용 😀
```tsx
{ tab === 1 && <AttendRankTab /> }
{ tab === 2 && <PointRankTab /> }
```

2023-08-16 01:46 UTC, jasper200207 commented on src/pages/rank/TopCard.tsx
> +              <Typography className="my-auto ml-2">{item.no}기</Typography>
MUI 자체 props를 몰랐네요 참고하겠습니다.
그럼 fontWeight는 일단 적용 안되더라고 props로 넣어두겠습니다.

2023-08-16 01:47 UTC, jasper200207 commented on src/pages/rank/Rank.tsx
> +          <Avatar alt="profile" className="mr-2 !h-8 !w-8 object-contain" />
기존에 img 였을때 넣었었는데 지금은 필요없어 보여 삭제하겠습니다

2023-08-16 05:05 UTC, publdaze approved these changes
👍 수고하셨습니다!

2023-08-16 07:59 UTC, merged