Feature/세미나 출석 이전,현재,최신 세미나 조회 #481
KEEPER31337/Homepage-Front-R2 pull request #506
Opened 2023-08-12 15:30 UTC by lcqff

## 연관 이슈
선행 PR: #489 

## 작업 요약
원래는 출석 남은 횟수를 로컬에 저장하는 PR이 선행PR로 있었는데 한번에 작업하다보니 합쳐진거같읍니다.....

## 작업 상세 설명
> 주요 기능 및 로직에 대한 설명을 작성

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분

## Preview 이미지

2023-08-26 09:47 UTC, publdaze reviewed
- #489 머지되면 pull 한 번 받아주세용~!

2023-08-26 15:34 UTC, pipisebastian commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const [incorrectCodeMsg, setIncorrectCodeMsg] = useState('ㅤ');
여기 공백은 일부로 둔건가용?? 그냥 궁금합니닷 호호

2023-08-26 15:36 UTC, pipisebastian approved these changes
수고하셨습니다!

2023-08-27 10:32 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +  const [incorrectCodeMsg, setIncorrectCodeMsg] = useState('ㅤ');
저거 헬퍼텍스트를 지정 안해두면 헬퍼텍스트 공간이 쑥 들어가면서 헬퍼텍스트가 있을 때랑 없을 때랑 간격차이가 생기드라구요~ 그래서 걍 평소에도 헬퍼텍스트 넣어두는 걸로 차이를 없앴습니당

2023-08-28 14:07 UTC, publdaze requested changes
localstorage 사용한 부분 저희 상태관리 라이브러리 `recoil`로 사용하면 좋을 것 같은데 바로 처리 가능하면 recoil로 해봐주시고 지금 바꾸기는 조금 까다로울 것 같다고하면 배포 이후에 refactoring 하는 걸로 합시다!

recoil 사용할 거면 로컬호스트에 저장하는 방법은
`member.recoil.ts` 참고해주시고,
세미나에만 사용되는 거니, 파일 위치 폴더 관리는 SignUp 폴더의 SignUp.recoil.ts 처럼 페이지 폴더 내부에 위치하면 같아요!

2023-08-28 14:07 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +        {seminarData?.seminarName.replaceAll('-', '.')} 세미나
이부분 로직 api쪽으로 빼면 더 깔끔할 것 같아요! (백엔드쪽에 형식 맞춰달라고 하는게 더 좋아보이긴 한데 요청하기 어렵다면..!)

```tsx
const useGetSeminarInfoQuery = (id: number) => {
  const fetcher = () =>
    axios.get(`/seminars/${id}`).then(({ data }) => {
      const transformedData = {
        ...data,
        seminarName: data.seminarName.replaceAll('-', '.')
        openTime: DateTime.fromISO(data.openTime),
        attendanceCloseTime: DateTime.fromISO(data.attendanceCloseTime),
        latenessCloseTime: DateTime.fromISO(data.latenessCloseTime),
      };
      return transformedData;
    });
  return useQuery<SeminarInfo>(seminarKeys.getSeminar, fetcher);
};
```
이런 식으로!

2023-08-28 14:07 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +            }}
```suggestion
            onClick={handleAttendButtonClick}
```

이렇게 가능하지 않나용?~?

2023-08-28 14:07 UTC, publdaze commented on src/pages/senimarAttend/SenimarAttend.tsx
> +  useGetSeminarInfoQuery,
얘 호출 안 되고 있는 것 같아요!

2023-08-29 08:30 UTC, publdaze requested changes

2023-08-29 08:33 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +    if (parseInt(localStorage.getItem('출석시도횟수') ?? '0', 10) + 1 >= 5) setExcessModalOpen(true);
오잉??? 그러고보니까 저렇게 하면 4회일때부터 안되네요??? +가 아니라 -를 해야하네요??
그냥 (parseInt(localStorage.getItem('출석시도횟수') ?? '0', 10) > 5로 바꿔두겠습니다,,,,

2023-08-29 08:39 UTC, publdaze approved these changes
코멘트 하나 남겨둔 건만 확인해봐주시면 될 것 같아요! 미리 approve 해두겠습니다!

2023-08-29 08:39 UTC, publdaze commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      if (attemptNum <= 5) {
여기도 `+ 1` 없어야 하죠?~? 아닌가?.. 확인 부탁드립니다!

2023-08-29 08:45 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +      if (attemptNum <= 5) {
앗~~ 저거는 출석 틀릴때마다 출석시도 횟수 1씩 늘리는 코드라서 있는게 맞는거같아요~~~!

2023-08-29 08:45 UTC, lcqff commented on src/pages/senimarAttend/Card/MemberCardContent.tsx
> +        {seminarData?.seminarName.replaceAll('-', '.')} 세미나
이거 깜빡하고 적용을 안했네요😅 적용하겠습니다

2023-08-29 08:53 UTC, merged