Feature/페이지네이션 기능 추가 #510
KEEPER31337/Homepage-Front-R2 pull request #515
Opened 2023-08-14 11:34 UTC by pipisebastian

## 연관 이슈
> #510 

## 작업 요약
> 도서검색 페이지네이션 기능 추가
> 이미지처럼, 컨텐츠가 6개 이하인건 빈 bookcard를 넣어줘야하는데, 추후에 이슈 따로파서 작업하겠습니다!

## 리뷰 요구사항
> 3분. react query 부분 제대로 썼는지 봐주시면 감사하겠습니닷..!

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/7c5f8072-4481-4d2d-9e9a-ce3d03f13ee8)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/69ae124c-1688-452a-96fa-3b82e56039bc)

2023-08-15 20:11 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-08-19 11:31 UTC, Ji-Hyeon212 approved these changes
수고하셨습니👍

2023-08-20 08:36 UTC, publdaze requested changes

2023-08-20 08:36 UTC, publdaze commented on src/api/libraryApi.ts
> +  bookListContent: 'bookList',
key는 배열 형태로 처리해주는 게 좋을 것 같아요!
https://tkdodo.eu/blog/effective-react-query-keys#always-use-array-keys

2023-08-20 08:36 UTC, publdaze commented on src/pages/Library/Library.tsx
> +        {bookListData?.content?.map((bookInfo: BookInfo) => (
API 반환할 때 해당 content 타입이 `BookInfo[]`으로 되어 있어서 `bookInfo: BookInfo`로 별도로 타입 명시하지 않아도 타입 추론 될 것 같네요 ?~?

2023-08-20 08:42 UTC, pipisebastian commented on src/pages/Library/Library.tsx
> +        {bookListData?.content?.map((bookInfo: BookInfo) => (
아항 넵넵!

2023-08-20 09:20 UTC, publdaze approved these changes
굿! 수고하셨습니다~!

2023-08-20 09:32 UTC, merged