Feature/도서 대여 목록 조회 api 연결 #486
KEEPER31337/Homepage-Front-R2 pull request #527
Opened 2023-08-20 11:20 UTC by pipisebastian

## 연관 이슈
> #486

## 작업 요약
- 도서 대여 목록 조회 api 추가
- 대출중인 도서 권수를 받아와서, BorrowStatus 컴포넌트(신청가능 권수 나타내주는 컴포넌트)에 반영

## 리뷰 요구사항
> 3분. 변수명 괜찮은지 확인부탁드립니다..

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/ecb7baf6-67f4-4279-b22c-0a8183a0145a)

2023-08-20 11:23 UTC, pipisebastian commented on src/api/libraryApi.ts
> +  return useQuery<{ content: BookInfo[]; totalElement: number }>(libraryKeys.bookList(param), fetcher);
이건 다른 이슈긴 한데, 해당 data가져오는게 content말고도 pagination 정보나, totalElement등을 가져오는데, query key 객체에서도 bookListContent보다는 bookList가 낫다고 생각해서 수정했습니다,.,!

![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/d7dd8a7c-e691-4311-9e26-3c4dc9fa6d3a)

2023-08-20 11:24 UTC, pipisebastian commented on src/api/libraryApi.ts
> +  return useQuery<{ content: BorrowedBookInfo[]; totalElement: number }>(libraryKeys.borrowedBookList, fetcher);
도서검색에서는 사실상 totalElement만 필요하긴한데, 나중에 프로필페이지에서 또 쓰일거 생각해서 content도 받아와줬습니다!

2023-08-20 11:25 UTC, pipisebastian commented on src/pages/Library/Status/BorrowStatus.tsx
> +      신청 가능 권수 : {MAX_BORROWABLE_BOOKS - borrowedBookCount}/{MAX_BORROWABLE_BOOKS}
아무것도 안빌렸을때는 5/5권으로 뜨고, 빌릴때마다 4/5, 3/5, 2/5~ 식으로 줄어듭니다!

2023-08-21 20:22 UTC, publdaze requested changes

2023-08-21 20:22 UTC, publdaze commented on src/pages/Library/Library.tsx
> +          MAX_BORROWABLE_BOOKS={MAX_BORROWABLE_BOOKS}
넘겨주는 값 자체는 대문자 + 스네이크 표기법으로 상수 데이터 네이밍으로 좋은 것 같은데 props명은 정해진 값이 아닌 상위에서 양한 값들을 받아올 수 있는 속성이라 네이밍이 어색한 것 같아요!

```suggestion 
          maxBorrowableBooks={MAX_BORROWABlE-BOOKS}
```
로 변경 어떨까요?

2023-08-21 20:22 UTC, publdaze commented on src/pages/Library/Status/BorrowStatus.tsx
> +      신청 가능 권수 : {MAX_BORROWABLE_BOOKS - borrowedBookCount}/{MAX_BORROWABLE_BOOKS}
으음? `현재 빌린 권수/신청 가능 권수`로 가야하지 않나요? 빌릴수록 MAX에 가까워져야 할 것 같은데..? 🤔
신청 가능 권수 카운트 다운으로 가고 싶으면 `/ max값` 빼고 가능 권수만 표기하는 게 맞는 것 같아요!

2023-08-24 08:50 UTC, pipisebastian commented on src/pages/Library/Status/BorrowStatus.tsx
> +      신청 가능 권수 : {MAX_BORROWABLE_BOOKS - borrowedBookCount}/{MAX_BORROWABLE_BOOKS}
근데 라벨이 신청가능권수인데, 진짜 신청이 가능한 권수를 나타내니까 5/5 -> 4/5가 맞지 않을까요..?
max값은 사용자가 몇권까지 빌릴 수 있는지 모르니까, 넣어주는게 좋아보입니다!

아니면 라벨을 현재 빌린 권수로 바꾸고, 0/5 -> 1/5처럼 빌릴수록 증가되게 할까요??

2023-08-24 10:08 UTC, pipisebastian commented on src/api/libraryApi.ts
> +}
음,,, 아니면 이부분은 타입선언 안하고, 그냥 `const useGetBookBorrowsQuery = ({ page, size }: { page?: number; size?: number })` 로 넣을까요? 이게 더 깔끔해보일지두요,,!

2023-08-24 10:10 UTC, publdaze commented on src/api/libraryApi.ts
> +}
그것도 괜찮을 것 같네욤!

2023-08-24 10:10 UTC, pipisebastian commented on src/api/libraryApi.ts
>  interface getBookListProps {
그리고 이부분도 Props인데, 은지님 BoardSearch타입도 이거랑 비슷하더라구요! 이것도 subfix로 Props대신 Search붙히는거 어떨까요??
`getBookListProps` -> `BookListSearch`로요!

2023-08-24 10:10 UTC, pipisebastian commented on src/pages/Library/Library.tsx
> +          MAX_BORROWABLE_BOOKS={MAX_BORROWABLE_BOOKS}
아항 넵넵!

2023-08-24 10:12 UTC, publdaze commented on src/api/libraryApi.ts
>  interface getBookListProps {
좋아요~!

2023-08-24 10:42 UTC, publdaze commented on src/pages/Library/Status/BorrowStatus.tsx
> +      신청 가능 권수 : {MAX_BORROWABLE_BOOKS - borrowedBookCount}/{MAX_BORROWABLE_BOOKS}
서윤님 말 다시 듣고 보니 괜찮은 것 같기도 하네요!! 크게 신경 안 써도 될 것 같습니다!

2023-08-24 10:44 UTC, publdaze approved these changes
타입 부분만 서윤님 얘기해주신 대로 반영하면 될 것 같아요! 미리 approve 해두겠습니다~!

2023-08-25 13:37 UTC, lcqff approved these changes
수고하셨습니당~!

2023-08-25 15:00 UTC, merged