Feature/search section 기능 구현 #532
KEEPER31337/Homepage-Front-R2 pull request #534
Opened 2023-08-20 16:50 UTC by pipisebastian

## 연관 이슈
- Close #532

## 작업 요약
- search section 기능 구현
- selector부분 id에 원래는 number만 가능했는데, string 타입도 추가해줬습니다! 
백엔드에 보낼때 'all', 'title'처럼 string을 보내기 때문에 추가했는데, 더 좋은 방법있다면 알려주세용!
- search section 쓰는 다른컴포넌트 (게시판, 도서관) 등에서 에러나길래 일단 주석처리 해줬습니다!

## 예시 코드
```tsx
 const bookNumberList = [
    { id: 'all', content: '제목 + 내용' },
    { id: 'title', content: '제목' },
    { id: 'content', content: '내용' },
  ];

  const [inputValue, setInputValue] = useState('');
  const [selectorValue, setSelectorValue] = useState('all');

  const handleSelectorChange = (event: SelectChangeEvent<unknown>) => {
    setSelectorValue(event.target.value as string);
  };
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };
  const handleSearchButtonClick = () => {
    console.log(selectorValue, inputValue, '검색 api 호출');
  };
```

```tsx
<SearchSection
          options={bookNumberList}
          selectorValue={selectorValue}
          onChangeSelector={handleSelectorChange}
          placeholder="도서명을 입력하세요."
          inputValue={inputValue}
          onchangeInput={handleInputChange}
          onSearchButtonClick={handleSearchButtonClick}
/>
```

## 리뷰 요구사항
- 3분

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/afeb2bd9-014a-4b9a-bcee-f96bf430e72f)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/09dacfb6-5188-4cfa-906c-a09ce525f4af)

2023-08-22 04:23 UTC, publdaze requested changes
`handleSelectorChange`, `handleInputChange`는 `SearchSection` 내부에서 제어해도 괜찮을 것 같기도 한데 외부에서 별도로 제어가 필요할 일이 있으련가요?~? 🤔

2023-08-24 14:19 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
넵! 그러면 searchInput 컴포넌트는 삭제하겠습니다용!

2023-08-24 14:21 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
헉 그런데 standard input에 디자인이 적용되어있군요,,! search : boolean props를 하나 추가해서 디자인적용을 뺄까요??
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/409d3e63-322d-4011-a37d-c87c0b24a6ef)

2023-08-24 14:25 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/ac3567be-8a4a-40fe-99eb-1df6166237a9)
search보단 IsSearchInput으로.. 추가하면 어떨까합니당!

2023-08-25 05:33 UTC, pipisebastian commented
> > > `handleSelectorChange`, `handleInputChange`는 `SearchSection` 내부에서 제어해도 괜찮을 것 같기도 한데 외부에서 별도로 제어가 필요할 일이 있으련가요?~? 🤔
> > 
> > 
> > 움..잘 이해가 안갑니다! handleSelectorChange에서 setState를 하는건데, 그럼 handleSelectorChange말고 setState를 searchSection 프롭스로 넘겨서, searchSection안에서 핸들링함수를 작성하라는 걸까요..?
> 
> 허걱 제가 너무 모호하게 말했던 것 같네요! 네 서윤님 이해하신게 맞아요! 핸들러 함수 내부 동작이 state 업데이트 해주는 동작만 있다면 핸들러 함수 매번 작성해주는 게 불필요할 수도 있을 것 같아서요! 그치만 `SearchInput`에서 너무 동작을 묶어두는 것 같으면 꼭 넣어야하는 건 아니니까 패스해도 되는 부분인 것 같습니다!

아항! 좋습니다! 더깔끔해지겠군요! 검색창을 커스텀할 것 같진 않아서.. 말씀하신대로 가겠습니다~~

2023-08-25 06:00 UTC, pipisebastian commented on src/components/Input/SearchInput.tsx
아항!! 넵넵!!

2023-08-25 07:39 UTC, publdaze requested changes

2023-08-25 07:39 UTC, publdaze commented on src/components/Input/SearchInput.tsx
> +      onKeyDown={handleOnKeyEnterPress}
props 명은 keyDown으로 바뀌었으니 핸들러 명은 `KeyPress` 말고 `keyDown`으로 변경해주는 게 좋을 것 같아요!

2023-08-25 10:33 UTC, lcqff approved these changes
굿입니다~ 수고하셨습니다~~!!👍👍

2023-08-25 15:56 UTC, publdaze approved these changes
굿!

2023-08-25 16:06 UTC, merged