Feature/autocomplete 공통컴포넌트 #432
KEEPER31337/Homepage-Front-R2 pull request #542
Opened 2023-08-22 17:26 UTC by jasper200207

## 연관 이슈
#432 

## 작업 요약
AutoComplete 컴포넌트 입니다

## 작업 상세 설명
필수값은 *로 표시했습니다.
다음과 같은 Props를 가지고 있습니다
- items : Array<Item>, 선택지 정보 입니다. 기본값 : [ ]
- *value : Array<Item> | Item | null, 선택한 항목입니다. 중복허용시 리스트를 1개만 선택시 null을 기본값으로 넣어야 합니다
- onChange : (v) => void , 선택시 실행되는 함수 입니다. 해당 함수에서 value를 바꿔주면 됩니다 기본값 : (v) => console.log(v)
- multiple : boolean, 중복 여부 입니다 기본값 : false
- grouped : boolean, 그룹 여부 입니다 기본값 : false
- placeholer : string, 아무것도 선택하지 않았을 때 띄우는 값 입니다 기본값 : ""
- className : string, tailwindcss를 위해 className을 Props로 받아옵니다 기본값 : ""
Item 클래스 구조 입니다
- *value : any, 선택한 항목의 값입니다
- *label : string, 선택한 항목을 나타낼 텍스트 입니다
- fixed : boolean, 고정값 여부 입니다.
- group: string, 그룹 이름 입니다.

## 리뷰 요구사항
> 15분
mui의 기본디자인을 사용하고 있는데 괜찮을지 확인 부탁드립니다.
실제로 사용할때 불편한점있으면 코멘트 부탁드립니다.
다은님은 리뷰어는 아니신데 직책관리에서 Auto Complete 사용하신다고 하셔서 추가로 달았습니다.

2023-08-22 17:29 UTC, publdaze commented
혹시 PR 내용에 사용 예시 하나 부탁드려도 될까요? 👀

2023-08-22 17:32 UTC, publdaze commented on src/components/Input/AutoComplete.tsx
> +  onChange = (v) => console.log(v),
기본 값 콘솔 찍는 걸로 해둔 이유가 궁금합니다!

2023-08-24 09:38 UTC, jasper200207 commented on src/components/Input/AutoComplete.tsx
> +  onChange = (v) => console.log(v),
특별한 이유가 있는건 아니고, 선택 제대로 되었는지 확인하기 편해서 넣었습니다..

2023-08-25 19:19 UTC, jasper200207 commented
> 혹시 PR 내용에 사용 예시 하나 부탁드려도 될까요? 👀

추가했습니다

2023-08-26 02:25 UTC, publdaze commented
mui의 기본디자인 괜찮아보이는데 일단 사용하다가 디자인 변경 필요할 것 같다 싶으면 그때 적용하는 걸로 하고 이 PR은 일단 이 디자인 대로 가는 걸로 합시다!

2023-08-26 09:58 UTC, publdaze requested changes

2023-08-26 09:58 UTC, publdaze commented on src/components/Input/AutoComplete.tsx
> +      onChange([...fixed, ...(v as Array<Item>).filter((item) => !item?.fixed)]);
`...(v as Array<Item>).filter((item) => !item?.fixed)` 부분이 뭘 나타내는 건지 한 번에 알아보기 어려운 것 같아서

```tsx
const fixedItems = items.filter((item) => item.fixed);
const nonFixedItems = (v as Array<Item>).filter((item) => !item?.fixed);
onChange([...fixedItems, ...nonFixedItems]);
```

이런 식으로 한 번 분리해주는 것도 괜찮을 것 같아요!

2023-08-26 15:30 UTC, pipisebastian approved these changes
수고하셨씁니다!

2023-08-27 02:56 UTC, publdaze approved these changes
굿!

2023-08-27 03:06 UTC, merged