Feature/대출 현황 탭 연체도서 목록 받아오기 #574
KEEPER31337/Homepage-Front-R2 pull request #575
Opened 2023-08-28 12:46 UTC by pipisebastian

## 연관 이슈
- #570  #573 선행리뷰 부탁드립니다~
-
## 작업 요약
- 연체도서 목록 받아와서 띄워줬습니다!
- 대출현황 탭에 테이블 목록 api는 지금 만드는 중이라, 연체도서부터 했습니다!

## 리뷰 요구사항
> 5분

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/b1b7bd23-089e-49e8-9530-d14b3cbaa7e4)

2023-08-28 15:00 UTC, pipisebastian commented on src/api/dto.ts
> +  status: '대출대기중' | '반납대기중' | '대출거부' | '대출승인' | '반납';
백엔드 status 5종류 다 넣어줬습니다!

2023-08-28 15:12 UTC, pipisebastian commented on src/api/libraryManageApi.ts
> +        let statusFront = '';
이게 백엔드에서 받아오는 status랑 프론트에서 나타내는게 달라서 이런식으로 로직 처리해줬는데괜찮을까요 ?? 사실 `statusFront`변수명 맘에 안듭니다..

그리고, 백엔드쪽에 요청해서 프론트랑 status이름 같게 만들어달라고 했긴한데,
그래도 여전히 [대출대기] status를 도서관리에선 [대출 신청]으로 보여주는 것처럼, 따로 변환이 필요하기 때문에 추후에 이름이 같아지더라도 똑같은 로직 사용할 예정입니다!

2023-08-28 15:13 UTC, pipisebastian commented on src/api/libraryManageApi.ts
> +          bookQuantity: '3/3', // `${borrowInfo.currentQuantity}/${borrowInfo.totalQuantity}`,
이건 백엔드에서 api에 currentQuantity, totalQuantity를 넘겨달라고 요청한 상태라서, 임시로 박아놨습니다!

2023-08-28 15:30 UTC, publdaze requested changes

2023-08-28 15:30 UTC, publdaze commented on src/api/libraryManageApi.ts
> +          status: statusFront,
```suggestion
        const borrowStatus = {
          대출대기중: '대출 신청',
          반납대기중: '반납 신청'
        }

        return {
          borrowInfoId: borrowInfo.borrowInfoId,
          status: borrowStatus[borrowInfo.status],
```

이런 식으로는 어떤가요? (깃헙에서 바로 작성해서 동작하는 코드인지는 한 번 확인해주세요!)

2023-08-28 15:30 UTC, publdaze commented on src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
> +import OverDueBookModal from '../Modal/OverdueBookModal';
```suggestion
import OverdueBookModal from '../Modal/OverdueBookModal';
```
오타같아요! 😄

2023-08-28 15:30 UTC, publdaze commented on src/api/libraryManageApi.ts
> +        let statusFront = '';
https://github.com/KEEPER31337/Homepage-Front-R2/pull/575#discussion_r1307568865

2023-08-28 17:20 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
> +import OverDueBookModal from '../Modal/OverdueBookModal';
아앗! 근데 알아서 동작하는게 신기하네용 ㅎㅎ

2023-08-28 17:20 UTC, pipisebastian commented on src/api/libraryManageApi.ts
> +          status: statusFront,
오홍!!! 좋습니다!!!

2023-08-28 17:35 UTC, pipisebastian commented on src/api/libraryManageApi.ts
> +          status: statusFront,
넘넘 좋습니다!! 수정했습니다!

2023-08-29 07:46 UTC, publdaze approved these changes
👍 코멘트 아래 달아둔 거 확인만 해주세요! approve 해두겠습니다!

2023-08-29 07:46 UTC, publdaze commented on src/pages/admin/LibraryManage/Modal/OverdueBookModal.tsx
> +  id: number;
여기 id 별도로 넣어주지 않아도 Table 내부에서 Row의 경우 id는 기본적으로 들어가도록 처리해두었답니다~!

2023-08-29 08:24 UTC, pipisebastian commented on src/pages/admin/LibraryManage/Modal/OverdueBookModal.tsx
> +  id: number;
아항!  (따봉!) 지웠습니당!!

2023-08-29 08:59 UTC, lcqff approved these changes
아주 멋집니다~~

2023-08-29 09:01 UTC, merged