Feature/도서, 도서관리 search section api 연결 #585
KEEPER31337/Homepage-Front-R2 pull request #586
Opened 2023-08-29 15:59 UTC by pipisebastian

## 연관 이슈
> 연관된 이슈를 모두 기재 → #[Issue번호] 형식

## 작업 요약
> 1~2줄 사이의 요약 설명

## 작업 상세 설명
> 주요 기능 및 로직에 대한 설명을 작성

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분

## Preview 이미지

2023-08-29 16:05 UTC, pipisebastian commented on src/pages/Library/SearchSection/LibrarySearchSection.tsx
> +    setSearchParams({ page: String(1), searchType: '', search: search.trim() });
검색유형에 아무것도 안넣으면 잘되기때문에 일단 빈 스트링 넣어줬습니다!

2023-08-31 11:00 UTC, publdaze reviewed
pull 한 번 받아주세용~~!

2023-08-31 12:13 UTC, pipisebastian commented on src/api/libraryManageApi.ts
> +          bookQuantity: `${borrowInfo.currentQuantity}/${borrowInfo.totalQuantity}`,
해당 파일은 백엔드 수정사항에 맞춰서 적용한겁니다!

2023-08-31 14:46 UTC, publdaze requested changes

2023-09-01 05:49 UTC, pipisebastian commented on src/pages/Library/SearchSection/LibrarySearchSection.tsx
맞네용,,! LibrarySearchSection 으로 가겠습니댜!

2023-09-01 05:53 UTC, publdaze approved these changes
구웃~!

2023-09-01 05:53 UTC, merged