feat : 도서페이지 썸네일 적용
KEEPER31337/Homepage-Front-R2 pull request #602
Opened 2023-09-02 20:04 UTC by pipisebastian

## 연관 이슈
- Close #602

## 작업 요약
-  도서페이지 썸네일 적용했씁니다!

## 리뷰 요구사항
- 0.5분

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/3a454103-9f7b-436c-b127-5b8104d0097e)

2023-09-03 02:22 UTC, publdaze requested changes

2023-09-03 02:22 UTC, publdaze commented on src/pages/Library/Card/BookCard.tsx
> +        )}
여기 `ServerImg` 컴포넌트 사용해주세요!
썸네일 있을 때 없을 때 해당 컴포넌트 내에서 처리해서 사용하는 곳에서 별도로 처리할 필요 없고, 서버 에러 관련해서도 공통적으로 핸들링할 에정입니다!

[참고](https://keepernewhome-5o41027.slack.com/archives/C04971678G7/p1691305410364559)

2023-09-03 08:28 UTC, pipisebastian commented on src/pages/Library/Card/BookCard.tsx
> +        )}
넵!! 수정했습니당!

2023-09-03 15:41 UTC, jasper200207 approved these changes
수고하셨습니다!

2023-09-04 01:23 UTC, publdaze approved these changes
굿!

2023-09-04 01:44 UTC, merged