Feature/프로필 섹션 구현 #661
KEEPER31337/Homepage-Front-R2 pull request #669
Opened 2023-09-17 12:52 UTC by pipisebastian

## 연관 이슈
- #661 
## 작업 요약
- 내프로필, 남프로필 기능구현
- 뱃지의 경우 추후 구현 예정

## 리뷰 요구사항
- 변수명 괜찮은지 확인부탁드립니다!

## Preview 이미지
내 프로필
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/5d07ccf5-4f24-4e67-ade6-99a258c52e33)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/4d62d100-3c9f-4434-bcb3-2998185b49fd)
남 프로필
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/aeb86ef5-fdf5-472c-9846-50815f402b76)

2023-09-18 07:20 UTC, publdaze requested changes

2023-09-18 07:20 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +        src={profileInfo?.thumbnailPath || ''}
여기 아마 서버 url로 넣어야 조회 가능할 거에요!
```suggestion
        src={profileInfo?.thumbnailPath ? getServerImgUrl(profileInfo?.thumbnailPath) : undefined}
```
(src 빈스트링으로도 기본이미지 출력 되나요?~? 저는 undefined로 처리했었어서 위에 예시 undefined 넣었긴 한데 빈스트링도 기본 이미지 출력 값으로 적용되는 값이면 꼭 undefined로 반영하실 필요는 없을 것 같습니다!)

test1 계정에 프로필 변경해뒀는데 한 번 테스트 해보시면 될 것 같아요!

2023-09-18 07:20 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +import React, { useState, useEffect } from 'react';
`useEffect` 사용 안 되고 있는 것 같습니다!

2023-09-18 07:27 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +        src={profileInfo?.thumbnailPath || ''}
alt 넣으면 fallback으로 alt 첫글자 떠서 이미지 못받아 왔을 때 기본 아바타 이미지 띄워주려면 alt 적용 안 해야 할거에욧..!

2023-09-18 09:42 UTC, publdaze requested changes

2023-09-18 09:42 UTC, publdaze commented on src/pages/Profile/Section/FollowList.tsx
> +    </List>
리스트 아이템 개수가 많아질 경우 스크롤로 처리될 수 있도록 높이 고정해두면 어떨까요?~?

2023-09-18 09:42 UTC, publdaze commented on src/pages/Profile/Section/FollowList.tsx
> +                alt="profile thumbnail"
여기도 기본 아바타 사용할 거면 alt 없어야 할 것 같아요!

2023-09-18 09:42 UTC, publdaze commented on src/pages/Profile/Section/FollowList.tsx
> +            <ListItemText primary={`${followInfo.generation.replace('.0', '')}기 ${followInfo.name}`} />
기수 변환하는 로직 기수 사용하는 곳에서 공통적으로 사용할 수 있는 부분인 것 같아서 `src/utils/converter.ts` 내부에 변환 함수로 따로 빼줘도 좋을 것 같아요! (+ api 받아와 뿌려주는 곳에 다 변환해야 하니 api 파일 내에서 먼저 변환하고 data 받아오면 한 번만 변환해서 받아올 수 있어서 더 깔끔할 것 같습니다!)

2023-09-21 12:46 UTC, pipisebastian commented on src/pages/Profile/Section/FollowList.tsx
> +    </List>
아항 그부분은 해당컴포넌트 바깥에 해놨었는데 안으로 옮기겠습니당@!

2023-09-21 12:49 UTC, pipisebastian commented on src/pages/Profile/Section/FollowList.tsx
> +            <ListItemText primary={`${followInfo.generation.replace('.0', '')}기 ${followInfo.name}`} />
아항 이런것도 있었군요!! 반영하겠씁니다~~

2023-09-21 13:52 UTC, publdaze commented on src/api/memberApi.ts
> +    });
```suggestion
    axios.get(`/members/${memberId}/profile`).then(({ data }: { data: ProfileInfo }) => {
      return {
        ...data,
        generation: formatGeneration(data.generation),
        follower: data.follower.map((followerInfo) => {
          return {
            ...followerInfo,
            generation: formatGeneration(followerInfo.generation),
          };
        }),
        followee: data.followee.map((followeeInfo) => {
          return {
            ...followeeInfo,
            generation: formatGeneration(followeeInfo.generation),
          };
        }),
      };
    });
```

하위요소에 직접적인 타입 대신 반환 값에 대한 타입 적용으로도 가능할 것 같네용!

2023-09-21 13:52 UTC, publdaze commented on src/utils/converter.ts
> +  return `${generation.replace('.0', '')}`;
여기 템플릿 리터럴으로 안해줘도 될 것 같아요!

```suggestion
  return generation.replace('.0', '');
```

2023-09-21 13:59 UTC, publdaze requested changes

2023-09-21 13:59 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +  const { mutate: UnFollowMember } = useUnFollowMemberMutation(otherMemberId);
여기 컴포넌트 아닌 단순 변수명은 첫글자 소문자로 해주면 좋을 것 같습니다!

2023-09-21 14:04 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +    return profileInfo?.follower.some((follower) => follower.id === myMemberId);
본인 id가 맞는 지 비교하는 로직
`useCheckAuth` 커스텀 훅의 `checkIsMyId`를 통해서 가능한데 활용해봐도 좋을 것 같습니다!

2023-09-21 14:04 UTC, publdaze commented on src/pages/Profile/Section/ProfileSection.tsx
> +        {myMemberId === profileInfo?.id ? (
여기도 마찬가지로 `checkIsMyId` 사용해도 될 것 같네요!

2023-09-22 12:36 UTC, pipisebastian commented on src/api/memberApi.ts
> +    });
오홍! 맞네용!! 감사합니다!

2023-09-22 13:55 UTC, publdaze approved these changes
👍

2023-09-22 13:59 UTC, merged