refactor : 상벌점 페이지 개선
KEEPER31337/Homepage-Front-R2 pull request #678
Opened 2023-09-18 08:26 UTC by jasper200207

## 연관 이슈
#663 

## 작업 요약
SettingMeritTypeModal Props 개선

## 작업 상세 설명
SettingMeritTypeModal Props를 변경했습니다.
- open을 입력받고 status는 edit 일 경우에만 받습니다.
- edit을 props로 받습니다.

## 리뷰 요구사항
5분

2023-09-22 02:17 UTC, publdaze requested changes

2023-09-22 02:17 UTC, publdaze commented on src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx
> +      />
여기서 generic 타입 전달하고 있지 않고, status나 edit props 전달에 따라서 edit인 지 판별하는 것 같은데 내부 타입에 generic 받는 거 제거 해도 되지 않을까요?~?

2023-09-24 06:59 UTC, jasper200207 commented on src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
> +  status?: Edit extends true ? MeritTypeModalInfo : null;
이 부분때문에 제네릭타입이 들어가야 합니다! edit의 true | false에 따라서 타입선언부에서 조건부 타입을 사용하기 위해 적용했습니다.

2023-09-24 06:59 UTC, jasper200207 commented on src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx
> +      />
조건부 타입에 필요해서 넣었습니다. 코멘트 달아뒀습니다.

2023-09-24 09:37 UTC, publdaze approved these changes
일단 코멘트 달아둔 부분 타입 어떻게 다룰지 관련 부분이라 동작에는 이상 없을 것 같아서 approve 해두겠습니다!

2023-09-24 09:37 UTC, publdaze commented on src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
> +  status?: Edit extends true ? MeritTypeModalInfo : null;
오홍 제 생각에는 제네릭타입은 여러 타입을 받기 위해 사용되는 타입인데, 여기서 사용되는 경우는 boolean 타입으로만 다뤄지는 것 같아서 edit의 타입 제약이 광범위 하다고 느껴지더라구요!

<img width="200" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/e212d331-8241-4250-86c7-a392bee3cfec">

여기서 어차피 `edit`일 경우에만 `status` set 해주고 있고, 그게 아니더라도 props로 `edit`일 경우에만 `status` 넘겨줄 수 있을 것 같아서

```tsx
interface SettingMeritTypeModalProps {
  open: boolean;
  edit?: boolean;
  status?: MeritTypeModalInfo;
```
이렇게 둬도 괜찮지 않을까 생각했었습니다!

2023-09-26 01:21 UTC, merged

2023-09-26 01:24 UTC, jasper200207 commented on src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
> +  status?: Edit extends true ? MeritTypeModalInfo : null;
status의 타입이 add와 edit일때 달랐었기 때문에 타입 분리가 되어있었는데 open이 분리되면서 굳이 필요가 없어졌기는 하네요.... 일단 머지하고 추후에 리펙토링으로 넘기겠습니다...