feat : 세미나 추가, 삭제 기능 구현
KEEPER31337/Homepage-Front-R2 pull request #695
Opened 2023-09-21 11:22 UTC by pipisebastian

## 연관 이슈
- #672 
- 
## 작업 요약
- 세미나 추가, 삭제 기능 구현
- 추가, 삭제시 완료되었다는 토스트 메시지는 추후에 추가 예정
- 백엔드 수정사항으로 응답 필드 네이밍 변경 

## 리뷰 요구사항
- 5

## Preview 이미지
<img width="682" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/2f8e25d6-79ca-4789-8846-93875cca901e">
<img width="695" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/71d52a99-029f-48b6-9953-8c85824b4f72">

2023-09-21 11:23 UTC, pipisebastian commented on src/api/dto.ts
> +  statusType: ActivityStatus;
응답 필드 네이밍 수정한겁니다

2023-09-21 11:23 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +    setSeminarDate(DateTime.now());
세미나 추가의 경우, 현재날짜를 디폴트로 해줬습니다

2023-09-21 11:24 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +  }, [isAddSeminarSuccess]);
혹시 이부분 useEffect쓰는거 말고 더 좋은 방법이 있을까용??

2023-09-21 11:26 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +    setSeminarId(Number(seminarList?.at(-1)?.id));
이건 최신 세미나 id를 디폴트로 해주려고 한건데, 이게
20일, 25일, 23일 순으로 세미나를 생성하면, 이순서 그대로 추가가 되서, 23일이 디폴트로 뜨더라구용.
이부분은 백엔드쪽에 20, 23, 25일로 따로 필터링요청하는게 좋을까요?

2023-09-21 11:27 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +  }, [seminarList]);
이것도 useEffect로 react query로 list 정상적으로 받아왔을때 seminarId를 set해준건데, 더 좋은 방법 있을까욥..!

2023-09-21 11:48 UTC, pipisebastian commented on src/pages/senimarAttend/SenimarAttend.tsx
> +      ))}
이부분은 원래있던 문제인것 같은데
 SeminarCard가 아무것도 없으면 [undefined, undefined, undefined]로 key중복이 뜨더라구요,, 그래서 해결했습니다!

2023-09-21 14:41 UTC, publdaze requested changes

2023-09-21 14:41 UTC, publdaze commented on src/api/seminarApi.ts
> +      return response.data;
여기서 onSuccess에서 return 해주는 값이
api response로 받아온 값을 `res`라고 치면 `res.data.data`가 될 것 같은데
해당 api 반환 값은 `res.data` 하위에 `data` 속성이 없는 것 같아서 한 번 확인 부탁드립니다!

2023-09-21 14:41 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +    addSeminar(seminarDate);
```suggestion
    addSeminar(seminarDate, {
      onSuccess: () => {
        handleClose();
      },
    });
```

https://github.com/KEEPER31337/Homepage-Front-R2/pull/695/files#r1332902919 이렇게 처리하면 호출 성공 시 바로 동기화된 처리가 가능할 것 같습니다! (delete 쪽에도 동일하게 처리하면 될 것 같네요!)

2023-09-21 14:42 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +  }, [isAddSeminarSuccess]);
https://github.com/KEEPER31337/Homepage-Front-R2/pull/695#discussion_r1333176417

2023-09-21 14:43 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +    setSeminarId(Number(seminarList?.at(-1)?.id));
네네 요청 드리는 게 좋을 것 같네요!

2023-09-22 13:10 UTC, pipisebastian commented on src/api/seminarApi.ts
> +      return response.data;
우엉 맞네요! undefined가 뜨는군요.. 고치겟씁니다!

2023-09-22 13:10 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
> +    addSeminar(seminarDate);
우엉.. 전 바봅니다...

2023-09-22 13:10 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +    setSeminarId(Number(seminarList?.at(-1)?.id));
넹!

2023-09-23 03:36 UTC, publdaze approved these changes
위에 코멘트 반영 해주시면 될 것 같아요! 먼저 approve 해둘게요~!

2023-09-23 03:36 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +        console.log(aaa);
data 찍어본 거 test 용인 것 같은데 지워주시면 될 것 같아용!

2023-09-23 03:36 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
>      setSeminarId(Number(seminarList?.at(-1)?.id));
if 문으로 `seminarList` 있을 때로 한 번 걸러주는 건 어떨까요?
`seminarList` 안 받아와졌을 때 `NaN`으로 들어가지 않을까 싶어서요!

2023-09-23 03:51 UTC, publdaze approved these changes
위 코멘트 하나만 반영해주면 될 것 같아요! 수고하셨습니다~!

2023-09-23 03:51 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
> +  }, [seminarList]);
`useQuery`에도 `onSuccess` 가 있긴 한데 반환되는 값중에 있는게 아니라서 오히려 복잡해질 수도 있을 것 같네용..!

이대로 가도 괜찮을 것 같은데,
`Number(seminarList?.at(0)?.id))`에서 내부값이 `undefined`가 될 경우 `NaN`이 되니까
if 문으로 `seminarList && seminarList.length > 0` 정도로 한 번 걸러주면 좋을 듯 하네요!

2023-09-23 04:01 UTC, merged