Feature/세미나 출석 상태 변경 기능 추가 #744
KEEPER31337/Homepage-Front-R2 pull request #770
Opened 2023-10-02 08:14 UTC by pipisebastian

## 연관 이슈
- Close #744

## 작업 요약
- 개인사정, 지각일 경우에만 사유 입력창 뜨도록

## 리뷰 요구사항
- 7분

## Preview 이미지
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/fa3ff2e9-329a-4258-978d-3f523038a2ab)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/037373c5-9fc8-482c-9bd8-428a35800386)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/34fc2ae5-016f-4574-a415-6ae842f1ceeb)
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/02d7c2b5-802f-4e34-82e5-58a640e9c914)

2023-10-04 02:57 UTC, publdaze requested changes

2023-10-04 02:57 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +  };
이거 첫글자 대문자로 한 이유가 있나요? boolean 반환하는 단순 변수 같아 보여서요!

2023-10-04 02:57 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +            helperText={isInvalidTitle && '사유을 입력해주세요'}
안내 문구에 보통 마침표 포함했어서 여기도 마침표로 `.` 넣어주면 어떨까요?~?

2023-10-04 02:57 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +  const [isInvalidTitle, setIsInvalidTitle] = useState(false);
여기 title이 어떤 걸 의미하는 건가요? 사유는 `excuse`로 관리하는 것 같은데 인풋이 사유 밖에 없어서 제목이라고 할만한게 뭐가 있는 지 파악이 잘 안되네용 👀

2023-10-05 08:56 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +  const [isInvalidTitle, setIsInvalidTitle] = useState(false);
오탑니다.. 수정햇서용

2023-10-05 08:56 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +  };
오탑니다..

2023-10-05 10:44 UTC, publdaze approved these changes
수고하셨습니다!

2023-10-05 10:44 UTC, merged