Feature/세미나관리 페이지 버그픽스 #791
KEEPER31337/Homepage-Front-R2 pull request #796
Opened 2023-10-10 12:23 UTC by pipisebastian

## 연관 이슈
- Close #791

## 작업 요약
- 동일한 날짜의 세미나는 생성할 수 없다는 문구 띄워주기
- 세미나 출석 상태 변경 안되는 버그 픽스
- 결석 사유 입력 안 해도 되도록 처리

## 리뷰 요구사항
- 5분

2023-10-10 12:27 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +    }
이게 저번에 세미나상태 변경이 안됬었던 이유인데,
처음코드는 만약 출석, 결석과 같이 excuse가 안들어갈 경우, isValid를 바로 false로 만들어줘서
api를 못돌게 했더라구용... 그래서 일단 isValid를 true로 만들어주고, excuse가 필요한 경우만 따로 유효성돌게 해줬습니다!

2023-10-11 03:48 UTC, publdaze requested changes

2023-10-11 03:58 UTC, publdaze commented
delelop pull 한 번 받아주세용! 중간에 세미나 출석 버그 픽스한게 있는데 같이 동작 확인해보려구요!

2023-10-12 11:07 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
>      return isValid;
아 네네! isValid true로 들어가야합니다! 근데 setIsInvalidExcuse(!isValid)가 밑에 
```
 <StandardInput
            className="w-52"
            error={isInvalidExcuse}
            helperText={isInvalidExcuse && '사유을 입력해주세요.'}
            label="사유"
            value={excuse}
            onChange={handleBookInfoChange}
          />
```
해당 코드에서 error쪽에 들어갈거라.. 일부러 valid가 아닌 InValid변수명으로 지어서, set할때 !IsValid 를 넣어서.. 그런건데,, 코드가 좀 헷갈리는 군요..
차라리 `isInvalidExcuse` 변수명 대신 `isvalidExcuse`로 넣은다음, 여기 error ={}으로 넣어줄때 error = {!isvalidExcuse} 이렇게 처리할까요??

2023-10-12 11:08 UTC, pipisebastian commented on src/api/seminarApi.ts
> +        toast.error('동일한 날짜의 세미나는 생성할 수 없다.');
이거 혹시 에러핸들링 제대로 사용 못 할 것 같아서 그런데, 일단 에러코드와는 상관없이 isError일때 '동일한 날짜의 ~'를 보여줘도 될까요?

2023-10-12 11:14 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +        { statusType, excuse: excuseTrim },
음 그럴까용? 뭔가 개발하는 입장에서 select가 바뀔때마다 excuse가 초기화되는게 번거로워서 일부로 냅둔건데, 실제 사용자는 신중하게 하니까.... select 변경될때마다 지워주게 하겠습니다!

2023-10-12 11:23 UTC, pipisebastian commented on src/api/seminarApi.ts
> +        toast.error('동일한 날짜의 세미나는 생성할 수 없다.');
생각나는게 mutation api에 helperText의 문구를 set하는 setState를 넘겨서, 해당코드내에서 setHelperText('동일한 문구~') 밖에 생각이 안납니다! 혹시 더 좋은 방법이 있을까요??
<img width="780" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/6958bed1-ff30-4d23-9008-fdee8ff099ac">

2023-10-12 11:28 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
> +        { statusType, excuse: excuseTrim },
적용했습니당!

2023-10-12 12:43 UTC, publdaze commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
>      return isValid;
아하 그렇군요! 네네 그렇게 처리 좋습니다!

2023-10-12 12:45 UTC, publdaze commented on src/api/seminarApi.ts
> +        toast.error('동일한 날짜의 세미나는 생성할 수 없다.');
저도 저희 프로젝트 구조에서는 그 방법 정도 생각나긴 한데 뭔가 구조적으로 더 깔끔하게 할 수 있는 방법으로 나중에 리팩토링 할 수 있으면 좋을 것 같네요..!

일단 그 방법으로 갑시다!

2023-10-12 12:47 UTC, publdaze approved these changes

2023-10-12 12:52 UTC, pipisebastian commented on src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
>      return isValid;
zzzz넹넹!

2023-10-12 13:03 UTC, publdaze approved these changes

2023-10-12 13:05 UTC, merged