Feature/프로필 페이지 버그 픽스 #793
KEEPER31337/Homepage-Front-R2 pull request #797
Opened 2023-10-10 12:47 UTC by pipisebastian

## 연관 이슈
- Close #793

## 작업 요약
- 커밋참고해주시면 감사하겠습니당!

## 작업 상세 설명
- 프로필 수정에서 학번 제거
- 계정정보 수정에서 비밀번호 변경은 아직 api 수정이 안되었기때문에 추후 작업 예정입니다

## 리뷰 요구사항
- 10분. 탭관련 괜찮은지 확인부탁드립니당!

## Preview 이미지

2023-10-10 12:48 UTC, pipisebastian commented on src/pages/Profile/Modal/EditAccountModal.tsx
> +          setIsEmailSent(false);
이건 안하면 이메일 중복체크 api가 2번 돌기 때문입니다!

2023-10-10 12:50 UTC, pipisebastian commented on src/pages/Profile/Modal/EditProfileModal.tsx
> +      <Stack direction={{ sm: 'column', md: 'row' }} spacing={4} justifyContent="space-between" alignItems="start">
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/2bc8db38-430d-4344-9e1e-28a69d51d187)
저 이름, 생일 input창이 모달창 정중앙에 있으면 좀 어색해보여서 위로 맞춰줬는데 괜찮을까용??

2023-10-12 02:03 UTC, jasper200207 approved these changes
수고하셨습니다

2023-10-12 16:46 UTC, publdaze commented on src/pages/Profile/Modal/EditProfileModal.tsx
> +      <Stack direction={{ sm: 'column', md: 'row' }} spacing={4} justifyContent="space-between" alignItems="start">
음 중앙에 사이 간격을 더 늘려보면 어떨까요? 위로 맞춰주니까 아래가 비어보여서..!!

2023-10-12 17:10 UTC, publdaze requested changes

2023-10-12 17:10 UTC, publdaze commented on src/pages/Profile/Profile.tsx
> -    { path: '*', element: <Navigate to="attendance" /> },
이거는 다시 넣어주는 게 좋을 것 같아요!
url에 탭 포함 안 된 상태, `profile/:memberid`로만 접근했을 때 리다이렉트 되도록 처리한 거라서요!

2023-10-12 17:16 UTC, pipisebastian commented on src/pages/Profile/Profile.tsx
> -    { path: '*', element: <Navigate to="attendance" /> },
앗 그게 왜냐묜.. 버그중에 뒤로가기가 안된다는 버그가 있었습니다! 근데 저게있으면 뒤로가가기 안돼고 계속 attendance로 갔어서. 혹시 좋은 방법 있을까용??

2023-10-12 17:26 UTC, publdaze commented on src/pages/Profile/Profile.tsx
> -    { path: '*', element: <Navigate to="attendance" /> },
음... 찾아봐야 할 것 같아요..!
그런데 일단 `profile/:memberId`로만 접근했을 때 화면이 정상적으로 뜨도록은 해줘야할 것 같아요!
본인이 아닌 사용자의 경우 위와 같이 url로 접근이 가능한데 본인 아이디로 넣으면 아래와 같이 뜨면 안 될 것 같아서..!
<img width="400" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/100af702-f44e-4f80-9026-fb889a4cdbaa">

2023-10-12 17:34 UTC, pipisebastian commented on src/api/memberApi.ts
> +    },
현재 비밀번호와는 어떨까용??
![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81643702/4202a9ec-3317-467b-8113-2f3c3f03d285)

2023-10-12 17:38 UTC, pipisebastian commented on src/pages/Profile/Profile.tsx
> -    { path: '*', element: <Navigate to="attendance" /> },
아항 넵! 근데 다시해보니까 뒤로 가기 잘되네용? 해,,해결,,!

2023-10-12 17:40 UTC, publdaze commented on src/api/memberApi.ts
> +    },
엇 이부분은 새 비밀번호가 되어야 할 것 같아요! 새 비밀번호 확인이라서..!

2023-10-12 17:48 UTC, pipisebastian commented on src/api/memberApi.ts
> +    },
어웅 헷갈리네용 근데 생각해보나까 이메일 변경말고 비밀번호 변경에서도 현재 비밀번호 틀렸을 경우 에러메시지 띄워주겟습니다!

2023-10-12 17:53 UTC, publdaze approved these changes

2023-10-12 17:53 UTC, merged