Feature/role constansts로 빼기 #848
KEEPER31337/Homepage-Front-R2 pull request #852
Opened 2023-12-10 09:40 UTC by pipisebastian

## 연관 이슈
- Close #848

## 작업 요약
- 잠싀만요..

## 작업 상세 설명

## To 리뷰어... 💌 
- 예상 리뷰 소요 시간 `5분`
- `MEMBER_ROLE` 상수를 선언하는 방식이 3가지인데, 어느게 좋을지 고민이 됩니다.. 코멘트로 설명 덧붙히겠습니다!
- 상수를 선언할 때, `chairman` 이 아닌 한글로 `회장`으로 선언해줬습니다! 영어를 안 쓴 이유는, 아무래도 영어는 한번에 이해하기 어려울 것 같, 코드를

2023-12-10 10:07 UTC, pipisebastian commented on src/constants/member.ts
> +  출제자: 'ROLE_출제자',
상수를 선언할 때, `chairman` 이 아닌 한글로 `회장`으로 선언해줬습니다! 영어로 하면 오히려 코드읽기가 어려울 것 같아서 입니다..! 그런데 한글의 경우, `FRONT_전산관리자`같은 경우 어떻게 선언해줘야할지(카멜케이스, _ 등등) 고민입니다..

2023-12-10 10:07 UTC, pipisebastian commented on src/constants/member.ts
> +} as const;
`MEMBER_ROLE` 상수를 선언하는 방식이 3가지인데, 어느게 좋을지 고민이 됩니다..
 1. `ROLE_회장`과 같이 바로 텍스트로 넣어주기 -> 해당 방식이 간단하지만, `ROLE_` 부분이 중복되는데 이걸 바로 박아버리기 애매했습니다.
 2. prefix 변수 `백틱`안에 같이 넣어주기 
 3. prefix 함수 만들어서 사용하기

2023-12-10 10:16 UTC, publdaze commented on src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
> +      {jobName !== MEMBER_ROLE.전산관리자 && (
굿!!

2023-12-10 10:19 UTC, publdaze commented on src/constants/member.ts
> +  출제자: 'ROLE_출제자',
한글 섞여있는 경우 `_` 좋은 것 같아요!

2023-12-10 10:30 UTC, publdaze commented on src/constants/member.ts
> +} as const;
2222

2023-12-10 10:31 UTC, pipisebastian commented on src/constants/member.ts
> +} as const;
왜죠!!!!!

2023-12-10 10:32 UTC, publdaze requested changes
1,2,3 선택된 걸로 반영되면 approve 하겠습니다!

2023-12-10 10:52 UTC, mun-kyeong commented on src/constants/member.ts
> +} as const;
저는 1번도 괜찮을 것 같긴 합니다!
- 이유
1. 에러 메시지를 상수로 바꾸는 과정에서는 (중복되더라도) 그냥 텍스트로 사용합니다.
2. prefix() 가 어떤 형태인지 알고 있다면 이해할 수 있겠지만, 모른다면 해당 함수를 타고 들어가서 확인을 해야할 것 같습니다

> 근데 공통되는걸 묶으려면 백틱을 사용하는게 조금 더 전달력이 좋을 것 같습니당

2023-12-11 10:16 UTC, publdaze commented on src/constants/member.ts
> +} as const;
> 왜죠!!!!!

1. `ROLE_`이라는 prefix를 백엔드와 공통적으로 사용하고 있는데, 직책을 어떻게 표기할 지에 따라서 충분히 변경 가능한 부분으로 보입니다. 1번으로 가게되면 변경될 경우 수동으로 업데이트 해주어야 하는 게 번거로울 것 같아요!
3. 사실 이게 제일 깔끔해보이지는 한데, 단순한 텍스트에 함수 실행문이 들어가는 게 조금 과한 것 같다는 생각도 들더라구요!

그래서 최종적으로 prefix 변수를 사용하지만 템플릿 리터럴로 표현된 2번으로 선택하였습니다! 하지만 prefix로 사용되는 `ROLE_`이 크게 변동이 많을 것 같은 부분은 아니라서 1번도 괜찮을 것 같아요!

2023-12-11 10:42 UTC, jasper200207 approved these changes
👍

2023-12-11 10:42 UTC, jasper200207 commented on src/constants/member.ts
> +} as const;
저도 2번이 좋아보입니다.
Prefix는 공통이라 추후에 바뀔때 처리도 쉬울듯 하고,
실제 사용하는 입장에서는 1번과 2번 모두 똑같이 보여서
코드쪽 처리가 쉬운 2번이 좋을거 같습니다.
밑에는 참고 이미지 입니다!

1번
<img width="605" alt="스크린샷 2023-12-11 오후 7 40 07" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/21f23303-4dc2-4025-8ee6-bcffa786fb80">

2번
<img width="534" alt="스크린샷 2023-12-11 오후 7 40 15" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/fbf51a04-e22a-46b6-9a2e-c998559ae8a0">

2023-12-11 11:10 UTC, publdaze approved these changes
굿굿!

2023-12-11 11:10 UTC, merged