Feature/에러 메세지 상수화 #846
KEEPER31337/Homepage-Front-R2 pull request #855
Opened 2023-12-10 10:47 UTC by mun-kyeong

## 연관 이슈
- #846 

## 작업 요약
- api와 연관된 error 및 success 메세지들을 상수로 묶어서 적용하였습니다. 

## 작업 상세 설명
- 각 주제별로 error 와 success로 나누어 메세지를 분류하였습니다. 

## 리뷰 요구사항
- 예상 리뷰 소요시간 `2분`

2023-12-10 11:00 UTC, publdaze requested changes
eslint 에러나는 거 확인 부탁드려요!
대부분 절대경로로 사용되는(@ 붙은거!) 것들이 상대 경로로 사용된 것 보다 위치가 밑에 있어서 뜨는 에러 같아요!

2023-12-10 11:02 UTC, publdaze commented on src/constants/apiResponseMsg.ts
> +    invalidAttendanceWithCount: (min: number) => `출석코드가 틀렸습니다. (남은 제출횟수 ${min}회)` as const,
요기는 왜 as const가 붙은 걸까요?!

2023-12-10 11:07 UTC, pipisebastian commented on src/constants/apiResponseMsg.ts
> +  errror: {
errror! r이 중간에 3개에용!

2023-12-10 11:07 UTC, pipisebastian commented on src/constants/apiResponseMsg.ts
> +    changedSuccess: '비밀번호가 변경되었습니다.',
음음.. 아예 changedPassword 보다 changed 로도 충분히 이해되지 않을까.. 합니다...

2023-12-11 10:08 UTC, pipisebastian commented on src/constants/apiResponseMsg.ts
> +    passwordMismatch: '현재 비밀번호가 일치하지 않습니다.',
이부분도 mismatch로 적어도 이해할 수 있을 것 같아요! PASSWORD.success.mismatch 로 들어가니까요!

2023-12-11 10:38 UTC, publdaze commented on src/constants/apiResponseMessage.ts
> +    passwordMismatch: '게시글의 비밀번호가 일치하지 않습니다.',
8번 라인은 `mismatchPassword`이고 16라인은 `passwordMismatch`네용!
통일해주거나, 8번라인은 이마 객체 이름에 password가 포함되어 있으니 `mismatch`만 있어도 괜찮을 것 같기도 합니다!

2023-12-11 10:39 UTC, publdaze approved these changes
굿입니다!

2023-12-11 10:48 UTC, jasper200207 commented on src/constants/apiResponseMsg.ts
> +    invalidAttendanceWithCount: (min: number) => `출석코드가 틀렸습니다. (남은 제출횟수 ${min}회)` as const,
as const 가 없으면 함수의 출력 형식이 string 으로 잡히고 있으면 햅틱 형식에 맞춰서 잡힙니다.
아래는 참고용 이미지 입니다. 한가지 문제점은 vscode상에서는 햅틱 안의 한글이 깨져보입니다....

``` (min: number) => `출석코드가 틀렸습니다. (남은 제출횟수 ${min}회)` ```
<img width="956" alt="스크린샷 2023-12-11 오후 7 45 22" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/87e3a586-2b4d-43b6-a68f-993c45883d3c">

``` (min: number) => `출석코드가 틀렸습니다. (남은 제출횟수 ${min}회)` as const ```
<img width="1054" alt="스크린샷 2023-12-11 오후 7 44 40" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/51306225/39098534-b42f-4364-8ab8-f8112c4213ef">

2023-12-11 10:54 UTC, jasper200207 approved these changes
큰 코멘트는 없어서 Approve 하겠습니다. 👍

2023-12-11 10:54 UTC, jasper200207 commented on src/constants/apiResponseMessage.ts
> +export const POST = {
큰 상관은 없을 듯 하긴 한데 POST 대신 BOARD는 어떨까요...?
REST API의 POST랑 용어가 겹쳐보입니다.

2023-12-11 10:54 UTC, jasper200207 commented on src/constants/apiResponseMessage.ts
> +export const ID = {
API와 용어를 맞추기 위해 LOGIN_ID도 괜찮아 보입니다.

2023-12-11 11:03 UTC, publdaze commented on src/constants/apiResponseMessage.ts
> +export const POST = {
오옹 저도 REST API의 POST가 살짝 떠올랐었는데..! ㅎㅎ

2023-12-11 13:15 UTC, merged