feat: toast ui 코드 하이라이터 가능하도록 처리
KEEPER31337/Homepage-Front-R2 pull request #894
Opened 2024-05-15 02:56 UTC by redzzzi

- toast ui의 code syntax highlight 모듈 임포트
- code syntax의 테마 설정을 위해 prismjs 임포트
- toast ui의 code syntax highlight에서 모든 언어를 지원하는 js 파일을 타입스크립트로 선언

#468

## 연관 이슈
- #468 

## 작업 요약
- 게시물 글쓰기에서 코드 작성 시  code syntax highlighter 기능을 추가하였습니다.

## 작업 상세 설명
- toast ui의 code syntax highlight 플러그인을 사용하였습니다.
- prismjs의 prism-tomorrow 테마를 적용하였습니다.

## 리뷰 요구사항
> 리뷰 예상 시간 및 집중 리뷰 부분

## Preview 이미지

2024-05-16 02:34 UTC, publdaze requested changes
수고하셨습니다 👍👍👍

2024-05-16 02:34 UTC, publdaze commented on src/components/Editor/StandardEditor.tsx
> +import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js';
> js 파일을 node_modules/@types 폴더 하위에 @toast-ui 폴더를 따로 만들어 declare module을 해주었는데, 해당 방법이 최적의 방법인지 궁금합니다!

이부분에 해당하는 js 파일 맞을까요?

먼저 `node_modules` 폴더는 패키지 관리자에 의해 관리돼서 패키지 업데이트나 재설치 시 변경사항이 사라질 수 있어요. 그리고 이 폴더는 깃에 업로드되지 않기 때문에, 다른 개발자들이 변경사항을 확인하기 어려울 수 있어서 `node_modules` 하위 파일을 직접 수정하는 것은 권장되지 않습니다.

declare module을 별도로 사용하신 이유가 있으신가요?
라이브러리에 대한 타입 정의가 없어서 직접 선언하신 거면, Definitely Typed에서 제공하는 공식 타입 정의(@types/라이브러리명) 우선적으로 찾아보면 좋을 것 같아요!
만약 공식 타입 정의가 없는 경우, `node_modules`가 아닌 프로젝트 내에 별도의 타입 정의 파일을 생성해 관리하는 거 추천드립니다!

2024-05-16 02:34 UTC, publdaze commented on src/components/Viewer/StandardViewer.tsx
> +import 'prismjs/themes/prism-tomorrow.css';
css 파일 import 부분 아래로 따로 빼준 거 굿굿입니다!
분류돼서 더 보기 좋네요👍

2024-05-20 14:57 UTC, redzzzi commented on src/components/Editor/StandardEditor.tsx
> +import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js';
(1) 기존에는 언어에 대한 highlight 지원을 `@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js' 모듈로 해결하려고 했지만, 일부 언어에 대한 prismjs 모듈을 활용하는 방식으로 바꾸었습니다.
(2) code syntax highlight를 지원하고자 하는 언어의 prismjs 모듈들을 `@constants/prismLang.ts ` 파일로 정리했습니다.

2024-05-21 06:28 UTC, publdaze requested changes

2024-05-21 06:28 UTC, publdaze commented on src/components/Editor/StandardEditor.tsx
> +import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js';
(1)
언어 적용 방식 바꾼 이유가 궁금해요! 🤔

(2)
`constants` 폴더는 공통적으로 사용되는 상수 관리에 사용하고 있는 폴더라서, 이 파일 같은 경우는 `constants` 폴더가 아닌 다른 경로에 배치하는 거 어떨까 제안드립니다!

설정 파일 관리하는 `config` 폴더 새로 만들어서 하위에 넣거나,
Editor에서만 사용될 파일일 경우에는 `components/Editor` 폴더 하위에 구성해도 찾기에 용이하지 않을까 싶네요.

작업하시면서 어디에 배치하면 찾기 편할 지 고민해보고 원하는 곳에 배치해주시면 될 것 같아요!

2024-05-21 06:28 UTC, publdaze commented on src/components/Editor/StandardEditor.tsx
> +import '@constants/prismLang';
import 분류해서 재정렬 해주면 보기 좋을 것 같아용. https://github.com/KEEPER31337/Homepage-Front-R2/pull/894#discussion_r1602511070 여기 처럼 css 파일끼리 모아서 하단에 배치했던 방식 좋았던 것 같습니다! Prism과 관련된 import 문 묶고 싶으셨던 의도면 그대로 가져가셔도 좋습니다!

2024-05-21 06:30 UTC, publdaze commented on src/components/Viewer/StandardViewer.tsx
> +import 'prismjs/themes/prism-tomorrow.css';
https://github.com/KEEPER31337/Homepage-Front-R2/pull/894#discussion_r1607705995 여기두요!

2024-05-21 10:28 UTC, redzzzi commented on src/components/Editor/StandardEditor.tsx
> +import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js';
(1) node_modules 내부에서 직접 수정하여 작동시키는 것이 적절하지 않은 방법이라는 것을 알고 최대한 프로젝트 내부에서 해당 js 파일을 선언할 수 있는 파일을 만들고자 했으나, 모듈 선언이 미숙해서인지 수차례 시도에도 결국 작동되지 않아서, 다양한 방법 끝에 prismjs 모듈을 사용하는 방향으로 바꾸었습니다. 😢

(2) 기존 toast-ui의 code syntax highlight 모듈을 활용할 수 있는 방법을 더 시도해보고, prismjs 모듈을 그대로 활용할 경우에 리뷰해주신대로 Editor 폴더 하위에 구성하는 방식으로 코드 수정을 하도록 하겠습니다!

감사합니다!!

2024-05-21 10:30 UTC, redzzzi commented on src/components/Editor/StandardEditor.tsx
> +import '@constants/prismLang';
Prism 관련 모듈을 모아두었던 것인데, 다시 보니 css 모듈끼리 묶는 게 더 나아보이네용! 반영하도록 하겠습니다. 감사합니다!!

2024-05-21 10:31 UTC, redzzzi commented on src/components/Viewer/StandardViewer.tsx
> +import 'prismjs/themes/prism-tomorrow.css';
넵. 감사합니다!

2024-05-23 06:51 UTC, oxomi commented
수고하셨습니당~!

2024-05-23 13:49 UTC, publdaze commented on src/components/Editor/StandardEditor.tsx
> +import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight-all.js';
> node_modules 내부에서 직접 수정하여 작동시키는 것이 적절하지 않은 방법이라는 것을 알고 최대한 프로젝트 내부에서 해당 js 파일을 선언할 수 있는 파일을 만들고자 했으나, 모듈 선언이 미숙해서인지 수차례 시도에도 결국 작동되지 않아서, 다양한 방법 끝에 prismjs 모듈을 사용하는 방향으로 바꾸었습니다. 😢

아하 그래도 다르게 적용할 수 있는 방법 잘 찾으셨네요👍👍
모듈 선언해서 적용하는 방법도 안 되는 원인 내부적으로 파고들어서 찾아보면 재밌을 것 같네요.
일단 approve하고 차차 공부해봅시당~~

2024-05-23 14:08 UTC, publdaze commented
아 제 PR이랑 코드 변경사항 둘다 에디터쪽 겹쳐서 conflict 나는군요!
develop pull 받아서 conflict 해결 후에 머지해주시면 됩니다!

2024-05-23 17:44 UTC, merged